In [62]:
# get the data maniplulation library 
import pandas as pd
import numpy as np
import re
import math
import gc
import plotly.graph_objects as go
import plotly.express as px
gc.collect()

2905

In [60]:
Covid51countries = pd.read_csv('/data/home/asher.katz/data/hypocognition/Covid51countries.csv')
Covid51countries

,country,countryname,StartDate,EndDate,Status,Progress,Duration,Finished,RecordedDate,home,...,gender,ladder,employment,losejob,covidsymptom,language,datasource,ISO3,longstring,na_count
0,10,Australia,04/05/2020 19:34,04/05/2020 19:40,0.0,100.0,337.0,1.0,04/05/2020 19:40,8.0,...,1.0,5.0,4,NaN,0.0,ZH-S,snowball,AUS,3,0
1,10,Australia,04/05/2020 20:26,04/05/2020 20:35,0.0,100.0,530.0,1.0,04/05/2020 20:35,9.0,...,2.0,7.0,3,NaN,NaN,ZH-S,snowball,AUS,3,0
2,10,Australia,05/05/2020 21:54,05/05/2020 22:07,0.0,100.0,793.0,1.0,05/05/2020 22:07,29.0,...,1.0,4.0,1,NaN,0.0,ZH-S,snowball,AUS,5,0
3,10,Australia,04/05/2020 20:29,04/05/2020 20:34,0.0,100.0,285.0,1.0,04/05/2020 20:34,73.0,...,2.0,5.0,4,NaN,0.0,ZH-S,snowball,AUS,4,0
4,10,Australia,19/04/2020 20:21,19/04/2020 20:27,0.0,100.0,367.0,1.0,19/04/2020 20:27,100.0,...,1.0,5.0,1,NaN,0.0,ZH-S,snowball,AUS,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24216,92,Kenya,25/04/2020 01:25,25/04/2020 02:44,0.0,100.0,4690.0,1.0,25/04/2020 02:44,100.0,...,2.0,4.0,4,NaN,0.0,EN,snowball,KEN,4,0
24217,92,Kenya,24/04/2020 11:06,24/04/2020 11:15,0.0,100.0,556.0,1.0,24/04/2020 11:15,100.0,...,1.0,6.0,5,0.0,0.0,EN,snowball,KEN,2,0
24218,92,Kenya,26/04/2020 10:16,26/04/2020 10:36,0.0,100.0,1218.0,1.0,26/04/2020 10:36,80.0,...,1.0,3.0,4,NaN,0.0,EN,snowball,KEN,3,0
24219,92,Kenya,23/04/2020 03:46,23/04/2020 04:13,0.0,100.0,1641.0,1.0,23/04/2020 04:13,3.0,...,1.0,3.0,4,NaN,0.0,EN,snowball,KEN,3,0
24220,92,Kenya,24/04/2020 00:31,24/04/2020 00:42,0.0,100.0,700.0,1.0,24/04/2020 00:42,50.0,...,2.0,6.0,4,NaN,0.0,EN,snowball,KEN,2,0

In [63]:
# we need to discard any countries where the primary language is definitly english, and for the remainder, select 1 primary language
selection = pd.read_csv("~/data/hypocognition/languages_per_country_selections.csv")
selection

,Unnamed: 0,country,language,lang_responses,total_responses,percent,countryname,ISO3,Unnamed: 8
0,15,26,PT-BR,306,325,94.153846,Brazil,BRA,NaN
1,24,28,BG,269,276,97.463768,Bulgaria,BGR,NaN
2,47,37,ES,469,493,95.131846,Chile,CHL,NaN
3,51,38,ZH-S,1988,2009,98.954704,China,CHN,NaN
4,57,39,ES,122,237,51.476793,Colombia,COL,see if you can clarify the differences between...
5,58,39,ES-ES,113,237,47.679325,Colombia,COL,NaN
6,60,45,HR,524,528,99.242424,Croatia,HRV,NaN
7,64,47,NL,180,235,76.595745,Curacao,CUW,NaN
8,67,50,DA,148,233,63.519313,Denmark,DNK,NaN
9,81,55,AR,817,824,99.150485,Egypt,EGY,NaN
10,83,63,FI,260,289,89.965398,Finland,FIN,NaN
11,93,64,FR,257,363,70.798898,France,FRA,NaN
12,119,67,KAT,234,236,99.152542,Georgia,GEO,NaN
13,121,68,DE,291,567,51.322751,Germany,DEU,NaN
14,151,70,EL,227,253,89.723320,Greece,GRC,NaN
15,164,78,ZH-T,139,228,60.964912,Hong Kong (S.A.R),HKG,traiditonal chinese.
16,165,78,ZH-S,55,228,24.122807,Hong Kong (S.A.R),HKG,"simpligied chinese. distinguished by script, n..."
17,170,79,HU,256,464,55.172414,Hungary,HUN,NaN
18,189,80,ISL,348,354,98.305085,Iceland,ISL,NaN
19,192,81,MAR,56,243,23.045267,India,IND,NaN
20,196,82,ID,648,656,98.780488,Indonesia,IDN,NaN
21,201,83,FA,187,195,95.897436,Iran,IRN,NaN
22,211,86,HE,151,211,71.563981,Israel,ISR,NaN
23,220,87,IT,426,466,91.416309,Italy,ITA,NaN
24,238,89,JA,1288,1352,95.266272,Japan,JPN,NaN
25,250,90,AR,233,236,98.728814,Jordan,JOR,NaN
26,253,91,RU,279,291,95.876289,Kazakhstan,KAZ,NaN
27,257,109,MS,155,214,72.429907,Malaysia,MYS,NaN
28,266,112,MALTI,284,1290,22.015504,Malta,MLT,NaN
29,288,128,NL,524,1348,38.872404,Netherlands,NLD,NaN
30,334,143,ES-ES,215,357,60.224090,Peru,PER,NaN
31,338,149,RU,577,586,98.464164,Russia,RUS,NaN
32,343,160,SR,351,354,99.152542,Serbia,SRB,NaN
33,358,170,AFRI,112,426,26.291080,South Africa,ZAF,NaN
34,364,173,CA,187,418,44.736842,Spain,ESP,NaN
35,386,177,SV,400,529,75.614367,Sweden,SWE,NaN
36,408,179,AR,247,248,99.596774,Syria,SYR,NaN
37,410,180,ZH-TW,747,761,98.160315,Taiwan,TWN,NaN
38,419,189,TR,253,346,73.121387,Turkey,TUR,NaN
39,426,193,UK,657,698,94.126074,Ukraine,UKR,NaN
40,493,202,VI,292,338,86.390533,Vietnam,VNM,NaN

In [64]:
filtered = Covid51countries[Covid51countries['countryname'].isin(selection['countryname']) & Covid51countries["language"].isin(selection['language'])]
filtered

,country,countryname,StartDate,EndDate,Status,Progress,Duration,Finished,RecordedDate,home,...,gender,ladder,employment,losejob,covidsymptom,language,datasource,ISO3,longstring,na_count
378,109,Malaysia,21/04/2020 19:11,21/04/2020 19:34,0.0,100.0,1373.0,1.0,21/04/2020 19:34,97.0,...,2.0,8.0,4,NaN,1.0,MS,snowball,MYS,9,0
379,109,Malaysia,18/04/2020 12:45,18/04/2020 13:08,0.0,100.0,1406.0,1.0,18/04/2020 13:08,90.0,...,2.0,6.0,4,NaN,0.0,ID,snowball,MYS,4,0
380,109,Malaysia,21/04/2020 06:27,21/04/2020 06:46,0.0,100.0,1135.0,1.0,21/04/2020 06:46,100.0,...,1.0,7.0,1,NaN,0.0,MS,snowball,MYS,3,0
381,109,Malaysia,20/04/2020 21:14,20/04/2020 21:29,0.0,100.0,951.0,1.0,20/04/2020 21:29,NaN,...,1.0,4.0,1,NaN,0.0,MS,snowball,MYS,5,0
382,109,Malaysia,21/04/2020 02:24,21/04/2020 02:37,0.0,100.0,745.0,1.0,21/04/2020 02:37,100.0,...,2.0,1.0,2,NaN,1.0,MS,snowball,MYS,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24009,91,Kazakhstan,25/04/2020 13:36,25/04/2020 13:44,0.0,100.0,470.0,1.0,25/04/2020 13:44,100.0,...,2.0,8.0,1,NaN,1.0,RU,snowball,KAZ,3,0
24010,91,Kazakhstan,06/05/2020 04:03,06/05/2020 04:18,0.0,100.0,884.0,1.0,06/05/2020 04:18,100.0,...,2.0,4.0,5,1.0,0.0,RU,snowball,KAZ,3,0
24011,91,Kazakhstan,06/05/2020 12:32,06/05/2020 12:41,0.0,100.0,573.0,1.0,06/05/2020 12:41,100.0,...,1.0,4.0,5,1.0,0.0,RU,snowball,KAZ,4,0
24012,91,Kazakhstan,06/05/2020 10:37,06/05/2020 10:49,0.0,100.0,701.0,1.0,06/05/2020 10:49,100.0,...,2.0,8.0,5,0.0,0.0,RU,snowball,KAZ,5,0
24013,91,Kazakhstan,06/05/2020 11:19,06/05/2020 11:32,0.0,100.0,776.0,1.0,06/05/2020 11:32,100.0,...,2.0,6.0,1,NaN,0.0,RU,snowball,KAZ,2,0

In [ ]:
# Are the languages in the "filtered" dataset actually filtered and now match the selected languages?
set(filtered['language'].unique()) == set(selection['language'].unique())

True

In [ ]:
#Are the countries in the "filtered" dataset actually filtered and now match the selected countries?
set(filtered['countryname'].unique()) == set(selection['countryname'].unique())

True

In [67]:
filtered = filtered.reset_index(drop=True)

Goals
* For each distinct language, what is the lexical ellaboration for each of the 20 emotions?
* For each distinct language, is there any statistical significance in the distribution of the results of any particular emotion?

In [68]:
filtered = filtered[['country', 'countryname', 'language', 'admiration', 'calm', 'compassion',
       'determination', 'moved', 'gratitude', 'hope', 'love', 'relief',
       'pleasure', 'anger', 'anxiety', 'boredom', 'confusion', 'disgust',
       'fear', 'frustration', 'loneliness', 'regret', 'sadness']].copy()

In [69]:
filtered

,country,countryname,language,admiration,calm,compassion,determination,moved,gratitude,hope,...,anger,anxiety,boredom,confusion,disgust,fear,frustration,loneliness,regret,sadness
0,109,Malaysia,MS,1.0,6.0,1.0,0.0,0.0,0.0,6.0,...,5.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
1,109,Malaysia,ID,1.0,5.0,6.0,4.0,5.0,5.0,5.0,...,4.0,5.0,5.0,5.0,1.0,4.0,1.0,0.0,1.0,1.0
2,109,Malaysia,MS,4.0,4.0,2.0,3.0,2.0,3.0,4.0,...,2.0,2.0,4.0,3.0,2.0,2.0,2.0,4.0,2.0,3.0
3,109,Malaysia,MS,3.0,3.0,3.0,3.0,3.0,1.0,0.0,...,0.0,3.0,3.0,0.0,0.0,3.0,0.0,3.0,1.0,4.0
4,109,Malaysia,MS,6.0,3.0,6.0,4.0,6.0,5.0,6.0,...,3.0,3.0,6.0,4.0,0.0,3.0,4.0,2.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17071,91,Kazakhstan,RU,1.0,3.0,3.0,1.0,5.0,5.0,3.0,...,4.0,2.0,3.0,2.0,2.0,3.0,2.0,3.0,3.0,2.0
17072,91,Kazakhstan,RU,3.0,3.0,6.0,2.0,6.0,5.0,5.0,...,4.0,4.0,4.0,0.0,1.0,5.0,2.0,2.0,6.0,5.0
17073,91,Kazakhstan,RU,3.0,3.0,3.0,3.0,4.0,4.0,0.0,...,3.0,2.0,0.0,3.0,3.0,2.0,5.0,4.0,4.0,3.0
17074,91,Kazakhstan,RU,2.0,3.0,6.0,2.0,2.0,1.0,6.0,...,4.0,4.0,3.0,3.0,3.0,3.0,3.0,1.0,6.0,4.0
17075,91,Kazakhstan,RU,0.0,1.0,4.0,2.0,1.0,3.0,1.0,...,4.0,4.0,0.0,1.0,0.0,4.0,2.0,0.0,6.0,5.0

In [86]:
lang_names = pd.read_csv('/data/home/asher.katz/hypocognition/reference/lang_names.csv')
merged_filtered = filtered.merge(lang_names, left_on="language", right_on="Code", how="left")
merged_filtered = merged_filtered.drop(columns=["Code"])
merged_filtered

,country,countryname,language,admiration,calm,compassion,determination,moved,gratitude,hope,...,anxiety,boredom,confusion,disgust,fear,frustration,loneliness,regret,sadness,Language_Name
0,109,Malaysia,MS,1.0,6.0,1.0,0.0,0.0,0.0,6.0,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,Malay
1,109,Malaysia,ID,1.0,5.0,6.0,4.0,5.0,5.0,5.0,...,5.0,5.0,5.0,1.0,4.0,1.0,0.0,1.0,1.0,Indonesian
2,109,Malaysia,MS,4.0,4.0,2.0,3.0,2.0,3.0,4.0,...,2.0,4.0,3.0,2.0,2.0,2.0,4.0,2.0,3.0,Malay
3,109,Malaysia,MS,3.0,3.0,3.0,3.0,3.0,1.0,0.0,...,3.0,3.0,0.0,0.0,3.0,0.0,3.0,1.0,4.0,Malay
4,109,Malaysia,MS,6.0,3.0,6.0,4.0,6.0,5.0,6.0,...,3.0,6.0,4.0,0.0,3.0,4.0,2.0,0.0,2.0,Malay
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17071,91,Kazakhstan,RU,1.0,3.0,3.0,1.0,5.0,5.0,3.0,...,2.0,3.0,2.0,2.0,3.0,2.0,3.0,3.0,2.0,Russian
17072,91,Kazakhstan,RU,3.0,3.0,6.0,2.0,6.0,5.0,5.0,...,4.0,4.0,0.0,1.0,5.0,2.0,2.0,6.0,5.0,Russian
17073,91,Kazakhstan,RU,3.0,3.0,3.0,3.0,4.0,4.0,0.0,...,2.0,0.0,3.0,3.0,2.0,5.0,4.0,4.0,3.0,Russian
17074,91,Kazakhstan,RU,2.0,3.0,6.0,2.0,2.0,1.0,6.0,...,4.0,3.0,3.0,3.0,3.0,3.0,1.0,6.0,4.0,Russian
17075,91,Kazakhstan,RU,0.0,1.0,4.0,2.0,1.0,3.0,1.0,...,4.0,0.0,1.0,0.0,4.0,2.0,0.0,6.0,5.0,Russian

In [ ]:
merged_filtered['language'].nunique()

34

In [ ]:
nan_rows = merged_filtered[merged_filtered.isna().any(axis=1)].reset_index(drop=True)
nan_rows

,country,countryname,language,admiration,calm,compassion,determination,moved,gratitude,hope,...,anger,anxiety,boredom,confusion,disgust,fear,frustration,loneliness,regret,sadness
0,112,Malta,MALTI,3.0,4.0,NaN,5.0,3.0,NaN,4.0,...,6.0,3.0,0.0,3.0,0.0,4.0,5.0,2.0,NaN,4.0
1,112,Malta,MALTI,NaN,0.0,4.0,2.0,6.0,3.0,NaN,...,NaN,2.0,3.0,NaN,NaN,3.0,2.0,3.0,2.0,4.0
2,112,Malta,MALTI,4.0,3.0,NaN,4.0,3.0,4.0,6.0,...,3.0,3.0,2.0,0.0,3.0,5.0,4.0,1.0,4.0,3.0
3,112,Malta,MALTI,3.0,5.0,4.0,3.0,6.0,4.0,3.0,...,4.0,NaN,3.0,4.0,4.0,2.0,4.0,4.0,NaN,4.0
4,112,Malta,MALTI,2.0,1.0,5.0,NaN,3.0,4.0,2.0,...,2.0,5.0,1.0,5.0,4.0,5.0,6.0,1.0,4.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,91,Kazakhstan,RU,6.0,6.0,6.0,6.0,3.0,6.0,6.0,...,0.0,0.0,0.0,6.0,0.0,0.0,4.0,0.0,6.0,0.0
441,91,Kazakhstan,RU,0.0,6.0,3.0,6.0,0.0,4.0,6.0,...,5.0,6.0,6.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0
442,91,Kazakhstan,RU,3.0,0.0,3.0,6.0,0.0,0.0,3.0,...,6.0,6.0,0.0,6.0,0.0,6.0,6.0,NaN,6.0,6.0
443,91,Kazakhstan,RU,1.0,3.0,4.0,5.0,4.0,4.0,3.0,...,4.0,5.0,1.0,1.0,1.0,4.0,3.0,3.0,1.0,4.0
444,91,Kazakhstan,RU,NaN,3.0,6.0,6.0,6.0,6.0,6.0,...,1.0,6.0,3.0,6.0,0.0,NaN,6.0,6.0,NaN,6.0

In [72]:
nan_rows.iloc[369]

country               80
countryname      Iceland
language             ISL
admiration           0.0
calm                 6.0
compassion           NaN
determination        3.0
moved                0.0
gratitude            3.0
hope                 5.0
love                 1.0
relief               4.0
pleasure             1.0
anger                2.0
anxiety              2.0
boredom              3.0
confusion            0.0
disgust              0.0
fear                 0.0
frustration          1.0
loneliness           0.0
regret               1.0
sadness              4.0
Name: 369, dtype: object

In [73]:
num_nan = filtered.isna().sum(axis=1).value_counts().sort_index()

In [74]:
num_nan.to_csv('~/data/hypocognition/output_results/num_nan.csv')

In [75]:
nan_rows.to_csv('~/data/hypocognition/output_results/nan_rows.csv')

In [139]:
emotions = ['admiration', 'calm', 'compassion',
       'determination', 'moved', 'gratitude', 'hope', 'love', 'relief',
       'pleasure', 'anger', 'anxiety', 'boredom', 'confusion', 'disgust',
       'fear', 'frustration', 'loneliness', 'regret', 'sadness']

In [140]:
len(emotions)

20

In [109]:
bila_full = pd.read_csv("/data/home/asher.katz/data/Fundemental-Emotions/output_results/bila_long_noun_lemmatized_full.csv")
bila_full

/tmp/ipykernel_875215/2621564582.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  bila_full = pd.read_csv("/data/home/asher.katz/data/Fundemental-Emotions/output_results/bila_long_noun_lemmatized_full.csv")

,Unnamed: 0,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,log_count
0,0,chi.14718491,abdomen,2.0,1.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,0.693147
1,1,chi.14718491,ability,2.0,2.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,1.098612
2,2,chi.14718491,absence,4.0,2.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,1.098612
3,3,chi.14718491,abstinence,2.0,5.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,1.791759
4,4,chi.14718491,abundance,3.0,4.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,1.609438
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1824416,1824416,wu.89119131142,zephyr,2.0,2.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,1.098612
1824417,1824417,wu.89119131142,zinc,2.0,2.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,1.098612
1824418,1824418,wu.89119131142,zone,6.0,4.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,1.609438
1824419,1824419,wu.89119131142,zoo,1.0,1.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,0.693147
1824420,1824420,wu.89119131142,zoom,5.0,1.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,0.693147

In [156]:
bila_full[bila_full['word']=='regret']

,Unnamed: 0,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,log_count
1278,1278,chi.14718491,regret,5.0,2.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.39210,7.948120,1.098612
6688,6688,coo.31924067983704,regret,5.0,41.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.86670,39.866700,3.737670
11411,11411,coo.31924099174934,regret,5.0,4.0,Western Flemish,vlaa1240,1917,Hill's Flemish-English and English-Flemish ves...,"Leopold B. Hill, 1917.",0,Eurasia,Indo-European,"Indo-European, Classical Indo-European, German...",3.11345,51.075400,1.609438
15993,15993,coo1.ark:/13960/t9m33d507,regret,5.0,3.0,Manx,manx1243,1866,The Manx dictionary.,"Printed for the Manx Society, 1866.",0,Eurasia,Indo-European,"Indo-European, Classical Indo-European, Celtic...",-4.45437,54.260400,1.386294
22270,22270,dictionaria.kalamang_visser_kara1499,regret,5.0,1.0,Kalamang,kara1499,2020,Kalamang dictionary,Dictionaria,Eline Visser,Papunesia,West Bomberai,West Bomberai,132.67800,-3.470370,0.693147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1810306,1810306,webonary.sisaali_frempong_tumu1242,regret,5.0,1.0,Sisaali,tumu1242,2022,Sisaali dictionary,GILLBT / SILAP,"Margrit Frempong, Caleb Batong",Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, North Volta-Congo...",-1.79707,10.634510,0.693147
1812497,1812497,webonary.sursurunga_hutchisson_surs1246,regret,5.0,1.0,Sursurunga,surs1246,2020,Sursurunga – English Dictionary,SIL International,Don Hutchisson,Papunesia,Austronesian,"Austronesian, Malayo-Polynesian, Eastern Malay...",152.76800,-3.990780,0.693147
1816909,1816909,webonary.turkmen_almamedow_turk1304,regret,5.0,23.0,Turkmen,turk1304,2014,Turkmen-English Dictionary,SIL International,"A. Almämedow, David Gray",Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, E...",59.17574,37.087190,3.178054
1820036,1820036,wu.89017649658,regret,5.0,3.0,Pennsylvania German,penn1240,1951,"Pennsylvania Dutch dictionary and handbook, wi...",William Penn Senior High School and Atreus Wan...,0,North America,Indo-European,"Indo-European, Classical Indo-European, German...",283.67890,40.030507,1.386294
1823479,1823479,wu.89119131142,regret,5.0,11.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.56550,-21.023100,2.484907

In [127]:
merged_filtered['countryname'].unique()

array(['Malaysia', 'Malta', 'Netherlands', 'Peru', 'Russia', 'Serbia',
       'South Africa', 'Spain', 'Sweden', 'Syria', 'Taiwan', 'Turkey',
       'Ukraine', 'Vietnam', 'Brazil', 'Bulgaria', 'Chile', 'China',
       'Colombia', 'Croatia', 'Curacao', 'Denmark', 'Egypt', 'Finland',
       'France', 'Georgia', 'Germany', 'Greece', 'Hong Kong (S.A.R)',
       'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Israel',
       'Italy', 'Japan', 'Jordan', 'Kazakhstan'], dtype=object)

In [128]:
merged_filtered[merged_filtered['countryname']=='China']

,country,countryname,language,admiration,calm,compassion,determination,moved,gratitude,hope,...,anxiety,boredom,confusion,disgust,fear,frustration,loneliness,regret,sadness,Language_Name
7308,38,China,ZH-S,5.0,3.0,6.0,5.0,5.0,4.0,6.0,...,4.0,2.0,2.0,1.0,3.0,1.0,2.0,0.0,2.0,Simplified Chinese
7309,38,China,ZH-S,3.0,2.0,2.0,4.0,1.0,1.0,2.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,Simplified Chinese
7310,38,China,ZH-S,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,6.0,6.0,6.0,0.0,5.0,0.0,0.0,0.0,6.0,Simplified Chinese
7311,38,China,ZH-S,3.0,4.0,4.0,3.0,4.0,4.0,6.0,...,4.0,5.0,4.0,4.0,4.0,5.0,4.0,4.0,2.0,Simplified Chinese
7312,38,China,ZH-S,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,3.0,1.0,3.0,0.0,1.0,2.0,0.0,0.0,4.0,Simplified Chinese
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9302,38,China,ZH-S,2.0,3.0,3.0,3.0,2.0,2.0,3.0,...,2.0,5.0,2.0,2.0,2.0,4.0,3.0,2.0,3.0,Simplified Chinese
9303,38,China,ZH-S,4.0,3.0,3.0,2.0,4.0,5.0,6.0,...,4.0,3.0,2.0,2.0,2.0,1.0,3.0,1.0,2.0,Simplified Chinese
9304,38,China,ZH-S,6.0,3.0,6.0,6.0,6.0,6.0,4.0,...,6.0,6.0,2.0,6.0,6.0,0.0,0.0,0.0,4.0,Simplified Chinese
9305,38,China,ZH-S,6.0,5.0,6.0,6.0,6.0,6.0,6.0,...,3.0,3.0,3.0,0.0,3.0,3.0,3.0,2.0,3.0,Simplified Chinese
9306,38,China,ZH-S,6.0,4.0,6.0,6.0,6.0,6.0,6.0,...,0.0,6.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,Simplified Chinese

In [106]:
covid_to_bila_lang_name_mapping = pd.read_csv("/data/home/asher.katz/hypocognition/reference/covid_to_bila_lang_name_mapping.csv")
covid_to_bila_lang_name_mapping = covid_to_bila_lang_name_mapping.sort_values(by = "easy")
covid_to_bila_lang_name_mapping

,study_language_names,bila_language_name_mapping,possible_alternative_bila_language_name_mappings,easy
2,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Yue Chinese, Hakka Chinese",0
6,Maltese,[No direct match],"Arabic, Italian (linguistically related)",0
23,Brazilian Portuguese,Portuguese,—,0
27,Catalan,[No direct match],"Spanish, French (Romance family)",0
24,Serbian,Serbian-Croatian-Bosnian,—,0
26,Croatian,Serbian-Croatian-Bosnian,—,0
17,Traditional Chinese (Taiwan),Mandarin Chinese,"Min Nan Chinese, Hakka Chinese",0
32,Traditional Chinese,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese",0
8,Hungarian,Hungarian,—,1
9,Italian,Italian,Sicilian,1
10,Greek,Greek,—,1
0,Malay,Standard Malay,Indonesian,1
3,Spanish (Spain),Spanish,Latin American Spanish,1
4,Arabic,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar...",1
5,Vietnamese,Vietnamese,—,1
1,Indonesian,Indonesian,Standard Malay,1
15,French,French,"Cajun French, Louisiana Creole French, Old French",1
14,Bulgarian,Bulgarian,—,1
13,Swedish,Swedish,—,1
12,German,German,"Moselle Franconian, Plautdietsch",1
11,Dutch,Dutch,Western Flemish,1
19,Finnish,Finnish,—,1
18,Persian,Persian,—,1
16,Danish,Danish,—,1
22,Turkish,Turkish,—,1
21,Ukrainian,Ukrainian,—,1
20,Icelandic,Icelandic,Old Norse,1
25,Spanish (General),Latin American Spanish,Spanish,1
28,Hebrew,Hebrew,Ancient Hebrew,1
29,Japanese,Japanese,—,1
30,Afrikaans,Afrikaans,Dutch,1
7,Russian,Russian,—,1
31,Georgian,Georgian,—,1
33,Marathi,Marathi,—,1

In [107]:
covid_to_bila_lang_name_mapping.to_csv("/data/home/asher.katz/data/hypocognition/output_results/covid_to_bila_lang_name_mapping.csv")

In [110]:
bila_full['langname'].unique()

array(['Nancowry', 'Turkish', 'Western Flemish', 'Manx', 'Daakaka',
       'Guarayu', 'Iquito', 'Kalamang', 'Media Lengua', 'Nen', 'Palula',
       'Sanzhi Dargwa', 'Teanu', 'Teop', 'Wersing', 'Bikol', 'Carolinian',
       'Hiligaynon', 'Kapampangan', 'Kapingamarangi', 'Kusaiean',
       'Mokilese', 'Palauan', 'Pangasinan', 'Woleaian',
       'Western Neo-Aramaic', 'Western Temne', 'Thompson', 'Wampanoag',
       'Dimasa', 'Mota', 'Northern Grebo', 'Sanskrit', 'Unami',
       'Wiltshire-Hampshire', 'Zigula-Mushungulu', 'Southern Sotho',
       'Bemba (Zambia)', 'Arikara', 'Slovenian', 'Belarusian', 'Ladino',
       'Muruwari', 'Berom', 'Osage', 'Moselle Franconian', 'Rendille',
       'Estonian', 'Somali', 'Luo (Kenya and Tanzania)', 'Romanian',
       'Slovak', 'Ha', 'Havasupai-Walapai-Yavapai', 'Diriku-Shambyu',
       'Esan', 'Nuu-chah-nulth', 'Kamba (Kenya)', 'Huron-Wyandot',
       'Borana-Arsi-Guji Oromo', 'Anufo', 'Bassa', 'Didinga',
       'Rennell-Bellona', 'Norwegian', 'Nung (Viet Nam)',
       'Levantine Arabic', 'Neo-Mandaic', 'Gilit Mesopotamian Arabic',
       'Central Kurdish', 'Javanese', 'Plateau Malagasy', 'Tiv', 'Breton',
       'Balinese', 'Zuni', 'Czech', 'Cajun French', 'Welsh', 'Scots',
       'Atakapa', 'Shan', 'Hawaiian', 'Serbian-Croatian-Bosnian',
       'Old Chinese', 'Middle High German', 'Eastern Canadian Inuktitut',
       'Sicilian', 'Polish', 'Biatah Bidayuh', 'Chamorro',
       'Western Frisian', 'Hindustani', 'Martu Wangka', 'Arapaho', 'Geez',
       'Southern Jinghpaw', 'Adyghe', 'Western Canadian Inuktitut',
       'Gela', 'Saurashtra', 'Comanche', 'Bengali', 'Eastern Armenian',
       'Temiar', 'Standard Malay', 'Hmong Njua', 'Mara Chin', 'Gedaged',
       'Mon', 'Gujarati', 'Khotanese', 'Kok Borok', 'Maguindanao',
       'Mahasu Pahari', 'Marshallese', 'Kuanyama', 'Cheyenne', 'Cahuilla',
       'Khwarezmian', 'Santali', 'Kuku-Yalanji', 'Gilbertese',
       'Yankunytjatjara', 'Dhargari', 'Djiwarli', 'Nugunu (Australia)',
       'Yuwaalaraay-Gamilaraay', 'Western Victoria', 'Bayungu',
       'Wariyangga', 'Yinggarda', 'Dhalandji', 'Adnyamathanha',
       'Hmong Daw', 'Kosarek Yale', 'Pintupi-Luritja', 'Yir-Yoront',
       'Alabama', 'Baram Kayan', 'Larike-Wakasihu', 'Avestan', 'Aneityum',
       'Beijing Mandarin', 'Lamba', 'Tokelau', 'Koasati',
       'Ancient Hebrew', 'Batad Ifugao', 'Tamambo', 'Oksapmin', 'Thayore',
       'Iban', 'Mongolian', 'Beng', 'Tausug', 'Hidatsa', 'Devon', 'Hindi',
       'Sinaugoro', 'Waray (Philippines)', 'Old Norse', 'Hausa', 'Ulster',
       'Goan Konkani', 'Ata', 'Bislama', 'Ute-Southern Paiute',
       'Wu Chinese', 'Albanian', 'Gulf Arabic', 'Yagaria', 'Maranao',
       'Muna', 'Andalusian Arabic', 'Badaga', 'North Azerbaijani',
       'Kazakh', 'Rotuman', 'Italian', 'North Alaskan Inupiatun',
       'Arabic', 'Liberia Kpelle', 'Yucatec Maya', 'Classical Nahuatl',
       'Tuwali Ifugao', 'Louisiana Creole French', 'Russian',
       'Central Tarahumara', 'Western Apache', 'Sanaani Arabic',
       'Garifuna', 'Creek', 'Bardi', 'Western Ojibwa', 'Yogad',
       'Upper Chehalis', 'Latin American Spanish',
       'Mising-Padam-Miri-Minyong', 'Lepcha', 'Kiliwa', 'Ipai',
       'Western Tlacolula Valley Zapotec', 'Chantyal', 'Masbatenyo',
       'Leh Ladakhi', 'Maithili', 'Katë', 'Swedish', 'Chang Naga',
       'Xhosa', 'Tuvinian', 'Mexican Spanish', 'Plains Cree', 'Ga',
       'Galician', 'Midland American English', 'Nzima', 'Powhatan',
       'Rabha', 'Korean', 'Yoruba', 'Afrikaans', 'Amharic', 'Singlish',
       'Latin', 'Bambara', 'Nandi', 'Marathi', 'Kumbainggar',
       'Yue Chinese', 'Mapun', 'Lakota', 'Yaqui', 'Northern Pashto',
       'Yakan', 'Jewish Babylonian Aramaic', 'Tahitian', 'Central Malay',
       'Tuvalu', 'Uripiv', 'Naro', 'Plautdietsch', 'Bulgarian',
       'Ngaanyatjarra', 'Lycian A', 'Finnish', 'Tee', 'Tamil', 'Bantawa',
       'Swahili', 'Kxoe', 'Busa', 'Boko (Benin)', 'Bokobaru',
       'Central Khmer', 'Dzongkha', 'Limbu', 'Agusan Manobo', 'Thao',
       'Malacca-Batavia Portuguese Creole', 'Mag-Anchi Ayta', 'Aleut',
       "S'gaw Karen", 'Tboli', 'Eastern Panjabi', "Mi'kmaq",
       'Jicarilla Apache', 'Akha', 'Raluana', 'Malayalam',
       'Kadazan Dusun', 'Tagalog-Pilipino', 'Tuamotuan', 'Kannada',
       'Tibetan', 'Cherokee', 'Hakka Chinese', 'Old English', 'French',
       'Sumerian', 'Urdu', 'Khasi', 'Bondo', 'Yana', 'Central Carrier',
       'Western Parbate Kham', 'Bodo-Mech', 'Oriya', 'Sembakung Murut',
       'Romblomanon', 'Chippewa', 'Ojibway', 'Baba Malay', 'Uighur',
       'Tigrinya', 'Kirghiz', 'Maori', 'Latvian',
       'Trinidadian Creole English', 'Tok Pisin', 'Uzbek', 'Yeyi',
       'Old French', 'Tanacross', 'Misima-Paneati', 'Sundanese', 'Caló',
       'Persian', 'Navajo', 'Hungarian', 'South-Central Koongo',
       'Bobangi', 'Nez Perce', 'Nyanja', "Kalispel-Pend d'Oreille",
       'Western Panjabi', 'Sudanese Arabic', 'Beja', 'Daakie', 'Dagaare',
       'Dalabon', 'Djinang', 'Eastern Shoshone', 'Fijian', 'Gbari',
       'Goemai', 'Iraqw', 'Komnzo', 'Mosuo', 'Mudburra', 'Nafsan',
       'Ngandi', 'Northern Alta', 'Nuxalk', 'Rongga', 'Sauk', 'Savosavo',
       'Vures', 'Wampar', 'Warlpiri', 'Yali', 'Aiwoo',
       'Pre-Angkorian Khmer', "'Are'are", 'Arosi', 'Awa', 'Bontok',
       'Buin', 'Canala', 'Cheke Holo', 'Chepang', 'Cook Islands Maori',
       'Dehong', 'Dehu', 'Dumagat', 'Enga', 'Fore', 'Futunu-Aniwa',
       'Grand Couli', 'Jabem', 'Jahai', 'Jingulu', 'Kalam', 'Kâte',
       'Kewa', 'Grass Koiari', 'Kwaio', 'Kwamera', 'Kwoma', 'Kyaka Enga',
       'Lau', 'Lenakel', 'Lisu', 'Lonwolwol', 'Mali', 'Mara', 'Mele',
       'Nakanai', 'Nengone', 'Orokolo', 'Paamese', 'Paiwan', 'Puluwat',
       'Rhade', 'Ritharngu', 'Selepet', 'Southeast Ambrym', 'Sye',
       'Takuu', 'Telefol', 'Tetum', 'Tolo', 'Toqabaqita', "Urak Lawoi'",
       'Warndarang', 'Wirangu', 'Yandruwandha', 'Yugambeh', 'Assyrian',
       'Yámana', 'Caribbean Hindustani', 'Mayan',
       'Western Huasteca Nahuatl', 'Cayubaba', 'Lokono',
       'Isthmus Zapotec', 'Haitian', 'Papiamento', 'Warao', "K'iche'",
       'Brazilian Portuguese', "Tohono O'odham", 'Border Kuna', 'Mailu',
       'Telugu', 'Min Dong Chinese', 'Essex', 'South Yorkshire English',
       'Sinhala', 'Western Bukidnon Manobo', 'Tunica', 'Niuean', 'Pali',
       'Vietnamese', 'Shekkacho', 'Sussex', 'Dutch', 'German',
       'Heiltsuk-Oowekyala', "Kwak'wala", 'Filipino', 'Portuguese',
       'Indonesian', 'Burmese', 'Lundayeh', 'Besisi',
       'Central Siberian Yupik', 'San Blas Kuna', 'Tonkawa',
       'Coast Miwok', 'Roviana', 'Northeast Maidu', 'Klamath-Modoc',
       'Cornish', 'Mangareva', 'Pohnpeian', 'Greek',
       'Tarifiyt-Beni-Iznasen-Eastern Middle Atlas Berber', "Dena'ina",
       'Akkadian', 'Scottish Gaelic', 'Icelandic', 'Egyptian Arabic',
       'Sindhi', 'Nupe-Nupe-Tako', 'Eastern Balochi', 'Sadri', 'Kudmali',
       'Assamese', 'Mansaka', 'Danish', 'Mundari', 'Semai',
       'East-Central Tangkhul Naga', 'Lithuanian', 'East Limba', 'Urhobo',
       'Karamojong', 'Kipsigis', 'Akan', 'Zande', 'Cebuano', 'Efik',
       'Tai Dón', 'Nepali', 'Lao', 'Manda (India)', 'Haisla', 'Rungus',
       'Ao Naga', 'Choctaw', 'Tonga (Tonga Islands)', 'Squamish',
       'Ho-Chunk', 'Malayo', 'Ukrainian', 'Syriac', 'Min Nan Chinese',
       'Mandarin Chinese', 'Upper Sorbian', 'Central Nicobarese', 'Tulu',
       "Sa'a", 'North Saami', 'Seneca',
       'Bolivar-North Chimborazo Highland Quichua', 'Ahtena', 'Tzotzil',
       'Yao', 'Western Abenaki', 'Yiddish', 'Dakota-Sioux', 'Spanish',
       'Kashmiri', 'Northwest Sahaptin', 'Irish',
       'Malecite-Passamaquoddy', 'Eastern Ojibwa', 'Moroccan Arabic',
       'Shona', 'Ndau', 'Mbukushu', 'Southwestern Dinka', 'Nuer', 'Swati',
       'Nyankole', 'Sango', 'Atayal', 'Tsonga', 'Wubuy', 'Chadian Arabic',
       'Bughotu', 'Yapese', 'Ho', 'Sidaama', 'Tswana', 'Abua', 'Mizo',
       'Gaam', 'Ganda', 'Lozi', 'Egyptian (Ancient)', 'Sabaic', 'Tangga',
       'Bini', 'Kinshasa Lingala', 'Kurukh', 'Ibibio', 'Toaripi', 'Igbo',
       'Izon', 'Tikopia', 'Kathmandu Valley Newari', 'Manipuri',
       'Giryama', 'Ewe', 'Venda', 'Yemeni Arabic', 'Georgian',
       'Wik-Mungkan', 'Zulu', 'Turkana', 'Mwaghavul',
       'West Central Oromo', 'Tangale', 'Pedi', 'Chuukese', 'Sora',
       'Mungaka', 'Mískito', 'Tiwi', 'Samoan', 'Central Kanuri',
       'East Taa', 'Mandinka', 'Gambian Wolof', 'Wolof', 'Gade',
       'Lega-Shabunda', 'Pulaar', 'Ndonga', 'Mambwe-Lungu', 'Masai',
       'Hebrew', 'Ilokano', 'Aromanian', 'Thai', 'Japanese',
       'Middle Chinese', 'Kwangali', 'Mbay', 'Pidgin Chinook Jargon',
       'Akawaio', 'Arta', 'Belanda Bor', 'Bongo', 'Buli', 'Caning',
       'Chizigula', 'Chufie', 'Chung', 'Shilluk-Cøllø', 'Dagbani', 'Daui',
       'Doromu-Koki', 'Fuyug', 'Gikyode', 'Gojri', 'Kinyarwanda', 'Lopit',
       'Lou', 'Lubwisi', 'Lugungu', 'Lugwere', 'Lunyole', 'Mampruli',
       'Mandari', 'Mungong', 'Reel', 'Sisaali', 'Sursurunga', 'Tampulma',
       'Turkmen', 'Pennsylvania German', 'Herero'], dtype=object)

In [141]:
bila_full_emotions = bila_full[bila_full['word'].isin(emotions)].reset_index(drop=True)
bila_full_emotions

,Unnamed: 0,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,log_count
0,40,chi.14718491,anger,5.0,2.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,1.098612
1,51,chi.14718491,anxiety,2.0,1.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,0.693147
2,350,chi.14718491,confusion,5.0,1.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,0.693147
3,483,chi.14718491,disgust,3.0,4.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,1.609438
4,606,chi.14718491,fear,8.0,9.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,2.302585
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6466,1822795,wu.89119131142,love,10.0,75.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,4.330733
6467,1823258,wu.89119131142,pleasure,5.0,13.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,2.639057
6468,1823479,wu.89119131142,regret,5.0,11.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,2.484907
6469,1823490,wu.89119131142,relief,11.0,10.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,2.397895
6470,1823618,wu.89119131142,sadness,3.0,12.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,2.564949

In [ ]:
# already filtered out everything but the 20 emotions
# now we want to filter evrything but the 39 languages
# Where are lang_name and Language_Names the Same?
emotions_in_survey_languages_in_bila = bila_full_emotions[bila_full_emotions['langname'].isin(merged_filtered['Language_Name'].unique())]

In [160]:
emotions_in_survey_languages_in_bila.reset_index(drop=True)
emotions_in_survey_languages_in_bila

,Unnamed: 0,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,log_count
9,1852,coo.31924067983704,admiration,3.0,10.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,2.397895
10,1977,coo.31924067983704,anger,5.0,85.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,4.454347
11,2014,coo.31924067983704,anxiety,2.0,77.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,4.356709
12,2442,coo.31924067983704,boredom,1.0,11.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,2.484907
13,3016,coo.31924067983704,compassion,2.0,33.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,3.526361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6145,1743853,uva.x004877953,love,10.0,639.0,Japanese,nucl1643,1974,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,6.461468
6146,1744969,uva.x004877953,pleasure,5.0,286.0,Japanese,nucl1643,1974,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,5.659482
6147,1745528,uva.x004877953,regret,5.0,107.0,Japanese,nucl1643,1974,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,4.682131
6148,1745555,uva.x004877953,relief,11.0,89.0,Japanese,nucl1643,1974,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,4.499810
6149,1745817,uva.x004877953,sadness,3.0,9.0,Japanese,nucl1643,1974,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,2.302585

In [163]:
set(emotions) - set(emotions_in_survey_languages_in_bila['word'].unique())

{'calm', 'moved'}

In [116]:
covid_to_bila_full_lang_name_mapping = pd.read_csv("/data/home/asher.katz/hypocognition/reference/covid_to_full_bila_lang_name_mapping.csv")
covid_to_bila_full_lang_name_mapping = covid_to_bila_full_lang_name_mapping.sort_values(by = "easy").reset_index(drop=True)
covid_to_bila_full_lang_name_mapping

,study_language_names,bila_language_name_mapping,possible_alternative_bila_language_name_mappings,easy
0,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese",0
1,Maltese,[No Direct Match],"Arabic, Italian (linguistically related)",0
2,Catalan,[No Direct Match],"Spanish, French (Romance family neighbors)",0
3,Traditional Chinese (Taiwan),Mandarin Chinese,"Min Nan Chinese, Hakka Chinese, Beijing Mandarin",0
4,Serbian,Serbian-Croatian-Bosnian,—,0
5,Croatian,Serbian-Croatian-Bosnian,—,0
6,Traditional Chinese,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese...",0
7,Indonesian,Indonesian,"Standard Malay, Central Malay, Baba Malay",1
8,Hungarian,Hungarian,—,1
9,Italian,Italian,"Sicilian, Aromanian",1
10,Greek,Greek,—,1
11,Dutch,Dutch,"Western Flemish, Afrikaans, Plautdietsch",1
12,Spanish (Spain),Spanish,"Mexican Spanish, Latin American Spanish, Andal...",1
13,Arabic,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar...",1
14,Vietnamese,Vietnamese,Nung (Viet Nam),1
15,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
16,French,French,"Old French, Cajun French, Louisiana Creole Fre...",1
17,Bulgarian,Bulgarian,—,1
18,Swedish,Swedish,—,1
19,German,German,"Middle High German, Moselle Franconian, Pennsy...",1
20,Icelandic,Icelandic,Old Norse,1
21,Danish,Danish,—,1
22,Persian,Persian,—,1
23,Finnish,Finnish,Estonian (closely related),1
24,Brazilian Portuguese,Brazilian Portuguese,Portuguese,1
25,Turkish,Turkish,Turkmen,1
26,Ukrainian,Ukrainian,—,1
27,Spanish (General),Latin American Spanish,"Spanish, Mexican Spanish",1
28,Hebrew,Hebrew,Ancient Hebrew,1
29,Japanese,Japanese,Middle Chinese (historical influence),1
30,Afrikaans,Afrikaans,"Dutch, Western Flemish",1
31,Russian,Russian,Belarusian (closely related),1
32,Georgian,Georgian,—,1
33,Marathi,Marathi,"Hindi, Sanskrit",1

In [147]:
# we need to make some connections with the different chinese lables
#Beijing Mandarin, Yue Chinese, Hakka Chinese, Min Nan Chinese, Mandarin Chinese, Min Dong Chinese,
chinese = bila_full_emotions[bila_full_emotions['langname'].isin(['Beijing Mandarin', 'Yue Chinese', 'Hakka Chinese', 'Min Nan Chinese', 'Mandarin Chinese', 'Min Dong Chinese'])]

In [148]:
chinese_table = (
    chinese
    .pivot_table(
        index="word",
        columns="langname",
        values="count",
        aggfunc="sum",
        fill_value=0
    )
    .reset_index()
    .rename(columns={"word": "Emotion"})
)
chinese_table

langname,Emotion,Beijing Mandarin,Hakka Chinese,Mandarin Chinese,Min Dong Chinese,Min Nan Chinese,Yue Chinese
0,admiration,0.0,2.0,24.0,3.0,2.0,11.0
1,anger,11.0,59.0,59.0,53.0,18.0,60.0
2,anxiety,4.0,13.0,33.0,15.0,5.0,27.0
3,boredom,0.0,0.0,5.0,0.0,0.0,0.0
4,compassion,0.0,5.0,9.0,6.0,4.0,12.0
5,confusion,2.0,16.0,19.0,36.0,3.0,45.0
6,determination,1.0,5.0,8.0,10.0,2.0,10.0
7,disgust,0.0,3.0,3.0,4.0,1.0,3.0
8,fear,5.0,105.0,89.0,68.0,8.0,108.0
9,frustration,0.0,0.0,7.0,0.0,0.0,0.0
10,gratitude,3.0,1.0,20.0,5.0,5.0,6.0
11,hope,6.0,7.0,20.0,11.0,3.0,6.0
12,loneliness,1.0,0.0,4.0,0.0,0.0,0.0
13,love,3.0,57.0,176.0,74.0,19.0,102.0
14,pleasure,4.0,25.0,52.0,33.0,9.0,57.0
15,regret,1.0,14.0,48.0,16.0,4.0,36.0
16,relief,3.0,5.0,28.0,11.0,5.0,8.0
17,sadness,0.0,1.0,7.0,2.0,3.0,2.0

In [ ]:
chinese_table = pd.concat(
    [chinese_table, pd.DataFrame(np.nan, index=range(2), columns=chinese_table.columns)],
    ignore_index=True
)
chinese_table['Emotion'] = emotions
chinese_table

In [151]:
chinese_table.to_csv('/data/home/asher.katz/data/hypocognition/output_results/chinese_table.csv')

In [164]:
merged_filtered.columns

Index(['country', 'countryname', 'language', 'admiration', 'calm',
       'compassion', 'determination', 'moved', 'gratitude', 'hope', 'love',
       'relief', 'pleasure', 'anger', 'anxiety', 'boredom', 'confusion',
       'disgust', 'fear', 'frustration', 'loneliness', 'regret', 'sadness',
       'Language_Name'],
      dtype='object')

In [166]:
bila_full_emotions['word'].unique()

array(['anger', 'anxiety', 'confusion', 'disgust', 'fear', 'love',
       'pleasure', 'regret', 'relief', 'admiration', 'boredom',
       'compassion', 'determination', 'frustration', 'gratitude', 'hope',
       'loneliness', 'sadness'], dtype=object)

In [153]:
merged_filtered_mapped =merged_filtered.merge(
    covid_to_bila_full_lang_name_mapping,
    left_on="Language_Name",
    right_on="study_language_names",
    how="left"
)

merged_filtered_mapped

,country,countryname,language,admiration,calm,compassion,determination,moved,gratitude,hope,...,fear,frustration,loneliness,regret,sadness,Language_Name,study_language_names,bila_language_name_mapping,possible_alternative_bila_language_name_mappings,easy
0,109,Malaysia,MS,1.0,6.0,1.0,0.0,0.0,0.0,6.0,...,6.0,6.0,6.0,6.0,6.0,Malay,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
1,109,Malaysia,ID,1.0,5.0,6.0,4.0,5.0,5.0,5.0,...,4.0,1.0,0.0,1.0,1.0,Indonesian,Indonesian,Indonesian,"Standard Malay, Central Malay, Baba Malay",1
2,109,Malaysia,MS,4.0,4.0,2.0,3.0,2.0,3.0,4.0,...,2.0,2.0,4.0,2.0,3.0,Malay,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
3,109,Malaysia,MS,3.0,3.0,3.0,3.0,3.0,1.0,0.0,...,3.0,0.0,3.0,1.0,4.0,Malay,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
4,109,Malaysia,MS,6.0,3.0,6.0,4.0,6.0,5.0,6.0,...,3.0,4.0,2.0,0.0,2.0,Malay,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17071,91,Kazakhstan,RU,1.0,3.0,3.0,1.0,5.0,5.0,3.0,...,3.0,2.0,3.0,3.0,2.0,Russian,Russian,Russian,Belarusian (closely related),1
17072,91,Kazakhstan,RU,3.0,3.0,6.0,2.0,6.0,5.0,5.0,...,5.0,2.0,2.0,6.0,5.0,Russian,Russian,Russian,Belarusian (closely related),1
17073,91,Kazakhstan,RU,3.0,3.0,3.0,3.0,4.0,4.0,0.0,...,2.0,5.0,4.0,4.0,3.0,Russian,Russian,Russian,Belarusian (closely related),1
17074,91,Kazakhstan,RU,2.0,3.0,6.0,2.0,2.0,1.0,6.0,...,3.0,3.0,1.0,6.0,4.0,Russian,Russian,Russian,Belarusian (closely related),1
17075,91,Kazakhstan,RU,0.0,1.0,4.0,2.0,1.0,3.0,1.0,...,4.0,2.0,0.0,6.0,5.0,Russian,Russian,Russian,Belarusian (closely related),1

In [154]:
df_merged = merged_filtered_mapped.merge(
    bila_full_emotions,
    left_on="bila_language_name_mapping",
    right_on="langname",
    how="left"
)

df_merged

,country,countryname,language,admiration,calm,compassion,determination,moved,gratitude,hope,...,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,log_count
0,109,Malaysia,MS,1.0,6.0,1.0,0.0,0.0,0.0,6.0,...,1992.0,Kamus Inggeris Melayu Dewan = An English-Malay...,"Dewan Bahasa dan Pustaka, Kementerian Pendidik...",0,Eurasia,Austronesian,"Austronesian, Malayo-Polynesian, Malayo-Sumbaw...",101.699,3.08896,2.772589
1,109,Malaysia,MS,1.0,6.0,1.0,0.0,0.0,0.0,6.0,...,1992.0,Kamus Inggeris Melayu Dewan = An English-Malay...,"Dewan Bahasa dan Pustaka, Kementerian Pendidik...",0,Eurasia,Austronesian,"Austronesian, Malayo-Polynesian, Malayo-Sumbaw...",101.699,3.08896,4.934474
2,109,Malaysia,MS,1.0,6.0,1.0,0.0,0.0,0.0,6.0,...,1992.0,Kamus Inggeris Melayu Dewan = An English-Malay...,"Dewan Bahasa dan Pustaka, Kementerian Pendidik...",0,Eurasia,Austronesian,"Austronesian, Malayo-Polynesian, Malayo-Sumbaw...",101.699,3.08896,3.637586
3,109,Malaysia,MS,1.0,6.0,1.0,0.0,0.0,0.0,6.0,...,1992.0,Kamus Inggeris Melayu Dewan = An English-Malay...,"Dewan Bahasa dan Pustaka, Kementerian Pendidik...",0,Eurasia,Austronesian,"Austronesian, Malayo-Polynesian, Malayo-Sumbaw...",101.699,3.08896,1.386294
4,109,Malaysia,MS,1.0,6.0,1.0,0.0,0.0,0.0,6.0,...,1992.0,Kamus Inggeris Melayu Dewan = An English-Malay...,"Dewan Bahasa dan Pustaka, Kementerian Pendidik...",0,Eurasia,Austronesian,"Austronesian, Malayo-Polynesian, Malayo-Sumbaw...",101.699,3.08896,1.098612
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294328,91,Kazakhstan,RU,0.0,1.0,4.0,2.0,1.0,3.0,1.0,...,1999.0,Random House Russian-English English-Russian d...,"Random House, c1999.",0,Eurasia,Indo-European,"Indo-European, Classical Indo-European, Balto-...",50.000,59.00000,3.044522
294329,91,Kazakhstan,RU,0.0,1.0,4.0,2.0,1.0,3.0,1.0,...,1999.0,Random House Russian-English English-Russian d...,"Random House, c1999.",0,Eurasia,Indo-European,"Indo-European, Classical Indo-European, Balto-...",50.000,59.00000,2.484907
294330,91,Kazakhstan,RU,0.0,1.0,4.0,2.0,1.0,3.0,1.0,...,1999.0,Random House Russian-English English-Russian d...,"Random House, c1999.",0,Eurasia,Indo-European,"Indo-European, Classical Indo-European, Balto-...",50.000,59.00000,1.945910
294331,91,Kazakhstan,RU,0.0,1.0,4.0,2.0,1.0,3.0,1.0,...,1999.0,Random House Russian-English English-Russian d...,"Random House, c1999.",0,Eurasia,Indo-European,"Indo-European, Classical Indo-European, Balto-...",50.000,59.00000,2.079442
294332,91,Kazakhstan,RU,0.0,1.0,4.0,2.0,1.0,3.0,1.0,...,1999.0,Random House Russian-English English-Russian d...,"Random House, c1999.",0,Eurasia,Indo-European,"Indo-European, Classical Indo-European, Balto-...",50.000,59.00000,1.098612