In [1]:
# get the data maniplulation library 
import pandas as pd
import numpy as np
import re
import math
import gc
import plotly.graph_objects as go
import plotly.express as px
gc.collect()

10

In [2]:
Covid51countries = pd.read_csv('/data/home/asher.katz/data/hypocognition/Covid51countries.csv')
Covid51countries

,country,countryname,StartDate,EndDate,Status,Progress,Duration,Finished,RecordedDate,home,...,gender,ladder,employment,losejob,covidsymptom,language,datasource,ISO3,longstring,na_count
0,10,Australia,04/05/2020 19:34,04/05/2020 19:40,0.0,100.0,337.0,1.0,04/05/2020 19:40,8.0,...,1.0,5.0,4,NaN,0.0,ZH-S,snowball,AUS,3,0
1,10,Australia,04/05/2020 20:26,04/05/2020 20:35,0.0,100.0,530.0,1.0,04/05/2020 20:35,9.0,...,2.0,7.0,3,NaN,NaN,ZH-S,snowball,AUS,3,0
2,10,Australia,05/05/2020 21:54,05/05/2020 22:07,0.0,100.0,793.0,1.0,05/05/2020 22:07,29.0,...,1.0,4.0,1,NaN,0.0,ZH-S,snowball,AUS,5,0
3,10,Australia,04/05/2020 20:29,04/05/2020 20:34,0.0,100.0,285.0,1.0,04/05/2020 20:34,73.0,...,2.0,5.0,4,NaN,0.0,ZH-S,snowball,AUS,4,0
4,10,Australia,19/04/2020 20:21,19/04/2020 20:27,0.0,100.0,367.0,1.0,19/04/2020 20:27,100.0,...,1.0,5.0,1,NaN,0.0,ZH-S,snowball,AUS,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24216,92,Kenya,25/04/2020 01:25,25/04/2020 02:44,0.0,100.0,4690.0,1.0,25/04/2020 02:44,100.0,...,2.0,4.0,4,NaN,0.0,EN,snowball,KEN,4,0
24217,92,Kenya,24/04/2020 11:06,24/04/2020 11:15,0.0,100.0,556.0,1.0,24/04/2020 11:15,100.0,...,1.0,6.0,5,0.0,0.0,EN,snowball,KEN,2,0
24218,92,Kenya,26/04/2020 10:16,26/04/2020 10:36,0.0,100.0,1218.0,1.0,26/04/2020 10:36,80.0,...,1.0,3.0,4,NaN,0.0,EN,snowball,KEN,3,0
24219,92,Kenya,23/04/2020 03:46,23/04/2020 04:13,0.0,100.0,1641.0,1.0,23/04/2020 04:13,3.0,...,1.0,3.0,4,NaN,0.0,EN,snowball,KEN,3,0
24220,92,Kenya,24/04/2020 00:31,24/04/2020 00:42,0.0,100.0,700.0,1.0,24/04/2020 00:42,50.0,...,2.0,6.0,4,NaN,0.0,EN,snowball,KEN,2,0

In [161]:
# we need to discard any countries where the primary language is definitly english, and for the remainder, select 1 primary language
selection = pd.read_csv("~/data/hypocognition/languages_per_country_selections.csv", index_col=0).reset_index(drop=True)
selection = selection.drop(['ISO3',	'Unnamed: 8', 'lang_responses',	'total_responses',	'percent'	], axis=1).reset_index(drop=True)
selection

    country language        countryname
0        26    PT-BR             Brazil
1        28       BG           Bulgaria
2        37       ES              Chile
3        38     ZH-S              China
4        39       ES           Colombia
5        45       HR            Croatia
6        47       NL            Curacao
7        50       DA            Denmark
8        55       AR              Egypt
9        63       FI            Finland
10       64       FR             France
11       67      KAT            Georgia
12       68       DE            Germany
13       70       EL             Greece
14       78     ZH-T  Hong Kong (S.A.R)
15       78     ZH-S  Hong Kong (S.A.R)
16       79       HU            Hungary
17       80      ISL            Iceland
18       81      MAR              India
19       82       ID          Indonesia
20       83       FA               Iran
21       86       HE             Israel
22       87       IT              Italy
23       89       JA              Japan
24       90       AR             Jordan
25       91       RU         Kazakhstan
26      109       MS           Malaysia
27      112    MALTI              Malta
28      128       NL        Netherlands
29      143    ES-ES               Peru
30      149       RU             Russia
31      160       SR             Serbia
32      170     AFRI       South Africa
33      173    ES-ES              Spain
34      177       SV             Sweden
35      179       AR              Syria
36      180    ZH-TW             Taiwan
37      189       TR             Turkey
38      193       UK            Ukraine
39      202       VI            Vietnam

In [164]:
filtered = Covid51countries.merge(
    selection[['country', 'language']],
    on=['country', 'language'],
    how='inner'
)

filtered

,country,countryname,StartDate,EndDate,Status,Progress,Duration,Finished,RecordedDate,home,...,gender,ladder,employment,losejob,covidsymptom,language,datasource,ISO3,longstring,na_count
0,109,Malaysia,21/04/2020 19:11,21/04/2020 19:34,0.0,100.0,1373.0,1.0,21/04/2020 19:34,97.0,...,2.0,8.0,4,NaN,1.0,MS,snowball,MYS,9,0
1,109,Malaysia,21/04/2020 06:27,21/04/2020 06:46,0.0,100.0,1135.0,1.0,21/04/2020 06:46,100.0,...,1.0,7.0,1,NaN,0.0,MS,snowball,MYS,3,0
2,109,Malaysia,20/04/2020 21:14,20/04/2020 21:29,0.0,100.0,951.0,1.0,20/04/2020 21:29,NaN,...,1.0,4.0,1,NaN,0.0,MS,snowball,MYS,5,0
3,109,Malaysia,21/04/2020 02:24,21/04/2020 02:37,0.0,100.0,745.0,1.0,21/04/2020 02:37,100.0,...,2.0,1.0,2,NaN,1.0,MS,snowball,MYS,2,0
4,109,Malaysia,20/04/2020 22:00,20/04/2020 22:09,0.0,100.0,538.0,1.0,20/04/2020 22:09,100.0,...,2.0,8.0,1,NaN,0.0,MS,snowball,MYS,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15072,91,Kazakhstan,25/04/2020 13:36,25/04/2020 13:44,0.0,100.0,470.0,1.0,25/04/2020 13:44,100.0,...,2.0,8.0,1,NaN,1.0,RU,snowball,KAZ,3,0
15073,91,Kazakhstan,06/05/2020 04:03,06/05/2020 04:18,0.0,100.0,884.0,1.0,06/05/2020 04:18,100.0,...,2.0,4.0,5,1.0,0.0,RU,snowball,KAZ,3,0
15074,91,Kazakhstan,06/05/2020 12:32,06/05/2020 12:41,0.0,100.0,573.0,1.0,06/05/2020 12:41,100.0,...,1.0,4.0,5,1.0,0.0,RU,snowball,KAZ,4,0
15075,91,Kazakhstan,06/05/2020 10:37,06/05/2020 10:49,0.0,100.0,701.0,1.0,06/05/2020 10:49,100.0,...,2.0,8.0,5,0.0,0.0,RU,snowball,KAZ,5,0
15076,91,Kazakhstan,06/05/2020 11:19,06/05/2020 11:32,0.0,100.0,776.0,1.0,06/05/2020 11:32,100.0,...,2.0,6.0,1,NaN,0.0,RU,snowball,KAZ,2,0

In [82]:
# Are the languages in the "filtered" dataset actually filtered and now match the selected languages?
set(filtered['language'].unique()) == set(selection['language'].unique())

True

In [83]:
#Are the countries in the "filtered" dataset actually filtered and now match the selected countries?
set(filtered['countryname'].unique()) == set(selection['countryname'].unique())

True

In [165]:
filtered = filtered.reset_index(drop=True)

Goals
* For each distinct language, what is the lexical ellaboration for each of the 20 emotions?
* For each distinct language, is there any statistical significance in the distribution of the results of any particular emotion?

In [167]:
# drop the rest of the ~75 columns
filtered = filtered[['country', 'countryname', 'language', 'admiration', 'calm', 'compassion',
       'determination', 'moved', 'gratitude', 'hope', 'love', 'relief',
       'pleasure', 'anger', 'anxiety', 'boredom', 'confusion', 'disgust',
       'fear', 'frustration', 'loneliness', 'regret', 'sadness']].copy()

In [169]:
# get a table which translates the language codes into names
lang_names = pd.read_csv('/data/home/asher.katz/hypocognition/reference/lang_names.csv')
merged_filtered = filtered.merge(lang_names, left_on="language", right_on="Code", how="left")
merged_filtered = merged_filtered.drop(columns=["Code"])
merged_filtered

,country,countryname,language,admiration,calm,compassion,determination,moved,gratitude,hope,...,anxiety,boredom,confusion,disgust,fear,frustration,loneliness,regret,sadness,Language_Name
0,109,Malaysia,MS,1.0,6.0,1.0,0.0,0.0,0.0,6.0,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,Malay
1,109,Malaysia,MS,4.0,4.0,2.0,3.0,2.0,3.0,4.0,...,2.0,4.0,3.0,2.0,2.0,2.0,4.0,2.0,3.0,Malay
2,109,Malaysia,MS,3.0,3.0,3.0,3.0,3.0,1.0,0.0,...,3.0,3.0,0.0,0.0,3.0,0.0,3.0,1.0,4.0,Malay
3,109,Malaysia,MS,6.0,3.0,6.0,4.0,6.0,5.0,6.0,...,3.0,6.0,4.0,0.0,3.0,4.0,2.0,0.0,2.0,Malay
4,109,Malaysia,MS,5.0,5.0,5.0,6.0,4.0,6.0,5.0,...,3.0,1.0,2.0,2.0,2.0,3.0,0.0,2.0,3.0,Malay
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15072,91,Kazakhstan,RU,1.0,3.0,3.0,1.0,5.0,5.0,3.0,...,2.0,3.0,2.0,2.0,3.0,2.0,3.0,3.0,2.0,Russian
15073,91,Kazakhstan,RU,3.0,3.0,6.0,2.0,6.0,5.0,5.0,...,4.0,4.0,0.0,1.0,5.0,2.0,2.0,6.0,5.0,Russian
15074,91,Kazakhstan,RU,3.0,3.0,3.0,3.0,4.0,4.0,0.0,...,2.0,0.0,3.0,3.0,2.0,5.0,4.0,4.0,3.0,Russian
15075,91,Kazakhstan,RU,2.0,3.0,6.0,2.0,2.0,1.0,6.0,...,4.0,3.0,3.0,3.0,3.0,3.0,1.0,6.0,4.0,Russian
15076,91,Kazakhstan,RU,0.0,1.0,4.0,2.0,1.0,3.0,1.0,...,4.0,0.0,1.0,0.0,4.0,2.0,0.0,6.0,5.0,Russian

In [87]:
merged_filtered['Language_Name'].nunique()

34

In [89]:
emotions = ['admiration', 'calm', 'compassion',
       'determination', 'moved', 'gratitude', 'hope', 'love', 'relief',
       'pleasure', 'anger', 'anxiety', 'boredom', 'confusion', 'disgust',
       'fear', 'frustration', 'loneliness', 'regret', 'sadness']

In [90]:
len(emotions)

20

In [91]:
# get the dataset of the dictionaries. We will look at how elaborated each of the twenty emotions are in each of the 39 languages
bila_nouns_full = pd.read_csv("/data/home/asher.katz/data/Fundemental-Emotions/output_results/bila_long_noun_lemmatized_full.csv", index_col=0)
bila_nouns_full

/tmp/ipykernel_927767/802338402.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  bila_nouns_full = pd.read_csv("/data/home/asher.katz/data/Fundemental-Emotions/output_results/bila_long_noun_lemmatized_full.csv", index_col=0)

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,log_count
0,chi.14718491,abdomen,2.0,1.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,0.693147
1,chi.14718491,ability,2.0,2.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,1.098612
2,chi.14718491,absence,4.0,2.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,1.098612
3,chi.14718491,abstinence,2.0,5.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,1.791759
4,chi.14718491,abundance,3.0,4.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,1.609438
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1824416,wu.89119131142,zephyr,2.0,2.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,1.098612
1824417,wu.89119131142,zinc,2.0,2.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,1.098612
1824418,wu.89119131142,zone,6.0,4.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,1.609438
1824419,wu.89119131142,zoo,1.0,1.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,0.693147
1824420,wu.89119131142,zoom,5.0,1.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,0.693147

In [227]:
dictionary_means = (
    bila_nouns_full
        .groupby('id', as_index=False)['count']
        .mean()
        .rename(columns={'count': 'dictionary_count_mean'})
)
dictionary_means

                                          id  dictionary_count_mean
0                               chi.14718491               8.153281
1                         coo.31924067983704              22.086550
2                         coo.31924099174934               2.813851
3                  coo1.ark:/13960/t9m33d507               5.176960
4     dictionaria.daakaka_vonprince_daka1243               2.854041
..                                       ...                    ...
611  webonary.sursurunga_hutchisson_surs1246              22.626872
612         webonary.tampulma_asare_tamp1252               8.364666
613      webonary.turkmen_almamedow_turk1304               9.002773
614                           wu.89017649658               4.613689
615                           wu.89119131142              13.889959

[616 rows x 2 columns]

In [92]:
bila_nouns_full_emotions = bila_nouns_full[bila_nouns_full['word'].isin(emotions)].reset_index(drop=True)
bila_nouns_full_emotions

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,log_count
0,chi.14718491,anger,5.0,2.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,1.098612
1,chi.14718491,anxiety,2.0,1.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,0.693147
2,chi.14718491,confusion,5.0,1.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,0.693147
3,chi.14718491,disgust,3.0,4.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,1.609438
4,chi.14718491,fear,8.0,9.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,2.302585
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6466,wu.89119131142,love,10.0,75.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,4.330733
6467,wu.89119131142,pleasure,5.0,13.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,2.639057
6468,wu.89119131142,regret,5.0,11.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,2.484907
6469,wu.89119131142,relief,11.0,10.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,2.397895
6470,wu.89119131142,sadness,3.0,12.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,2.564949

In [93]:
ne = bila_nouns_full_emotions['word'].unique()
ne

array(['anger', 'anxiety', 'confusion', 'disgust', 'fear', 'love',
       'pleasure', 'regret', 'relief', 'admiration', 'boredom',
       'compassion', 'determination', 'frustration', 'gratitude', 'hope',
       'loneliness', 'sadness'], dtype=object)

In [94]:
set(emotions) - set(ne)

{'calm', 'moved'}

So the dataset is missing two of the survey emotions

In [95]:
bila_nouns_full[bila_nouns_full['word']=='moved']

Empty DataFrame
Columns: [id, word, nsenses, count, langname, glottocode, year, title, imprint, author, area, langfamily, affiliation, longitude, latitude, log_count]
Index: []

In [96]:
bila_nouns_full[bila_nouns_full['word']=='calm']

Empty DataFrame
Columns: [id, word, nsenses, count, langname, glottocode, year, title, imprint, author, area, langfamily, affiliation, longitude, latitude, log_count]
Index: []

In [97]:
bila_nouns_verbs_adjs_full = pd.read_csv('/data/home/asher.katz/data/Fundemental-Emotions/biladataset/bila_long_nounverbadj_full.csv', index_col=0)
bila_nouns_verbs_adjs_full

                                                  word    count
id
aeu.ark:/13960/t1cj95d96                    abandoning      3.0
aeu.ark:/13960/t1cj95d96                     abatement      2.0
aeu.ark:/13960/t1cj95d96                         abide      7.0
aeu.ark:/13960/t1cj95d96                       abiding      2.0
aeu.ark:/13960/t1cj95d96                       ability      4.0
...                                                ...      ...
wu.89063890263            all_wiktionary_filtered_data   2244.0
wu.89067554840            all_wiktionary_filtered_data   1376.0
wu.89091407866            all_wiktionary_filtered_data  61587.0
wu.89092536275            all_wiktionary_filtered_data    109.0
wu.89104398193            all_wiktionary_filtered_data    215.0

[21335425 rows x 2 columns]

In [39]:
bila_nouns_verbs_adjs_full[bila_nouns_verbs_adjs_full['word']=='moved']

                           word  count
id
aeu.ark:/13960/t1cj95d96  moved    6.0
aeu.ark:/13960/t2x36pn57  moved    1.0
aeu.ark:/13960/t9087337n  moved    3.0
bc.ark:/13960/t01051k5f   moved   81.0
chi.085159567             moved    3.0
...                         ...    ...
uva.x001179297            moved    NaN
uva.x001180088            moved    NaN
uva.x002016721            moved    NaN
uva.x002599880            moved    NaN
uva.x004082894            moved    NaN

[1874 rows x 2 columns]

In [40]:
bila_nouns_verbs_adjs_full[bila_nouns_verbs_adjs_full['word']=='calm']

                          word  count
id
aeu.ark:/13960/t1cj95d96  calm   12.0
aeu.ark:/13960/t2x36pn57  calm    1.0
aeu.ark:/13960/t8bg3nq48  calm    2.0
aeu.ark:/13960/t9087337n  calm    6.0
bc.ark:/13960/t01051k5f   calm   56.0
...                        ...    ...
uc1.31210008444158        calm    NaN
uc2.ark:/13960/t36114x4w  calm    NaN
uva.x001152873            calm    NaN
uva.x002186953            calm    NaN
uva.x002252932            calm    NaN

[2300 rows x 2 columns]

In [63]:
bila_nouns_verbs_adjs_full['word'].nunique()

20195

In [98]:
covid_to_bila_lang_name_mapping = pd.read_csv("/data/home/asher.katz/hypocognition/reference/covid_to_bila_lang_name_mapping.csv")
covid_to_bila_lang_name_mapping = covid_to_bila_lang_name_mapping.sort_values(by = "easy")
covid_to_bila_lang_name_mapping

,study_language_names,bila_language_name_mapping,possible_alternative_bila_language_name_mappings,easy
2,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Yue Chinese, Hakka Chinese",0
6,Maltese,[No direct match],"Arabic, Italian (linguistically related)",0
23,Brazilian Portuguese,Portuguese,—,0
27,Catalan,[No direct match],"Spanish, French (Romance family)",0
24,Serbian,Serbian-Croatian-Bosnian,—,0
26,Croatian,Serbian-Croatian-Bosnian,—,0
17,Traditional Chinese (Taiwan),Mandarin Chinese,"Min Nan Chinese, Hakka Chinese",0
32,Traditional Chinese,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese",0
8,Hungarian,Hungarian,—,1
9,Italian,Italian,Sicilian,1
10,Greek,Greek,—,1
0,Malay,Standard Malay,Indonesian,1
3,Spanish (Spain),Spanish,Latin American Spanish,1
4,Arabic,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar...",1
5,Vietnamese,Vietnamese,—,1
1,Indonesian,Indonesian,Standard Malay,1
15,French,French,"Cajun French, Louisiana Creole French, Old French",1
14,Bulgarian,Bulgarian,—,1
13,Swedish,Swedish,—,1
12,German,German,"Moselle Franconian, Plautdietsch",1
11,Dutch,Dutch,Western Flemish,1
19,Finnish,Finnish,—,1
18,Persian,Persian,—,1
16,Danish,Danish,—,1
22,Turkish,Turkish,—,1
21,Ukrainian,Ukrainian,—,1
20,Icelandic,Icelandic,Old Norse,1
25,Spanish (General),Latin American Spanish,Spanish,1
28,Hebrew,Hebrew,Ancient Hebrew,1
29,Japanese,Japanese,—,1
30,Afrikaans,Afrikaans,Dutch,1
7,Russian,Russian,—,1
31,Georgian,Georgian,—,1
33,Marathi,Marathi,—,1

In [144]:
# already filtered out everything but the 20 emotions
# now we want to filter evrything but the 39 languages
# Where are lang_name and Language_Names the Same?
emotions_in_survey_languages_in_bila = bila_nouns_full_emotions[bila_nouns_full_emotions['langname'].isin(merged_filtered['Language_Name'].unique())].reset_index(drop=True)
emotions_in_survey_languages_in_bila

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,log_count
0,coo.31924067983704,admiration,3.0,10.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,2.397895
1,coo.31924067983704,anger,5.0,85.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,4.454347
2,coo.31924067983704,anxiety,2.0,77.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,4.356709
3,coo.31924067983704,boredom,1.0,11.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,2.484907
4,coo.31924067983704,compassion,2.0,33.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,3.526361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409,uva.x004877953,love,10.0,639.0,Japanese,nucl1643,1974,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,6.461468
410,uva.x004877953,pleasure,5.0,286.0,Japanese,nucl1643,1974,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,5.659482
411,uva.x004877953,regret,5.0,107.0,Japanese,nucl1643,1974,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,4.682131
412,uva.x004877953,relief,11.0,89.0,Japanese,nucl1643,1974,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,4.499810
413,uva.x004877953,sadness,3.0,9.0,Japanese,nucl1643,1974,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,2.302585

In [145]:
covid_to_bila_nouns_full_lang_name_mapping = pd.read_csv("/data/home/asher.katz/hypocognition/reference/covid_to_full_bila_lang_name_mapping.csv")
covid_to_bila_nouns_full_lang_name_mapping = covid_to_bila_nouns_full_lang_name_mapping.sort_values(by = "easy").reset_index(drop=True)
covid_to_bila_nouns_full_lang_name_mapping

,study_language_names,bila_language_name_mapping,possible_alternative_bila_language_name_mappings,easy
0,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese",0
1,Maltese,[No Direct Match],"Arabic, Italian (linguistically related)",0
2,Catalan,[No Direct Match],"Spanish, French (Romance family neighbors)",0
3,Traditional Chinese (Taiwan),Mandarin Chinese,"Min Nan Chinese, Hakka Chinese, Beijing Mandarin",0
4,Serbian,Serbian-Croatian-Bosnian,—,0
5,Croatian,Serbian-Croatian-Bosnian,—,0
6,Traditional Chinese,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese...",0
7,Indonesian,Indonesian,"Standard Malay, Central Malay, Baba Malay",1
8,Hungarian,Hungarian,—,1
9,Italian,Italian,"Sicilian, Aromanian",1
10,Greek,Greek,—,1
11,Dutch,Dutch,"Western Flemish, Afrikaans, Plautdietsch",1
12,Spanish (Spain),Spanish,"Mexican Spanish, Latin American Spanish, Andal...",1
13,Arabic,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar...",1
14,Vietnamese,Vietnamese,Nung (Viet Nam),1
15,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
16,French,French,"Old French, Cajun French, Louisiana Creole Fre...",1
17,Bulgarian,Bulgarian,—,1
18,Swedish,Swedish,—,1
19,German,German,"Middle High German, Moselle Franconian, Pennsy...",1
20,Icelandic,Icelandic,Old Norse,1
21,Danish,Danish,—,1
22,Persian,Persian,—,1
23,Finnish,Finnish,Estonian (closely related),1
24,Brazilian Portuguese,Brazilian Portuguese,Portuguese,1
25,Turkish,Turkish,Turkmen,1
26,Ukrainian,Ukrainian,—,1
27,Spanish (General),Latin American Spanish,"Spanish, Mexican Spanish",1
28,Hebrew,Hebrew,Ancient Hebrew,1
29,Japanese,Japanese,Middle Chinese (historical influence),1
30,Afrikaans,Afrikaans,"Dutch, Western Flemish",1
31,Russian,Russian,Belarusian (closely related),1
32,Georgian,Georgian,—,1
33,Marathi,Marathi,"Hindi, Sanskrit",1

In [102]:
# we need to make some connections with the different chinese lables
#Beijing Mandarin, Yue Chinese, Hakka Chinese, Min Nan Chinese, Mandarin Chinese, Min Dong Chinese,
chinese = bila_nouns_full_emotions[bila_nouns_full_emotions['langname'].isin(['Beijing Mandarin', 'Yue Chinese', 'Hakka Chinese', 'Min Nan Chinese', 'Mandarin Chinese', 'Min Dong Chinese'])]
chinese

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,log_count
1480,mdp.39015031036794,anger,5.0,11.0,Beijing Mandarin,beij1234,1910,English-Chinese pocket dictionary of Peking co...,"American Presbyterian Mission Press, 1910.",0,Eurasia,Sino-Tibetan,"Sino-Tibetan, Sinitic, Classical-Middle-Modern...",116.117277,39.938547,2.484907
1481,mdp.39015031036794,anxiety,2.0,4.0,Beijing Mandarin,beij1234,1910,English-Chinese pocket dictionary of Peking co...,"American Presbyterian Mission Press, 1910.",0,Eurasia,Sino-Tibetan,"Sino-Tibetan, Sinitic, Classical-Middle-Modern...",116.117277,39.938547,1.609438
1482,mdp.39015031036794,confusion,5.0,2.0,Beijing Mandarin,beij1234,1910,English-Chinese pocket dictionary of Peking co...,"American Presbyterian Mission Press, 1910.",0,Eurasia,Sino-Tibetan,"Sino-Tibetan, Sinitic, Classical-Middle-Modern...",116.117277,39.938547,1.098612
1483,mdp.39015031036794,determination,5.0,1.0,Beijing Mandarin,beij1234,1910,English-Chinese pocket dictionary of Peking co...,"American Presbyterian Mission Press, 1910.",0,Eurasia,Sino-Tibetan,"Sino-Tibetan, Sinitic, Classical-Middle-Modern...",116.117277,39.938547,0.693147
1484,mdp.39015031036794,fear,8.0,5.0,Beijing Mandarin,beij1234,1910,English-Chinese pocket dictionary of Peking co...,"American Presbyterian Mission Press, 1910.",0,Eurasia,Sino-Tibetan,"Sino-Tibetan, Sinitic, Classical-Middle-Modern...",116.117277,39.938547,1.791759
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5089,uc1.l0088545033,love,10.0,176.0,Mandarin Chinese,mand1415,2004,Wai yan she jing bian Ying Han Han Ying ci dia...,"Wai yu jiao xue yu yan jiu chu ban she, 2004, ...",0,Eurasia,Sino-Tibetan,"Sino-Tibetan, Sinitic, Classical-Middle-Modern...",116.228000,40.020900,5.176150
5090,uc1.l0088545033,pleasure,5.0,52.0,Mandarin Chinese,mand1415,2004,Wai yan she jing bian Ying Han Han Ying ci dia...,"Wai yu jiao xue yu yan jiu chu ban she, 2004, ...",0,Eurasia,Sino-Tibetan,"Sino-Tibetan, Sinitic, Classical-Middle-Modern...",116.228000,40.020900,3.970292
5091,uc1.l0088545033,regret,5.0,48.0,Mandarin Chinese,mand1415,2004,Wai yan she jing bian Ying Han Han Ying ci dia...,"Wai yu jiao xue yu yan jiu chu ban she, 2004, ...",0,Eurasia,Sino-Tibetan,"Sino-Tibetan, Sinitic, Classical-Middle-Modern...",116.228000,40.020900,3.891820
5092,uc1.l0088545033,relief,11.0,28.0,Mandarin Chinese,mand1415,2004,Wai yan she jing bian Ying Han Han Ying ci dia...,"Wai yu jiao xue yu yan jiu chu ban she, 2004, ...",0,Eurasia,Sino-Tibetan,"Sino-Tibetan, Sinitic, Classical-Middle-Modern...",116.228000,40.020900,3.367296
5093,uc1.l0088545033,sadness,3.0,7.0,Mandarin Chinese,mand1415,2004,Wai yan she jing bian Ying Han Han Ying ci dia...,"Wai yu jiao xue yu yan jiu chu ban she, 2004, ...",0,Eurasia,Sino-Tibetan,"Sino-Tibetan, Sinitic, Classical-Middle-Modern...",116.228000,40.020900,2.079442

In [103]:
chinese_table = (
    chinese
    .pivot_table(
        index="word",
        columns="langname",
        values="count",
        aggfunc="sum",
        fill_value=0
    )
    .reset_index()
    .rename(columns={"word": "Emotion"})
)
chinese_table

langname,Emotion,Beijing Mandarin,Hakka Chinese,Mandarin Chinese,Min Dong Chinese,Min Nan Chinese,Yue Chinese
0,admiration,0.0,2.0,24.0,3.0,2.0,11.0
1,anger,11.0,59.0,59.0,53.0,18.0,60.0
2,anxiety,4.0,13.0,33.0,15.0,5.0,27.0
3,boredom,0.0,0.0,5.0,0.0,0.0,0.0
4,compassion,0.0,5.0,9.0,6.0,4.0,12.0
5,confusion,2.0,16.0,19.0,36.0,3.0,45.0
6,determination,1.0,5.0,8.0,10.0,2.0,10.0
7,disgust,0.0,3.0,3.0,4.0,1.0,3.0
8,fear,5.0,105.0,89.0,68.0,8.0,108.0
9,frustration,0.0,0.0,7.0,0.0,0.0,0.0
10,gratitude,3.0,1.0,20.0,5.0,5.0,6.0
11,hope,6.0,7.0,20.0,11.0,3.0,6.0
12,loneliness,1.0,0.0,4.0,0.0,0.0,0.0
13,love,3.0,57.0,176.0,74.0,19.0,102.0
14,pleasure,4.0,25.0,52.0,33.0,9.0,57.0
15,regret,1.0,14.0,48.0,16.0,4.0,36.0
16,relief,3.0,5.0,28.0,11.0,5.0,8.0
17,sadness,0.0,1.0,7.0,2.0,3.0,2.0

In [104]:
chinese_table = pd.concat(
    [chinese_table, pd.DataFrame(np.nan, index=range(2), columns=chinese_table.columns)],
    ignore_index=True
)
chinese_table

langname,Emotion,Beijing Mandarin,Hakka Chinese,Mandarin Chinese,Min Dong Chinese,Min Nan Chinese,Yue Chinese
0,admiration,0.0,2.0,24.0,3.0,2.0,11.0
1,anger,11.0,59.0,59.0,53.0,18.0,60.0
2,anxiety,4.0,13.0,33.0,15.0,5.0,27.0
3,boredom,0.0,0.0,5.0,0.0,0.0,0.0
4,compassion,0.0,5.0,9.0,6.0,4.0,12.0
5,confusion,2.0,16.0,19.0,36.0,3.0,45.0
6,determination,1.0,5.0,8.0,10.0,2.0,10.0
7,disgust,0.0,3.0,3.0,4.0,1.0,3.0
8,fear,5.0,105.0,89.0,68.0,8.0,108.0
9,frustration,0.0,0.0,7.0,0.0,0.0,0.0
10,gratitude,3.0,1.0,20.0,5.0,5.0,6.0
11,hope,6.0,7.0,20.0,11.0,3.0,6.0
12,loneliness,1.0,0.0,4.0,0.0,0.0,0.0
13,love,3.0,57.0,176.0,74.0,19.0,102.0
14,pleasure,4.0,25.0,52.0,33.0,9.0,57.0
15,regret,1.0,14.0,48.0,16.0,4.0,36.0
16,relief,3.0,5.0,28.0,11.0,5.0,8.0
17,sadness,0.0,1.0,7.0,2.0,3.0,2.0
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [105]:
chinese_table.loc[18,'Emotion'] = "calm"
chinese_table.loc[19,'Emotion'] = "moved"
chinese_table

langname,Emotion,Beijing Mandarin,Hakka Chinese,Mandarin Chinese,Min Dong Chinese,Min Nan Chinese,Yue Chinese
0,admiration,0.0,2.0,24.0,3.0,2.0,11.0
1,anger,11.0,59.0,59.0,53.0,18.0,60.0
2,anxiety,4.0,13.0,33.0,15.0,5.0,27.0
3,boredom,0.0,0.0,5.0,0.0,0.0,0.0
4,compassion,0.0,5.0,9.0,6.0,4.0,12.0
5,confusion,2.0,16.0,19.0,36.0,3.0,45.0
6,determination,1.0,5.0,8.0,10.0,2.0,10.0
7,disgust,0.0,3.0,3.0,4.0,1.0,3.0
8,fear,5.0,105.0,89.0,68.0,8.0,108.0
9,frustration,0.0,0.0,7.0,0.0,0.0,0.0
10,gratitude,3.0,1.0,20.0,5.0,5.0,6.0
11,hope,6.0,7.0,20.0,11.0,3.0,6.0
12,loneliness,1.0,0.0,4.0,0.0,0.0,0.0
13,love,3.0,57.0,176.0,74.0,19.0,102.0
14,pleasure,4.0,25.0,52.0,33.0,9.0,57.0
15,regret,1.0,14.0,48.0,16.0,4.0,36.0
16,relief,3.0,5.0,28.0,11.0,5.0,8.0
17,sadness,0.0,1.0,7.0,2.0,3.0,2.0
18,calm,NaN,NaN,NaN,NaN,NaN,NaN
19,moved,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
chinese_table.to_csv('/data/home/asher.katz/data/hypocognition/output_results/chinese_table.csv')

In [170]:
# Add a language name pa for the the bila dataset language names
merged_filtered_mapped =merged_filtered.merge(
    covid_to_bila_nouns_full_lang_name_mapping,
    left_on="Language_Name",
    right_on="study_language_names",
    how="left"
)

merged_filtered_mapped

,country,countryname,language,admiration,calm,compassion,determination,moved,gratitude,hope,...,fear,frustration,loneliness,regret,sadness,Language_Name,study_language_names,bila_language_name_mapping,possible_alternative_bila_language_name_mappings,easy
0,109,Malaysia,MS,1.0,6.0,1.0,0.0,0.0,0.0,6.0,...,6.0,6.0,6.0,6.0,6.0,Malay,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
1,109,Malaysia,MS,4.0,4.0,2.0,3.0,2.0,3.0,4.0,...,2.0,2.0,4.0,2.0,3.0,Malay,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
2,109,Malaysia,MS,3.0,3.0,3.0,3.0,3.0,1.0,0.0,...,3.0,0.0,3.0,1.0,4.0,Malay,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
3,109,Malaysia,MS,6.0,3.0,6.0,4.0,6.0,5.0,6.0,...,3.0,4.0,2.0,0.0,2.0,Malay,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
4,109,Malaysia,MS,5.0,5.0,5.0,6.0,4.0,6.0,5.0,...,2.0,3.0,0.0,2.0,3.0,Malay,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15072,91,Kazakhstan,RU,1.0,3.0,3.0,1.0,5.0,5.0,3.0,...,3.0,2.0,3.0,3.0,2.0,Russian,Russian,Russian,Belarusian (closely related),1
15073,91,Kazakhstan,RU,3.0,3.0,6.0,2.0,6.0,5.0,5.0,...,5.0,2.0,2.0,6.0,5.0,Russian,Russian,Russian,Belarusian (closely related),1
15074,91,Kazakhstan,RU,3.0,3.0,3.0,3.0,4.0,4.0,0.0,...,2.0,5.0,4.0,4.0,3.0,Russian,Russian,Russian,Belarusian (closely related),1
15075,91,Kazakhstan,RU,2.0,3.0,6.0,2.0,2.0,1.0,6.0,...,3.0,3.0,1.0,6.0,4.0,Russian,Russian,Russian,Belarusian (closely related),1
15076,91,Kazakhstan,RU,0.0,1.0,4.0,2.0,1.0,3.0,1.0,...,4.0,2.0,0.0,6.0,5.0,Russian,Russian,Russian,Belarusian (closely related),1

In [147]:
merged_filtered_mapped["study_language_names"].nunique()

33

In [148]:
merged_filtered_mapped["bila_language_name_mapping"].nunique()

30

In [149]:
merged_filtered_mapped['countryname'].nunique()

39

## the discrepency is because Mandarin Chinese, [No Direct Match], Serbian-Croatian-Bosnian, and something else appear for more than one country. 39 countries -> 33 response languages -> 30 bila dictionarys.

In [107]:
merged_filtered_mapped

,country,countryname,language,admiration,calm,compassion,determination,moved,gratitude,hope,...,fear,frustration,loneliness,regret,sadness,Language_Name,study_language_names,bila_language_name_mapping,possible_alternative_bila_language_name_mappings,easy
0,109,Malaysia,MS,1.0,6.0,1.0,0.0,0.0,0.0,6.0,...,6.0,6.0,6.0,6.0,6.0,Malay,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
1,109,Malaysia,MS,4.0,4.0,2.0,3.0,2.0,3.0,4.0,...,2.0,2.0,4.0,2.0,3.0,Malay,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
2,109,Malaysia,MS,3.0,3.0,3.0,3.0,3.0,1.0,0.0,...,3.0,0.0,3.0,1.0,4.0,Malay,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
3,109,Malaysia,MS,6.0,3.0,6.0,4.0,6.0,5.0,6.0,...,3.0,4.0,2.0,0.0,2.0,Malay,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
4,109,Malaysia,MS,5.0,5.0,5.0,6.0,4.0,6.0,5.0,...,2.0,3.0,0.0,2.0,3.0,Malay,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15267,91,Kazakhstan,RU,1.0,3.0,3.0,1.0,5.0,5.0,3.0,...,3.0,2.0,3.0,3.0,2.0,Russian,Russian,Russian,Belarusian (closely related),1
15268,91,Kazakhstan,RU,3.0,3.0,6.0,2.0,6.0,5.0,5.0,...,5.0,2.0,2.0,6.0,5.0,Russian,Russian,Russian,Belarusian (closely related),1
15269,91,Kazakhstan,RU,3.0,3.0,3.0,3.0,4.0,4.0,0.0,...,2.0,5.0,4.0,4.0,3.0,Russian,Russian,Russian,Belarusian (closely related),1
15270,91,Kazakhstan,RU,2.0,3.0,6.0,2.0,2.0,1.0,6.0,...,3.0,3.0,1.0,6.0,4.0,Russian,Russian,Russian,Belarusian (closely related),1
15271,91,Kazakhstan,RU,0.0,1.0,4.0,2.0,1.0,3.0,1.0,...,4.0,2.0,0.0,6.0,5.0,Russian,Russian,Russian,Belarusian (closely related),1

In [156]:
bila_nouns_full['langname'].unique()

array(['Nancowry', 'Turkish', 'Western Flemish', 'Manx', 'Daakaka',
       'Guarayu', 'Iquito', 'Kalamang', 'Media Lengua', 'Nen', 'Palula',
       'Sanzhi Dargwa', 'Teanu', 'Teop', 'Wersing', 'Bikol', 'Carolinian',
       'Hiligaynon', 'Kapampangan', 'Kapingamarangi', 'Kusaiean',
       'Mokilese', 'Palauan', 'Pangasinan', 'Woleaian',
       'Western Neo-Aramaic', 'Western Temne', 'Thompson', 'Wampanoag',
       'Dimasa', 'Mota', 'Northern Grebo', 'Sanskrit', 'Unami',
       'Wiltshire-Hampshire', 'Zigula-Mushungulu', 'Southern Sotho',
       'Bemba (Zambia)', 'Arikara', 'Slovenian', 'Belarusian', 'Ladino',
       'Muruwari', 'Berom', 'Osage', 'Moselle Franconian', 'Rendille',
       'Estonian', 'Somali', 'Luo (Kenya and Tanzania)', 'Romanian',
       'Slovak', 'Ha', 'Havasupai-Walapai-Yavapai', 'Diriku-Shambyu',
       'Esan', 'Nuu-chah-nulth', 'Kamba (Kenya)', 'Huron-Wyandot',
       'Borana-Arsi-Guji Oromo', 'Anufo', 'Bassa', 'Didinga',
       'Rennell-Bellona', 'Norwegian', 'Nung (Viet Nam)',
       'Levantine Arabic', 'Neo-Mandaic', 'Gilit Mesopotamian Arabic',
       'Central Kurdish', 'Javanese', 'Plateau Malagasy', 'Tiv', 'Breton',
       'Balinese', 'Zuni', 'Czech', 'Cajun French', 'Welsh', 'Scots',
       'Atakapa', 'Shan', 'Hawaiian', 'Serbian-Croatian-Bosnian',
       'Old Chinese', 'Middle High German', 'Eastern Canadian Inuktitut',
       'Sicilian', 'Polish', 'Biatah Bidayuh', 'Chamorro',
       'Western Frisian', 'Hindustani', 'Martu Wangka', 'Arapaho', 'Geez',
       'Southern Jinghpaw', 'Adyghe', 'Western Canadian Inuktitut',
       'Gela', 'Saurashtra', 'Comanche', 'Bengali', 'Eastern Armenian',
       'Temiar', 'Standard Malay', 'Hmong Njua', 'Mara Chin', 'Gedaged',
       'Mon', 'Gujarati', 'Khotanese', 'Kok Borok', 'Maguindanao',
       'Mahasu Pahari', 'Marshallese', 'Kuanyama', 'Cheyenne', 'Cahuilla',
       'Khwarezmian', 'Santali', 'Kuku-Yalanji', 'Gilbertese',
       'Yankunytjatjara', 'Dhargari', 'Djiwarli', 'Nugunu (Australia)',
       'Yuwaalaraay-Gamilaraay', 'Western Victoria', 'Bayungu',
       'Wariyangga', 'Yinggarda', 'Dhalandji', 'Adnyamathanha',
       'Hmong Daw', 'Kosarek Yale', 'Pintupi-Luritja', 'Yir-Yoront',
       'Alabama', 'Baram Kayan', 'Larike-Wakasihu', 'Avestan', 'Aneityum',
       'Beijing Mandarin', 'Lamba', 'Tokelau', 'Koasati',
       'Ancient Hebrew', 'Batad Ifugao', 'Tamambo', 'Oksapmin', 'Thayore',
       'Iban', 'Mongolian', 'Beng', 'Tausug', 'Hidatsa', 'Devon', 'Hindi',
       'Sinaugoro', 'Waray (Philippines)', 'Old Norse', 'Hausa', 'Ulster',
       'Goan Konkani', 'Ata', 'Bislama', 'Ute-Southern Paiute',
       'Wu Chinese', 'Albanian', 'Gulf Arabic', 'Yagaria', 'Maranao',
       'Muna', 'Andalusian Arabic', 'Badaga', 'North Azerbaijani',
       'Kazakh', 'Rotuman', 'Italian', 'North Alaskan Inupiatun',
       'Arabic', 'Liberia Kpelle', 'Yucatec Maya', 'Classical Nahuatl',
       'Tuwali Ifugao', 'Louisiana Creole French', 'Russian',
       'Central Tarahumara', 'Western Apache', 'Sanaani Arabic',
       'Garifuna', 'Creek', 'Bardi', 'Western Ojibwa', 'Yogad',
       'Upper Chehalis', 'Latin American Spanish',
       'Mising-Padam-Miri-Minyong', 'Lepcha', 'Kiliwa', 'Ipai',
       'Western Tlacolula Valley Zapotec', 'Chantyal', 'Masbatenyo',
       'Leh Ladakhi', 'Maithili', 'Katë', 'Swedish', 'Chang Naga',
       'Xhosa', 'Tuvinian', 'Mexican Spanish', 'Plains Cree', 'Ga',
       'Galician', 'Midland American English', 'Nzima', 'Powhatan',
       'Rabha', 'Korean', 'Yoruba', 'Afrikaans', 'Amharic', 'Singlish',
       'Latin', 'Bambara', 'Nandi', 'Marathi', 'Kumbainggar',
       'Yue Chinese', 'Mapun', 'Lakota', 'Yaqui', 'Northern Pashto',
       'Yakan', 'Jewish Babylonian Aramaic', 'Tahitian', 'Central Malay',
       'Tuvalu', 'Uripiv', 'Naro', 'Plautdietsch', 'Bulgarian',
       'Ngaanyatjarra', 'Lycian A', 'Finnish', 'Tee', 'Tamil', 'Bantawa',
       'Swahili', 'Kxoe', 'Busa', 'Boko (Benin)', 'Bokobaru',
       'Central Khmer', 'Dzongkha', 'Limbu', 'Agusan Manobo', 'Thao',
       'Malacca-Batavia Portuguese Creole', 'Mag-Anchi Ayta', 'Aleut',
       "S'gaw Karen", 'Tboli', 'Eastern Panjabi', "Mi'kmaq",
       'Jicarilla Apache', 'Akha', 'Raluana', 'Malayalam',
       'Kadazan Dusun', 'Tagalog-Pilipino', 'Tuamotuan', 'Kannada',
       'Tibetan', 'Cherokee', 'Hakka Chinese', 'Old English', 'French',
       'Sumerian', 'Urdu', 'Khasi', 'Bondo', 'Yana', 'Central Carrier',
       'Western Parbate Kham', 'Bodo-Mech', 'Oriya', 'Sembakung Murut',
       'Romblomanon', 'Chippewa', 'Ojibway', 'Baba Malay', 'Uighur',
       'Tigrinya', 'Kirghiz', 'Maori', 'Latvian',
       'Trinidadian Creole English', 'Tok Pisin', 'Uzbek', 'Yeyi',
       'Old French', 'Tanacross', 'Misima-Paneati', 'Sundanese', 'Caló',
       'Persian', 'Navajo', 'Hungarian', 'South-Central Koongo',
       'Bobangi', 'Nez Perce', 'Nyanja', "Kalispel-Pend d'Oreille",
       'Western Panjabi', 'Sudanese Arabic', 'Beja', 'Daakie', 'Dagaare',
       'Dalabon', 'Djinang', 'Eastern Shoshone', 'Fijian', 'Gbari',
       'Goemai', 'Iraqw', 'Komnzo', 'Mosuo', 'Mudburra', 'Nafsan',
       'Ngandi', 'Northern Alta', 'Nuxalk', 'Rongga', 'Sauk', 'Savosavo',
       'Vures', 'Wampar', 'Warlpiri', 'Yali', 'Aiwoo',
       'Pre-Angkorian Khmer', "'Are'are", 'Arosi', 'Awa', 'Bontok',
       'Buin', 'Canala', 'Cheke Holo', 'Chepang', 'Cook Islands Maori',
       'Dehong', 'Dehu', 'Dumagat', 'Enga', 'Fore', 'Futunu-Aniwa',
       'Grand Couli', 'Jabem', 'Jahai', 'Jingulu', 'Kalam', 'Kâte',
       'Kewa', 'Grass Koiari', 'Kwaio', 'Kwamera', 'Kwoma', 'Kyaka Enga',
       'Lau', 'Lenakel', 'Lisu', 'Lonwolwol', 'Mali', 'Mara', 'Mele',
       'Nakanai', 'Nengone', 'Orokolo', 'Paamese', 'Paiwan', 'Puluwat',
       'Rhade', 'Ritharngu', 'Selepet', 'Southeast Ambrym', 'Sye',
       'Takuu', 'Telefol', 'Tetum', 'Tolo', 'Toqabaqita', "Urak Lawoi'",
       'Warndarang', 'Wirangu', 'Yandruwandha', 'Yugambeh', 'Assyrian',
       'Yámana', 'Caribbean Hindustani', 'Mayan',
       'Western Huasteca Nahuatl', 'Cayubaba', 'Lokono',
       'Isthmus Zapotec', 'Haitian', 'Papiamento', 'Warao', "K'iche'",
       'Brazilian Portuguese', "Tohono O'odham", 'Border Kuna', 'Mailu',
       'Telugu', 'Min Dong Chinese', 'Essex', 'South Yorkshire English',
       'Sinhala', 'Western Bukidnon Manobo', 'Tunica', 'Niuean', 'Pali',
       'Vietnamese', 'Shekkacho', 'Sussex', 'Dutch', 'German',
       'Heiltsuk-Oowekyala', "Kwak'wala", 'Filipino', 'Portuguese',
       'Indonesian', 'Burmese', 'Lundayeh', 'Besisi',
       'Central Siberian Yupik', 'San Blas Kuna', 'Tonkawa',
       'Coast Miwok', 'Roviana', 'Northeast Maidu', 'Klamath-Modoc',
       'Cornish', 'Mangareva', 'Pohnpeian', 'Greek',
       'Tarifiyt-Beni-Iznasen-Eastern Middle Atlas Berber', "Dena'ina",
       'Akkadian', 'Scottish Gaelic', 'Icelandic', 'Egyptian Arabic',
       'Sindhi', 'Nupe-Nupe-Tako', 'Eastern Balochi', 'Sadri', 'Kudmali',
       'Assamese', 'Mansaka', 'Danish', 'Mundari', 'Semai',
       'East-Central Tangkhul Naga', 'Lithuanian', 'East Limba', 'Urhobo',
       'Karamojong', 'Kipsigis', 'Akan', 'Zande', 'Cebuano', 'Efik',
       'Tai Dón', 'Nepali', 'Lao', 'Manda (India)', 'Haisla', 'Rungus',
       'Ao Naga', 'Choctaw', 'Tonga (Tonga Islands)', 'Squamish',
       'Ho-Chunk', 'Malayo', 'Ukrainian', 'Syriac', 'Min Nan Chinese',
       'Mandarin Chinese', 'Upper Sorbian', 'Central Nicobarese', 'Tulu',
       "Sa'a", 'North Saami', 'Seneca',
       'Bolivar-North Chimborazo Highland Quichua', 'Ahtena', 'Tzotzil',
       'Yao', 'Western Abenaki', 'Yiddish', 'Dakota-Sioux', 'Spanish',
       'Kashmiri', 'Northwest Sahaptin', 'Irish',
       'Malecite-Passamaquoddy', 'Eastern Ojibwa', 'Moroccan Arabic',
       'Shona', 'Ndau', 'Mbukushu', 'Southwestern Dinka', 'Nuer', 'Swati',
       'Nyankole', 'Sango', 'Atayal', 'Tsonga', 'Wubuy', 'Chadian Arabic',
       'Bughotu', 'Yapese', 'Ho', 'Sidaama', 'Tswana', 'Abua', 'Mizo',
       'Gaam', 'Ganda', 'Lozi', 'Egyptian (Ancient)', 'Sabaic', 'Tangga',
       'Bini', 'Kinshasa Lingala', 'Kurukh', 'Ibibio', 'Toaripi', 'Igbo',
       'Izon', 'Tikopia', 'Kathmandu Valley Newari', 'Manipuri',
       'Giryama', 'Ewe', 'Venda', 'Yemeni Arabic', 'Georgian',
       'Wik-Mungkan', 'Zulu', 'Turkana', 'Mwaghavul',
       'West Central Oromo', 'Tangale', 'Pedi', 'Chuukese', 'Sora',
       'Mungaka', 'Mískito', 'Tiwi', 'Samoan', 'Central Kanuri',
       'East Taa', 'Mandinka', 'Gambian Wolof', 'Wolof', 'Gade',
       'Lega-Shabunda', 'Pulaar', 'Ndonga', 'Mambwe-Lungu', 'Masai',
       'Hebrew', 'Ilokano', 'Aromanian', 'Thai', 'Japanese',
       'Middle Chinese', 'Kwangali', 'Mbay', 'Pidgin Chinook Jargon',
       'Akawaio', 'Arta', 'Belanda Bor', 'Bongo', 'Buli', 'Caning',
       'Chizigula', 'Chufie', 'Chung', 'Shilluk-Cøllø', 'Dagbani', 'Daui',
       'Doromu-Koki', 'Fuyug', 'Gikyode', 'Gojri', 'Kinyarwanda', 'Lopit',
       'Lou', 'Lubwisi', 'Lugungu', 'Lugwere', 'Lunyole', 'Mampruli',
       'Mandari', 'Mungong', 'Reel', 'Sisaali', 'Sursurunga', 'Tampulma',
       'Turkmen', 'Pennsylvania German', 'Herero'], dtype=object)

In [171]:
bila_nouns_full_emotions_filtered = bila_nouns_full_emotions[bila_nouns_full_emotions['langname'].isin(covid_to_bila_lang_name_mapping['bila_language_name_mapping'].values)]
bila_nouns_full_emotions_filtered

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,log_count
9,coo.31924067983704,admiration,3.0,10.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,2.397895
10,coo.31924067983704,anger,5.0,85.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,4.454347
11,coo.31924067983704,anxiety,2.0,77.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,4.356709
12,coo.31924067983704,boredom,1.0,11.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,2.484907
13,coo.31924067983704,compassion,2.0,33.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,3.526361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6145,uva.x004877953,love,10.0,639.0,Japanese,nucl1643,1974,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,6.461468
6146,uva.x004877953,pleasure,5.0,286.0,Japanese,nucl1643,1974,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,5.659482
6147,uva.x004877953,regret,5.0,107.0,Japanese,nucl1643,1974,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,4.682131
6148,uva.x004877953,relief,11.0,89.0,Japanese,nucl1643,1974,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,4.499810
6149,uva.x004877953,sadness,3.0,9.0,Japanese,nucl1643,1974,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,2.302585

## your table vision was wrong.
### you need to generate an 18 emotions per language columns, rows are all the respondants
### maybe you'd say that is already what the merged covid looks like but it has all languages
### then you would need the 18 emotions as columsn, rows are the 616 languages in the bila dataset.

In [173]:
merged_filtered_mapped

,country,countryname,language,admiration,calm,compassion,determination,moved,gratitude,hope,...,fear,frustration,loneliness,regret,sadness,Language_Name,study_language_names,bila_language_name_mapping,possible_alternative_bila_language_name_mappings,easy
0,109,Malaysia,MS,1.0,6.0,1.0,0.0,0.0,0.0,6.0,...,6.0,6.0,6.0,6.0,6.0,Malay,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
1,109,Malaysia,MS,4.0,4.0,2.0,3.0,2.0,3.0,4.0,...,2.0,2.0,4.0,2.0,3.0,Malay,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
2,109,Malaysia,MS,3.0,3.0,3.0,3.0,3.0,1.0,0.0,...,3.0,0.0,3.0,1.0,4.0,Malay,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
3,109,Malaysia,MS,6.0,3.0,6.0,4.0,6.0,5.0,6.0,...,3.0,4.0,2.0,0.0,2.0,Malay,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
4,109,Malaysia,MS,5.0,5.0,5.0,6.0,4.0,6.0,5.0,...,2.0,3.0,0.0,2.0,3.0,Malay,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo, Indonesian",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15072,91,Kazakhstan,RU,1.0,3.0,3.0,1.0,5.0,5.0,3.0,...,3.0,2.0,3.0,3.0,2.0,Russian,Russian,Russian,Belarusian (closely related),1
15073,91,Kazakhstan,RU,3.0,3.0,6.0,2.0,6.0,5.0,5.0,...,5.0,2.0,2.0,6.0,5.0,Russian,Russian,Russian,Belarusian (closely related),1
15074,91,Kazakhstan,RU,3.0,3.0,3.0,3.0,4.0,4.0,0.0,...,2.0,5.0,4.0,4.0,3.0,Russian,Russian,Russian,Belarusian (closely related),1
15075,91,Kazakhstan,RU,2.0,3.0,6.0,2.0,2.0,1.0,6.0,...,3.0,3.0,1.0,6.0,4.0,Russian,Russian,Russian,Belarusian (closely related),1
15076,91,Kazakhstan,RU,0.0,1.0,4.0,2.0,1.0,3.0,1.0,...,4.0,2.0,0.0,6.0,5.0,Russian,Russian,Russian,Belarusian (closely related),1

In [226]:
bila_nouns_full_emotions_filtered

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,log_count
9,coo.31924067983704,admiration,3.0,10.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,2.397895
10,coo.31924067983704,anger,5.0,85.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,4.454347
11,coo.31924067983704,anxiety,2.0,77.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,4.356709
12,coo.31924067983704,boredom,1.0,11.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,2.484907
13,coo.31924067983704,compassion,2.0,33.0,Turkish,nucl1301,1991,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,3.526361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6145,uva.x004877953,love,10.0,639.0,Japanese,nucl1643,1974,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,6.461468
6146,uva.x004877953,pleasure,5.0,286.0,Japanese,nucl1643,1974,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,5.659482
6147,uva.x004877953,regret,5.0,107.0,Japanese,nucl1643,1974,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,4.682131
6148,uva.x004877953,relief,11.0,89.0,Japanese,nucl1643,1974,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,4.499810
6149,uva.x004877953,sadness,3.0,9.0,Japanese,nucl1643,1974,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,2.302585

In [174]:
bila_nouns_full_emotions_filtered['langname'].unique()

array(['Turkish', 'Serbian-Croatian-Bosnian', 'Standard Malay', 'Italian',
       'Arabic', 'Russian', 'Latin American Spanish', 'Swedish',
       'Afrikaans', 'Marathi', 'Bulgarian', 'Finnish', 'French',
       'Persian', 'Hungarian', 'Vietnamese', 'Dutch', 'German',
       'Portuguese', 'Indonesian', 'Greek', 'Icelandic', 'Danish',
       'Ukrainian', 'Mandarin Chinese', 'Spanish', 'Georgian', 'Hebrew',
       'Japanese'], dtype=object)

In [229]:
elab_per_emotion = bila_nouns_full_emotions_filtered[['langname',   'glottocode','word', 'count',  'id', 'year']]
elab_per_emotion

      langname glottocode        word  count                  id  year
9      Turkish   nucl1301  admiration   10.0  coo.31924067983704  1991
10     Turkish   nucl1301       anger   85.0  coo.31924067983704  1991
11     Turkish   nucl1301     anxiety   77.0  coo.31924067983704  1991
12     Turkish   nucl1301     boredom   11.0  coo.31924067983704  1991
13     Turkish   nucl1301  compassion   33.0  coo.31924067983704  1991
...        ...        ...         ...    ...                 ...   ...
6145  Japanese   nucl1643        love  639.0      uva.x004877953  1974
6146  Japanese   nucl1643    pleasure  286.0      uva.x004877953  1974
6147  Japanese   nucl1643      regret  107.0      uva.x004877953  1974
6148  Japanese   nucl1643      relief   89.0      uva.x004877953  1974
6149  Japanese   nucl1643     sadness    9.0      uva.x004877953  1974

[514 rows x 6 columns]

In [230]:
stats_by_country = (
    merged_filtered_mapped
    .groupby(['countryname', 'bila_language_name_mapping'])[emotions]
    .agg(['mean', 'std'])
)
stats_by_country = pd.DataFrame(stats_by_country)
stats_by_country

                                             admiration                calm  \
                                                   mean       std      mean
countryname       bila_language_name_mapping
Brazil            Brazilian Portuguese         3.540984  1.745047  3.421569
Bulgaria          Bulgarian                    2.498141  1.980548  3.334572
Chile             Latin American Spanish       2.867521  1.901080  2.899358
China             Mandarin Chinese             4.365940  1.736698  3.914807
Colombia          Latin American Spanish       3.409836  1.974022  3.418033
Croatia           Serbian-Croatian-Bosnian     2.552581  1.680006  3.332061
Curacao           Dutch                        3.627778  1.743401  3.961111
Denmark           Danish                       2.668919  1.513605  3.445946
Egypt             Arabic                       2.547472  1.886575  3.622222
Finland           Finnish                      2.738462  1.547467  3.726923
France            French                       3.357977  1.801764  3.746094
Georgia           Georgian                     2.523605  1.866354  3.248927
Germany           German                       2.804124  1.800225  3.628866
Greece            Greek                        2.328889  1.887059  3.337778
Hong Kong (S.A.R) Mandarin Chinese             2.845361  1.831448  3.118557
Hungary           Hungarian                    2.679688  1.925815  3.265625
Iceland           Icelandic                    3.469741  1.867297  3.299712
India             Marathi                      3.500000  1.768410  3.982143
Indonesia         Indonesian                   3.201863  1.577327  3.834365
Iran              Persian                      2.347826  1.745782  2.774194
Israel            Hebrew                       1.569536  1.718565  3.240000
Italy             Italian                      2.966981  1.900316  3.327059
Japan             Japanese                     2.602176  1.523357  3.559441
Jordan            Arabic                       3.108225  1.965235  3.952586
Kazakhstan        Russian                      2.438849  1.958468  3.469534
Malaysia          Standard Malay               3.793548  1.548761  4.000000
Malta             [No Direct Match]            3.287234  1.787396  2.936620
Netherlands       Dutch                        3.325048  1.646279  3.671756
Peru              Spanish                      3.706161  1.884501  3.693023
Russia            Russian                      2.553043  1.774840  3.349565
Serbia            Serbian-Croatian-Bosnian     2.712644  1.846614  3.517143
South Africa      Afrikaans                    2.946429  1.712904  3.642857
Spain             Spanish                      3.428571  1.994498  3.428571
Sweden            Swedish                      3.300000  1.774224  3.580000
Syria             Arabic                       1.849372  1.996402  3.377593
Taiwan            Mandarin Chinese             3.993307  1.660520  3.666667
Turkey            Turkish                      2.027888  1.760460  3.611111
Ukraine           Ukrainian                    2.856489  1.644428  3.203957
Vietnam           Vietnamese                   4.219178  1.746841  4.263699

                                                       compassion            \
                                                   std       mean       std
countryname       bila_language_name_mapping
Brazil            Brazilian Portuguese        1.502585   4.633987  1.319471
Bulgaria          Bulgarian                   1.712431   4.313433  1.590788
Chile             Latin American Spanish      1.546330   3.893390  1.693798
China             Mandarin Chinese            1.683731   4.240976  1.701800
Colombia          Latin American Spanish      1.419115   4.024590  1.678563
Croatia           Serbian-Croatian-Bosnian    1.485572   2.904398  1.650043
Curacao           Dutch                       1.607816   4.777778  1.174951
Denmark           Danish                      1.531012   4.067568  1.450602
Egypt             Arabic                      1.728264   4.173006  1.710858
Finland           Finnish                     1.380520   4.042471  1.350471
France            French                      1.587322   3.809339  1.648458
Georgia           Georgian                    1.698836   4.444444  1.507887
Germany           German                      1.620895   4.347079  1.283778
Greece            Greek                       1.538681   3.843049  1.662391
Hong Kong (S.A.R) Mandarin Chinese            1.432909   3.432990  1.624981
Hungary           Hungarian                   1.730848   4.507812  1.343079
Iceland           Icelandic                   1.757585   4.388406  1.601193
India             Marathi                     1.700172   3.946429  1.633954
Indonesia         Indonesian                  1.327863   4.547287  1.238492
Iran              Persian                     1.831431   3.770053  1.705639
Israel            Hebrew                      1.407935   4.013245  1.316494
Italy             Italian                     1.516839   3.613208  1.729022
Japan             Japanese                    1.254913   3.533385  1.375941
Jordan            Arabic                      1.807247   4.359307  1.718414
Kazakhstan        Russian                     1.641953   3.602151  1.755606
Malaysia          Standard Malay              1.232672   4.432258  1.304435
Malta             [No Direct Match]           1.564693   3.687943  1.623382
Netherlands       Dutch                       1.413904   4.160305  1.402357
Peru              Spanish                     1.503484   4.483721  1.500301
Russia            Russian                     1.524902   3.557292  1.654564
Serbia            Serbian-Croatian-Bosnian    1.580139   4.312321  1.465069
South Africa      Afrikaans                   1.341353   4.196429  1.505780
Spain             Spanish                     1.616365   3.971154  1.742984
Sweden            Swedish                     1.482936   4.537500  1.289477
Syria             Arabic                      2.045971   3.878543  1.921589
Taiwan            Mandarin Chinese            1.549020   3.722520  1.628423
Turkey            Turkish                     1.439191   3.956349  1.627111
Ukraine           Ukrainian                   1.565963   3.576220  1.516419
Vietnam           Vietnamese                  1.350442   3.872852  1.779476

                                             determination            \
                                                      mean       std
countryname       bila_language_name_mapping
Brazil            Brazilian Portuguese            3.725490  1.593986
Bulgaria          Bulgarian                       3.565056  1.684113
Chile             Latin American Spanish          3.370450  1.700109
China             Mandarin Chinese                4.165992  1.693406
Colombia          Latin American Spanish          3.818182  1.653280
Croatia           Serbian-Croatian-Bosnian        3.508604  1.438863
Curacao           Dutch                           4.000000  1.549914
Denmark           Danish                          3.351351  1.483996
Egypt             Arabic                          3.161090  1.728845
Finland           Finnish                         3.532819  1.327221
France            French                          3.727626  1.582292
Georgia           Georgian                        3.692308  1.815345
Germany           German                          3.468966  1.464955
Greece            Greek                           3.444934  1.682894
Hong Kong (S.A.R) Mandarin Chinese                3.247423  1.537314
Hungary           Hungarian                       3.652344  1.698972
Iceland           Icelandic                       3.589595  1.611303
India             Marathi                         3.660714  1.880781
Indonesia         Indonesian                      3.827372  1.301711
Iran              Persian                         3.290323  1.601220
Israel            Hebrew                          3.403974  1.493001
Italy             Italian                         3.716981  1.558958
Japan             Japanese                        2.964258  1.522347
Jordan            Arabic                          3.754386  1.846828
Kazakhstan        Russian                         3.283154  1.783851
Malaysia          Standard Malay                  3.845161  1.372939
Malta             [No Direct Match]               3.568905  1.614876
Netherlands       Dutch                           3.553435  1.404380
Peru              Spanish                         3.939252  1.457070
Russia            Russian                         3.057292  1.579824
Serbia            Serbian-Croatian-Bosnian        3.794286  1.579950
South Africa      Afrikaans                       3.696429  1.570214
Spain             Spanish                         3.461538  1.773172
Sweden            Swedish                         3.675000  1.374445
Syria             Arabic                          2.888889  2.168520
Taiwan            Mandarin Chinese                3.695710  1.540472
Turkey            Turkish                         3.804781  1.561325
Ukraine           Ukrainian                       3.260274  1.528436
Vietnam           Vietnamese                      4.096220  1.507803

                                                 moved            ...  \
                                                  mean       std  ...
countryname       bila_language_name_mapping                      ...
Brazil            Brazilian Portuguese        4.464052  1.603382  ...
Bulgaria          Bulgarian                   3.587361  1.860024  ...
Chile             Latin American Spanish      3.886266  1.722072  ...
China             Mandarin Chinese            4.426538  1.700508  ...
Colombia          Latin American Spanish      4.049180  1.719372  ...
Croatia           Serbian-Croatian-Bosnian    2.654580  1.664199  ...
Curacao           Dutch                       3.394444  1.632413  ...
Denmark           Danish                      3.304054  1.417379  ...
Egypt             Arabic                      4.028325  1.684172  ...
Finland           Finnish                     3.084615  1.655852  ...
France            French                      3.046693  1.710994  ...
Georgia           Georgian                    3.424893  1.794310  ...
Germany           German                      3.529412  1.559024  ...
Greece            Greek                       3.273128  1.910690  ...
Hong Kong (S.A.R) Mandarin Chinese            3.030928  1.653720  ...
Hungary           Hungarian                   2.847656  1.927162  ...
Iceland           Icelandic                   2.489914  1.878318  ...
India             Marathi                     2.357143  1.920498  ...
Indonesia         Indonesian                  4.057099  1.293718  ...
Iran              Persian                     3.150538  1.845059  ...
Israel            Hebrew                      2.980132  1.601958  ...
Italy             Italian                     3.280660  1.828072  ...
Japan             Japanese                    2.777174  1.525502  ...
Jordan            Arabic                      3.899123  1.781797  ...
Kazakhstan        Russian                     2.587814  2.029990  ...
Malaysia          Standard Malay              3.490323  1.656815  ...
Malta             [No Direct Match]           3.742958  1.813023  ...
Netherlands       Dutch                       3.409178  1.592870  ...
Peru              Spanish                     4.455814  1.493491  ...
Russia            Russian                     2.503484  1.727255  ...
Serbia            Serbian-Croatian-Bosnian    3.339031  1.771727  ...
South Africa      Afrikaans                   3.142857  1.686497  ...
Spain             Spanish                     3.894231  1.576023  ...
Sweden            Swedish                     3.120000  1.646931  ...
Syria             Arabic                      3.651452  1.962908  ...
Taiwan            Mandarin Chinese            3.935657  1.593995  ...
Turkey            Turkish                     3.234127  1.854451  ...
Ukraine           Ukrainian                   2.955860  1.657264  ...
Vietnam           Vietnamese                  4.185567  1.667105  ...

                                                  fear           frustration  \
                                                  mean       std        mean
countryname       bila_language_name_mapping
Brazil            Brazilian Portuguese        3.603279  1.757500    3.437908
Bulgaria          Bulgarian                   2.561338  1.954938    3.029740
Chile             Latin American Spanish      3.528785  1.836746    4.119914
China             Mandarin Chinese            1.809500  1.726083    1.815642
Colombia          Latin American Spanish      3.024590  1.943258    3.409836
Croatia           Serbian-Croatian-Bosnian    2.739962  1.825025    3.430210
Curacao           Dutch                       2.477778  1.933115    3.005556
Denmark           Danish                      1.824324  1.610832    3.148649
Egypt             Arabic                      3.556790  1.953694    3.419434
Finland           Finnish                     2.509653  1.600298    3.846154
France            French                      2.155642  1.796018    3.156250
Georgia           Georgian                    2.497854  1.864192    2.965665
Germany           German                      2.323024  1.757384    3.186207
Greece            Greek                       2.637168  1.939356    3.508850
Hong Kong (S.A.R) Mandarin Chinese            2.515464  1.734224    2.556701
Hungary           Hungarian                   2.511719  1.823555    3.125000
Iceland           Icelandic                   2.227666  1.861548    2.129683
India             Marathi                     2.053571  1.891797    1.839286
Indonesia         Indonesian                  3.141085  1.749073    2.213292
Iran              Persian                     2.972973  1.929272    3.005405
Israel            Hebrew                      2.092715  1.733401    3.125828
Italy             Italian                     2.666667  1.799782    3.320000
Japan             Japanese                    2.630148  1.743227    3.111888
Jordan            Arabic                      2.711207  2.012570    3.116379
Kazakhstan        Russian                     2.276978  1.979746    2.602151
Malaysia          Standard Malay              2.503226  1.785127    2.412903
Malta             [No Direct Match]           3.042254  1.933061    3.887324
Netherlands       Dutch                       2.408397  1.663121    3.574427
Peru              Spanish                     2.868545  1.827875    3.181395
Russia            Russian                     2.394415  1.771404    2.713542
Serbia            Serbian-Croatian-Bosnian    2.424501  1.785457    2.742857
South Africa      Afrikaans                   2.883929  1.911301    3.991071
Spain             Spanish                     2.371429  1.771880    3.228571
Sweden            Swedish                     2.315000  1.693501    3.170000
Syria             Arabic                      2.122449  2.012590    2.275720
Taiwan            Mandarin Chinese            1.990617  1.625689    1.842035
Turkey            Turkish                     2.948617  1.892269    2.881423
Ukraine           Ukrainian                   2.393293  1.827914    2.936073
Vietnam           Vietnamese                  1.688356  1.687472    2.441781

                                                       loneliness            \
                                                   std       mean       std
countryname       bila_language_name_mapping
Brazil            Brazilian Portuguese        1.941201   2.518033  2.069635
Bulgaria          Bulgarian                   2.089207   2.334572  2.154385
Chile             Latin American Spanish      1.731608   2.869658  2.067930
China             Mandarin Chinese            1.763461   1.812437  1.826492
Colombia          Latin American Spanish      1.897167   2.578512  2.170837
Croatia           Serbian-Croatian-Bosnian    1.808983   2.692748  1.952364
Curacao           Dutch                       1.877527   1.894444  1.853570
Denmark           Danish                      1.852980   2.277027  2.026427
Egypt             Arabic                      2.007981   3.686275  2.140949
Finland           Finnish                     1.699246   2.776062  1.927978
France            French                      1.829765   1.961089  1.932060
Georgia           Georgian                    1.920539   2.439655  2.131149
Germany           German                      1.856388   2.178694  1.887078
Greece            Greek                       1.663306   2.537445  2.015901
Hong Kong (S.A.R) Mandarin Chinese            1.837824   2.458763  1.931696
Hungary           Hungarian                   1.919967   1.863281  2.000211
Iceland           Icelandic                   1.890931   2.465318  2.160303
India             Marathi                     1.961231   1.857143  1.833314
Indonesia         Indonesian                  1.869821   2.545595  1.978368
Iran              Persian                     1.918155   2.940860  2.032638
Israel            Hebrew                      1.690383   2.026490  1.754792
Italy             Italian                     1.944077   2.535377  1.968709
Japan             Japanese                    1.729330   2.007764  1.817621
Jordan            Arabic                      2.076312   3.304348  2.156230
Kazakhstan        Russian                     2.078356   2.039568  2.156817
Malaysia          Standard Malay              1.689490   2.296774  2.064462
Malta             [No Direct Match]           1.820956   2.704225  2.094208
Netherlands       Dutch                       1.658224   2.335878  1.853572
Peru              Spanish                     1.988196   1.604651  1.720404
Russia            Russian                     1.983293   2.157986  2.033897
Serbia            Serbian-Croatian-Bosnian    1.952779   2.194286  2.000565
South Africa      Afrikaans                   1.579688   2.276786  1.996437
Spain             Spanish                     1.912797   1.971429  2.011779
Sweden            Swedish                     1.835626   2.140000  1.990050
Syria             Arabic                      2.142184   2.325103  2.281181
Taiwan            Mandarin Chinese            1.638740   1.605087  1.640841
Turkey            Turkish                     1.976491   2.494071  2.042447
Ukraine           Ukrainian                   1.930703   2.181402  1.950304
Vietnam           Vietnamese                  1.901356   1.859589  1.964674

                                                regret             sadness  \
                                                  mean       std      mean
countryname       bila_language_name_mapping
Brazil            Brazilian Portuguese        1.934426  1.881951  3.321311
Bulgaria          Bulgarian                   2.929104  2.009018  3.252788
Chile             Latin American Spanish      2.352564  1.969156  3.799145
China             Mandarin Chinese            1.477009  1.701083  2.256709
Colombia          Latin American Spanish      1.721311  1.601973  3.459016
Croatia           Serbian-Croatian-Bosnian    2.795802  1.713266  2.990458
Curacao           Dutch                       1.350000  1.645970  2.622222
Denmark           Danish                      1.479730  1.655622  1.601351
Egypt             Arabic                      2.710591  2.129295  4.047970
Finland           Finnish                     1.534615  1.570343  2.953668
France            French                      1.582031  1.708430  2.503906
Georgia           Georgian                    2.497854  1.916634  3.277778
Germany           German                      2.037931  1.705459  2.656357
Greece            Greek                       1.778761  1.836589  3.251101
Hong Kong (S.A.R) Mandarin Chinese            1.974227  1.755629  2.649485
Hungary           Hungarian                   1.906250  1.723824  2.703125
Iceland           Icelandic                   1.527378  1.776931  2.376437

In [231]:
stats_by_country.columns = [
    f"{emotion}_{stat}" for emotion, stat in stats_by_country.columns
]
stats_by_country = stats_by_country.reset_index()
stats_by_country

,countryname,bila_language_name_mapping,admiration_mean,admiration_std,calm_mean,calm_std,compassion_mean,compassion_std,determination_mean,determination_std,...,fear_mean,fear_std,frustration_mean,frustration_std,loneliness_mean,loneliness_std,regret_mean,regret_std,sadness_mean,sadness_std
0,Brazil,Brazilian Portuguese,3.540984,1.745047,3.421569,1.502585,4.633987,1.319471,3.725490,1.593986,...,3.603279,1.757500,3.437908,1.941201,2.518033,2.069635,1.934426,1.881951,3.321311,1.833991
1,Bulgaria,Bulgarian,2.498141,1.980548,3.334572,1.712431,4.313433,1.590788,3.565056,1.684113,...,2.561338,1.954938,3.029740,2.089207,2.334572,2.154385,2.929104,2.009018,3.252788,1.930519
2,Chile,Latin American Spanish,2.867521,1.901080,2.899358,1.546330,3.893390,1.693798,3.370450,1.700109,...,3.528785,1.836746,4.119914,1.731608,2.869658,2.067930,2.352564,1.969156,3.799145,1.745670
3,China,Mandarin Chinese,4.365940,1.736698,3.914807,1.683731,4.240976,1.701800,4.165992,1.693406,...,1.809500,1.726083,1.815642,1.763461,1.812437,1.826492,1.477009,1.701083,2.256709,1.848471
4,Colombia,Latin American Spanish,3.409836,1.974022,3.418033,1.419115,4.024590,1.678563,3.818182,1.653280,...,3.024590,1.943258,3.409836,1.897167,2.578512,2.170837,1.721311,1.601973,3.459016,1.916210
5,Croatia,Serbian-Croatian-Bosnian,2.552581,1.680006,3.332061,1.485572,2.904398,1.650043,3.508604,1.438863,...,2.739962,1.825025,3.430210,1.808983,2.692748,1.952364,2.795802,1.713266,2.990458,1.759406
6,Curacao,Dutch,3.627778,1.743401,3.961111,1.607816,4.777778,1.174951,4.000000,1.549914,...,2.477778,1.933115,3.005556,1.877527,1.894444,1.853570,1.350000,1.645970,2.622222,1.906049
7,Denmark,Danish,2.668919,1.513605,3.445946,1.531012,4.067568,1.450602,3.351351,1.483996,...,1.824324,1.610832,3.148649,1.852980,2.277027,2.026427,1.479730,1.655622,1.601351,1.732993
8,Egypt,Arabic,2.547472,1.886575,3.622222,1.728264,4.173006,1.710858,3.161090,1.728845,...,3.556790,1.953694,3.419434,2.007981,3.686275,2.140949,2.710591,2.129295,4.047970,1.806232
9,Finland,Finnish,2.738462,1.547467,3.726923,1.380520,4.042471,1.350471,3.532819,1.327221,...,2.509653,1.600298,3.846154,1.699246,2.776062,1.927978,1.534615,1.570343,2.953668,1.672212
10,France,French,3.357977,1.801764,3.746094,1.587322,3.809339,1.648458,3.727626,1.582292,...,2.155642,1.796018,3.156250,1.829765,1.961089,1.932060,1.582031,1.708430,2.503906,1.874489
11,Georgia,Georgian,2.523605,1.866354,3.248927,1.698836,4.444444,1.507887,3.692308,1.815345,...,2.497854,1.864192,2.965665,1.920539,2.439655,2.131149,2.497854,1.916634,3.277778,1.955453
12,Germany,German,2.804124,1.800225,3.628866,1.620895,4.347079,1.283778,3.468966,1.464955,...,2.323024,1.757384,3.186207,1.856388,2.178694,1.887078,2.037931,1.705459,2.656357,1.749518
13,Greece,Greek,2.328889,1.887059,3.337778,1.538681,3.843049,1.662391,3.444934,1.682894,...,2.637168,1.939356,3.508850,1.663306,2.537445,2.015901,1.778761,1.836589,3.251101,1.886945
14,Hong Kong (S.A.R),Mandarin Chinese,2.845361,1.831448,3.118557,1.432909,3.432990,1.624981,3.247423,1.537314,...,2.515464,1.734224,2.556701,1.837824,2.458763,1.931696,1.974227,1.755629,2.649485,1.694497
15,Hungary,Hungarian,2.679688,1.925815,3.265625,1.730848,4.507812,1.343079,3.652344,1.698972,...,2.511719,1.823555,3.125000,1.919967,1.863281,2.000211,1.906250,1.723824,2.703125,1.869715
16,Iceland,Icelandic,3.469741,1.867297,3.299712,1.757585,4.388406,1.601193,3.589595,1.611303,...,2.227666,1.861548,2.129683,1.890931,2.465318,2.160303,1.527378,1.776931,2.376437,1.964884
17,India,Marathi,3.500000,1.768410,3.982143,1.700172,3.946429,1.633954,3.660714,1.880781,...,2.053571,1.891797,1.839286,1.961231,1.857143,1.833314,1.254545,1.723672,2.381818,2.022932
18,Indonesia,Indonesian,3.201863,1.577327,3.834365,1.327863,4.547287,1.238492,3.827372,1.301711,...,3.141085,1.749073,2.213292,1.869821,2.545595,1.978368,2.066563,1.647238,2.933333,1.730317
19,Iran,Persian,2.347826,1.745782,2.774194,1.831431,3.770053,1.705639,3.290323,1.601220,...,2.972973,1.929272,3.005405,1.918155,2.940860,2.032638,2.659459,1.999383,3.556150,1.881089
20,Israel,Hebrew,1.569536,1.718565,3.240000,1.407935,4.013245,1.316494,3.403974,1.493001,...,2.092715,1.733401,3.125828,1.690383,2.026490,1.754792,1.662252,1.616116,2.536424,1.765502
21,Italy,Italian,2.966981,1.900316,3.327059,1.516839,3.613208,1.729022,3.716981,1.558958,...,2.666667,1.799782,3.320000,1.944077,2.535377,1.968709,2.411765,1.928523,3.343529,1.723755
22,Japan,Japanese,2.602176,1.523357,3.559441,1.254913,3.533385,1.375941,2.964258,1.522347,...,2.630148,1.743227,3.111888,1.729330,2.007764,1.817621,1.956522,1.623824,2.601399,1.710028
23,Jordan,Arabic,3.108225,1.965235,3.952586,1.807247,4.359307,1.718414,3.754386,1.846828,...,2.711207,2.012570,3.116379,2.076312,3.304348,2.156230,2.515152,2.218202,3.700000,1.917855
24,Kazakhstan,Russian,2.438849,1.958468,3.469534,1.641953,3.602151,1.755606,3.283154,1.783851,...,2.276978,1.979746,2.602151,2.078356,2.039568,2.156817,2.773381,2.002456,3.028674,1.913386
25,Malaysia,Standard Malay,3.793548,1.548761,4.000000,1.232672,4.432258,1.304435,3.845161,1.372939,...,2.503226,1.785127,2.412903,1.689490,2.296774,2.064462,1.980645,1.672819,2.761290,1.643894
26,Malta,[No Direct Match],3.287234,1.787396,2.936620,1.564693,3.687943,1.623382,3.568905,1.614876,...,3.042254,1.933061,3.887324,1.820956,2.704225,2.094208,3.446809,1.838402,3.727915,1.794445
27,Netherlands,Dutch,3.325048,1.646279,3.671756,1.413904,4.160305,1.402357,3.553435,1.404380,...,2.408397,1.663121,3.574427,1.658224,2.335878,1.853572,1.402672,1.482876,2.869981,1.738211
28,Peru,Spanish,3.706161,1.884501,3.693023,1.503484,4.483721,1.500301,3.939252,1.457070,...,2.868545,1.827875,3.181395,1.988196,1.604651,1.720404,1.469767,1.617015,3.065116,1.768214
29,Russia,Russian,2.553043,1.774840,3.349565,1.524902,3.557292,1.654564,3.057292,1.579824,...,2.394415,1.771404,2.713542,1.983293,2.157986,2.033897,2.841739,1.816781,3.288194,1.748619
30,Serbia,Serbian-Croatian-Bosnian,2.712644,1.846614,3.517143,1.580139,4.312321,1.465069,3.794286,1.579950,...,2.424501,1.785457,2.742857,1.952779,2.194286,2.000565,2.965616,1.932472,2.985755,1.818106
31,South Africa,Afrikaans,2.946429,1.712904,3.642857,1.341353,4.196429,1.505780,3.696429,1.570214,...,2.883929,1.911301,3.991071,1.579688,2.276786,1.996437,2.098214,1.888609,3.160714,1.872290
32,Spain,Spanish,3.428571,1.994498,3.428571,1.616365,3.971154,1.742984,3.461538,1.773172,...,2.371429,1.771880,3.228571,1.912797,1.971429,2.011779,1.428571,1.663275,3.066667,1.733531
33,Sweden,Swedish,3.300000,1.774224,3.580000,1.482936,4.537500,1.289477,3.675000,1.374445,...,2.315000,1.693501,3.170000,1.835626,2.140000,1.990050,1.355890,1.523240,2.680000,1.773546
34,Syria,Arabic,1.849372,1.996402,3.377593,2.045971,3.878543,1.921589,2.888889,2.168520,...,2.122449,2.012590,2.275720,2.142184,2.325103,2.281181,1.636364,1.955946,2.799180,2.200972
35,Taiwan,Mandarin Chinese,3.993307,1.660520,3.666667,1.549020,3.722520,1.628423,3.695710,1.540472,...,1.990617,1.625689,1.842035,1.638740,1.605087,1.640841,1.215818,1.466518,1.962416,1.652201
36,Turkey,Turkish,2.027888,1.760460,3.611111,1.439191,3.956349,1.627111,3.804781,1.561325,...,2.948617,1.892269,2.881423,1.976491,2.494071,2.042447,1.768000,1.788567,3.575397,1.681357
37,Ukraine,Ukrainian,2.856489,1.644428,3.203957,1.565963,3.576220,1.516419,3.260274,1.528436,...,2.393293,1.827914,2.936073,1.930703,2.181402,1.950304,2.705793,1.814369,3.169466,1.849121
38,Vietnam,Vietnamese,4.219178,1.746841,4.263699,1.350442,3.872852,1.779476,4.096220,1.507803,...,1.688356,1.687472,2.441781,1.901356,1.859589,1.964674,1.534247,1.709743,2.047945,1.841978

In [232]:
stats_long = (
    stats_by_country
    .set_index(['countryname', 'bila_language_name_mapping'])
    .filter(regex='_(mean|std)$')
    .stack()
    .reset_index()
)

stats_long[['word', 'stat']] = stats_long['level_2'].str.rsplit('_', n=1, expand=True)
stats_long = stats_long.rename(columns={0: 'value'}).drop(columns='level_2')

stats_long = (
    stats_long
    .pivot_table(
        index=['countryname', 'bila_language_name_mapping', 'word'],
        columns='stat',
        values='value'
    )
    .reset_index()
)

merged = elab_per_emotion.merge(
    stats_long,
    left_on=['langname', 'word'],
    right_on=['bila_language_name_mapping', 'word'],
    how='left'
)

merged

,langname,glottocode,word,count,id,year,countryname,bila_language_name_mapping,mean,std
0,Turkish,nucl1301,admiration,10.0,coo.31924067983704,1991,Turkey,Turkish,2.027888,1.760460
1,Turkish,nucl1301,anger,85.0,coo.31924067983704,1991,Turkey,Turkish,3.460000,1.871473
2,Turkish,nucl1301,anxiety,77.0,coo.31924067983704,1991,Turkey,Turkish,3.150794,1.862045
3,Turkish,nucl1301,boredom,11.0,coo.31924067983704,1991,Turkey,Turkish,3.529644,1.880379
4,Turkish,nucl1301,compassion,33.0,coo.31924067983704,1991,Turkey,Turkish,3.956349,1.627111
...,...,...,...,...,...,...,...,...,...,...
671,Japanese,nucl1643,love,639.0,uva.x004877953,1974,Japan,Japanese,3.614130,1.511732
672,Japanese,nucl1643,pleasure,286.0,uva.x004877953,1974,Japan,Japanese,2.717172,1.495210
673,Japanese,nucl1643,regret,107.0,uva.x004877953,1974,Japan,Japanese,1.956522,1.623824
674,Japanese,nucl1643,relief,89.0,uva.x004877953,1974,Japan,Japanese,2.403263,1.417428
675,Japanese,nucl1643,sadness,9.0,uva.x004877953,1974,Japan,Japanese,2.601399,1.710028

In [233]:
merged = merged.merge(
    dictionary_means,
    left_on='id',
    right_on='id',
    how='left'
)
merged

,langname,glottocode,word,count,id,year,countryname,bila_language_name_mapping,mean,std,dictionary_count_mean
0,Turkish,nucl1301,admiration,10.0,coo.31924067983704,1991,Turkey,Turkish,2.027888,1.760460,22.086550
1,Turkish,nucl1301,anger,85.0,coo.31924067983704,1991,Turkey,Turkish,3.460000,1.871473,22.086550
2,Turkish,nucl1301,anxiety,77.0,coo.31924067983704,1991,Turkey,Turkish,3.150794,1.862045,22.086550
3,Turkish,nucl1301,boredom,11.0,coo.31924067983704,1991,Turkey,Turkish,3.529644,1.880379,22.086550
4,Turkish,nucl1301,compassion,33.0,coo.31924067983704,1991,Turkey,Turkish,3.956349,1.627111,22.086550
...,...,...,...,...,...,...,...,...,...,...,...
671,Japanese,nucl1643,love,639.0,uva.x004877953,1974,Japan,Japanese,3.614130,1.511732,44.928707
672,Japanese,nucl1643,pleasure,286.0,uva.x004877953,1974,Japan,Japanese,2.717172,1.495210,44.928707
673,Japanese,nucl1643,regret,107.0,uva.x004877953,1974,Japan,Japanese,1.956522,1.623824,44.928707
674,Japanese,nucl1643,relief,89.0,uva.x004877953,1974,Japan,Japanese,2.403263,1.417428,44.928707
675,Japanese,nucl1643,sadness,9.0,uva.x004877953,1974,Japan,Japanese,2.601399,1.710028,44.928707

In [234]:
merged = merged.rename(columns={'mean': "response_mean"})
merged = merged.rename(columns={'std': "response_std"})
merged = merged.drop('bila_language_name_mapping', axis=1)
merged = merged[['langname', 'countryname', 'word', 'count', 'dictionary_count_mean', 'response_mean', 'response_std', 'id', 'year', 'glottocode' ]]
merged = merged.sort_values(by=["langname", 'word'])
merged

,langname,countryname,word,count,dictionary_count_mean,response_mean,response_std,id,year,glottocode
234,Afrikaans,South Africa,admiration,6.0,32.003835,2.946429,1.712904,mdp.39015054154474,1999,afri1274
235,Afrikaans,South Africa,anger,55.0,32.003835,2.785714,1.803043,mdp.39015054154474,1999,afri1274
236,Afrikaans,South Africa,anxiety,30.0,32.003835,3.535714,1.765171,mdp.39015054154474,1999,afri1274
237,Afrikaans,South Africa,boredom,5.0,32.003835,2.241071,1.889971,mdp.39015054154474,1999,afri1274
238,Afrikaans,South Africa,compassion,15.0,32.003835,4.196429,1.505780,mdp.39015054154474,1999,afri1274
...,...,...,...,...,...,...,...,...,...,...
370,Vietnamese,Vietnam,love,308.0,43.597815,4.786942,1.311475,uc1.31210024487306,2003,viet1252
371,Vietnamese,Vietnam,pleasure,216.0,43.597815,2.832192,1.885719,uc1.31210024487306,2003,viet1252
372,Vietnamese,Vietnam,regret,59.0,43.597815,1.534247,1.709743,uc1.31210024487306,2003,viet1252
373,Vietnamese,Vietnam,relief,74.0,43.597815,3.199313,1.720505,uc1.31210024487306,2003,viet1252
374,Vietnamese,Vietnam,sadness,51.0,43.597815,2.047945,1.841978,uc1.31210024487306,2003,viet1252

In [235]:
merged = merged.reset_index(drop=True)
merged

,langname,countryname,word,count,dictionary_count_mean,response_mean,response_std,id,year,glottocode
0,Afrikaans,South Africa,admiration,6.0,32.003835,2.946429,1.712904,mdp.39015054154474,1999,afri1274
1,Afrikaans,South Africa,anger,55.0,32.003835,2.785714,1.803043,mdp.39015054154474,1999,afri1274
2,Afrikaans,South Africa,anxiety,30.0,32.003835,3.535714,1.765171,mdp.39015054154474,1999,afri1274
3,Afrikaans,South Africa,boredom,5.0,32.003835,2.241071,1.889971,mdp.39015054154474,1999,afri1274
4,Afrikaans,South Africa,compassion,15.0,32.003835,4.196429,1.505780,mdp.39015054154474,1999,afri1274
...,...,...,...,...,...,...,...,...,...,...
671,Vietnamese,Vietnam,love,308.0,43.597815,4.786942,1.311475,uc1.31210024487306,2003,viet1252
672,Vietnamese,Vietnam,pleasure,216.0,43.597815,2.832192,1.885719,uc1.31210024487306,2003,viet1252
673,Vietnamese,Vietnam,regret,59.0,43.597815,1.534247,1.709743,uc1.31210024487306,2003,viet1252
674,Vietnamese,Vietnam,relief,74.0,43.597815,3.199313,1.720505,uc1.31210024487306,2003,viet1252
675,Vietnamese,Vietnam,sadness,51.0,43.597815,2.047945,1.841978,uc1.31210024487306,2003,viet1252

In [238]:
merged = merged.sort_values(by=["langname", 'countryname','word'])

In [239]:
merged.to_csv("/data/home/asher.katz/data/hypocognition/output_results/covid_bila_merge.csv")

In [218]:
merged.columns

Index(['langname', 'glottocode', 'word', 'count', 'id', 'year', 'countryname',
       'response_mean', 'std'],
      dtype='object')

In [244]:

import plotly.express as px

# 1. Prepare data for the Heatmap
# We'll pivot the data to show Languages on one axis and Emotion Words on the other
heatmap_data = merged.pivot_table(
    index='langname', 
    columns='word', 
    values='response_mean', 
    aggfunc='mean'
)

# Create the Interactive Heatmap
fig_heatmap = px.imshow(
    heatmap_data,
    labels=dict(x="Emotion Word", y="Language", color="Intensity (Mean)"),
    x=heatmap_data.columns,
    y=heatmap_data.index,
    color_continuous_scale='Viridis',
    title='<b>Cross-Linguistic Emotional Intensity Heatmap</b><br><sup>Average survey response mean for each emotion word by language</sup>',
    aspect="auto"
)

fig_heatmap.update_layout(
    title_font_size=20,
    xaxis_tickangle=-45,
    width=1000,
    height=800
)

# 2. Interactive Scatter Plot
# This helps visualize the relationship between word frequency and response intensity
fig_scatter = px.scatter(
    merged, 
    x='count', 
    y='response_mean', 
    color='word',
    size='dictionary_count_mean', # Size points by dictionary frequency
    hover_data=['langname', 'countryname'],
    title='<b>Word Frequency vs. Emotional Intensity</b>',
    labels={'count': 'Word Count', 'response_mean': 'Mean Response'},
    trendline="ols", # Adds a trend line to see general correlation
    template='plotly_white'
)

# To view these in a notebook or browser:
fig_heatmap.show()
fig_scatter.show()

# To save as interactive HTML files:
# fig_heatmap.write_html("emotion_heatmap.html")
# fig_scatter.write_html("emotion_scatter.html")

In [247]:
import plotly.express as px


# 1. Calculate the 'Relative Usage Index'
merged['rel_usage_index'] = (merged['count'] / merged['dictionary_count_mean']) * 100

# 2. Create the Bubble Chart
fig = px.scatter(
    merged, 
    x='rel_usage_index', 
    y='response_mean',
    size='count',          # Larger bubbles = more survey responses
    color='response_std',  # Color shows agreement/disagreement
    hover_name='word',     # Show the emotion word on hover
    hover_data=['langname', 'countryname', 'count'],
    color_continuous_scale='RdBu_r', # Red for high variance, Blue for consensus
    title='<b>Emotional Salience: Usage Prominence vs. Intensity</b>',
    labels={
        'rel_usage_index': 'Relative Usage Index (Survey vs. Dict %)',
        'response_mean': 'Average Intensity (Mean)',
        'response_std': 'Response Variation (Std Dev)'
    },
    template='plotly_white'
)

# Optional: Use a log scale for X if some words have massive relative frequency
# fig.update_xaxes(type="log") 

fig.show()

In [ ]:

# 1. Calculate the 'Relative Usage Index'
merged['rel_usage_index'] = (merged['count'] / merged['dictionary_count_mean']) * 100
merged['log_count'] = log(merged['count'])

# 2. Create the Square, High-Contrast Bubble Chart
fig = px.scatter(
    merged, 
    x='rel_usage_index', 
    y='response_mean',
    size='count',          
    color='response_std',  
    hover_name='word',     
    hover_data=['langname', 'countryname'],
    # 'Viridis' is much easier to see than 'RdBu' on a white background
    color_continuous_scale='viridis', 
    opacity=0.85,          # Increased opacity so bubbles aren't faint
    title='<b>Emotional Salience: Usage Prominence vs. Intensity</b>',
    labels={
        'rel_usage_index': 'Relative Usage Index (%)',
        'response_mean': 'Average Intensity (Mean)',
        'response_std': 'Response Variation (Std Dev)'
    },
    template='plotly_white',
    # Setting equal width and height makes the plot square
    width=800,
    height=800
)

# 3. Add a border to markers to make them distinct
fig.update_traces(
    marker=dict(
        line=dict(width=1, color='black')
    ),
    selector=dict(mode='markers')
)

# Adjust layout for better readability
fig.update_layout(
    title_x=0.5,
    margin=dict(l=50, r=50, t=80, b=50),
    coloraxis_colorbar=dict(title="Variation (Std)")
)

fig.show()

In [255]:
import plotly.express as px
import pandas as pd
import numpy as np

# Assuming your dataframe is named 'merged'
# 1. Calculate the 'Relative Usage Index'
merged['ellaboration_relative_to_mean'] = (merged['count'] / merged['dictionary_count_mean'])

# 2. Calculate Log of Count to normalize bubble sizes
# np.log1p is used to handle low counts gracefully (calculates ln(1+x))
merged['log_count'] = np.log1p(merged['count'])

# 3. Create the Square, High-Contrast Bubble Chart
fig = px.scatter(
    merged, 
    x='ellaboration_relative_to_mean', 
    y='response_std',
    size='log_count',       # Using log_count for more uniform bubble sizes
    color='response_mean',  
    hover_name='word',     
    hover_data=['langname', 'countryname', 'count'], # Keep raw 'count' in hover
    color_continuous_scale='viridis', 
    opacity=0.85,
    title='<b>Ellaboration_relative_to_mean (Log Scaled) vs. Response STD </b>',
    labels={
        'ellaboration_relative_to_mean': 'ellaboration_relative_to_mean (count/dictionary_count_mean)',
        'response_mean': 'Mean of responses',
        'response_std': 'STD of responses',
        'log_count': 'Log of Count'
    },
    template='plotly_white',
    width=800,
    height=800
)

# 4. Refine marker appearance
fig.update_traces(
    marker=dict(
        line=dict(width=1, color='black'),
        sizemode='area', # Ensures bubble size is proportional to the area
        sizeref=0.1      # Adjust this number if bubbles are still too large/small
    ),
    selector=dict(mode='markers')
)

# 5. Center title and adjust colorbar
fig.update_layout(
    title_x=0.5,
    margin=dict(l=50, r=50, t=80, b=50),
    coloraxis_colorbar=dict(title="Response_mean")
)

fig.show()