In [5]:
# load libraries 
import pandas as pd
import numpy as np
import re
import math
import plotly.graph_objects as go
import plotly.express as px
from pathlib import Path

In [6]:
# get the SUN covid study dataset
Covid51countries = pd.read_csv(Path("~/Projects/hypocognition/data/raw/Covid51countries.csv").expanduser())
Covid51countries

,country,countryname,StartDate,EndDate,Status,Progress,Duration,Finished,RecordedDate,home,...,gender,ladder,employment,losejob,covidsymptom,language,datasource,ISO3,longstring,na_count
0,10,Australia,04/05/2020 19:34,04/05/2020 19:40,0.0,100.0,337.0,1.0,04/05/2020 19:40,8.0,...,1.0,5.0,4,NaN,0.0,ZH-S,snowball,AUS,3,0
1,10,Australia,04/05/2020 20:26,04/05/2020 20:35,0.0,100.0,530.0,1.0,04/05/2020 20:35,9.0,...,2.0,7.0,3,NaN,NaN,ZH-S,snowball,AUS,3,0
2,10,Australia,05/05/2020 21:54,05/05/2020 22:07,0.0,100.0,793.0,1.0,05/05/2020 22:07,29.0,...,1.0,4.0,1,NaN,0.0,ZH-S,snowball,AUS,5,0
3,10,Australia,04/05/2020 20:29,04/05/2020 20:34,0.0,100.0,285.0,1.0,04/05/2020 20:34,73.0,...,2.0,5.0,4,NaN,0.0,ZH-S,snowball,AUS,4,0
4,10,Australia,19/04/2020 20:21,19/04/2020 20:27,0.0,100.0,367.0,1.0,19/04/2020 20:27,100.0,...,1.0,5.0,1,NaN,0.0,ZH-S,snowball,AUS,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24216,92,Kenya,25/04/2020 01:25,25/04/2020 02:44,0.0,100.0,4690.0,1.0,25/04/2020 02:44,100.0,...,2.0,4.0,4,NaN,0.0,EN,snowball,KEN,4,0
24217,92,Kenya,24/04/2020 11:06,24/04/2020 11:15,0.0,100.0,556.0,1.0,24/04/2020 11:15,100.0,...,1.0,6.0,5,0.0,0.0,EN,snowball,KEN,2,0
24218,92,Kenya,26/04/2020 10:16,26/04/2020 10:36,0.0,100.0,1218.0,1.0,26/04/2020 10:36,80.0,...,1.0,3.0,4,NaN,0.0,EN,snowball,KEN,3,0
24219,92,Kenya,23/04/2020 03:46,23/04/2020 04:13,0.0,100.0,1641.0,1.0,23/04/2020 04:13,3.0,...,1.0,3.0,4,NaN,0.0,EN,snowball,KEN,3,0
24220,92,Kenya,24/04/2020 00:31,24/04/2020 00:42,0.0,100.0,700.0,1.0,24/04/2020 00:42,50.0,...,2.0,6.0,4,NaN,0.0,EN,snowball,KEN,2,0

In [7]:
mask = (Covid51countries["countryname"] == "Spain") & (Covid51countries["language"] == "ES")
Covid51countries.loc[mask, "language"] = "ES-ES"

In [8]:
# We want to use on only one language of responses for each country
# Further, that language cannot be English

# Calculate the number of responses for each country
country_response_count = pd.DataFrame(Covid51countries[['countryname', 'ISO3']].value_counts())

#collect the languages which people used to respond from each country
languages_per_country = Covid51countries.groupby('countryname')['language'].value_counts().reset_index(name="count")

# mereg num resposes to languages people used
languages_per_country = languages_per_country.merge(
    country_response_count,
    on="countryname",
    how="left"
)

# Clean up
languages_per_country = languages_per_country.rename(columns={"count_x": "lang_responses", "count_y": "total_responses"})
languages_per_country["percent"] = languages_per_country["lang_responses"] / languages_per_country["total_responses"] * 100

languages_per_country

    countryname language  lang_responses  total_responses    percent
0     Australia     ZH-S             181              378  47.883598
1     Australia       EN             156              378  41.269841
2     Australia       ID              12              378   3.174603
3     Australia     ZH-T              10              378   2.645503
4     Australia       VI               5              378   1.322751
..          ...      ...             ...              ...        ...
495     Vietnam     ZH-S               2              338   0.591716
496     Vietnam       FR               1              338   0.295858
497     Vietnam       JA               1              338   0.295858
498     Vietnam       PL               1              338   0.295858
499     Vietnam    ZH-TW               1              338   0.295858

[500 rows x 5 columns]

In [9]:
# get a table which translates some of the language codes into names
lang_names = pd.read_csv(Path("~/Projects/hypocognition/data/external/lang_names.csv"))
languages_per_country = languages_per_country.merge(lang_names, left_on="language", right_on="Code", how="left")
languages_per_country = languages_per_country.drop(columns=["Code"])
languages_per_country

,countryname,language,lang_responses,total_responses,percent,Language_Name
0,Australia,ZH-S,181,378,47.883598,Simplified Chinese
1,Australia,EN,156,378,41.269841,English
2,Australia,ID,12,378,3.174603,Indonesian
3,Australia,ZH-T,10,378,2.645503,Traditional Chinese
4,Australia,VI,5,378,1.322751,Vietnamese
...,...,...,...,...,...,...
495,Vietnam,ZH-S,2,338,0.591716,Simplified Chinese
496,Vietnam,FR,1,338,0.295858,French
497,Vietnam,JA,1,338,0.295858,Japanese
498,Vietnam,PL,1,338,0.295858,Polish
499,Vietnam,ZH-TW,1,338,0.295858,Traditional Chinese (Taiwan)

In [10]:
languages_per_country.to_csv(Path("~/Projects/hypocognition/data/processed/languages_per_country.csv").expanduser())

In [11]:
selection = pd.read_csv(Path("~/Projects/hypocognition/data/processed/sun_bila_selection.csv").expanduser())

In [12]:
# Lets filter the dataset using our new selection
filtered = Covid51countries.merge(
    selection,
    on=['countryname', 'language'],
    how='inner'
)
filtered

,country,countryname,StartDate,EndDate,Status,Progress,Duration,Finished,RecordedDate,home,...,datasource,ISO3,longstring,na_count,Unnamed: 0,lang_responses,total_responses,percent,Language_Name,Mapped_Target_Language
0,10,Australia,04/05/2020 19:34,04/05/2020 19:40,0.0,100.0,337.0,1.0,04/05/2020 19:40,8.0,...,snowball,AUS,3,0,0,181,378,47.883598,Simplified Chinese,Mandarin Chinese
1,10,Australia,04/05/2020 20:26,04/05/2020 20:35,0.0,100.0,530.0,1.0,04/05/2020 20:35,9.0,...,snowball,AUS,3,0,0,181,378,47.883598,Simplified Chinese,Mandarin Chinese
2,10,Australia,05/05/2020 21:54,05/05/2020 22:07,0.0,100.0,793.0,1.0,05/05/2020 22:07,29.0,...,snowball,AUS,5,0,0,181,378,47.883598,Simplified Chinese,Mandarin Chinese
3,10,Australia,04/05/2020 20:29,04/05/2020 20:34,0.0,100.0,285.0,1.0,04/05/2020 20:34,73.0,...,snowball,AUS,4,0,0,181,378,47.883598,Simplified Chinese,Mandarin Chinese
4,10,Australia,19/04/2020 20:21,19/04/2020 20:27,0.0,100.0,367.0,1.0,19/04/2020 20:27,100.0,...,snowball,AUS,3,0,0,181,378,47.883598,Simplified Chinese,Mandarin Chinese
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15515,91,Kazakhstan,25/04/2020 13:36,25/04/2020 13:44,0.0,100.0,470.0,1.0,25/04/2020 13:44,100.0,...,snowball,KAZ,3,0,28,279,291,95.876289,Russian,Russian
15516,91,Kazakhstan,06/05/2020 04:03,06/05/2020 04:18,0.0,100.0,884.0,1.0,06/05/2020 04:18,100.0,...,snowball,KAZ,3,0,28,279,291,95.876289,Russian,Russian
15517,91,Kazakhstan,06/05/2020 12:32,06/05/2020 12:41,0.0,100.0,573.0,1.0,06/05/2020 12:41,100.0,...,snowball,KAZ,4,0,28,279,291,95.876289,Russian,Russian
15518,91,Kazakhstan,06/05/2020 10:37,06/05/2020 10:49,0.0,100.0,701.0,1.0,06/05/2020 10:49,100.0,...,snowball,KAZ,5,0,28,279,291,95.876289,Russian,Russian
15519,91,Kazakhstan,06/05/2020 11:19,06/05/2020 11:32,0.0,100.0,776.0,1.0,06/05/2020 11:32,100.0,...,snowball,KAZ,2,0,28,279,291,95.876289,Russian,Russian

In [13]:
filtered = filtered[filtered["Mapped_Target_Language"]!="NONE"]

In [14]:
filtered[filtered['countryname']=="Spain"]['Language_Name'].unique()

array(['Spanish (Spain)'], dtype=object)

In [15]:
# Check to make sure it worked
filtered.groupby('countryname')['Language_Name'].unique()

countryname
Australia                                   [Simplified Chinese]
Brazil                                    [Brazilian Portuguese]
Bulgaria                                             [Bulgarian]
Canada                                      [Simplified Chinese]
Chile                                                  [Spanish]
China                                       [Simplified Chinese]
Colombia                                               [Spanish]
Croatia                                               [Croatian]
Curacao                                                  [Dutch]
Denmark                                                 [Danish]
Egypt                                                   [Arabic]
Finland                                                [Finnish]
France                                                  [French]
Georgia                                               [Georgian]
Germany                                                 [German]
Ghana                                       [Simplified Chinese]
Greece                                                   [Greek]
Hong Kong (S.A.R)                          [Traditional Chinese]
Hungary                                              [Hungarian]
Iceland                                              [Icelandic]
India                                                  [Marathi]
Indonesia                                           [Indonesian]
Iran                                                   [Persian]
Ireland                                               [Croatian]
Israel                                                  [Hebrew]
Italy                                                  [Italian]
Japan                                                 [Japanese]
Jordan                                                  [Arabic]
Kazakhstan                                             [Russian]
Malaysia                                                 [Malay]
Mongolia                                               [Russian]
Netherlands                                              [Dutch]
New Zealand                                 [Simplified Chinese]
Pakistan                                                [French]
Peru                                           [Spanish (Spain)]
Russia                                                 [Russian]
Serbia                                                 [Serbian]
Singapore                                   [Simplified Chinese]
South Africa                                         [Afrikaans]
Spain                                          [Spanish (Spain)]
Sweden                                                 [Swedish]
Syria                                                   [Arabic]
Taiwan                            [Traditional Chinese (Taiwan)]
Trinidad and Tobago                                    [Spanish]
Turkey                                                 [Turkish]
Ukraine                                              [Ukrainian]
United Kingdom (UK)                         [Simplified Chinese]
United States of America (USA)              [Simplified Chinese]
Vietnam                                             [Vietnamese]
Name: Language_Name, dtype: object

In [16]:
filtered.groupby('countryname')['Mapped_Target_Language'].unique()

countryname
Australia                                 [Mandarin Chinese]
Brazil                                [Brazilian Portuguese]
Bulgaria                                         [Bulgarian]
Canada                                    [Mandarin Chinese]
Chile                                              [Spanish]
China                                     [Mandarin Chinese]
Colombia                                           [Spanish]
Croatia                           [Serbian-Croatian-Bosnian]
Curacao                                              [Dutch]
Denmark                                             [Danish]
Egypt                                               [Arabic]
Finland                                            [Finnish]
France                                              [French]
Georgia                                           [Georgian]
Germany                                             [German]
Ghana                                     [Mandarin Chinese]
Greece                                               [Greek]
Hong Kong (S.A.R)                         [Mandarin Chinese]
Hungary                                          [Hungarian]
Iceland                                          [Icelandic]
India                                              [Marathi]
Indonesia                                       [Indonesian]
Iran                                               [Persian]
Ireland                           [Serbian-Croatian-Bosnian]
Israel                                              [Hebrew]
Italy                                              [Italian]
Japan                                             [Japanese]
Jordan                                              [Arabic]
Kazakhstan                                         [Russian]
Malaysia                                    [Standard Malay]
Mongolia                                           [Russian]
Netherlands                                          [Dutch]
New Zealand                               [Mandarin Chinese]
Pakistan                                            [French]
Peru                                               [Spanish]
Russia                                             [Russian]
Serbia                            [Serbian-Croatian-Bosnian]
Singapore                                 [Mandarin Chinese]
South Africa                                     [Afrikaans]
Spain                                              [Spanish]
Sweden                                             [Swedish]
Syria                                               [Arabic]
Taiwan                                    [Mandarin Chinese]
Trinidad and Tobago                                [Spanish]
Turkey                                             [Turkish]
Ukraine                                          [Ukrainian]
United Kingdom (UK)                       [Mandarin Chinese]
United States of America (USA)            [Mandarin Chinese]
Vietnam                                         [Vietnamese]
Name: Mapped_Target_Language, dtype: object

Goals
* For each distinct language, what is the lexical ellaboration for each of the 20 emotions?
* For each distinct language, is there any statistical significance in the distribution of the results of any particular emotion?

In [17]:
# drop the rest of the ~75 columns
filtered = filtered[['countryname', 'countryname', 'Language_Name', 'language', 'percent', 'admiration', 'calm', 'compassion',
       'determination', 'moved', 'gratitude', 'hope', 'love', 'relief',
       'pleasure', 'anger', 'anxiety', 'boredom', 'confusion', 'disgust',
       'fear', 'frustration', 'loneliness', 'regret', 'sadness']].copy()

In [18]:
emotions = ['admiration', 'calm', 'compassion',
       'determination', 'moved', 'gratitude', 'hope', 'love', 'relief',
       'pleasure', 'anger', 'anxiety', 'boredom', 'confusion', 'disgust',
       'fear', 'frustration', 'loneliness', 'regret', 'sadness']

In [19]:
# get the dataset of the dictionaries. We will look at how elaborated each of the twenty emotions are in each of the 39 languages
bila_nouns_full = pd.read_csv(Path("~/Projects/hypocognition/data/raw/bila_long_noun_lemmatized_full.csv").expanduser(), index_col=0)
bila_nouns_full

/tmp/ipykernel_2912789/268126284.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  bila_nouns_full = pd.read_csv(Path("~/Projects/hypocognition/data/raw/bila_long_noun_lemmatized_full.csv").expanduser(), index_col=0)

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,estimate,regression_elaboration,dictsize_data,simple_elaboration,log_count
0,chi.14718491,ability,2.0,2.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.725128,-1.424169,10499,0.000190,1.098612
1,chi.14718491,accomplice,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-0.156552,10499,0.000000,0.000000
2,chi.14718491,account,14.0,9.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-7.520776,-2.250524,10499,0.000857,2.302585
3,chi.14718491,acre,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-0.444142,10499,0.000000,0.000000
4,chi.14718491,act,15.0,6.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,0.000000,0.000000,10499,0.000571,1.945910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5282195,wu.89119131142,prouds,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282196,wu.89119131142,facilitator,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282197,wu.89119131142,teacher-librarian,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282198,wu.89119131142,pandani,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282199,wu.89119131142,seat-bone,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000

In [20]:
with open(Path("~/Projects/hypocognition/data/external/stopwords.txt").expanduser()) as f:
    words = [line.strip() for line in f if line.strip()]
words

['word',
 'name',
 'form',
 'verb',
 'sound',
 'noun',
 'letter',
 'language',
 'class',
 'case',
 'mark',
 'comp',
 'note',
 'term',
 'meaning',
 'root',
 'sense',
 'prep',
 'speech',
 'subject',
 'sign',
 'character',
 'prop',
 'dictionary',
 'article',
 'adjective',
 'stem',
 'sentence',
 'particle',
 'dial',
 'person',
 'fig',
 'phrase',
 'section',
 'compound',
 'par',
 'con',
 'sub',
 'thing',
 'place',
 'part',
 'kind',
 'act',
 'way',
 'cause',
 'set',
 'side',
 'piece',
 'end',
 'state',
 'use',
 'round',
 'point',
 'manner',
 'object',
 'change',
 'matter',
 'action',
 'self',
 'top',
 'cover',
 'measure',
 'bit',
 'sort',
 'type',
 'good',
 'colour',
 'lot',
 'min',
 'middle',
 'degree',
 'member',
 'house',
 'home',
 'school',
 'work',
 'life',
 'mind',
 'number',
 'art',
 'world',
 'level',
 'style',
 'variety',
 'amount',
 'show',
 'specie',
 'man',
 'men',
 'woman',
 'women',
 'people',
 'family',
 'father',
 'mother',
 'son',
 'daughter',
 'child',
 'wife',
 'husband',
 'boy',
 'girl',
 'brother',
 'sister',
 'day',
 'night',
 'year',
 'period',
 'time',
 'advance',
 'base',
 'beat',
 'block',
 'blow',
 'break',
 'center',
 'charge',
 'discharge',
 'dress',
 'drive',
 'fall',
 'field',
 'flat',
 'ground',
 'head',
 'light',
 'line',
 'order',
 'pack',
 'post',
 'pound',
 'return',
 'rise',
 'roll',
 'shift',
 'shot',
 'spot',
 'step',
 'stick',
 'stock',
 'strike',
 'support',
 'swing',
 'tap',
 'crack',
 'face',
 'hook',
 'pitch',
 'fly',
 'white',
 'back',
 'check',
 'clearing',
 'cut',
 'deal',
 'dip',
 'double',
 'key',
 'opening',
 'press',
 'release',
 'saw',
 'shooting',
 'square',
 'strain',
 'stretch',
 'touch',
 'twist',
 'bound',
 'cutting',
 'down',
 'drove',
 'have',
 'right',
 'rose',
 'standing',
 'well',
 'bearing',
 'drawing',
 'short',
 'cleaner',
 'beating',
 'black',
 'holding',
 'working',
 'setting',
 'making']

In [21]:
# remove stop words
bila_nouns_full = bila_nouns_full[~bila_nouns_full["word"].isin(words)]
bila_nouns_full

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,estimate,regression_elaboration,dictsize_data,simple_elaboration,log_count
0,chi.14718491,ability,2.0,2.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.725128,-1.424169,10499,0.000190,1.098612
1,chi.14718491,accomplice,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-0.156552,10499,0.000000,0.000000
2,chi.14718491,account,14.0,9.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-7.520776,-2.250524,10499,0.000857,2.302585
3,chi.14718491,acre,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-0.444142,10499,0.000000,0.000000
6,chi.14718491,actor,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-1.633890,10499,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5282195,wu.89119131142,prouds,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282196,wu.89119131142,facilitator,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282197,wu.89119131142,teacher-librarian,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282198,wu.89119131142,pandani,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282199,wu.89119131142,seat-bone,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000

In [22]:
tot_words = bila_nouns_full.groupby('id')['word'].nunique().reset_index(name='Total_words_in_dict')
tot_words

                                          id  Total_words_in_dict
0                               chi.14718491                 8390
1                         coo.31924067983704                 8390
2                         coo.31924099174934                 8390
3                  coo1.ark:/13960/t9m33d507                 8390
4     dictionaria.daakaka_vonprince_daka1243                 8390
..                                       ...                  ...
611  webonary.sursurunga_hutchisson_surs1246                 8390
612         webonary.tampulma_asare_tamp1252                 8390
613      webonary.turkmen_almamedow_turk1304                 8390
614                           wu.89017649658                 8390
615                           wu.89119131142                 8390

[616 rows x 2 columns]

In [23]:
tot_counts = bila_nouns_full.groupby('id')['count'].sum().reset_index(name='Total_counts_in_dict')
tot_counts

                                          id  Total_counts_in_dict
0                               chi.14718491               10499.0
1                         coo.31924067983704              121674.0
2                         coo.31924099174934               10358.0
3                  coo1.ark:/13960/t9m33d507               20574.0
4     dictionaria.daakaka_vonprince_daka1243                1825.0
..                                       ...                   ...
611  webonary.sursurunga_hutchisson_surs1246               32836.0
612         webonary.tampulma_asare_tamp1252                4117.0
613      webonary.turkmen_almamedow_turk1304               27273.0
614                           wu.89017649658               12018.0
615                           wu.89119131142               33359.0

[616 rows x 2 columns]

In [24]:
# I think we will needs these later
dictionary_means = (
    bila_nouns_full
        .groupby('id', as_index=False)['count']
        .mean()
        .rename(columns={'count': 'dictionary_count_mean'})
)
dictionary_means

                                          id  dictionary_count_mean
0                               chi.14718491               1.251371
1                         coo.31924067983704              14.502265
2                         coo.31924099174934               1.234565
3                  coo1.ark:/13960/t9m33d507               2.452205
4     dictionaria.daakaka_vonprince_daka1243               0.217521
..                                       ...                    ...
611  webonary.sursurunga_hutchisson_surs1246               3.913707
612         webonary.tampulma_asare_tamp1252               0.490703
613      webonary.turkmen_almamedow_turk1304               3.250656
614                           wu.89017649658               1.432420
615                           wu.89119131142               3.976043

[616 rows x 2 columns]

In [25]:
bila_nouns_full_emotions = bila_nouns_full[bila_nouns_full['word'].isin(emotions)].reset_index(drop=True)
bila_nouns_full_emotions

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,estimate,regression_elaboration,dictsize_data,simple_elaboration,log_count
0,chi.14718491,fear,8.0,9.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-7.520776,-1.337584,10499,0.000857,2.302585
1,chi.14718491,pleasure,5.0,5.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.031819,-1.571145,10499,0.000476,1.791759
2,chi.14718491,regret,5.0,2.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.725128,-0.486657,10499,0.000190,1.098612
3,chi.14718491,admiration,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-0.710507,10499,0.000000,0.000000
4,chi.14718491,anger,5.0,2.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.725128,-2.335062,10499,0.000190,1.098612
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11083,wu.89119131142,disgust,3.0,16.0,Herero,here1253,1989.0,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,-7.795743,3.869782,33359,0.000480,2.833213
11084,wu.89119131142,frustration,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-10.629344,-0.596842,33359,0.000000,0.000000
11085,wu.89119131142,loneliness,3.0,4.0,Herero,here1253,1989.0,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,-9.019809,1.825273,33359,0.000120,1.609438
11086,wu.89119131142,relief,11.0,10.0,Herero,here1253,1989.0,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,-8.231207,0.866433,33359,0.000300,2.397895
11087,wu.89119131142,boredom,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-10.629344,-0.597769,33359,0.000000,0.000000

the dataset is missing two of the survey emotions, {'calm', 'moved'}

In [26]:
# already filtered out everything but the 20 emotions
# now we want to filter evrything but the 39 languages
# Where are lang_name and Language_Names the Same?
emotions_in_survey_languages_in_bila = bila_nouns_full_emotions[bila_nouns_full_emotions['langname'].isin(filtered['Language_Name'].unique())].reset_index(drop=True)
emotions_in_survey_languages_in_bila

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,estimate,regression_elaboration,dictsize_data,simple_elaboration,log_count
0,coo.31924067983704,fear,8.0,126.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-6.924086,1.952545,121674,0.001036,4.844187
1,coo.31924067983704,pleasure,5.0,107.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-7.086289,3.153327,121674,0.000879,4.682131
2,coo.31924067983704,regret,5.0,41.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-8.031261,2.670962,121674,0.000337,3.737670
3,coo.31924067983704,admiration,3.0,10.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-9.371276,-0.854986,121674,0.000082,2.397895
4,coo.31924067983704,anger,5.0,85.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-7.314243,0.579516,121674,0.000699,4.454347
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,uva.x004877953,disgust,3.0,13.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-9.940215,-4.505457,282895,0.000046,2.639057
428,uva.x004877953,frustration,3.0,6.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-10.633387,-1.588076,282895,0.000021,1.945910
429,uva.x004877953,loneliness,3.0,7.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-10.499852,-1.873436,282895,0.000025,2.079442
430,uva.x004877953,relief,11.0,89.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-8.079201,3.907437,282895,0.000315,4.499810
431,uva.x004877953,boredom,1.0,6.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-10.633387,-1.590590,282895,0.000021,1.945910

In [27]:
# I asked gemini to map our study languages names to language names from the bila dataset
covid_to_bila_nouns_full_lang_name_mapping = pd.read_csv(Path("~/Projects/hypocognition/data/external/covid_to_full_bila_lang_name_mapping.csv"))
covid_to_bila_nouns_full_lang_name_mapping

,code,study_language_names,bila_language_name_mapping,possible_alternative_bila_language_name_mappings
0,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
1,EN,English,NaN,"Midland American English, Singlish, Devon, Sus..."
2,ID,Indonesian,Indonesian,"Standard Malay, Central Malay, Baba Malay"
3,ZH-T,Traditional Chinese,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese..."
4,VI,Vietnamese,Vietnamese,Nung (Viet Nam)
5,DA,Danish,Danish,NaN
6,AR,Arabic,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
7,ES,Spanish,Spanish,"Latin American Spanish, Mexican Spanish"
8,AFRI,Afrikaans,Afrikaans,Dutch
9,ES-ES,Spanish (Spain),Spanish,NaN
10,ET,Estonian,Estonian,Finnish
11,FR,French,French,"Old French, Cajun French, Louisiana Creole French"
12,JA,Japanese,Japanese,Middle Chinese
13,SR,Serbian,Serbian-Croatian-Bosnian,NaN
14,ZH-TW,Traditional Chinese (Taiwan),Mandarin Chinese,"Min Nan Chinese, Hakka Chinese"
15,PT-BR,Brazilian Portuguese,Brazilian Portuguese,Portuguese
16,PT,Portuguese,Portuguese,Brazilian Portuguese
17,IT,Italian,Italian,Sicilian
18,BG,Bulgarian,Bulgarian,NaN
19,RU,Russian,Russian,Belarusian
20,FA,Persian,Persian,NaN
21,UK,Ukrainian,Ukrainian,NaN
22,NL,Dutch,Dutch,Western Flemish
23,DE,German,German,"Moselle Franconian, Plautdietsch, Pennsylvania..."
24,MS,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo"
25,TR,Turkish,Turkish,Turkmen
26,HR,Croatian,Serbian-Croatian-Bosnian,NaN
27,ISL,Icelandic,Icelandic,Old Norse
28,NO,Norwegian,Norwegian,NaN
29,RO,Romanian,Romanian,Aromanian
30,FI,Finnish,Finnish,Estonian
31,KAT,Georgian,Georgian,NaN
32,SV,Swedish,Swedish,NaN
33,EL,Greek,Greek,NaN
34,CA,Catalan,NaN,"Spanish, French"
35,HU,Hungarian,Hungarian,NaN
36,SL,Slovenian,Slovenian,NaN
37,CS,Czech,Czech,NaN
38,PL,Polish,Polish,NaN
39,SK,Slovak,Slovak,NaN
40,MAR,Marathi,Marathi,NaN
41,HI,Hindi,Hindi,"Hindustani, Caribbean Hindustani"
42,HE,Hebrew,Hebrew,Ancient Hebrew
43,KO,Korean,Korean,NaN
44,KAZ,Kazakh,Kazakh,NaN
45,ML,Malayalam,Malayalam,NaN
46,MALTI,Maltese,NaN,"Arabic, Italian"
47,FILIP,Filipino,Filipino,Tagalog-Pilipino
48,DARI,Dari,Persian,NaN

In [28]:
# Update selection table 
selection_in_bila =selection.merge(
    covid_to_bila_nouns_full_lang_name_mapping,
    left_on="Language_Name",
    right_on="study_language_names",
    how="left"
)

selection_in_bila

,Unnamed: 0,countryname,language,lang_responses,total_responses,percent,Language_Name,Mapped_Target_Language,code,study_language_names,bila_language_name_mapping,possible_alternative_bila_language_name_mappings
0,0,Australia,ZH-S,181,378,47.883598,Simplified Chinese,Mandarin Chinese,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
1,1,Brazil,PT-BR,306,325,94.153846,Brazilian Portuguese,Brazilian Portuguese,PT-BR,Brazilian Portuguese,Brazilian Portuguese,Portuguese
2,2,Bulgaria,BG,269,276,97.463768,Bulgarian,Bulgarian,BG,Bulgarian,Bulgarian,NaN
3,3,Canada,ZH-S,26,286,9.090909,Simplified Chinese,Mandarin Chinese,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
4,4,Chile,ES,469,493,95.131846,Spanish,Spanish,ES,Spanish,Spanish,"Latin American Spanish, Mexican Spanish"
5,5,China,ZH-S,1988,2009,98.954704,Simplified Chinese,Mandarin Chinese,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
6,6,Colombia,ES,122,237,51.476793,Spanish,Spanish,ES,Spanish,Spanish,"Latin American Spanish, Mexican Spanish"
7,7,Croatia,HR,524,528,99.242424,Croatian,Serbian-Croatian-Bosnian,HR,Croatian,Serbian-Croatian-Bosnian,NaN
8,8,Curacao,NL,180,235,76.595745,Dutch,Dutch,NL,Dutch,Dutch,Western Flemish
9,9,Denmark,DA,148,233,63.519313,Danish,Danish,DA,Danish,Danish,NaN
10,10,Egypt,AR,817,824,99.150485,Arabic,Arabic,AR,Arabic,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
11,11,Finland,FI,260,289,89.965398,Finnish,Finnish,FI,Finnish,Finnish,Estonian
12,12,France,FR,257,363,70.798898,French,French,FR,French,French,"Old French, Cajun French, Louisiana Creole French"
13,13,Georgia,KAT,234,236,99.152542,Georgian,Georgian,KAT,Georgian,Georgian,NaN
14,14,Germany,DE,291,567,51.322751,German,German,DE,German,German,"Moselle Franconian, Plautdietsch, Pennsylvania..."
15,15,Ghana,ZH-S,1,328,0.304878,Simplified Chinese,Mandarin Chinese,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
16,16,Greece,EL,227,253,89.723320,Greek,Greek,EL,Greek,Greek,NaN
17,17,Hong Kong (S.A.R),ZH-T,139,228,60.964912,Traditional Chinese,Mandarin Chinese,ZH-T,Traditional Chinese,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese..."
18,18,Hungary,HU,256,464,55.172414,Hungarian,Hungarian,HU,Hungarian,Hungarian,NaN
19,19,Iceland,ISL,348,354,98.305085,Icelandic,Icelandic,ISL,Icelandic,Icelandic,Old Norse
20,20,India,MAR,56,243,23.045267,Marathi,Marathi,MAR,Marathi,Marathi,NaN
21,21,Indonesia,ID,648,656,98.780488,Indonesian,Indonesian,ID,Indonesian,Indonesian,"Standard Malay, Central Malay, Baba Malay"
22,22,Iran,FA,187,195,95.897436,Persian,Persian,FA,Persian,Persian,NaN
23,23,Ireland,HR,3,362,0.828729,Croatian,Serbian-Croatian-Bosnian,HR,Croatian,Serbian-Croatian-Bosnian,NaN
24,24,Israel,HE,151,211,71.563981,Hebrew,Hebrew,HE,Hebrew,Hebrew,Ancient Hebrew
25,25,Italy,IT,426,466,91.416309,Italian,Italian,IT,Italian,Italian,Sicilian
26,26,Japan,JA,1288,1352,95.266272,Japanese,Japanese,JA,Japanese,Japanese,Middle Chinese
27,27,Jordan,AR,233,236,98.728814,Arabic,Arabic,AR,Arabic,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
28,28,Kazakhstan,RU,279,291,95.876289,Russian,Russian,RU,Russian,Russian,Belarusian
29,29,Malaysia,MS,155,214,72.429907,Malay,Standard Malay,MS,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo"
30,30,Malta,MALTI,284,1290,22.015504,Maltese,NONE,MALTI,Maltese,NaN,"Arabic, Italian"
31,31,Mongolia,RU,13,208,6.250000,Russian,Russian,RU,Russian,Russian,Belarusian
32,32,Netherlands,NL,524,1348,38.872404,Dutch,Dutch,NL,Dutch,Dutch,Western Flemish
33,33,New Zealand,ZH-S,102,262,38.931298,Simplified Chinese,Mandarin Chinese,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
34,34,Pakistan,FR,2,557,0.359066,French,French,FR,French,French,"Old French, Cajun French, Louisiana Creole French"
35,35,Peru,ES-ES,215,357,60.224090,Spanish (Spain),Spanish,ES-ES,Spanish (Spain),Spanish,NaN
36,36,Russia,RU,577,586,98.464164,Russian,Russian,RU,Russian,Russian,Belarusian
37,37,Serbia,SR,351,354,99.152542,Serbian,Serbian-Croatian-Bosnian,SR,Serbian,Serbian-Croatian-Bosnian,NaN
38,38,Singapore,ZH-S,8,208,3.846154,Simplified Chinese,Mandarin Chinese,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
39,39,South Africa,AFRI,112,426,26.291080,Afrikaans,Afrikaans,AFRI,Afrikaans,Afrikaans,Dutch
40,40,Spain,CA,187,418,44.736842,Spanish (Spain),Spanish,ES-ES,Spanish (Spain),Spanish,NaN
41,41,Sweden,SV,400,529,75.614367,Swedish,Swedish,SV,Swedish,Swedish,NaN
42,42,Syria,AR,247,248,99.596774,Arabic,Arabic,AR,Arabic,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
43,43,Taiwan,ZH-TW,747,761,98.160315,Traditional Chinese (Taiwan),Mandarin Chinese,ZH-TW,Traditional Chinese (Taiwan),Mandarin Chinese,"Min Nan Chinese, Hakka Chinese"
44,44,Trinidad and Tobago,ES,1,334,0.299401,Spanish,Spanish,ES,Spanish,Spanish,"Latin American Spanish, Mexican Spanish"
45,45,Turkey,TR,253,346,73.121387,Turkish,Turkish,TR,Turkish,Turkish,Turkmen
46,46,Ukraine,UK,657,698,94.126074,Ukrainian,Ukrainian,UK,Ukrainian,Ukrainian,NaN
47,47,United Kingdom (UK),ZH-S,34,662,5.135952,Simplified Chinese,Mandarin Chinese,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
48,48,United States of America (USA),ZH-S,45,952,4.726891,Simplified Chinese,Mandarin Chinese,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
49,49,Vietnam,VI,292,338,86.390533,Vietnamese,Vietnamese,VI,Vietnamese,Vietnamese,Nung (Viet Nam)

In [29]:
selection_in_bila.columns

Index(['Unnamed: 0', 'countryname', 'language', 'lang_responses',
       'total_responses', 'percent', 'Language_Name', 'Mapped_Target_Language',
       'code', 'study_language_names', 'bila_language_name_mapping',
       'possible_alternative_bila_language_name_mappings'],
      dtype='object')

In [30]:
selection_in_bila = selection_in_bila[['countryname', 'language','study_language_names', 'bila_language_name_mapping', 'lang_responses', 'total_responses',
       'percent',
       'possible_alternative_bila_language_name_mappings']]

In [31]:
selection_in_bila.to_csv("~/Projects/hypocognition/data/processed/MAX_selection_in_bila.csv")

In [32]:
# Add a language name map for the the bila dataset language names
filtered_mapped =filtered.merge(
    covid_to_bila_nouns_full_lang_name_mapping,
    left_on="Language_Name",
    right_on="study_language_names",
    how="left"
)

filtered_mapped

,countryname,countryname,Language_Name,language,percent,admiration,calm,compassion,determination,moved,...,disgust,fear,frustration,loneliness,regret,sadness,code,study_language_names,bila_language_name_mapping,possible_alternative_bila_language_name_mappings
0,Australia,Australia,Simplified Chinese,ZH-S,47.883598,5.0,3.0,3.0,5.0,4.0,...,2.0,1.0,2.0,1.0,1.0,1.0,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
1,Australia,Australia,Simplified Chinese,ZH-S,47.883598,2.0,3.0,3.0,0.0,4.0,...,3.0,3.0,1.0,1.0,2.0,2.0,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
2,Australia,Australia,Simplified Chinese,ZH-S,47.883598,3.0,3.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
3,Australia,Australia,Simplified Chinese,ZH-S,47.883598,6.0,1.0,4.0,4.0,4.0,...,4.0,4.0,3.0,6.0,1.0,2.0,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
4,Australia,Australia,Simplified Chinese,ZH-S,47.883598,0.0,6.0,6.0,6.0,2.0,...,2.0,4.0,2.0,1.0,0.0,3.0,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15231,Kazakhstan,Kazakhstan,Russian,RU,95.876289,1.0,3.0,3.0,1.0,5.0,...,2.0,3.0,2.0,3.0,3.0,2.0,RU,Russian,Russian,Belarusian
15232,Kazakhstan,Kazakhstan,Russian,RU,95.876289,3.0,3.0,6.0,2.0,6.0,...,1.0,5.0,2.0,2.0,6.0,5.0,RU,Russian,Russian,Belarusian
15233,Kazakhstan,Kazakhstan,Russian,RU,95.876289,3.0,3.0,3.0,3.0,4.0,...,3.0,2.0,5.0,4.0,4.0,3.0,RU,Russian,Russian,Belarusian
15234,Kazakhstan,Kazakhstan,Russian,RU,95.876289,2.0,3.0,6.0,2.0,2.0,...,3.0,3.0,3.0,1.0,6.0,4.0,RU,Russian,Russian,Belarusian
15235,Kazakhstan,Kazakhstan,Russian,RU,95.876289,0.0,1.0,4.0,2.0,1.0,...,0.0,4.0,2.0,0.0,6.0,5.0,RU,Russian,Russian,Belarusian

In [33]:
filtered_mapped = filtered_mapped[filtered_mapped['bila_language_name_mapping'].notna()]
filtered_mapped

,countryname,countryname,Language_Name,language,percent,admiration,calm,compassion,determination,moved,...,disgust,fear,frustration,loneliness,regret,sadness,code,study_language_names,bila_language_name_mapping,possible_alternative_bila_language_name_mappings
0,Australia,Australia,Simplified Chinese,ZH-S,47.883598,5.0,3.0,3.0,5.0,4.0,...,2.0,1.0,2.0,1.0,1.0,1.0,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
1,Australia,Australia,Simplified Chinese,ZH-S,47.883598,2.0,3.0,3.0,0.0,4.0,...,3.0,3.0,1.0,1.0,2.0,2.0,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
2,Australia,Australia,Simplified Chinese,ZH-S,47.883598,3.0,3.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
3,Australia,Australia,Simplified Chinese,ZH-S,47.883598,6.0,1.0,4.0,4.0,4.0,...,4.0,4.0,3.0,6.0,1.0,2.0,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
4,Australia,Australia,Simplified Chinese,ZH-S,47.883598,0.0,6.0,6.0,6.0,2.0,...,2.0,4.0,2.0,1.0,0.0,3.0,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15231,Kazakhstan,Kazakhstan,Russian,RU,95.876289,1.0,3.0,3.0,1.0,5.0,...,2.0,3.0,2.0,3.0,3.0,2.0,RU,Russian,Russian,Belarusian
15232,Kazakhstan,Kazakhstan,Russian,RU,95.876289,3.0,3.0,6.0,2.0,6.0,...,1.0,5.0,2.0,2.0,6.0,5.0,RU,Russian,Russian,Belarusian
15233,Kazakhstan,Kazakhstan,Russian,RU,95.876289,3.0,3.0,3.0,3.0,4.0,...,3.0,2.0,5.0,4.0,4.0,3.0,RU,Russian,Russian,Belarusian
15234,Kazakhstan,Kazakhstan,Russian,RU,95.876289,2.0,3.0,6.0,2.0,2.0,...,3.0,3.0,3.0,1.0,6.0,4.0,RU,Russian,Russian,Belarusian
15235,Kazakhstan,Kazakhstan,Russian,RU,95.876289,0.0,1.0,4.0,2.0,1.0,...,0.0,4.0,2.0,0.0,6.0,5.0,RU,Russian,Russian,Belarusian

In [34]:
filtered_mapped["study_language_names"].unique()

array(['Simplified Chinese', 'Malay', 'Russian', 'Dutch', 'French',
       'Spanish (Spain)', 'Serbian', 'Afrikaans', 'Swedish', 'Arabic',
       'Traditional Chinese (Taiwan)', 'Spanish', 'Turkish', 'Ukrainian',
       'Vietnamese', 'Brazilian Portuguese', 'Bulgarian', 'Croatian',
       'Danish', 'Finnish', 'Georgian', 'German', 'Greek',
       'Traditional Chinese', 'Hungarian', 'Icelandic', 'Marathi',
       'Indonesian', 'Persian', 'Hebrew', 'Italian', 'Japanese'],
      dtype=object)

In [35]:
filtered_mapped["study_language_names"].nunique()

32

In [36]:
filtered_mapped["bila_language_name_mapping"].nunique()

28

In [37]:
filtered_mapped['countryname'].nunique()

countryname    49
countryname    49
dtype: int64

In [38]:
filtered_mapped = filtered_mapped.loc[:, ~filtered_mapped.columns.duplicated()]

In [39]:
bila_nouns_full_emotions_filtered = bila_nouns_full_emotions[bila_nouns_full_emotions['langname'].isin(covid_to_bila_nouns_full_lang_name_mapping['bila_language_name_mapping'].values)]
bila_nouns_full_emotions_filtered

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,estimate,regression_elaboration,dictsize_data,simple_elaboration,log_count
18,coo.31924067983704,fear,8.0,126.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-6.924086,1.952545,121674,0.001036,4.844187
19,coo.31924067983704,pleasure,5.0,107.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-7.086289,3.153327,121674,0.000879,4.682131
20,coo.31924067983704,regret,5.0,41.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-8.031261,2.670962,121674,0.000337,3.737670
21,coo.31924067983704,admiration,3.0,10.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-9.371276,-0.854986,121674,0.000082,2.397895
22,coo.31924067983704,anger,5.0,85.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-7.314243,0.579516,121674,0.000699,4.454347
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10417,uva.x004877953,disgust,3.0,13.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-9.940215,-4.505457,282895,0.000046,2.639057
10418,uva.x004877953,frustration,3.0,6.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-10.633387,-1.588076,282895,0.000021,1.945910
10419,uva.x004877953,loneliness,3.0,7.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-10.499852,-1.873436,282895,0.000025,2.079442
10420,uva.x004877953,relief,11.0,89.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-8.079201,3.907437,282895,0.000315,4.499810
10421,uva.x004877953,boredom,1.0,6.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-10.633387,-1.590590,282895,0.000021,1.945910

In [40]:
bila_nouns_full_emotions_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 713 entries, 18 to 10421
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      713 non-null    object
 1   word                    713 non-null    object
 2   nsenses                 713 non-null    float64
 3   count                   713 non-null    float64
 4   langname                713 non-null    object
 5   glottocode              713 non-null    object
 6   year                    713 non-null    float64
 7   title                   713 non-null    object
 8   imprint                 713 non-null    object
 9   author                  713 non-null    object
 10  area                    713 non-null    object
 11  langfamily              713 non-null    object
 12  affiliation             713 non-null    object
 13  longitude               713 non-null    float64
 14  latitude                713 non-null    float64
 15  estimate                713 non-null    float64
 16  regression_elaboration  713 non-null    float64
 17  dictsize_data           713 non-null    int64
 18  simple_elaboration      713 non-null    float64
 19  log_count               713 non-null    float64
dtypes: float64(9), int64(1), object(10)
memory usage: 117.0+ KB

In [41]:
# add the rows of the emotions words which don't appear in each dictionary
bila_emotions = bila_nouns_full_emotions_filtered['word'].unique()
full_index = pd.MultiIndex.from_product(
    [bila_nouns_full_emotions_filtered["id"].unique(), bila_emotions],
    names=["id", "word"]
)

In [42]:

bila_nouns_full_emotions_filtered_full = (
    bila_nouns_full_emotions_filtered
    .set_index(["id", "word"])
    .reindex(full_index)
    .reset_index()
)
num_cols = ["nsenses", "count", "log_count"]
bila_nouns_full_emotions_filtered_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 738 entries, 0 to 737
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      738 non-null    object
 1   word                    738 non-null    object
 2   nsenses                 713 non-null    float64
 3   count                   713 non-null    float64
 4   langname                713 non-null    object
 5   glottocode              713 non-null    object
 6   year                    713 non-null    float64
 7   title                   713 non-null    object
 8   imprint                 713 non-null    object
 9   author                  713 non-null    object
 10  area                    713 non-null    object
 11  langfamily              713 non-null    object
 12  affiliation             713 non-null    object
 13  longitude               713 non-null    float64
 14  latitude                713 non-null    float64
 15  estimate                713 non-null    float64
 16  regression_elaboration  713 non-null    float64
 17  dictsize_data           713 non-null    float64
 18  simple_elaboration      713 non-null    float64
 19  log_count               713 non-null    float64
dtypes: float64(10), object(10)
memory usage: 115.4+ KB

In [43]:

#set the number columns to 0 where NaN
bila_nouns_full_emotions_filtered_full[num_cols] = bila_nouns_full_emotions_filtered_full[num_cols].fillna(0)
meta_cols = [
    "langname", "glottocode", "year", "title", "imprint", "author",
    "area", "langfamily", "affiliation", "longitude", "latitude"
]
bila_nouns_full_emotions_filtered_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 738 entries, 0 to 737
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      738 non-null    object
 1   word                    738 non-null    object
 2   nsenses                 738 non-null    float64
 3   count                   738 non-null    float64
 4   langname                713 non-null    object
 5   glottocode              713 non-null    object
 6   year                    713 non-null    float64
 7   title                   713 non-null    object
 8   imprint                 713 non-null    object
 9   author                  713 non-null    object
 10  area                    713 non-null    object
 11  langfamily              713 non-null    object
 12  affiliation             713 non-null    object
 13  longitude               713 non-null    float64
 14  latitude                713 non-null    float64
 15  estimate                713 non-null    float64
 16  regression_elaboration  713 non-null    float64
 17  dictsize_data           713 non-null    float64
 18  simple_elaboration      713 non-null    float64
 19  log_count               738 non-null    float64
dtypes: float64(10), object(10)
memory usage: 115.4+ KB

In [44]:
# fill the those zero rows with dictionary meta -data
bila_nouns_full_emotions_filtered_full[meta_cols] = (
    bila_nouns_full_emotions_filtered_full
    .groupby("id")[meta_cols]
    .transform("first")
)

bila_nouns_full_emotions_filtered_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 738 entries, 0 to 737
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      738 non-null    object
 1   word                    738 non-null    object
 2   nsenses                 738 non-null    float64
 3   count                   738 non-null    float64
 4   langname                738 non-null    object
 5   glottocode              738 non-null    object
 6   year                    738 non-null    float64
 7   title                   738 non-null    object
 8   imprint                 738 non-null    object
 9   author                  738 non-null    object
 10  area                    738 non-null    object
 11  langfamily              738 non-null    object
 12  affiliation             738 non-null    object
 13  longitude               738 non-null    float64
 14  latitude                738 non-null    float64
 15  estimate                713 non-null    float64
 16  regression_elaboration  713 non-null    float64
 17  dictsize_data           713 non-null    float64
 18  simple_elaboration      713 non-null    float64
 19  log_count               738 non-null    float64
dtypes: float64(10), object(10)
memory usage: 115.4+ KB

In [45]:
elab_per_emotion = bila_nouns_full_emotions_filtered_full[['langname',   'glottocode','word', 'count',  'id', 'year',"simple_elaboration", "regression_elaboration",	"dictsize_data"	]]
elab_per_emotion

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data
0,Turkish,nucl1301,fear,126.0,coo.31924067983704,1991.0,0.001036,1.952545,121674.0
1,Turkish,nucl1301,pleasure,107.0,coo.31924067983704,1991.0,0.000879,3.153327,121674.0
2,Turkish,nucl1301,regret,41.0,coo.31924067983704,1991.0,0.000337,2.670962,121674.0
3,Turkish,nucl1301,admiration,10.0,coo.31924067983704,1991.0,0.000082,-0.854986,121674.0
4,Turkish,nucl1301,anger,85.0,coo.31924067983704,1991.0,0.000699,0.579516,121674.0
...,...,...,...,...,...,...,...,...,...
733,Japanese,nucl1643,disgust,13.0,uva.x004877953,1974.0,0.000046,-4.505457,282895.0
734,Japanese,nucl1643,frustration,6.0,uva.x004877953,1974.0,0.000021,-1.588076,282895.0
735,Japanese,nucl1643,loneliness,7.0,uva.x004877953,1974.0,0.000025,-1.873436,282895.0
736,Japanese,nucl1643,relief,89.0,uva.x004877953,1974.0,0.000315,3.907437,282895.0
737,Japanese,nucl1643,boredom,6.0,uva.x004877953,1974.0,0.000021,-1.590590,282895.0

In [46]:
elab_per_emotion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 738 entries, 0 to 737
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   langname                738 non-null    object
 1   glottocode              738 non-null    object
 2   word                    738 non-null    object
 3   count                   738 non-null    float64
 4   id                      738 non-null    object
 5   year                    738 non-null    float64
 6   simple_elaboration      713 non-null    float64
 7   regression_elaboration  713 non-null    float64
 8   dictsize_data           713 non-null    float64
dtypes: float64(5), object(4)
memory usage: 52.0+ KB

In [47]:
stats_by_country = (
    filtered_mapped
    .groupby(['countryname', 'bila_language_name_mapping'])[emotions]
    .agg(['mean', 'std'])
)
stats_by_country = pd.DataFrame(stats_by_country)
stats_by_country

                                                          admiration  \
                                                                mean
countryname                    bila_language_name_mapping
Australia                      Mandarin Chinese             3.413408
Brazil                         Brazilian Portuguese         3.540984
Bulgaria                       Bulgarian                    2.498141
Canada                         Mandarin Chinese             3.076923
Chile                          Spanish                      2.867521
China                          Mandarin Chinese             4.365940
Colombia                       Spanish                      3.409836
Croatia                        Serbian-Croatian-Bosnian     2.552581
Curacao                        Dutch                        3.627778
Denmark                        Danish                       2.668919
Egypt                          Arabic                       2.547472
Finland                        Finnish                      2.738462
France                         French                       3.357977
Georgia                        Georgian                     2.523605
Germany                        German                       2.804124
Ghana                          Mandarin Chinese             6.000000
Greece                         Greek                        2.328889
Hong Kong (S.A.R)              Mandarin Chinese             2.669065
Hungary                        Hungarian                    2.679688
Iceland                        Icelandic                    3.469741
India                          Marathi                      3.500000
Indonesia                      Indonesian                   3.201863
Iran                           Persian                      2.347826
Ireland                        Serbian-Croatian-Bosnian     0.666667
Israel                         Hebrew                       1.569536
Italy                          Italian                      2.966981
Japan                          Japanese                     2.602176
Jordan                         Arabic                       3.108225
Kazakhstan                     Russian                      2.438849
Malaysia                       Standard Malay               3.793548
Mongolia                       Russian                      2.461538
Netherlands                    Dutch                        3.325048
New Zealand                    Mandarin Chinese             3.215686
Pakistan                       French                       2.000000
Peru                           Spanish                      3.706161
Russia                         Russian                      2.553043
Serbia                         Serbian-Croatian-Bosnian     2.712644
Singapore                      Mandarin Chinese             3.250000
South Africa                   Afrikaans                    2.946429
Spain                          Spanish                      4.021390
Sweden                         Swedish                      3.300000
Syria                          Arabic                       1.849372
Taiwan                         Mandarin Chinese             3.993307
Trinidad and Tobago            Spanish                      3.000000
Turkey                         Turkish                      2.027888
Ukraine                        Ukrainian                    2.856489
United Kingdom (UK)            Mandarin Chinese             4.088235
United States of America (USA) Mandarin Chinese             3.044444
Vietnam                        Vietnamese                   4.219178

                                                                         calm  \
                                                                std      mean
countryname                    bila_language_name_mapping
Australia                      Mandarin Chinese            1.892338  3.849162
Brazil                         Brazilian Portuguese        1.745047  3.421569
Bulgaria                       Bulgarian                   1.980548  3.334572
Canada                         Mandarin Chinese            2.018377  3.576923
Chile                          Spanish                     1.901080  2.899358
China                          Mandarin Chinese            1.736698  3.914807
Colombia                       Spanish                     1.974022  3.418033
Croatia                        Serbian-Croatian-Bosnian    1.680006  3.332061
Curacao                        Dutch                       1.743401  3.961111
Denmark                        Danish                      1.513605  3.445946
Egypt                          Arabic                      1.886575  3.622222
Finland                        Finnish                     1.547467  3.726923
France                         French                      1.801764  3.746094
Georgia                        Georgian                    1.866354  3.248927
Germany                        German                      1.800225  3.628866
Ghana                          Mandarin Chinese                 NaN  6.000000
Greece                         Greek                       1.887059  3.337778
Hong Kong (S.A.R)              Mandarin Chinese            1.770894  3.064748
Hungary                        Hungarian                   1.925815  3.265625
Iceland                        Icelandic                   1.867297  3.299712
India                          Marathi                     1.768410  3.982143
Indonesia                      Indonesian                  1.577327  3.834365
Iran                           Persian                     1.745782  2.774194
Ireland                        Serbian-Croatian-Bosnian    1.154701  3.000000
Israel                         Hebrew                      1.718565  3.240000
Italy                          Italian                     1.900316  3.327059
Japan                          Japanese                    1.523357  3.559441
Jordan                         Arabic                      1.965235  3.952586
Kazakhstan                     Russian                     1.958468  3.469534
Malaysia                       Standard Malay              1.548761  4.000000
Mongolia                       Russian                     2.221688  3.615385
Netherlands                    Dutch                       1.646279  3.671756
New Zealand                    Mandarin Chinese            1.859562  4.019608
Pakistan                       French                      1.414214  2.500000
Peru                           Spanish                     1.884501  3.693023
Russia                         Russian                     1.774840  3.349565
Serbia                         Serbian-Croatian-Bosnian    1.846614  3.517143
Singapore                      Mandarin Chinese            1.281740  3.375000
South Africa                   Afrikaans                   1.712904  3.642857
Spain                          Spanish                     1.671897  3.941176
Sweden                         Swedish                     1.774224  3.580000
Syria                          Arabic                      1.996402  3.377593
Taiwan                         Mandarin Chinese            1.660520  3.666667
Trinidad and Tobago            Spanish                          NaN  5.000000
Turkey                         Turkish                     1.760460  3.611111
Ukraine                        Ukrainian                   1.644428  3.203957
United Kingdom (UK)            Mandarin Chinese            1.781515  3.970588
United States of America (USA) Mandarin Chinese            1.594815  3.133333
Vietnam                        Vietnamese                  1.746841  4.263699

                                                                     \
                                                                std
countryname                    bila_language_name_mapping
Australia                      Mandarin Chinese            1.609186
Brazil                         Brazilian Portuguese        1.502585
Bulgaria                       Bulgarian                   1.712431
Canada                         Mandarin Chinese            1.447013
Chile                          Spanish                     1.546330
China                          Mandarin Chinese            1.683731
Colombia                       Spanish                     1.419115
Croatia                        Serbian-Croatian-Bosnian    1.485572
Curacao                        Dutch                       1.607816
Denmark                        Danish                      1.531012
Egypt                          Arabic                      1.728264
Finland                        Finnish                     1.380520
France                         French                      1.587322
Georgia                        Georgian                    1.698836
Germany                        German                      1.620895
Ghana                          Mandarin Chinese                 NaN
Greece                         Greek                       1.538681
Hong Kong (S.A.R)              Mandarin Chinese            1.455667
Hungary                        Hungarian                   1.730848
Iceland                        Icelandic                   1.757585
India                          Marathi                     1.700172
Indonesia                      Indonesian                  1.327863
Iran                           Persian                     1.831431
Ireland                        Serbian-Croatian-Bosnian    1.000000
Israel                         Hebrew                      1.407935
Italy                          Italian                     1.516839
Japan                          Japanese                    1.254913
Jordan                         Arabic                      1.807247
Kazakhstan                     Russian                     1.641953
Malaysia                       Standard Malay              1.232672
Mongolia                       Russian                     1.804553
Netherlands                    Dutch                       1.413904
New Zealand                    Mandarin Chinese            1.807467
Pakistan                       French                      2.121320
Peru                           Spanish                     1.503484
Russia                         Russian                     1.524902
Serbia                         Serbian-Croatian-Bosnian    1.580139
Singapore                      Mandarin Chinese            1.187735
South Africa                   Afrikaans                   1.341353
Spain                          Spanish                     1.308272
Sweden                         Swedish                     1.482936
Syria                          Arabic                      2.045971
Taiwan                         Mandarin Chinese            1.549020
Trinidad and Tobago            Spanish                          NaN
Turkey                         Turkish                     1.439191
Ukraine                        Ukrainian                   1.565963
United Kingdom (UK)            Mandarin Chinese            1.336783
United States of America (USA) Mandarin Chinese            1.659682
Vietnam                        Vietnamese                  1.350442

                                                          compassion  \
                                                                mean
countryname                    bila_language_name_mapping
Australia                      Mandarin Chinese             4.055556
Brazil                         Brazilian Portuguese         4.633987
Bulgaria                       Bulgarian                    4.313433
Canada                         Mandarin Chinese             4.153846
Chile                          Spanish                      3.893390
China                          Mandarin Chinese             4.240976
Colombia                       Spanish                      4.024590
Croatia                        Serbian-Croatian-Bosnian     2.904398
Curacao                        Dutch                        4.777778
Denmark                        Danish                       4.067568
Egypt                          Arabic                       4.173006
Finland                        Finnish                      4.042471
France                         French                       3.809339
Georgia                        Georgian                     4.444444
Germany                        German                       4.347079
Ghana                          Mandarin Chinese             6.000000
Greece                         Greek                        3.843049
Hong Kong (S.A.R)              Mandarin Chinese             3.323741
Hungary                        Hungarian                    4.507812
Iceland                        Icelandic                    4.388406
India                          Marathi                      3.946429
Indonesia                      Indonesian                   4.547287
Iran                           Persian                      3.770053
Ireland                        Serbian-Croatian-Bosnian     3.000000
Israel                         Hebrew                       4.013245
Italy                          Italian                      3.613208
Japan                          Japanese                     3.533385
Jordan                         Arabic                       4.359307
Kazakhstan                     Russian                      3.602151
Malaysia                       Standard Malay               4.432258
Mongolia                       Russian                      2.692308
Netherlands                    Dutch                        4.160305
New Zealand                    Mandarin Chinese             3.693069
Pakistan                       French                       3.500000
Peru                           Spanish                      4.483721
Russia                         Russian                      3.557292
Serbia                         Serbian-Croatian-Bosnian     4.312321
Singapore                      Mandarin Chinese             3.625000
South Africa                   Afrikaans                    4.196429
Spain                          Spanish                      4.080645
Sweden                         Swedish                      4.537500
Syria                          Arabic                       3.878543
Taiwan                         Mandarin Chinese             3.722520
Trinidad and Tobago            Spanish                      4.000000
Turkey                         Turkish                      3.956349
Ukraine                        Ukrainian                    3.576220
United Kingdom (UK)            Mandarin Chinese             4.529412
United States of America (USA) Mandarin Chinese             4.222222
Vietnam                        Vietnamese                   3.872852

                                                                     \
                                                                std
countryname                    bila_language_name_mapping
Australia                      Mandarin Chinese            1.780472
Brazil                         Brazilian Portuguese        1.319471
Bulgaria                       Bulgarian                   1.590788
Canada                         Mandarin Chinese            1.689788
Chile                          Spanish                     1.693798
China                          Mandarin Chinese            1.701800
Colombia                       Spanish                     1.678563
Croatia                        Serbian-Croatian-Bosnian    1.650043
Curacao                        Dutch                       1.174951
Denmark                        Danish                      1.450602
Egypt                          Arabic                      1.710858
Finland                        Finnish                     1.350471
France                         French                      1.648458
Georgia                        Georgian                    1.507887
Germany                        German                      1.283778
Ghana                          Mandarin Chinese                 NaN
Greece                         Greek                       1.662391
Hong Kong (S.A.R)              Mandarin Chinese            1.616114
Hungary                        Hungarian                   1.343079
Iceland                        Icelandic                   1.601193
India                          Marathi                     1.633954
Indonesia                      Indonesian                  1.238492
Iran                           Persian                     1.705639
Ireland                        Serbian-Croatian-Bosnian    2.000000
Israel                         Hebrew                      1.316494
Italy                          Italian                     1.729022
Japan                          Japanese                    1.375941
Jordan                         Arabic                      1.718414
Kazakhstan                     Russian                     1.755606
Malaysia                       Standard Malay              1.304435
Mongolia                       Russian                     2.358835
Netherlands                    Dutch                       1.402357
New Zealand                    Mandarin Chinese            1.579510
Pakistan                       French                      2.121320
Peru                           Spanish                     1.500301
Russia                         Russian                     1.654564
Serbia                         Serbian-Croatian-Bosnian    1.465069
Singapore                      Mandarin Chinese            1.685018
South Africa                   Afrikaans                   1.505780
Spain                          Spanish                     1.610423
Sweden                         Swedish                     1.289477
Syria                          Arabic                      1.921589
Taiwan                         Mandarin Chinese            1.628423
Trinidad and Tobago            Spanish                          NaN
Turkey                         Turkish                     1.627111
Ukraine                        Ukrainian                   1.516419
United Kingdom (UK)            Mandarin Chinese            1.461326
United States of America (USA) Mandarin Chinese            1.730592
Vietnam                        Vietnamese                  1.779476

                                                          determination  \
                                                                   mean
countryname                    bila_language_name_mapping
Australia                      Mandarin Chinese                3.887640
Brazil                         Brazilian Portuguese            3.725490
Bulgaria                       Bulgarian                       3.565056
Canada                         Mandarin Chinese                3.615385
Chile                          Spanish                         3.370450
China                          Mandarin Chinese                4.165992
Colombia                       Spanish                         3.818182
Croatia                        Serbian-Croatian-Bosnian        3.508604
Curacao                        Dutch                           4.000000
Denmark                        Danish                          3.351351
Egypt                          Arabic                          3.161090
Finland                        Finnish                         3.532819
France                         French                          3.727626
Georgia                        Georgian                        3.692308
Germany                        German                          3.468966
Ghana                          Mandarin Chinese                6.000000
Greece                         Greek                           3.444934
Hong Kong (S.A.R)              Mandarin Chinese                3.366906
Hungary                        Hungarian                       3.652344
Iceland                        Icelandic                       3.589595
India                          Marathi                         3.660714

In [48]:
stats_by_country.columns = [
    f"{emotion}_{stat}" for emotion, stat in stats_by_country.columns
]
stats_by_country = stats_by_country.reset_index()
stats_by_country

,countryname,bila_language_name_mapping,admiration_mean,admiration_std,calm_mean,calm_std,compassion_mean,compassion_std,determination_mean,determination_std,...,fear_mean,fear_std,frustration_mean,frustration_std,loneliness_mean,loneliness_std,regret_mean,regret_std,sadness_mean,sadness_std
0,Australia,Mandarin Chinese,3.413408,1.892338,3.849162,1.609186,4.055556,1.780472,3.887640,1.604642,...,1.878453,1.631846,1.972067,1.730202,1.900000,1.818895,1.309392,1.473232,1.955556,1.680723
1,Brazil,Brazilian Portuguese,3.540984,1.745047,3.421569,1.502585,4.633987,1.319471,3.725490,1.593986,...,3.603279,1.757500,3.437908,1.941201,2.518033,2.069635,1.934426,1.881951,3.321311,1.833991
2,Bulgaria,Bulgarian,2.498141,1.980548,3.334572,1.712431,4.313433,1.590788,3.565056,1.684113,...,2.561338,1.954938,3.029740,2.089207,2.334572,2.154385,2.929104,2.009018,3.252788,1.930519
3,Canada,Mandarin Chinese,3.076923,2.018377,3.576923,1.447013,4.153846,1.689788,3.615385,1.328967,...,2.500000,1.881489,2.769231,1.795721,2.807692,1.720912,1.884615,1.451259,3.192308,1.720912
4,Chile,Spanish,2.867521,1.901080,2.899358,1.546330,3.893390,1.693798,3.370450,1.700109,...,3.528785,1.836746,4.119914,1.731608,2.869658,2.067930,2.352564,1.969156,3.799145,1.745670
5,China,Mandarin Chinese,4.365940,1.736698,3.914807,1.683731,4.240976,1.701800,4.165992,1.693406,...,1.809500,1.726083,1.815642,1.763461,1.812437,1.826492,1.477009,1.701083,2.256709,1.848471
6,Colombia,Spanish,3.409836,1.974022,3.418033,1.419115,4.024590,1.678563,3.818182,1.653280,...,3.024590,1.943258,3.409836,1.897167,2.578512,2.170837,1.721311,1.601973,3.459016,1.916210
7,Croatia,Serbian-Croatian-Bosnian,2.552581,1.680006,3.332061,1.485572,2.904398,1.650043,3.508604,1.438863,...,2.739962,1.825025,3.430210,1.808983,2.692748,1.952364,2.795802,1.713266,2.990458,1.759406
8,Curacao,Dutch,3.627778,1.743401,3.961111,1.607816,4.777778,1.174951,4.000000,1.549914,...,2.477778,1.933115,3.005556,1.877527,1.894444,1.853570,1.350000,1.645970,2.622222,1.906049
9,Denmark,Danish,2.668919,1.513605,3.445946,1.531012,4.067568,1.450602,3.351351,1.483996,...,1.824324,1.610832,3.148649,1.852980,2.277027,2.026427,1.479730,1.655622,1.601351,1.732993
10,Egypt,Arabic,2.547472,1.886575,3.622222,1.728264,4.173006,1.710858,3.161090,1.728845,...,3.556790,1.953694,3.419434,2.007981,3.686275,2.140949,2.710591,2.129295,4.047970,1.806232
11,Finland,Finnish,2.738462,1.547467,3.726923,1.380520,4.042471,1.350471,3.532819,1.327221,...,2.509653,1.600298,3.846154,1.699246,2.776062,1.927978,1.534615,1.570343,2.953668,1.672212
12,France,French,3.357977,1.801764,3.746094,1.587322,3.809339,1.648458,3.727626,1.582292,...,2.155642,1.796018,3.156250,1.829765,1.961089,1.932060,1.582031,1.708430,2.503906,1.874489
13,Georgia,Georgian,2.523605,1.866354,3.248927,1.698836,4.444444,1.507887,3.692308,1.815345,...,2.497854,1.864192,2.965665,1.920539,2.439655,2.131149,2.497854,1.916634,3.277778,1.955453
14,Germany,German,2.804124,1.800225,3.628866,1.620895,4.347079,1.283778,3.468966,1.464955,...,2.323024,1.757384,3.186207,1.856388,2.178694,1.887078,2.037931,1.705459,2.656357,1.749518
15,Ghana,Mandarin Chinese,6.000000,NaN,6.000000,NaN,6.000000,NaN,6.000000,NaN,...,0.000000,NaN,0.000000,NaN,3.000000,NaN,0.000000,NaN,1.000000,NaN
16,Greece,Greek,2.328889,1.887059,3.337778,1.538681,3.843049,1.662391,3.444934,1.682894,...,2.637168,1.939356,3.508850,1.663306,2.537445,2.015901,1.778761,1.836589,3.251101,1.886945
17,Hong Kong (S.A.R),Mandarin Chinese,2.669065,1.770894,3.064748,1.455667,3.323741,1.616114,3.366906,1.489791,...,2.633094,1.765794,2.431655,1.813997,2.345324,1.909975,1.956835,1.785085,2.618705,1.750344
18,Hungary,Hungarian,2.679688,1.925815,3.265625,1.730848,4.507812,1.343079,3.652344,1.698972,...,2.511719,1.823555,3.125000,1.919967,1.863281,2.000211,1.906250,1.723824,2.703125,1.869715
19,Iceland,Icelandic,3.469741,1.867297,3.299712,1.757585,4.388406,1.601193,3.589595,1.611303,...,2.227666,1.861548,2.129683,1.890931,2.465318,2.160303,1.527378,1.776931,2.376437,1.964884
20,India,Marathi,3.500000,1.768410,3.982143,1.700172,3.946429,1.633954,3.660714,1.880781,...,2.053571,1.891797,1.839286,1.961231,1.857143,1.833314,1.254545,1.723672,2.381818,2.022932
21,Indonesia,Indonesian,3.201863,1.577327,3.834365,1.327863,4.547287,1.238492,3.827372,1.301711,...,3.141085,1.749073,2.213292,1.869821,2.545595,1.978368,2.066563,1.647238,2.933333,1.730317
22,Iran,Persian,2.347826,1.745782,2.774194,1.831431,3.770053,1.705639,3.290323,1.601220,...,2.972973,1.929272,3.005405,1.918155,2.940860,2.032638,2.659459,1.999383,3.556150,1.881089
23,Ireland,Serbian-Croatian-Bosnian,0.666667,1.154701,3.000000,1.000000,3.000000,2.000000,3.666667,2.516611,...,4.666667,1.154701,5.333333,1.154701,5.666667,0.577350,4.666667,1.527525,4.333333,2.886751
24,Israel,Hebrew,1.569536,1.718565,3.240000,1.407935,4.013245,1.316494,3.403974,1.493001,...,2.092715,1.733401,3.125828,1.690383,2.026490,1.754792,1.662252,1.616116,2.536424,1.765502
25,Italy,Italian,2.966981,1.900316,3.327059,1.516839,3.613208,1.729022,3.716981,1.558958,...,2.666667,1.799782,3.320000,1.944077,2.535377,1.968709,2.411765,1.928523,3.343529,1.723755
26,Japan,Japanese,2.602176,1.523357,3.559441,1.254913,3.533385,1.375941,2.964258,1.522347,...,2.630148,1.743227,3.111888,1.729330,2.007764,1.817621,1.956522,1.623824,2.601399,1.710028
27,Jordan,Arabic,3.108225,1.965235,3.952586,1.807247,4.359307,1.718414,3.754386,1.846828,...,2.711207,2.012570,3.116379,2.076312,3.304348,2.156230,2.515152,2.218202,3.700000,1.917855
28,Kazakhstan,Russian,2.438849,1.958468,3.469534,1.641953,3.602151,1.755606,3.283154,1.783851,...,2.276978,1.979746,2.602151,2.078356,2.039568,2.156817,2.773381,2.002456,3.028674,1.913386
29,Malaysia,Standard Malay,3.793548,1.548761,4.000000,1.232672,4.432258,1.304435,3.845161,1.372939,...,2.503226,1.785127,2.412903,1.689490,2.296774,2.064462,1.980645,1.672819,2.761290,1.643894
30,Mongolia,Russian,2.461538,2.221688,3.615385,1.804553,2.692308,2.358835,3.384615,2.103111,...,2.615385,2.142369,2.230769,1.690850,0.692308,1.182132,2.923077,2.289889,1.615385,1.804553
31,Netherlands,Dutch,3.325048,1.646279,3.671756,1.413904,4.160305,1.402357,3.553435,1.404380,...,2.408397,1.663121,3.574427,1.658224,2.335878,1.853572,1.402672,1.482876,2.869981,1.738211
32,New Zealand,Mandarin Chinese,3.215686,1.859562,4.019608,1.807467,3.693069,1.579510,3.485149,1.797854,...,1.686275,1.740493,1.831683,1.887164,1.852941,2.065257,1.150000,1.578741,1.500000,1.602906
33,Pakistan,French,2.000000,1.414214,2.500000,2.121320,3.500000,2.121320,4.000000,0.000000,...,3.000000,1.414214,4.500000,2.121320,4.500000,0.707107,5.000000,0.000000,4.500000,0.707107
34,Peru,Spanish,3.706161,1.884501,3.693023,1.503484,4.483721,1.500301,3.939252,1.457070,...,2.868545,1.827875,3.181395,1.988196,1.604651,1.720404,1.469767,1.617015,3.065116,1.768214
35,Russia,Russian,2.553043,1.774840,3.349565,1.524902,3.557292,1.654564,3.057292,1.579824,...,2.394415,1.771404,2.713542,1.983293,2.157986,2.033897,2.841739,1.816781,3.288194,1.748619
36,Serbia,Serbian-Croatian-Bosnian,2.712644,1.846614,3.517143,1.580139,4.312321,1.465069,3.794286,1.579950,...,2.424501,1.785457,2.742857,1.952779,2.194286,2.000565,2.965616,1.932472,2.985755,1.818106
37,Singapore,Mandarin Chinese,3.250000,1.281740,3.375000,1.187735,3.625000,1.685018,2.500000,1.511858,...,1.250000,0.886405,2.625000,0.916125,1.375000,1.505941,1.500000,1.309307,1.500000,1.195229
38,South Africa,Afrikaans,2.946429,1.712904,3.642857,1.341353,4.196429,1.505780,3.696429,1.570214,...,2.883929,1.911301,3.991071,1.579688,2.276786,1.996437,2.098214,1.888609,3.160714,1.872290
39,Spain,Spanish,4.021390,1.671897,3.941176,1.308272,4.080645,1.610423,3.914439,1.365140,...,2.588235,1.740248,2.967914,1.759471,1.994652,1.836012,1.315508,1.545693,3.149733,1.713023
40,Sweden,Swedish,3.300000,1.774224,3.580000,1.482936,4.537500,1.289477,3.675000,1.374445,...,2.315000,1.693501,3.170000,1.835626,2.140000,1.990050,1.355890,1.523240,2.680000,1.773546
41,Syria,Arabic,1.849372,1.996402,3.377593,2.045971,3.878543,1.921589,2.888889,2.168520,...,2.122449,2.012590,2.275720,2.142184,2.325103,2.281181,1.636364,1.955946,2.799180,2.200972
42,Taiwan,Mandarin Chinese,3.993307,1.660520,3.666667,1.549020,3.722520,1.628423,3.695710,1.540472,...,1.990617,1.625689,1.842035,1.638740,1.605087,1.640841,1.215818,1.466518,1.962416,1.652201
43,Trinidad and Tobago,Spanish,3.000000,NaN,5.000000,NaN,4.000000,NaN,4.000000,NaN,...,1.000000,NaN,4.000000,NaN,1.000000,NaN,3.000000,NaN,3.000000,NaN
44,Turkey,Turkish,2.027888,1.760460,3.611111,1.439191,3.956349,1.627111,3.804781,1.561325,...,2.948617,1.892269,2.881423,1.976491,2.494071,2.042447,1.768000,1.788567,3.575397,1.681357
45,Ukraine,Ukrainian,2.856489,1.644428,3.203957,1.565963,3.576220,1.516419,3.260274,1.528436,...,2.393293,1.827914,2.936073,1.930703,2.181402,1.950304,2.705793,1.814369,3.169466,1.849121
46,United Kingdom (UK),Mandarin Chinese,4.088235,1.781515,3.970588,1.336783,4.529412,1.461326,3.147059,1.653872,...,2.264706,1.675290,3.088235,1.975113,2.382353,2.296436,2.676471,1.934074,3.088235,1.621216
47,United States of America (USA),Mandarin Chinese,3.044444,1.594815,3.133333,1.659682,4.222222,1.730592,3.377778,1.735837,...,2.733333,1.801515,2.933333,2.104109,2.488889,2.095691,1.666667,2.078024,2.666667,1.870829
48,Vietnam,Vietnamese,4.219178,1.746841,4.263699,1.350442,3.872852,1.779476,4.096220,1.507803,...,1.688356,1.687472,2.441781,1.901356,1.859589,1.964674,1.534247,1.709743,2.047945,1.841978

In [49]:
stats_long = (
    stats_by_country
    .set_index(['countryname', 'bila_language_name_mapping'])
    .filter(regex='_(mean|std)$')
    .stack()
    .reset_index()
)

stats_long[['word', 'stat']] = stats_long['level_2'].str.rsplit('_', n=1, expand=True)
stats_long = stats_long.rename(columns={0: 'value'}).drop(columns='level_2')

stats_long = (
    stats_long
    .pivot_table(
        index=['countryname', 'bila_language_name_mapping', 'word'],
        columns='stat',
        values='value'
    )
    .reset_index()
)

In [50]:

merged = elab_per_emotion.merge(
    stats_long,
    left_on=['langname', 'word'],
    right_on=['bila_language_name_mapping', 'word'],
    how='left'
)

merged

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,mean,std
0,Turkish,nucl1301,fear,126.0,coo.31924067983704,1991.0,0.001036,1.952545,121674.0,Turkey,Turkish,2.948617,1.892269
1,Turkish,nucl1301,pleasure,107.0,coo.31924067983704,1991.0,0.000879,3.153327,121674.0,Turkey,Turkish,3.083665,1.643463
2,Turkish,nucl1301,regret,41.0,coo.31924067983704,1991.0,0.000337,2.670962,121674.0,Turkey,Turkish,1.768000,1.788567
3,Turkish,nucl1301,admiration,10.0,coo.31924067983704,1991.0,0.000082,-0.854986,121674.0,Turkey,Turkish,2.027888,1.760460
4,Turkish,nucl1301,anger,85.0,coo.31924067983704,1991.0,0.000699,0.579516,121674.0,Turkey,Turkish,3.460000,1.871473
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111,Japanese,nucl1643,disgust,13.0,uva.x004877953,1974.0,0.000046,-4.505457,282895.0,Japan,Japanese,2.854701,1.747655
1112,Japanese,nucl1643,frustration,6.0,uva.x004877953,1974.0,0.000021,-1.588076,282895.0,Japan,Japanese,3.111888,1.729330
1113,Japanese,nucl1643,loneliness,7.0,uva.x004877953,1974.0,0.000025,-1.873436,282895.0,Japan,Japanese,2.007764,1.817621
1114,Japanese,nucl1643,relief,89.0,uva.x004877953,1974.0,0.000315,3.907437,282895.0,Japan,Japanese,2.403263,1.417428
1115,Japanese,nucl1643,boredom,6.0,uva.x004877953,1974.0,0.000021,-1.590590,282895.0,Japan,Japanese,3.180901,1.939018

In [51]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1116 entries, 0 to 1115
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   langname                    1116 non-null   object
 1   glottocode                  1116 non-null   object
 2   word                        1116 non-null   object
 3   count                       1116 non-null   float64
 4   id                          1116 non-null   object
 5   year                        1116 non-null   float64
 6   simple_elaboration          1091 non-null   float64
 7   regression_elaboration      1091 non-null   float64
 8   dictsize_data               1091 non-null   float64
 9   countryname                 882 non-null    object
 10  bila_language_name_mapping  882 non-null    object
 11  mean                        882 non-null    float64
 12  std                         845 non-null    float64
dtypes: float64(7), object(6)
memory usage: 113.5+ KB

In [52]:
# add the dictionary_count_mean column
merged = merged.merge(
    dictionary_means,
    left_on='id',
    right_on='id',
    how='left'
)
merged

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,mean,std,dictionary_count_mean
0,Turkish,nucl1301,fear,126.0,coo.31924067983704,1991.0,0.001036,1.952545,121674.0,Turkey,Turkish,2.948617,1.892269,14.502265
1,Turkish,nucl1301,pleasure,107.0,coo.31924067983704,1991.0,0.000879,3.153327,121674.0,Turkey,Turkish,3.083665,1.643463,14.502265
2,Turkish,nucl1301,regret,41.0,coo.31924067983704,1991.0,0.000337,2.670962,121674.0,Turkey,Turkish,1.768000,1.788567,14.502265
3,Turkish,nucl1301,admiration,10.0,coo.31924067983704,1991.0,0.000082,-0.854986,121674.0,Turkey,Turkish,2.027888,1.760460,14.502265
4,Turkish,nucl1301,anger,85.0,coo.31924067983704,1991.0,0.000699,0.579516,121674.0,Turkey,Turkish,3.460000,1.871473,14.502265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111,Japanese,nucl1643,disgust,13.0,uva.x004877953,1974.0,0.000046,-4.505457,282895.0,Japan,Japanese,2.854701,1.747655,33.718117
1112,Japanese,nucl1643,frustration,6.0,uva.x004877953,1974.0,0.000021,-1.588076,282895.0,Japan,Japanese,3.111888,1.729330,33.718117
1113,Japanese,nucl1643,loneliness,7.0,uva.x004877953,1974.0,0.000025,-1.873436,282895.0,Japan,Japanese,2.007764,1.817621,33.718117
1114,Japanese,nucl1643,relief,89.0,uva.x004877953,1974.0,0.000315,3.907437,282895.0,Japan,Japanese,2.403263,1.417428,33.718117
1115,Japanese,nucl1643,boredom,6.0,uva.x004877953,1974.0,0.000021,-1.590590,282895.0,Japan,Japanese,3.180901,1.939018,33.718117

In [53]:
merged = merged[merged['countryname'].notna()]

In [54]:
merged.columns

Index(['langname', 'glottocode', 'word', 'count', 'id', 'year',
       'simple_elaboration', 'regression_elaboration', 'dictsize_data',
       'countryname', 'bila_language_name_mapping', 'mean', 'std',
       'dictionary_count_mean'],
      dtype='object')

In [55]:
# clarify the meaning of mean
merged = merged.rename(columns={'mean': "response_mean"})
# Clarify what std we're talking about
merged = merged.rename(columns={'std': "response_std"})
# drop a bunch of columns

merged = merged[['langname', 'glottocode', 'word', 'count', 'id', 'year',
       'simple_elaboration', 'regression_elaboration', 'dictsize_data',
       'countryname', 'bila_language_name_mapping', 'response_mean',
       'response_std', 'dictionary_count_mean' ]]
merged = merged.sort_values(by=["langname", 'word'])
merged

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,response_mean,response_std,dictionary_count_mean
417,Afrikaans,afri1274,admiration,6.0,mdp.39015054154474,1999.0,0.000028,-3.291632,212992.0,South Africa,Afrikaans,2.946429,1.712904,25.386412
418,Afrikaans,afri1274,anger,55.0,mdp.39015054154474,1999.0,0.000258,-6.741147,212992.0,South Africa,Afrikaans,2.785714,1.803043,25.386412
421,Afrikaans,afri1274,anxiety,30.0,mdp.39015054154474,1999.0,0.000141,-2.655449,212992.0,South Africa,Afrikaans,3.535714,1.765171,25.386412
431,Afrikaans,afri1274,boredom,5.0,mdp.39015054154474,1999.0,0.000023,-1.176312,212992.0,South Africa,Afrikaans,2.241071,1.889971,25.386412
419,Afrikaans,afri1274,compassion,15.0,mdp.39015054154474,1999.0,0.000070,-2.918472,212992.0,South Africa,Afrikaans,4.196429,1.505780,25.386412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,Vietnamese,viet1252,love,308.0,uc1.31210024487306,2003.0,0.001143,-1.138291,269366.0,Vietnam,Vietnamese,4.786942,1.311475,32.105602
595,Vietnamese,viet1252,pleasure,216.0,uc1.31210024487306,2003.0,0.000802,3.511485,269366.0,Vietnam,Vietnamese,2.832192,1.885719,32.105602
596,Vietnamese,viet1252,regret,59.0,uc1.31210024487306,2003.0,0.000219,0.052866,269366.0,Vietnam,Vietnamese,1.534247,1.709743,32.105602
610,Vietnamese,viet1252,relief,74.0,uc1.31210024487306,2003.0,0.000275,2.404758,269366.0,Vietnam,Vietnamese,3.199313,1.720505,32.105602
606,Vietnamese,viet1252,sadness,51.0,uc1.31210024487306,2003.0,0.000189,4.028092,269366.0,Vietnam,Vietnamese,2.047945,1.841978,32.105602

In [56]:
merged = merged.reset_index(drop=True)
merged

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,response_mean,response_std,dictionary_count_mean
0,Afrikaans,afri1274,admiration,6.0,mdp.39015054154474,1999.0,0.000028,-3.291632,212992.0,South Africa,Afrikaans,2.946429,1.712904,25.386412
1,Afrikaans,afri1274,anger,55.0,mdp.39015054154474,1999.0,0.000258,-6.741147,212992.0,South Africa,Afrikaans,2.785714,1.803043,25.386412
2,Afrikaans,afri1274,anxiety,30.0,mdp.39015054154474,1999.0,0.000141,-2.655449,212992.0,South Africa,Afrikaans,3.535714,1.765171,25.386412
3,Afrikaans,afri1274,boredom,5.0,mdp.39015054154474,1999.0,0.000023,-1.176312,212992.0,South Africa,Afrikaans,2.241071,1.889971,25.386412
4,Afrikaans,afri1274,compassion,15.0,mdp.39015054154474,1999.0,0.000070,-2.918472,212992.0,South Africa,Afrikaans,4.196429,1.505780,25.386412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,Vietnamese,viet1252,love,308.0,uc1.31210024487306,2003.0,0.001143,-1.138291,269366.0,Vietnam,Vietnamese,4.786942,1.311475,32.105602
878,Vietnamese,viet1252,pleasure,216.0,uc1.31210024487306,2003.0,0.000802,3.511485,269366.0,Vietnam,Vietnamese,2.832192,1.885719,32.105602
879,Vietnamese,viet1252,regret,59.0,uc1.31210024487306,2003.0,0.000219,0.052866,269366.0,Vietnam,Vietnamese,1.534247,1.709743,32.105602
880,Vietnamese,viet1252,relief,74.0,uc1.31210024487306,2003.0,0.000275,2.404758,269366.0,Vietnam,Vietnamese,3.199313,1.720505,32.105602
881,Vietnamese,viet1252,sadness,51.0,uc1.31210024487306,2003.0,0.000189,4.028092,269366.0,Vietnam,Vietnamese,2.047945,1.841978,32.105602

In [57]:
merged[merged['countryname']=="China"]

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,response_mean,response_std,dictionary_count_mean
380,Mandarin Chinese,mand1415,admiration,24.0,uc1.l0088545033,2004.0,0.000236,3.652824,101618.0,China,Mandarin Chinese,4.365940,1.736698,12.1118
390,Mandarin Chinese,mand1415,anger,59.0,uc1.l0088545033,2004.0,0.000581,-0.995820,101618.0,China,Mandarin Chinese,1.956434,1.812030,12.1118
400,Mandarin Chinese,mand1415,anxiety,33.0,uc1.l0088545033,2004.0,0.000325,1.855676,101618.0,China,Mandarin Chinese,2.632892,1.879226,12.1118
410,Mandarin Chinese,mand1415,boredom,5.0,uc1.l0088545033,2004.0,0.000049,0.545344,101618.0,China,Mandarin Chinese,2.329782,1.948270,12.1118
420,Mandarin Chinese,mand1415,compassion,9.0,uc1.l0088545033,2004.0,0.000089,-1.569685,101618.0,China,Mandarin Chinese,4.240976,1.701800,12.1118
430,Mandarin Chinese,mand1415,confusion,19.0,uc1.l0088545033,2004.0,0.000187,-2.766752,101618.0,China,Mandarin Chinese,2.270421,1.809292,12.1118
440,Mandarin Chinese,mand1415,determination,8.0,uc1.l0088545033,2004.0,0.000079,-1.131749,101618.0,China,Mandarin Chinese,4.165992,1.693406,12.1118
450,Mandarin Chinese,mand1415,disgust,3.0,uc1.l0088545033,2004.0,0.000030,-2.957027,101618.0,China,Mandarin Chinese,1.745197,1.751591,12.1118
460,Mandarin Chinese,mand1415,fear,89.0,uc1.l0088545033,2004.0,0.000876,-0.020181,101618.0,China,Mandarin Chinese,1.809500,1.726083,12.1118
470,Mandarin Chinese,mand1415,frustration,7.0,uc1.l0088545033,2004.0,0.000069,1.444598,101618.0,China,Mandarin Chinese,1.815642,1.763461,12.1118
480,Mandarin Chinese,mand1415,gratitude,20.0,uc1.l0088545033,2004.0,0.000197,2.593497,101618.0,China,Mandarin Chinese,4.213090,1.766079,12.1118
490,Mandarin Chinese,mand1415,hope,20.0,uc1.l0088545033,2004.0,0.000197,1.984625,101618.0,China,Mandarin Chinese,4.528934,1.634887,12.1118
500,Mandarin Chinese,mand1415,loneliness,4.0,uc1.l0088545033,2004.0,0.000039,-0.344534,101618.0,China,Mandarin Chinese,1.812437,1.826492,12.1118
510,Mandarin Chinese,mand1415,love,176.0,uc1.l0088545033,2004.0,0.001732,4.113460,101618.0,China,Mandarin Chinese,4.577157,1.554621,12.1118
520,Mandarin Chinese,mand1415,pleasure,52.0,uc1.l0088545033,2004.0,0.000512,-1.741132,101618.0,China,Mandarin Chinese,3.481275,1.788756,12.1118
530,Mandarin Chinese,mand1415,regret,48.0,uc1.l0088545033,2004.0,0.000472,5.141360,101618.0,China,Mandarin Chinese,1.477009,1.701083,12.1118
540,Mandarin Chinese,mand1415,relief,28.0,uc1.l0088545033,2004.0,0.000276,1.397026,101618.0,China,Mandarin Chinese,2.084221,1.851055,12.1118
550,Mandarin Chinese,mand1415,sadness,7.0,uc1.l0088545033,2004.0,0.000069,-1.073548,101618.0,China,Mandarin Chinese,2.256709,1.848471,12.1118

In [58]:
merged['word'].nunique()

18

In [59]:
merged = merged.sort_values(by=["langname", 'countryname','word'])
merged = merged.reset_index(drop=True)
merged = merged.fillna(0)

In [60]:
merged

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,response_mean,response_std,dictionary_count_mean
0,Afrikaans,afri1274,admiration,6.0,mdp.39015054154474,1999.0,0.000028,-3.291632,212992.0,South Africa,Afrikaans,2.946429,1.712904,25.386412
1,Afrikaans,afri1274,anger,55.0,mdp.39015054154474,1999.0,0.000258,-6.741147,212992.0,South Africa,Afrikaans,2.785714,1.803043,25.386412
2,Afrikaans,afri1274,anxiety,30.0,mdp.39015054154474,1999.0,0.000141,-2.655449,212992.0,South Africa,Afrikaans,3.535714,1.765171,25.386412
3,Afrikaans,afri1274,boredom,5.0,mdp.39015054154474,1999.0,0.000023,-1.176312,212992.0,South Africa,Afrikaans,2.241071,1.889971,25.386412
4,Afrikaans,afri1274,compassion,15.0,mdp.39015054154474,1999.0,0.000070,-2.918472,212992.0,South Africa,Afrikaans,4.196429,1.505780,25.386412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,Vietnamese,viet1252,love,308.0,uc1.31210024487306,2003.0,0.001143,-1.138291,269366.0,Vietnam,Vietnamese,4.786942,1.311475,32.105602
878,Vietnamese,viet1252,pleasure,216.0,uc1.31210024487306,2003.0,0.000802,3.511485,269366.0,Vietnam,Vietnamese,2.832192,1.885719,32.105602
879,Vietnamese,viet1252,regret,59.0,uc1.31210024487306,2003.0,0.000219,0.052866,269366.0,Vietnam,Vietnamese,1.534247,1.709743,32.105602
880,Vietnamese,viet1252,relief,74.0,uc1.31210024487306,2003.0,0.000275,2.404758,269366.0,Vietnam,Vietnamese,3.199313,1.720505,32.105602
881,Vietnamese,viet1252,sadness,51.0,uc1.31210024487306,2003.0,0.000189,4.028092,269366.0,Vietnam,Vietnamese,2.047945,1.841978,32.105602

In [61]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 882 entries, 0 to 881
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   langname                    882 non-null    object
 1   glottocode                  882 non-null    object
 2   word                        882 non-null    object
 3   count                       882 non-null    float64
 4   id                          882 non-null    object
 5   year                        882 non-null    float64
 6   simple_elaboration          882 non-null    float64
 7   regression_elaboration      882 non-null    float64
 8   dictsize_data               882 non-null    float64
 9   countryname                 882 non-null    object
 10  bila_language_name_mapping  882 non-null    object
 11  response_mean               882 non-null    float64
 12  response_std                882 non-null    float64
 13  dictionary_count_mean       882 non-null    float64
dtypes: float64(8), object(6)
memory usage: 96.6+ KB

In [62]:
merged.to_csv(Path("~/Projects/hypocognition/data/processed/MAX_covid_bila_merge.csv").expanduser())

"Moving forward, could you create a table with the following columns (broken down into the 36 samples):
* The sample country
* The language
* The correlation between the log count and the response means
* The correlation between the log count and the response SDs
* The correlation between the log count and the absolute distance of the response means from the scale midpoint

In [63]:
merged['response_mean'].mean()

np.float64(3.027895463883044)

In [64]:

# log count (add 1 to avoid log(0) just in case)
merged2 = merged.copy()
merged2["log_count"] = np.log(merged2["count"] + 1)

def corr_within_group(df, x, y):
    return df[x].corr(df[y])

countries = merged2['countryname'].unique().tolist()

for c in countries:
    df = merged2[merged2['countryname']==c]
    print(c,df['log_count'].corr(df['response_mean']), df['log_count'].corr(df['response_std']))

South Africa 0.09148865168961892 -0.12653514046747824
Egypt -0.11433067618319566 0.13329119935570388
Jordan -0.22730182023960746 0.22199851220158942
Syria 0.08928912107744537 -0.29449735181619413
Brazil 0.1624355100367705 -0.09586451876984464
Bulgaria 0.2914576122549996 -0.510940348557617
Denmark -0.3228657980051242 -0.19173518683367818
Curacao -0.22717185923377653 -0.01279205981994988
Netherlands -0.22757861410314467 -0.30170812809299574
Finland 0.0720360849933431 -0.29966805278456204
France -0.12485678545510513 0.16444273794734743
Pakistan 0.15151736280403277 0.16453879766845736
Georgia -0.09763318852656655 0.08255505707391594
Germany 0.17814793850857474 -0.09156428792952183
Greece 0.155470088914526 -0.2718482113675404
Israel -0.19576632870638763 0.22289222905270406
Hungary 0.27087397624337056 -0.3665163766184561
Iceland 0.13037213359602945 -0.3824791026602647
Indonesia -0.01639818458273091 -0.10834449797267735
Italy -0.02900174620842426 -0.3471079511701444
Japan 0.0804512593809085 -0.4519920306637275
Australia 0.16409225986275572 -0.05047382146015632
Canada -0.053858673079066485 0.04828292352265023
China 0.19149418297264034 -0.4047439145055948
Ghana -0.16692425371482827 nan
Hong Kong (S.A.R) 0.11720350313316244 -0.37759598035115294
New Zealand 0.15374600482006429 -0.25211976351828347
Singapore 0.08374671097135508 -0.10298398758317759
Taiwan 0.23941839478073407 -0.3061637790253629
United Kingdom (UK) 0.15175790499801153 -0.42469243040977406
United States of America (USA) 0.04065752923180417 -0.3032431768160892
India 0.05353987345805218 -0.04789252552447254
Iran -0.04999927688577651 -0.052835803463284245
Kazakhstan -0.08288509303617991 0.24975091174620737
Mongolia 0.041567947168032 0.35749803984623213
Russia -0.07352418265199077 0.1308098406054469
Croatia -0.3635695112544323 -0.037433554771570336
Ireland 0.16053956339287956 0.15205753784389725
Serbia -0.2598865860917221 -0.005079796650854438
Chile 0.1999888821873698 -0.15350370047937148
Colombia 0.02940717256565985 -0.27058882302767007
Peru 0.07703882461051899 0.06639217967192046
Spain -0.04244600457684137 0.13703796328524492
Trinidad and Tobago -0.05971627779523961 nan
Malaysia 0.1651937808983266 -0.28022368490738875
Sweden -0.06578773149503762 -0.21453055017820025
Turkey 0.28189768382983316 -0.32792732052609985
Ukraine 0.15457774093530283 0.016344073727504627
Vietnam 0.07716127645995545 -0.4397485234107762

/data/home/asher.katz/miniconda3/envs/hypenv/lib/python3.11/site-packages/numpy/lib/_function_base_impl.py:3023: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/data/home/asher.katz/miniconda3/envs/hypenv/lib/python3.11/site-packages/numpy/lib/_function_base_impl.py:3024: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

In [65]:
import numpy as np

merged2 = merged.copy()

# log count
merged2["log_count"] = np.log(merged2["count"] + 1)

# absolute distance from midpoint
SCALE_MIDPOINT = merged2["response_mean"].mean()
merged2["abs_dist_midpoint"] = (
    merged2["response_mean"] - SCALE_MIDPOINT
).abs()

result = (
    merged2
    .groupby(["countryname", "langname", "id"])
    .agg(
        corr_logcount_response_mean=(
            "log_count",
            lambda x: x.corr(
                merged2.loc[x.index, "response_mean"]
            )
        ),
        corr_logcount_response_sd=(
            "log_count",
            lambda x: x.corr(
                merged2.loc[x.index, "response_std"]
            )
        ),
        corr_logcount_abs_dist_midpoint=(
            "log_count",
            lambda x: x.corr(
                merged2.loc[x.index, "abs_dist_midpoint"]
            )
        ),

    )
    .reset_index()
)

/data/home/asher.katz/miniconda3/envs/hypenv/lib/python3.11/site-packages/numpy/lib/_function_base_impl.py:3023: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/data/home/asher.katz/miniconda3/envs/hypenv/lib/python3.11/site-packages/numpy/lib/_function_base_impl.py:3024: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

In [66]:
result

,countryname,langname,id,corr_logcount_response_mean,corr_logcount_response_sd,corr_logcount_abs_dist_midpoint
0,Australia,Mandarin Chinese,uc1.l0088545033,0.164092,-0.050474,-0.050495
1,Brazil,Brazilian Portuguese,txu.059173018640743,0.162436,-0.095865,0.060763
2,Bulgaria,Bulgarian,mdp.39015058560494,0.291458,-0.510940,0.256754
3,Canada,Mandarin Chinese,uc1.l0088545033,-0.053859,0.048283,0.283331
4,Chile,Spanish,umn.31951d01452389x,0.199989,-0.153504,0.284414
5,China,Mandarin Chinese,uc1.l0088545033,0.191494,-0.404744,0.107092
6,Colombia,Spanish,umn.31951d01452389x,0.029407,-0.270589,-0.066229
7,Croatia,Serbian-Croatian-Bosnian,mdp.39015012891506,-0.363570,-0.037434,-0.237194
8,Curacao,Dutch,uc1.31822004083036,-0.227172,-0.012792,-0.209157
9,Denmark,Danish,uc1.b3832576,-0.322866,-0.191735,0.325635
10,Egypt,Arabic,mdp.39015043036436,-0.114331,0.133291,-0.347282
11,Finland,Finnish,mdp.39015059174667,0.072036,-0.299668,-0.090822
12,France,French,mdp.39015066787105,-0.124857,0.164443,-0.171960
13,Georgia,Georgian,uva.x001957729,-0.097633,0.082555,0.153910
14,Germany,German,uc1.31822005249149,0.178148,-0.091564,0.026480
15,Ghana,Mandarin Chinese,uc1.l0088545033,-0.166924,NaN,0.393153
16,Greece,Greek,uc1.32106014581794,0.155470,-0.271848,0.089275
17,Hong Kong (S.A.R),Mandarin Chinese,uc1.l0088545033,0.117204,-0.377596,0.113337
18,Hungary,Hungarian,miun.aee0517.0001.001,0.270874,-0.366516,0.238853
19,Iceland,Icelandic,uc1.32106020063118,0.130372,-0.382479,0.239283
20,India,Marathi,mdp.39015055371309,0.053540,-0.047893,-0.092976
21,Indonesia,Indonesian,uc1.31822029604741,-0.016398,-0.108344,-0.186482
22,Iran,Persian,mdp.49015002913532,-0.049999,-0.052836,-0.064321
23,Ireland,Serbian-Croatian-Bosnian,mdp.39015012891506,0.160540,0.152058,-0.207657
24,Israel,Hebrew,uva.x004242694,-0.195766,0.222892,0.162689
25,Italy,Italian,mdp.39015042010226,-0.029002,-0.347108,0.233879
26,Japan,Japanese,uva.x004877953,0.080451,-0.451992,0.212679
27,Jordan,Arabic,mdp.39015043036436,-0.227302,0.221999,-0.187992
28,Kazakhstan,Russian,mdp.39015046500511,-0.082885,0.249751,-0.043992
29,Malaysia,Standard Malay,mdp.39015022909470,0.165194,-0.280224,0.230423
30,Mongolia,Russian,mdp.39015046500511,0.041568,0.357498,-0.266201
31,Netherlands,Dutch,uc1.31822004083036,-0.227579,-0.301708,-0.158814
32,New Zealand,Mandarin Chinese,uc1.l0088545033,0.153746,-0.252120,0.013472
33,Pakistan,French,mdp.39015066787105,0.151517,0.164539,-0.163290
34,Peru,Spanish,umn.31951d01452389x,0.077039,0.066392,-0.102366
35,Russia,Russian,mdp.39015046500511,-0.073524,0.130810,0.157392
36,Serbia,Serbian-Croatian-Bosnian,mdp.39015012891506,-0.259887,-0.005080,-0.371525
37,Singapore,Mandarin Chinese,uc1.l0088545033,0.083747,-0.102984,0.139741
38,South Africa,Afrikaans,mdp.39015054154474,0.091489,-0.126535,-0.066164
39,Spain,Spanish,umn.31951d01452389x,-0.042446,0.137038,-0.139912
40,Sweden,Swedish,mdp.39015052442327,-0.065788,-0.214531,0.092176
41,Syria,Arabic,mdp.39015043036436,0.089289,-0.294497,-0.133924
42,Taiwan,Mandarin Chinese,uc1.l0088545033,0.239418,-0.306164,-0.029929
43,Trinidad and Tobago,Spanish,umn.31951d01452389x,-0.059716,NaN,0.097955
44,Turkey,Turkish,coo.31924067983704,0.281898,-0.327927,-0.001509
45,Ukraine,Ukrainian,uc1.l0070891726,0.154578,0.016344,0.230726
46,United Kingdom (UK),Mandarin Chinese,uc1.l0088545033,0.151758,-0.424692,0.273042
47,United States of America (USA),Mandarin Chinese,uc1.l0088545033,0.040658,-0.303243,0.356781
48,Vietnam,Vietnamese,uc1.31210024487306,0.077161,-0.439749,0.139925

In [117]:
result.to_csv(Path("~/Projects/hypocognition/data/processed/MAX_corr_covid_bila.csv").expanduser())

In [69]:
corr1 = pd.read_csv(Path("~/Projects/hypocognition/data/processed/covid_bila_correlation (7).csv").expanduser(), index_col=0)
corr1

,countryname,langname,id,corr_logcount_response_mean,corr_logcount_response_sd,corr_logcount_abs_dist_midpoint
0,Brazil,Brazilian Portuguese,txu.059173018640743,0.162436,-0.095865,0.058824
1,Bulgaria,Bulgarian,mdp.39015058560494,0.291458,-0.510940,0.265190
2,Chile,Latin American Spanish,mdp.39015050181174,0.371436,-0.362343,0.241720
3,China,Mandarin Chinese,uc1.l0088545033,0.191494,-0.404744,0.116186
4,Colombia,Latin American Spanish,mdp.39015050181174,0.236561,-0.175261,-0.137527
5,Croatia,Serbian-Croatian-Bosnian,mdp.39015012891506,-0.363570,-0.037434,-0.247292
6,Curacao,Dutch,uc1.31822004083036,-0.227172,-0.012792,-0.211604
7,Denmark,Danish,uc1.b3832576,-0.322866,-0.191735,0.313704
8,Egypt,Arabic,mdp.39015043036436,-0.114331,0.133291,-0.338161
9,Finland,Finnish,mdp.39015059174667,0.072036,-0.299668,-0.086969
10,France,French,mdp.39015066787105,-0.124857,0.164443,-0.189558
11,Georgia,Georgian,uva.x001957729,-0.097633,0.082555,0.153907
12,Germany,German,uc1.31822005249149,0.178148,-0.091564,0.031446
13,Greece,Greek,uc1.32106014581794,0.155470,-0.271848,0.093607
14,Hong Kong (S.A.R),Mandarin Chinese,uc1.l0088545033,0.117204,-0.377596,0.118987
15,Hungary,Hungarian,miun.aee0517.0001.001,0.270874,-0.366516,0.245819
16,Iceland,Icelandic,uc1.32106020063118,0.130372,-0.382479,0.245592
17,India,Marathi,mdp.39015055371309,0.053540,-0.047893,-0.092318
18,Indonesia,Indonesian,uc1.31822029604741,-0.016398,-0.108344,-0.185877
19,Iran,Persian,mdp.49015002913532,-0.049999,-0.052836,-0.071096
20,Israel,Hebrew,uva.x004242694,-0.195766,0.222892,0.152080
21,Italy,Italian,mdp.39015042010226,-0.029002,-0.347108,0.223311
22,Japan,Japanese,uva.x004877953,0.080451,-0.451992,0.205383
23,Jordan,Arabic,mdp.39015043036436,-0.227302,0.221999,-0.194765
24,Kazakhstan,Russian,mdp.39015046500511,-0.082885,0.249751,-0.055657
25,Malaysia,Standard Malay,mdp.39015022909470,0.165194,-0.280224,0.226831
26,Netherlands,Dutch,uc1.31822004083036,-0.227579,-0.301708,-0.172442
27,Peru,Spanish,umn.31951d01452389x,0.077039,0.066392,-0.106625
28,Russia,Russian,mdp.39015046500511,-0.073524,0.130810,0.149592
29,Serbia,Serbian-Croatian-Bosnian,mdp.39015012891506,-0.259887,-0.005080,-0.369801
30,South Africa,Afrikaans,mdp.39015054154474,0.091489,-0.126535,-0.062975
31,Spain,Spanish,umn.31951d01452389x,0.013715,-0.008544,-0.040810
32,Sweden,Swedish,mdp.39015052442327,-0.065788,-0.214531,0.093415
33,Syria,Arabic,mdp.39015043036436,0.089289,-0.294497,-0.136173
34,Taiwan,Mandarin Chinese,uc1.l0088545033,0.239418,-0.306164,-0.019556
35,Turkey,Turkish,coo.31924067983704,0.281898,-0.327927,0.013609
36,Ukraine,Ukrainian,uc1.l0070891726,0.154578,0.016344,0.232985
37,Vietnam,Vietnamese,uc1.31210024487306,0.077161,-0.439749,0.141320

In [70]:
both = result.merge(
    corr1,
    on="countryname"
)
both

,countryname,langname_x,id_x,corr_logcount_response_mean_x,corr_logcount_response_sd_x,corr_logcount_abs_dist_midpoint_x,langname_y,id_y,corr_logcount_response_mean_y,corr_logcount_response_sd_y,corr_logcount_abs_dist_midpoint_y
0,Brazil,Brazilian Portuguese,txu.059173018640743,0.162436,-0.095865,0.060763,Brazilian Portuguese,txu.059173018640743,0.162436,-0.095865,0.058824
1,Bulgaria,Bulgarian,mdp.39015058560494,0.291458,-0.510940,0.256754,Bulgarian,mdp.39015058560494,0.291458,-0.510940,0.265190
2,Chile,Spanish,umn.31951d01452389x,0.199989,-0.153504,0.284414,Latin American Spanish,mdp.39015050181174,0.371436,-0.362343,0.241720
3,China,Mandarin Chinese,uc1.l0088545033,0.191494,-0.404744,0.107092,Mandarin Chinese,uc1.l0088545033,0.191494,-0.404744,0.116186
4,Colombia,Spanish,umn.31951d01452389x,0.029407,-0.270589,-0.066229,Latin American Spanish,mdp.39015050181174,0.236561,-0.175261,-0.137527
5,Croatia,Serbian-Croatian-Bosnian,mdp.39015012891506,-0.363570,-0.037434,-0.237194,Serbian-Croatian-Bosnian,mdp.39015012891506,-0.363570,-0.037434,-0.247292
6,Curacao,Dutch,uc1.31822004083036,-0.227172,-0.012792,-0.209157,Dutch,uc1.31822004083036,-0.227172,-0.012792,-0.211604
7,Denmark,Danish,uc1.b3832576,-0.322866,-0.191735,0.325635,Danish,uc1.b3832576,-0.322866,-0.191735,0.313704
8,Egypt,Arabic,mdp.39015043036436,-0.114331,0.133291,-0.347282,Arabic,mdp.39015043036436,-0.114331,0.133291,-0.338161
9,Finland,Finnish,mdp.39015059174667,0.072036,-0.299668,-0.090822,Finnish,mdp.39015059174667,0.072036,-0.299668,-0.086969
10,France,French,mdp.39015066787105,-0.124857,0.164443,-0.171960,French,mdp.39015066787105,-0.124857,0.164443,-0.189558
11,Georgia,Georgian,uva.x001957729,-0.097633,0.082555,0.153910,Georgian,uva.x001957729,-0.097633,0.082555,0.153907
12,Germany,German,uc1.31822005249149,0.178148,-0.091564,0.026480,German,uc1.31822005249149,0.178148,-0.091564,0.031446
13,Greece,Greek,uc1.32106014581794,0.155470,-0.271848,0.089275,Greek,uc1.32106014581794,0.155470,-0.271848,0.093607
14,Hong Kong (S.A.R),Mandarin Chinese,uc1.l0088545033,0.117204,-0.377596,0.113337,Mandarin Chinese,uc1.l0088545033,0.117204,-0.377596,0.118987
15,Hungary,Hungarian,miun.aee0517.0001.001,0.270874,-0.366516,0.238853,Hungarian,miun.aee0517.0001.001,0.270874,-0.366516,0.245819
16,Iceland,Icelandic,uc1.32106020063118,0.130372,-0.382479,0.239283,Icelandic,uc1.32106020063118,0.130372,-0.382479,0.245592
17,India,Marathi,mdp.39015055371309,0.053540,-0.047893,-0.092976,Marathi,mdp.39015055371309,0.053540,-0.047893,-0.092318
18,Indonesia,Indonesian,uc1.31822029604741,-0.016398,-0.108344,-0.186482,Indonesian,uc1.31822029604741,-0.016398,-0.108344,-0.185877
19,Iran,Persian,mdp.49015002913532,-0.049999,-0.052836,-0.064321,Persian,mdp.49015002913532,-0.049999,-0.052836,-0.071096
20,Israel,Hebrew,uva.x004242694,-0.195766,0.222892,0.162689,Hebrew,uva.x004242694,-0.195766,0.222892,0.152080
21,Italy,Italian,mdp.39015042010226,-0.029002,-0.347108,0.233879,Italian,mdp.39015042010226,-0.029002,-0.347108,0.223311
22,Japan,Japanese,uva.x004877953,0.080451,-0.451992,0.212679,Japanese,uva.x004877953,0.080451,-0.451992,0.205383
23,Jordan,Arabic,mdp.39015043036436,-0.227302,0.221999,-0.187992,Arabic,mdp.39015043036436,-0.227302,0.221999,-0.194765
24,Kazakhstan,Russian,mdp.39015046500511,-0.082885,0.249751,-0.043992,Russian,mdp.39015046500511,-0.082885,0.249751,-0.055657
25,Malaysia,Standard Malay,mdp.39015022909470,0.165194,-0.280224,0.230423,Standard Malay,mdp.39015022909470,0.165194,-0.280224,0.226831
26,Netherlands,Dutch,uc1.31822004083036,-0.227579,-0.301708,-0.158814,Dutch,uc1.31822004083036,-0.227579,-0.301708,-0.172442
27,Peru,Spanish,umn.31951d01452389x,0.077039,0.066392,-0.102366,Spanish,umn.31951d01452389x,0.077039,0.066392,-0.106625
28,Russia,Russian,mdp.39015046500511,-0.073524,0.130810,0.157392,Russian,mdp.39015046500511,-0.073524,0.130810,0.149592
29,Serbia,Serbian-Croatian-Bosnian,mdp.39015012891506,-0.259887,-0.005080,-0.371525,Serbian-Croatian-Bosnian,mdp.39015012891506,-0.259887,-0.005080,-0.369801
30,South Africa,Afrikaans,mdp.39015054154474,0.091489,-0.126535,-0.066164,Afrikaans,mdp.39015054154474,0.091489,-0.126535,-0.062975
31,Spain,Spanish,umn.31951d01452389x,-0.042446,0.137038,-0.139912,Spanish,umn.31951d01452389x,0.013715,-0.008544,-0.040810
32,Sweden,Swedish,mdp.39015052442327,-0.065788,-0.214531,0.092176,Swedish,mdp.39015052442327,-0.065788,-0.214531,0.093415
33,Syria,Arabic,mdp.39015043036436,0.089289,-0.294497,-0.133924,Arabic,mdp.39015043036436,0.089289,-0.294497,-0.136173
34,Taiwan,Mandarin Chinese,uc1.l0088545033,0.239418,-0.306164,-0.029929,Mandarin Chinese,uc1.l0088545033,0.239418,-0.306164,-0.019556
35,Turkey,Turkish,coo.31924067983704,0.281898,-0.327927,-0.001509,Turkish,coo.31924067983704,0.281898,-0.327927,0.013609
36,Ukraine,Ukrainian,uc1.l0070891726,0.154578,0.016344,0.230726,Ukrainian,uc1.l0070891726,0.154578,0.016344,0.232985
37,Vietnam,Vietnamese,uc1.31210024487306,0.077161,-0.439749,0.139925,Vietnamese,uc1.31210024487306,0.077161,-0.439749,0.141320

In [71]:
both.columns

Index(['countryname', 'langname_x', 'id_x', 'corr_logcount_response_mean_x',
       'corr_logcount_response_sd_x', 'corr_logcount_abs_dist_midpoint_x',
       'langname_y', 'id_y', 'corr_logcount_response_mean_y',
       'corr_logcount_response_sd_y', 'corr_logcount_abs_dist_midpoint_y'],
      dtype='object')

In [72]:
both = both[['countryname', 'langname_x','langname_y', 'id_x','id_y',  'corr_logcount_response_mean_x','corr_logcount_response_mean_y',
       'corr_logcount_response_sd_x','corr_logcount_response_sd_y', 'corr_logcount_abs_dist_midpoint_x','corr_logcount_abs_dist_midpoint_y']]
both

,countryname,langname_x,langname_y,id_x,id_y,corr_logcount_response_mean_x,corr_logcount_response_mean_y,corr_logcount_response_sd_x,corr_logcount_response_sd_y,corr_logcount_abs_dist_midpoint_x,corr_logcount_abs_dist_midpoint_y
0,Brazil,Brazilian Portuguese,Brazilian Portuguese,txu.059173018640743,txu.059173018640743,0.162436,0.162436,-0.095865,-0.095865,0.060763,0.058824
1,Bulgaria,Bulgarian,Bulgarian,mdp.39015058560494,mdp.39015058560494,0.291458,0.291458,-0.510940,-0.510940,0.256754,0.265190
2,Chile,Spanish,Latin American Spanish,umn.31951d01452389x,mdp.39015050181174,0.199989,0.371436,-0.153504,-0.362343,0.284414,0.241720
3,China,Mandarin Chinese,Mandarin Chinese,uc1.l0088545033,uc1.l0088545033,0.191494,0.191494,-0.404744,-0.404744,0.107092,0.116186
4,Colombia,Spanish,Latin American Spanish,umn.31951d01452389x,mdp.39015050181174,0.029407,0.236561,-0.270589,-0.175261,-0.066229,-0.137527
5,Croatia,Serbian-Croatian-Bosnian,Serbian-Croatian-Bosnian,mdp.39015012891506,mdp.39015012891506,-0.363570,-0.363570,-0.037434,-0.037434,-0.237194,-0.247292
6,Curacao,Dutch,Dutch,uc1.31822004083036,uc1.31822004083036,-0.227172,-0.227172,-0.012792,-0.012792,-0.209157,-0.211604
7,Denmark,Danish,Danish,uc1.b3832576,uc1.b3832576,-0.322866,-0.322866,-0.191735,-0.191735,0.325635,0.313704
8,Egypt,Arabic,Arabic,mdp.39015043036436,mdp.39015043036436,-0.114331,-0.114331,0.133291,0.133291,-0.347282,-0.338161
9,Finland,Finnish,Finnish,mdp.39015059174667,mdp.39015059174667,0.072036,0.072036,-0.299668,-0.299668,-0.090822,-0.086969
10,France,French,French,mdp.39015066787105,mdp.39015066787105,-0.124857,-0.124857,0.164443,0.164443,-0.171960,-0.189558
11,Georgia,Georgian,Georgian,uva.x001957729,uva.x001957729,-0.097633,-0.097633,0.082555,0.082555,0.153910,0.153907
12,Germany,German,German,uc1.31822005249149,uc1.31822005249149,0.178148,0.178148,-0.091564,-0.091564,0.026480,0.031446
13,Greece,Greek,Greek,uc1.32106014581794,uc1.32106014581794,0.155470,0.155470,-0.271848,-0.271848,0.089275,0.093607
14,Hong Kong (S.A.R),Mandarin Chinese,Mandarin Chinese,uc1.l0088545033,uc1.l0088545033,0.117204,0.117204,-0.377596,-0.377596,0.113337,0.118987
15,Hungary,Hungarian,Hungarian,miun.aee0517.0001.001,miun.aee0517.0001.001,0.270874,0.270874,-0.366516,-0.366516,0.238853,0.245819
16,Iceland,Icelandic,Icelandic,uc1.32106020063118,uc1.32106020063118,0.130372,0.130372,-0.382479,-0.382479,0.239283,0.245592
17,India,Marathi,Marathi,mdp.39015055371309,mdp.39015055371309,0.053540,0.053540,-0.047893,-0.047893,-0.092976,-0.092318
18,Indonesia,Indonesian,Indonesian,uc1.31822029604741,uc1.31822029604741,-0.016398,-0.016398,-0.108344,-0.108344,-0.186482,-0.185877
19,Iran,Persian,Persian,mdp.49015002913532,mdp.49015002913532,-0.049999,-0.049999,-0.052836,-0.052836,-0.064321,-0.071096
20,Israel,Hebrew,Hebrew,uva.x004242694,uva.x004242694,-0.195766,-0.195766,0.222892,0.222892,0.162689,0.152080
21,Italy,Italian,Italian,mdp.39015042010226,mdp.39015042010226,-0.029002,-0.029002,-0.347108,-0.347108,0.233879,0.223311
22,Japan,Japanese,Japanese,uva.x004877953,uva.x004877953,0.080451,0.080451,-0.451992,-0.451992,0.212679,0.205383
23,Jordan,Arabic,Arabic,mdp.39015043036436,mdp.39015043036436,-0.227302,-0.227302,0.221999,0.221999,-0.187992,-0.194765
24,Kazakhstan,Russian,Russian,mdp.39015046500511,mdp.39015046500511,-0.082885,-0.082885,0.249751,0.249751,-0.043992,-0.055657
25,Malaysia,Standard Malay,Standard Malay,mdp.39015022909470,mdp.39015022909470,0.165194,0.165194,-0.280224,-0.280224,0.230423,0.226831
26,Netherlands,Dutch,Dutch,uc1.31822004083036,uc1.31822004083036,-0.227579,-0.227579,-0.301708,-0.301708,-0.158814,-0.172442
27,Peru,Spanish,Spanish,umn.31951d01452389x,umn.31951d01452389x,0.077039,0.077039,0.066392,0.066392,-0.102366,-0.106625
28,Russia,Russian,Russian,mdp.39015046500511,mdp.39015046500511,-0.073524,-0.073524,0.130810,0.130810,0.157392,0.149592
29,Serbia,Serbian-Croatian-Bosnian,Serbian-Croatian-Bosnian,mdp.39015012891506,mdp.39015012891506,-0.259887,-0.259887,-0.005080,-0.005080,-0.371525,-0.369801
30,South Africa,Afrikaans,Afrikaans,mdp.39015054154474,mdp.39015054154474,0.091489,0.091489,-0.126535,-0.126535,-0.066164,-0.062975
31,Spain,Spanish,Spanish,umn.31951d01452389x,umn.31951d01452389x,-0.042446,0.013715,0.137038,-0.008544,-0.139912,-0.040810
32,Sweden,Swedish,Swedish,mdp.39015052442327,mdp.39015052442327,-0.065788,-0.065788,-0.214531,-0.214531,0.092176,0.093415
33,Syria,Arabic,Arabic,mdp.39015043036436,mdp.39015043036436,0.089289,0.089289,-0.294497,-0.294497,-0.133924,-0.136173
34,Taiwan,Mandarin Chinese,Mandarin Chinese,uc1.l0088545033,uc1.l0088545033,0.239418,0.239418,-0.306164,-0.306164,-0.029929,-0.019556
35,Turkey,Turkish,Turkish,coo.31924067983704,coo.31924067983704,0.281898,0.281898,-0.327927,-0.327927,-0.001509,0.013609
36,Ukraine,Ukrainian,Ukrainian,uc1.l0070891726,uc1.l0070891726,0.154578,0.154578,0.016344,0.016344,0.230726,0.232985
37,Vietnam,Vietnamese,Vietnamese,uc1.31210024487306,uc1.31210024487306,0.077161,0.077161,-0.439749,-0.439749,0.139925,0.141320

In [73]:
both.to_csv(Path("~/Projects/hypocognition/data/processed/corr_comparison.csv").expanduser())

In [218]:
merged.columns

Index(['langname', 'glottocode', 'word', 'count', 'id', 'year', 'countryname',
       'response_mean', 'std'],
      dtype='object')

In [176]:
import plotly.graph_objects as go

df_plot = result.copy()
df_plot = df_plot.sort_values('langname')
df_plot["sample"] = df_plot["countryname"] + " – " + df_plot["langname"]

In [177]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=df_plot["sample"],
    y=df_plot["corr_logcount_response_mean"],
    mode="markers",
    name="Corr(log count, response mean)",
    marker=dict(size=9, color="lime")
))

fig.add_trace(go.Scatter(
    x=df_plot["sample"],
    y=df_plot["corr_logcount_response_sd"],
    mode="markers",
    name="Corr(log count, response SD)",
    marker=dict(size=9, color= 'blue')
))

fig.add_trace(go.Scatter(
    x=df_plot["sample"],
    y=df_plot["corr_logcount_abs_dist_midpoint"],
    mode="markers",
    name="Corr(log count, |mean − midpoint|)",
    marker=dict(size=9, color="red")
))

fig.update_layout(
    title="Correlations between Log Count and Response Measures",
    yaxis_title="Pearson correlation",
    xaxis_title="Sample (Country – Language)",
    xaxis_tickangle=45,
    height=600,
    legend_title="Correlation type",
    template="simple_white"
)

fig.show()

In [178]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=df_plot["sample"],
    y=df_plot["corr_logcount_response_mean"],
    mode="lines+markers",
    name="Corr(log count, response mean)",
    marker=dict(size=9, color="lime"),
    line=dict(width=2, color="lime")
))

fig.add_trace(go.Scatter(
    x=df_plot["sample"],
    y=df_plot["corr_logcount_response_sd"],
    mode="lines+markers",
    name="Corr(log count, response SD)",
    marker=dict(size=9, color="blue"),
    line=dict(width=2, color="blue")
))

fig.add_trace(go.Scatter(
    x=df_plot["sample"],
    y=df_plot["corr_logcount_abs_dist_midpoint"],
    mode="lines+markers",
    name="Corr(log count, |mean − midpoint|)",
    marker=dict(size=9, color="red"),
    line=dict(width=2, color="red")
))

fig.add_hline(
    y=0,
    line_width=2,
    line_color="black"
)


fig.update_layout(
    title="Correlations between Log Count and Response Measures",
    yaxis_title="Pearson correlation",
    xaxis_title="Sample (Country – Language)",
    xaxis_tickangle=45,
    height=700,
    legend_title="Correlation type",
    template="simple_white"
)

fig.show()

In [2130]:
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=df_plot["langname"],
    y=df_plot["corr_logcount_response_mean"],
    mode="markers",
    name="Corr(log count, response mean)",
    marker=dict(size=9, color="lime")
))

fig.add_trace(go.Scatter(
    x=df_plot["langname"],
    y=df_plot["corr_logcount_response_sd"],
    mode="markers",
    name="Corr(log count, response SD)",
    marker=dict(size=9, color="blue")
))

fig.add_trace(go.Scatter(
    x=df_plot["langname"],
    y=df_plot["corr_logcount_abs_dist_midpoint"],
    mode="markers",
    name="Corr(log count, |mean − midpoint|)",
    marker=dict(size=9, color="red")
))

# horizontal zero line
fig.add_hline(
    y=0,
    line_width=1,
    line_dash="solid",
    line_color="black"
)

fig.update_layout(
    title="Correlations by Language, Searching for Hypocognition",
    xaxis_title="Language",
    yaxis_title="Pearson correlation",
    xaxis_tickangle=45,
    height=700,
    template="simple_white",
    legend_title="Correlation type"
)

fig.show()

In [ ]:
fig.write_html(Path("reference/lang_names.csv"))