In [657]:
# load libraries 
import pandas as pd
import numpy as np
import re
import math
import plotly.graph_objects as go
import plotly.express as px
from pathlib import Path

In [658]:
# get the SUN covid study dataset
Covid51countries = pd.read_csv(Path("~/Projects/hypocognition/data/raw/Covid51countries.csv").expanduser())
Covid51countries

,country,countryname,StartDate,EndDate,Status,Progress,Duration,Finished,RecordedDate,home,...,gender,ladder,employment,losejob,covidsymptom,language,datasource,ISO3,longstring,na_count
0,10,Australia,04/05/2020 19:34,04/05/2020 19:40,0.0,100.0,337.0,1.0,04/05/2020 19:40,8.0,...,1.0,5.0,4,NaN,0.0,ZH-S,snowball,AUS,3,0
1,10,Australia,04/05/2020 20:26,04/05/2020 20:35,0.0,100.0,530.0,1.0,04/05/2020 20:35,9.0,...,2.0,7.0,3,NaN,NaN,ZH-S,snowball,AUS,3,0
2,10,Australia,05/05/2020 21:54,05/05/2020 22:07,0.0,100.0,793.0,1.0,05/05/2020 22:07,29.0,...,1.0,4.0,1,NaN,0.0,ZH-S,snowball,AUS,5,0
3,10,Australia,04/05/2020 20:29,04/05/2020 20:34,0.0,100.0,285.0,1.0,04/05/2020 20:34,73.0,...,2.0,5.0,4,NaN,0.0,ZH-S,snowball,AUS,4,0
4,10,Australia,19/04/2020 20:21,19/04/2020 20:27,0.0,100.0,367.0,1.0,19/04/2020 20:27,100.0,...,1.0,5.0,1,NaN,0.0,ZH-S,snowball,AUS,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24216,92,Kenya,25/04/2020 01:25,25/04/2020 02:44,0.0,100.0,4690.0,1.0,25/04/2020 02:44,100.0,...,2.0,4.0,4,NaN,0.0,EN,snowball,KEN,4,0
24217,92,Kenya,24/04/2020 11:06,24/04/2020 11:15,0.0,100.0,556.0,1.0,24/04/2020 11:15,100.0,...,1.0,6.0,5,0.0,0.0,EN,snowball,KEN,2,0
24218,92,Kenya,26/04/2020 10:16,26/04/2020 10:36,0.0,100.0,1218.0,1.0,26/04/2020 10:36,80.0,...,1.0,3.0,4,NaN,0.0,EN,snowball,KEN,3,0
24219,92,Kenya,23/04/2020 03:46,23/04/2020 04:13,0.0,100.0,1641.0,1.0,23/04/2020 04:13,3.0,...,1.0,3.0,4,NaN,0.0,EN,snowball,KEN,3,0
24220,92,Kenya,24/04/2020 00:31,24/04/2020 00:42,0.0,100.0,700.0,1.0,24/04/2020 00:42,50.0,...,2.0,6.0,4,NaN,0.0,EN,snowball,KEN,2,0

In [659]:
# combine Spanish and Spanish(spain) for spain
# mask = (Covid51countries["countryname"] == "Spain") & (Covid51countries["language"] == "ES")
# Covid51countries.loc[mask, "language"] = "ES-ES"

In [660]:
# add language names to the df
lang_names = pd.read_csv(Path("~/Projects/hypocognition/data/external/lang_names.csv"))
Covid51countries = Covid51countries.merge(lang_names, left_on="language", right_on="Code", how="left")
Covid51countries

,country,countryname,StartDate,EndDate,Status,Progress,Duration,Finished,RecordedDate,home,...,employment,losejob,covidsymptom,language,datasource,ISO3,longstring,na_count,Code,Language_Name
0,10,Australia,04/05/2020 19:34,04/05/2020 19:40,0.0,100.0,337.0,1.0,04/05/2020 19:40,8.0,...,4,NaN,0.0,ZH-S,snowball,AUS,3,0,ZH-S,Simplified Chinese
1,10,Australia,04/05/2020 20:26,04/05/2020 20:35,0.0,100.0,530.0,1.0,04/05/2020 20:35,9.0,...,3,NaN,NaN,ZH-S,snowball,AUS,3,0,ZH-S,Simplified Chinese
2,10,Australia,05/05/2020 21:54,05/05/2020 22:07,0.0,100.0,793.0,1.0,05/05/2020 22:07,29.0,...,1,NaN,0.0,ZH-S,snowball,AUS,5,0,ZH-S,Simplified Chinese
3,10,Australia,04/05/2020 20:29,04/05/2020 20:34,0.0,100.0,285.0,1.0,04/05/2020 20:34,73.0,...,4,NaN,0.0,ZH-S,snowball,AUS,4,0,ZH-S,Simplified Chinese
4,10,Australia,19/04/2020 20:21,19/04/2020 20:27,0.0,100.0,367.0,1.0,19/04/2020 20:27,100.0,...,1,NaN,0.0,ZH-S,snowball,AUS,3,0,ZH-S,Simplified Chinese
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24216,92,Kenya,25/04/2020 01:25,25/04/2020 02:44,0.0,100.0,4690.0,1.0,25/04/2020 02:44,100.0,...,4,NaN,0.0,EN,snowball,KEN,4,0,EN,English
24217,92,Kenya,24/04/2020 11:06,24/04/2020 11:15,0.0,100.0,556.0,1.0,24/04/2020 11:15,100.0,...,5,0.0,0.0,EN,snowball,KEN,2,0,EN,English
24218,92,Kenya,26/04/2020 10:16,26/04/2020 10:36,0.0,100.0,1218.0,1.0,26/04/2020 10:36,80.0,...,4,NaN,0.0,EN,snowball,KEN,3,0,EN,English
24219,92,Kenya,23/04/2020 03:46,23/04/2020 04:13,0.0,100.0,1641.0,1.0,23/04/2020 04:13,3.0,...,4,NaN,0.0,EN,snowball,KEN,3,0,EN,English
24220,92,Kenya,24/04/2020 00:31,24/04/2020 00:42,0.0,100.0,700.0,1.0,24/04/2020 00:42,50.0,...,4,NaN,0.0,EN,snowball,KEN,2,0,EN,English

In [661]:
# merge croatian, bosnian and serbian
scb = ["Serbian", "Croatian", "Bosnian"]
Covid51countries = Covid51countries.drop(columns=['language'])
Covid51countries.loc[Covid51countries["Language_Name"].isin(scb), "Language_Name"] = "Serbian-Croatian-Bosnian"

In [662]:
# We want to use on only one language of responses for each country
# Further, that language cannot be English

# Calculate the number of responses for each country
country_response_count = pd.DataFrame(Covid51countries[['countryname', 'ISO3']].value_counts())

#collect the languages which people used to respond from each country
languages_per_country = Covid51countries.groupby('countryname')['Language_Name'].value_counts().reset_index(name="count")

# mereg num resposes to languages people used
languages_per_country = languages_per_country.merge(
    country_response_count,
    on="countryname",
    how="left"
)

# Clean up
languages_per_country = languages_per_country.rename(columns={"count_x": "lang_responses", "count_y": "total_responses"})
languages_per_country["percent"] = languages_per_country["lang_responses"] / languages_per_country["total_responses"] * 100

languages_per_country

,countryname,Language_Name,lang_responses,total_responses,percent
0,Australia,Simplified Chinese,181,378,47.883598
1,Australia,English,156,378,41.269841
2,Australia,Indonesian,12,378,3.174603
3,Australia,Traditional Chinese,10,378,2.645503
4,Australia,Vietnamese,5,378,1.322751
...,...,...,...,...,...
491,Vietnam,Simplified Chinese,2,338,0.591716
492,Vietnam,French,1,338,0.295858
493,Vietnam,Japanese,1,338,0.295858
494,Vietnam,Polish,1,338,0.295858
495,Vietnam,Traditional Chinese (Taiwan),1,338,0.295858

In [663]:
non_eng = languages_per_country[languages_per_country['Language_Name'] != "English"]
non_eng

,countryname,Language_Name,lang_responses,total_responses,percent
0,Australia,Simplified Chinese,181,378,47.883598
2,Australia,Indonesian,12,378,3.174603
3,Australia,Traditional Chinese,10,378,2.645503
4,Australia,Vietnamese,5,378,1.322751
5,Australia,Danish,3,378,0.793651
...,...,...,...,...,...
491,Vietnam,Simplified Chinese,2,338,0.591716
492,Vietnam,French,1,338,0.295858
493,Vietnam,Japanese,1,338,0.295858
494,Vietnam,Polish,1,338,0.295858
495,Vietnam,Traditional Chinese (Taiwan),1,338,0.295858

In [664]:
# gather list of top names
try:
    del top2
except:
    pass
for n in non_eng['countryname'].unique():
    df = non_eng[non_eng['countryname'] == n].reset_index(drop=True)
    try:
        top2 = pd.concat([top2, df.iloc[0:2]], ignore_index=True)
    except:
        top2 = df.iloc[0:2]

top2

,countryname,Language_Name,lang_responses,total_responses,percent
0,Australia,Simplified Chinese,181,378,47.883598
1,Australia,Indonesian,12,378,3.174603
2,Brazil,Brazilian Portuguese,306,325,94.153846
3,Brazil,Spanish,7,325,2.153846
4,Bulgaria,Bulgarian,269,276,97.463768
...,...,...,...,...,...
89,United Kingdom (UK),Hungarian,24,662,3.625378
90,United States of America (USA),Simplified Chinese,45,952,4.726891
91,United States of America (USA),Traditional Chinese (Taiwan),28,952,2.941176
92,Vietnam,Vietnamese,292,338,86.390533
93,Vietnam,Danish,3,338,0.887574

In [665]:
# we are short the 2*50 rows we'd excpect.
top2['countryname'].value_counts()

countryname
Australia                         2
Brazil                            2
Bulgaria                          2
Canada                            2
Chile                             2
China                             2
Colombia                          2
Croatia                           2
Curacao                           2
Denmark                           2
Finland                           2
France                            2
Greece                            2
Germany                           2
Hong Kong (S.A.R)                 2
Indonesia                         2
India                             2
Hungary                           2
United States of America (USA)    2
Russia                            2
Serbia                            2
Iran                              2
Israel                            2
Ireland                           2
Italy                             2
Japan                             2
Malta                             2
Jordan                            2
Kazakhstan                        2
Malaysia                          2
Netherlands                       2
Mongolia                          2
New Zealand                       2
Peru                              2
Vietnam                           2
Taiwan                            2
Turkey                            2
Singapore                         2
Spain                             2
South Africa                      2
Sweden                            2
Syria                             2
United Kingdom (UK)               2
Ukraine                           2
Egypt                             1
Georgia                           1
Ghana                             1
Iceland                           1
Pakistan                          1
Trinidad and Tobago               1
Name: count, dtype: int64

In [666]:
covid_to_bila_nouns_full_lang_name_mapping = pd.read_csv(Path("~/Projects/hypocognition/data/external/covid_to_full_bila_lang_name_mapping.csv"))
covid_to_bila_nouns_full_lang_name_mapping

,code,study_language_names,bila_language_name_mapping,possible_alternative_bila_language_name_mappings
0,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
1,EN,English,NaN,"Midland American English, Singlish, Devon, Sus..."
2,ID,Indonesian,Indonesian,"Standard Malay, Central Malay, Baba Malay"
3,ZH-T,Traditional Chinese,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese..."
4,VI,Vietnamese,Vietnamese,Nung (Viet Nam)
5,DA,Danish,Danish,NaN
6,AR,Arabic,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
7,ES,Spanish,Latin American Spanish,"Spanish, Mexican Spanish"
8,AFRI,Afrikaans,Afrikaans,Dutch
9,ES-ES,Spanish (Spain),Spanish,NaN
10,ET,Estonian,Estonian,Finnish
11,FR,French,French,"Old French, Cajun French, Louisiana Creole French"
12,JA,Japanese,Japanese,Middle Chinese
13,"HR, SR",Serbian-Croatian-Bosnian,Serbian-Croatian-Bosnian,NaN
14,ZH-TW,Traditional Chinese (Taiwan),Mandarin Chinese,"Min Nan Chinese, Hakka Chinese"
15,PT-BR,Brazilian Portuguese,Brazilian Portuguese,Portuguese
16,PT,Portuguese,Portuguese,Brazilian Portuguese
17,IT,Italian,Italian,Sicilian
18,BG,Bulgarian,Bulgarian,NaN
19,RU,Russian,Russian,Belarusian
20,FA,Persian,Persian,NaN
21,UK,Ukrainian,Ukrainian,NaN
22,NL,Dutch,Dutch,Western Flemish
23,DE,German,German,"Moselle Franconian, Plautdietsch, Pennsylvania..."
24,MS,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo"
25,TR,Turkish,Turkish,Turkmen
26,ISL,Icelandic,Icelandic,Old Norse
27,NO,Norwegian,Norwegian,NaN
28,RO,Romanian,Romanian,Aromanian
29,FI,Finnish,Finnish,Estonian
30,KAT,Georgian,Georgian,NaN
31,SV,Swedish,Swedish,NaN
32,EL,Greek,Greek,NaN
33,CA,Catalan,NaN,"Spanish, French"
34,HU,Hungarian,Hungarian,NaN
35,SL,Slovenian,Slovenian,NaN
36,CS,Czech,Czech,NaN
37,PL,Polish,Polish,NaN
38,SK,Slovak,Slovak,NaN
39,MAR,Marathi,Marathi,NaN
40,HI,Hindi,Hindi,"Hindustani, Caribbean Hindustani"
41,HE,Hebrew,Hebrew,Ancient Hebrew
42,KO,Korean,Korean,NaN
43,KAZ,Kazakh,Kazakh,NaN
44,ML,Malayalam,Malayalam,NaN
45,MALTI,Maltese,NaN,"Arabic, Italian"
46,FILIP,Filipino,Filipino,Tagalog-Pilipino
47,DARI,Dari,Persian,NaN

In [667]:
top2[top2['countryname']=='Croatia']

,countryname,Language_Name,lang_responses,total_responses,percent
14,Croatia,Serbian-Croatian-Bosnian,526,528,99.621212
15,Croatia,German,1,528,0.189394

In [668]:
top2[top2['countryname']=='Serbia']

,countryname,Language_Name,lang_responses,total_responses,percent
69,Serbia,Serbian-Croatian-Bosnian,352,354,99.435028
70,Serbia,Danish,1,354,0.282486

In [669]:
covid_to_bila_nouns_full_lang_name_mapping[covid_to_bila_nouns_full_lang_name_mapping['study_language_names']=='Serbian-Croatian-Bosnian']

,code,study_language_names,bila_language_name_mapping,possible_alternative_bila_language_name_mappings
13,"HR, SR",Serbian-Croatian-Bosnian,Serbian-Croatian-Bosnian,NaN

In [670]:
selection = top2.merge(
    covid_to_bila_nouns_full_lang_name_mapping,
    left_on="Language_Name",
    right_on = "study_language_names",
    how = "left"
).drop(columns=["code", "study_language_names"])

In [671]:
with pd.option_context('display.max_rows', None):
    display(selection)

,countryname,Language_Name,lang_responses,total_responses,percent,bila_language_name_mapping,possible_alternative_bila_language_name_mappings
0,Australia,Simplified Chinese,181,378,47.883598,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
1,Australia,Indonesian,12,378,3.174603,Indonesian,"Standard Malay, Central Malay, Baba Malay"
2,Brazil,Brazilian Portuguese,306,325,94.153846,Brazilian Portuguese,Portuguese
3,Brazil,Spanish,7,325,2.153846,Latin American Spanish,"Spanish, Mexican Spanish"
4,Bulgaria,Bulgarian,269,276,97.463768,Bulgarian,NaN
5,Bulgaria,Arabic,1,276,0.362319,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
6,Canada,Simplified Chinese,26,286,9.090909,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
7,Canada,French,14,286,4.895105,French,"Old French, Cajun French, Louisiana Creole French"
8,Chile,Spanish,469,493,95.131846,Latin American Spanish,"Spanish, Mexican Spanish"
9,Chile,Spanish (Spain),20,493,4.056795,Spanish,NaN
10,China,Simplified Chinese,1988,2009,98.954704,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
11,China,Traditional Chinese,7,2009,0.348432,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese..."
12,Colombia,Spanish,122,237,51.476793,Latin American Spanish,"Spanish, Mexican Spanish"
13,Colombia,Spanish (Spain),113,237,47.679325,Spanish,NaN
14,Croatia,Serbian-Croatian-Bosnian,526,528,99.621212,Serbian-Croatian-Bosnian,NaN
15,Croatia,German,1,528,0.189394,German,"Moselle Franconian, Plautdietsch, Pennsylvania..."
16,Curacao,Dutch,180,235,76.595745,Dutch,Western Flemish
17,Curacao,German,1,235,0.425532,German,"Moselle Franconian, Plautdietsch, Pennsylvania..."
18,Denmark,Danish,148,233,63.519313,Danish,NaN
19,Denmark,Icelandic,34,233,14.592275,Icelandic,Old Norse
20,Egypt,Arabic,817,824,99.150485,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
21,Finland,Finnish,260,289,89.965398,Finnish,Estonian
22,Finland,Swedish,7,289,2.422145,Swedish,NaN
23,France,French,257,363,70.798898,French,"Old French, Cajun French, Louisiana Creole French"
24,France,Arabic,24,363,6.611570,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
25,Georgia,Georgian,234,236,99.152542,Georgian,NaN
26,Germany,German,291,567,51.322751,German,"Moselle Franconian, Plautdietsch, Pennsylvania..."
27,Germany,Arabic,123,567,21.693122,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
28,Ghana,Simplified Chinese,1,328,0.304878,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
29,Greece,Greek,227,253,89.723320,Greek,NaN
30,Greece,Serbian-Croatian-Bosnian,8,253,3.162055,Serbian-Croatian-Bosnian,NaN
31,Hong Kong (S.A.R),Traditional Chinese,139,228,60.964912,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese..."
32,Hong Kong (S.A.R),Simplified Chinese,55,228,24.122807,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
33,Hungary,Hungarian,256,464,55.172414,Hungarian,NaN
34,Hungary,Arabic,13,464,2.801724,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
35,Iceland,Icelandic,348,354,98.305085,Icelandic,Old Norse
36,India,Marathi,56,243,23.045267,Marathi,NaN
37,India,Hindi,31,243,12.757202,Hindi,"Hindustani, Caribbean Hindustani"
38,Indonesia,Indonesian,648,656,98.780488,Indonesian,"Standard Malay, Central Malay, Baba Malay"
39,Indonesia,Dutch,2,656,0.304878,Dutch,Western Flemish
40,Iran,Persian,187,195,95.897436,Persian,NaN
41,Iran,French,1,195,0.512821,French,"Old French, Cajun French, Louisiana Creole French"
42,Ireland,Serbian-Croatian-Bosnian,3,362,0.828729,Serbian-Croatian-Bosnian,NaN
43,Ireland,Polish,2,362,0.552486,Polish,NaN
44,Israel,Hebrew,151,211,71.563981,Hebrew,Ancient Hebrew
45,Israel,Russian,7,211,3.317536,Russian,Belarusian
46,Italy,Italian,426,466,91.416309,Italian,Sicilian
47,Italy,Simplified Chinese,7,466,1.502146,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
48,Japan,Japanese,1288,1352,95.266272,Japanese,Middle Chinese
49,Japan,Simplified Chinese,22,1352,1.627219,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
50,Jordan,Arabic,233,236,98.728814,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
51,Jordan,Danish,1,236,0.423729,Danish,NaN
52,Kazakhstan,Russian,279,291,95.876289,Russian,Belarusian
53,Kazakhstan,Kazakh,4,291,1.374570,Kazakh,NaN
54,Malaysia,Malay,155,214,72.429907,Standard Malay,"Central Malay, Baba Malay, Malayo"
55,Malaysia,Indonesian,3,214,1.401869,Indonesian,"Standard Malay, Central Malay, Baba Malay"
56,Malta,Maltese,284,1290,22.015504,NaN,"Arabic, Italian"
57,Malta,Italian,4,1290,0.310078,Italian,Sicilian
58,Mongolia,Russian,13,208,6.250000,Russian,Belarusian
59,Mongolia,Korean,2,208,0.961538,Korean,NaN
60,Netherlands,Dutch,524,1348,38.872404,Dutch,Western Flemish
61,Netherlands,Arabic,144,1348,10.682493,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
62,New Zealand,Simplified Chinese,102,262,38.931298,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
63,New Zealand,Danish,2,262,0.763359,Danish,NaN
64,Pakistan,French,2,557,0.359066,French,"Old French, Cajun French, Louisiana Creole French"
65,Peru,Spanish (Spain),215,357,60.224090,Spanish,NaN
66,Peru,Spanish,128,357,35.854342,Latin American Spanish,"Spanish, Mexican Spanish"
67,Russia,Russian,577,586,98.464164,Russian,Belarusian
68,Russia,Arabic,1,586,0.170648,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
69,Serbia,Serbian-Croatian-Bosnian,352,354,99.435028,Serbian-Croatian-Bosnian,NaN
70,Serbia,Danish,1,354,0.282486,Danish,NaN
71,Singapore,Simplified Chinese,8,208,3.846154,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
72,Singapore,Danish,3,208,1.442308,Danish,NaN
73,South Africa,Afrikaans,112,426,26.291080,Afrikaans,Dutch
74,South Africa,French,7,426,1.643192,French,"Old French, Cajun French, Louisiana Creole French"
75,Spain,Catalan,187,418,44.736842,NaN,"Spanish, French"
76,Spain,Spanish (Spain),105,418,25.119617,Spanish,NaN
77,Sweden,Swedish,400,529,75.614367,Swedish,NaN
78,Sweden,Arabic,23,529,4.347826,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
79,Syria,Arabic,247,248,99.596774,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
80,Syria,Serbian-Croatian-Bosnian,1,248,0.403226,Serbian-Croatian-Bosnian,NaN
81,Taiwan,Traditional Chinese (Taiwan),747,761,98.160315,Mandarin Chinese,"Min Nan Chinese, Hakka Chinese"
82,Taiwan,Simplified Chinese,4,761,0.525624,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
83,Trinidad and Tobago,Spanish,1,334,0.299401,Latin American Spanish,"Spanish, Mexican Spanish"
84,Turkey,Turkish,253,346,73.121387,Turkish,Turkmen
85,Turkey,Arabic,77,346,22.254335,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
86,Ukraine,Ukrainian,657,698,94.126074,Ukrainian,NaN
87,Ukraine,Russian,34,698,4.871060,Russian,Belarusian
88,United Kingdom (UK),Simplified Chinese,34,662,5.135952,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
89,United Kingdom (UK),Hungarian,24,662,3.625378,Hungarian,NaN
90,United States of America (USA),Simplified Chinese,45,952,4.726891,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
91,United States of America (USA),Traditional Chinese (Taiwan),28,952,2.941176,Mandarin Chinese,"Min Nan Chinese, Hakka Chinese"
92,Vietnam,Vietnamese,292,338,86.390533,Vietnamese,Nung (Viet Nam)
93,Vietnam,Danish,3,338,0.887574,Danish,NaN

In [672]:
# simplest way to get the table right is to just tweak it in excel and load it back in
selection.to_csv(Path("~/Projects/hypocognition/data/processed/MAX_outline_selection.csv").expanduser())

In [673]:
selection = pd.read_csv(Path("~/Projects/hypocognition/data/processed/MAX_selection_in_bila.csv").expanduser(), index_col=0).reset_index(drop=True)
selection

,countryname,Language_Name,lang_responses,total_responses,percent,bila_language_name_mapping,possible_alternative_bila_language_name_mappings,Selected
0,Australia,Simplified Chinese,181,378,47.883598,Mandarin Chinese,"Beijing Mandarin, Wu Chinese",1
1,Brazil,Brazilian Portuguese,306,325,94.153846,Brazilian Portuguese,Portuguese,1
2,Bulgaria,Bulgarian,269,276,97.463768,Bulgarian,NaN,1
3,Canada,Simplified Chinese,26,286,9.090909,Mandarin Chinese,"Beijing Mandarin, Wu Chinese",1
4,Chile,Spanish,469,493,95.131846,Latin American Spanish,"Spanish, Mexican Spanish",1
5,China,Simplified Chinese,1988,2009,98.954704,Mandarin Chinese,"Beijing Mandarin, Wu Chinese",1
6,Colombia,Spanish,122,237,51.476793,Latin American Spanish,"Spanish, Mexican Spanish",1
7,Croatia,Serbian-Croatian-Bosnian,524,528,99.242424,Serbian-Croatian-Bosnian,NaN,1
8,Curacao,Dutch,180,235,76.595745,Dutch,Western Flemish,1
9,Denmark,Danish,148,233,63.519313,Danish,NaN,1
10,Egypt,Arabic,817,824,99.150485,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar...",1
11,Finland,Finnish,260,289,89.965398,Finnish,Estonian,1
12,France,French,257,363,70.798898,French,"Old French, Cajun French, Louisiana Creole French",1
13,Georgia,Georgian,234,236,99.152542,Georgian,NaN,1
14,Germany,German,291,567,51.322751,German,"Moselle Franconian, Plautdietsch, Pennsylvania...",1
15,Ghana,Simplified Chinese,1,328,0.304878,Mandarin Chinese,"Beijing Mandarin, Wu Chinese",1
16,Greece,Greek,227,253,89.723320,Greek,NaN,1
17,Hong Kong (S.A.R),Traditional Chinese,139,228,60.964912,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese...",1
18,Hungary,Hungarian,256,464,55.172414,Hungarian,NaN,1
19,Iceland,Icelandic,348,354,98.305085,Icelandic,Old Norse,1
20,India,Marathi,56,243,23.045267,Marathi,NaN,1
21,Indonesia,Indonesian,648,656,98.780488,Indonesian,"Standard Malay, Central Malay, Baba Malay",1
22,Iran,Persian,187,195,95.897436,Persian,NaN,1
23,Ireland,Serbian-Croatian-Bosnian,3,362,0.828729,Serbian-Croatian-Bosnian,NaN,1
24,Israel,Hebrew,151,211,71.563981,Hebrew,Ancient Hebrew,1
25,Italy,Italian,426,466,91.416309,Italian,Sicilian,1
26,Japan,Japanese,1288,1352,95.266272,Japanese,Middle Chinese,1
27,Jordan,Arabic,233,236,98.728814,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar...",1
28,Kazakhstan,Russian,279,291,95.876289,Russian,Belarusian,1
29,Malaysia,Malay,155,214,72.429907,Standard Malay,"Central Malay, Baba Malay, Malayo",1
30,Malta,Maltese,284,1290,22.015504,NaN,"Arabic, Italian",1
31,Mongolia,Russian,13,208,6.250000,Russian,Belarusian,1
32,Netherlands,Dutch,524,1348,38.872404,Dutch,Western Flemish,1
33,New Zealand,Simplified Chinese,102,262,38.931298,Mandarin Chinese,"Beijing Mandarin, Wu Chinese",1
34,Pakistan,French,2,557,0.359066,French,"Old French, Cajun French, Louisiana Creole French",1
35,Peru,Spanish (Spain),215,357,60.224090,Spanish,NaN,1
36,Russia,Russian,577,586,98.464164,Russian,Belarusian,1
37,Serbia,Serbian-Croatian-Bosnian,351,354,99.152542,Serbian-Croatian-Bosnian,NaN,1
38,Singapore,Simplified Chinese,8,208,3.846154,Mandarin Chinese,"Beijing Mandarin, Wu Chinese",1
39,South Africa,Afrikaans,112,426,26.291080,Afrikaans,Dutch,1
40,Spain,Spanish (Spain),126,418,30.143541,Spanish,NaN,1
41,Sweden,Swedish,400,529,75.614367,Swedish,NaN,1
42,Syria,Arabic,247,248,99.596774,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar...",1
43,Taiwan,Traditional Chinese (Taiwan),747,761,98.160315,Mandarin Chinese,"Min Nan Chinese, Hakka Chinese",1
44,Trinidad and Tobago,Spanish,1,334,0.299401,Latin American Spanish,"Spanish, Mexican Spanish",1
45,Turkey,Turkish,253,346,73.121387,Turkish,Turkmen,1
46,Ukraine,Ukrainian,657,698,94.126074,Ukrainian,NaN,1
47,United Kingdom (UK),Simplified Chinese,34,662,5.135952,Mandarin Chinese,"Beijing Mandarin, Wu Chinese",1
48,United States of America (USA),Simplified Chinese,45,952,4.726891,Mandarin Chinese,"Beijing Mandarin, Wu Chinese",1
49,Vietnam,Vietnamese,292,338,86.390533,Vietnamese,Nung (Viet Nam),1

In [674]:
# Lets filter the dataset using our new selection
filtered = Covid51countries.merge(
    selection,
    on=['countryname', 'Language_Name'],
    how='inner'
)
filtered

,country,countryname,StartDate,EndDate,Status,Progress,Duration,Finished,RecordedDate,home,...,longstring,na_count,Code,Language_Name,lang_responses,total_responses,percent,bila_language_name_mapping,possible_alternative_bila_language_name_mappings,Selected
0,10,Australia,04/05/2020 19:34,04/05/2020 19:40,0.0,100.0,337.0,1.0,04/05/2020 19:40,8.0,...,3,0,ZH-S,Simplified Chinese,181,378,47.883598,Mandarin Chinese,"Beijing Mandarin, Wu Chinese",1
1,10,Australia,04/05/2020 20:26,04/05/2020 20:35,0.0,100.0,530.0,1.0,04/05/2020 20:35,9.0,...,3,0,ZH-S,Simplified Chinese,181,378,47.883598,Mandarin Chinese,"Beijing Mandarin, Wu Chinese",1
2,10,Australia,05/05/2020 21:54,05/05/2020 22:07,0.0,100.0,793.0,1.0,05/05/2020 22:07,29.0,...,5,0,ZH-S,Simplified Chinese,181,378,47.883598,Mandarin Chinese,"Beijing Mandarin, Wu Chinese",1
3,10,Australia,04/05/2020 20:29,04/05/2020 20:34,0.0,100.0,285.0,1.0,04/05/2020 20:34,73.0,...,4,0,ZH-S,Simplified Chinese,181,378,47.883598,Mandarin Chinese,"Beijing Mandarin, Wu Chinese",1
4,10,Australia,19/04/2020 20:21,19/04/2020 20:27,0.0,100.0,367.0,1.0,19/04/2020 20:27,100.0,...,3,0,ZH-S,Simplified Chinese,181,378,47.883598,Mandarin Chinese,"Beijing Mandarin, Wu Chinese",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15436,91,Kazakhstan,25/04/2020 13:36,25/04/2020 13:44,0.0,100.0,470.0,1.0,25/04/2020 13:44,100.0,...,3,0,RU,Russian,279,291,95.876289,Russian,Belarusian,1
15437,91,Kazakhstan,06/05/2020 04:03,06/05/2020 04:18,0.0,100.0,884.0,1.0,06/05/2020 04:18,100.0,...,3,0,RU,Russian,279,291,95.876289,Russian,Belarusian,1
15438,91,Kazakhstan,06/05/2020 12:32,06/05/2020 12:41,0.0,100.0,573.0,1.0,06/05/2020 12:41,100.0,...,4,0,RU,Russian,279,291,95.876289,Russian,Belarusian,1
15439,91,Kazakhstan,06/05/2020 10:37,06/05/2020 10:49,0.0,100.0,701.0,1.0,06/05/2020 10:49,100.0,...,5,0,RU,Russian,279,291,95.876289,Russian,Belarusian,1
15440,91,Kazakhstan,06/05/2020 11:19,06/05/2020 11:32,0.0,100.0,776.0,1.0,06/05/2020 11:32,100.0,...,2,0,RU,Russian,279,291,95.876289,Russian,Belarusian,1

In [675]:
# only use selected countries
filtered = filtered[filtered["Selected"]==1]

In [676]:
# Check to make sure it worked
filtered.groupby('countryname')['Language_Name'].unique()

countryname
Australia                                   [Simplified Chinese]
Brazil                                    [Brazilian Portuguese]
Bulgaria                                             [Bulgarian]
Canada                                      [Simplified Chinese]
Chile                                                  [Spanish]
China                                       [Simplified Chinese]
Colombia                                               [Spanish]
Croatia                               [Serbian-Croatian-Bosnian]
Curacao                                                  [Dutch]
Denmark                                                 [Danish]
Egypt                                                   [Arabic]
Finland                                                [Finnish]
France                                                  [French]
Georgia                                               [Georgian]
Germany                                                 [German]
Ghana                                       [Simplified Chinese]
Greece                                                   [Greek]
Hong Kong (S.A.R)                          [Traditional Chinese]
Hungary                                              [Hungarian]
Iceland                                              [Icelandic]
India                                                  [Marathi]
Indonesia                                           [Indonesian]
Iran                                                   [Persian]
Ireland                               [Serbian-Croatian-Bosnian]
Israel                                                  [Hebrew]
Italy                                                  [Italian]
Japan                                                 [Japanese]
Jordan                                                  [Arabic]
Kazakhstan                                             [Russian]
Malaysia                                                 [Malay]
Malta                                                  [Maltese]
Mongolia                                               [Russian]
Netherlands                                              [Dutch]
New Zealand                                 [Simplified Chinese]
Pakistan                                                [French]
Peru                                           [Spanish (Spain)]
Russia                                                 [Russian]
Serbia                                [Serbian-Croatian-Bosnian]
Singapore                                   [Simplified Chinese]
South Africa                                         [Afrikaans]
Spain                                          [Spanish (Spain)]
Sweden                                                 [Swedish]
Syria                                                   [Arabic]
Taiwan                            [Traditional Chinese (Taiwan)]
Trinidad and Tobago                                    [Spanish]
Turkey                                                 [Turkish]
Ukraine                                              [Ukrainian]
United Kingdom (UK)                         [Simplified Chinese]
United States of America (USA)              [Simplified Chinese]
Vietnam                                             [Vietnamese]
Name: Language_Name, dtype: object

In [677]:
filtered.groupby('countryname')['bila_language_name_mapping'].unique()

countryname
Australia                                 [Mandarin Chinese]
Brazil                                [Brazilian Portuguese]
Bulgaria                                         [Bulgarian]
Canada                                    [Mandarin Chinese]
Chile                               [Latin American Spanish]
China                                     [Mandarin Chinese]
Colombia                            [Latin American Spanish]
Croatia                           [Serbian-Croatian-Bosnian]
Curacao                                              [Dutch]
Denmark                                             [Danish]
Egypt                                               [Arabic]
Finland                                            [Finnish]
France                                              [French]
Georgia                                           [Georgian]
Germany                                             [German]
Ghana                                     [Mandarin Chinese]
Greece                                               [Greek]
Hong Kong (S.A.R)                         [Mandarin Chinese]
Hungary                                          [Hungarian]
Iceland                                          [Icelandic]
India                                              [Marathi]
Indonesia                                       [Indonesian]
Iran                                               [Persian]
Ireland                           [Serbian-Croatian-Bosnian]
Israel                                              [Hebrew]
Italy                                              [Italian]
Japan                                             [Japanese]
Jordan                                              [Arabic]
Kazakhstan                                         [Russian]
Malaysia                                    [Standard Malay]
Malta                                                  [nan]
Mongolia                                           [Russian]
Netherlands                                          [Dutch]
New Zealand                               [Mandarin Chinese]
Pakistan                                            [French]
Peru                                               [Spanish]
Russia                                             [Russian]
Serbia                            [Serbian-Croatian-Bosnian]
Singapore                                 [Mandarin Chinese]
South Africa                                     [Afrikaans]
Spain                                              [Spanish]
Sweden                                             [Swedish]
Syria                                               [Arabic]
Taiwan                                    [Mandarin Chinese]
Trinidad and Tobago                 [Latin American Spanish]
Turkey                                             [Turkish]
Ukraine                                          [Ukrainian]
United Kingdom (UK)                       [Mandarin Chinese]
United States of America (USA)            [Mandarin Chinese]
Vietnam                                         [Vietnamese]
Name: bila_language_name_mapping, dtype: object

Goals
* For each distinct language, what is the lexical ellaboration for each of the 20 emotions?
* For each distinct language, is there any statistical significance in the distribution of the results of any particular emotion?

In [679]:
# drop the rest of the ~75 columns
filtered = filtered[['countryname', 'countryname', 'Language_Name', 'bila_language_name_mapping','admiration', 'calm', 'compassion',
       'determination', 'moved', 'gratitude', 'hope', 'love', 'relief',
       'pleasure', 'anger', 'anxiety', 'boredom', 'confusion', 'disgust',
       'fear', 'frustration', 'loneliness', 'regret', 'sadness']].copy()

emotions = ['admiration', 'calm', 'compassion',
       'determination', 'moved', 'gratitude', 'hope', 'love', 'relief',
       'pleasure', 'anger', 'anxiety', 'boredom', 'confusion', 'disgust',
       'fear', 'frustration', 'loneliness', 'regret', 'sadness']

In [680]:
# get the dataset of the dictionaries. We will look at how elaborated each of the twenty emotions are in each of the 39 languages
bila_nouns_full = pd.read_csv(Path("~/Projects/hypocognition/data/raw/bila_long_noun_lemmatized_full.csv").expanduser(), index_col=0)
bila_nouns_full

/tmp/ipykernel_2912789/268126284.py:2: DtypeWarning:

Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,estimate,regression_elaboration,dictsize_data,simple_elaboration,log_count
0,chi.14718491,ability,2.0,2.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.725128,-1.424169,10499,0.000190,1.098612
1,chi.14718491,accomplice,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-0.156552,10499,0.000000,0.000000
2,chi.14718491,account,14.0,9.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-7.520776,-2.250524,10499,0.000857,2.302585
3,chi.14718491,acre,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-0.444142,10499,0.000000,0.000000
4,chi.14718491,act,15.0,6.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,0.000000,0.000000,10499,0.000571,1.945910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5282195,wu.89119131142,prouds,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282196,wu.89119131142,facilitator,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282197,wu.89119131142,teacher-librarian,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282198,wu.89119131142,pandani,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282199,wu.89119131142,seat-bone,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000

In [681]:
with open(Path("~/Projects/hypocognition/data/external/stopwords.txt").expanduser()) as f:
    words = [line.strip() for line in f if line.strip()]

In [682]:
# remove stop words
bila_nouns_full = bila_nouns_full[~bila_nouns_full["word"].isin(words)]
bila_nouns_full

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,estimate,regression_elaboration,dictsize_data,simple_elaboration,log_count
0,chi.14718491,ability,2.0,2.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.725128,-1.424169,10499,0.000190,1.098612
1,chi.14718491,accomplice,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-0.156552,10499,0.000000,0.000000
2,chi.14718491,account,14.0,9.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-7.520776,-2.250524,10499,0.000857,2.302585
3,chi.14718491,acre,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-0.444142,10499,0.000000,0.000000
6,chi.14718491,actor,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-1.633890,10499,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5282195,wu.89119131142,prouds,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282196,wu.89119131142,facilitator,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282197,wu.89119131142,teacher-librarian,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282198,wu.89119131142,pandani,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282199,wu.89119131142,seat-bone,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000

In [683]:
tot_words = bila_nouns_full.groupby('id')['word'].nunique().reset_index(name='Total_words_in_dict')
tot_counts = bila_nouns_full.groupby('id')['count'].sum().reset_index(name='Total_counts_in_dict')

In [684]:
# I think we will needs these later
dictionary_means = (
    bila_nouns_full
        .groupby('id', as_index=False)['count']
        .mean()
        .rename(columns={'count': 'dictionary_count_mean'})
)

In [685]:
# filter just the emotions
bila_nouns_full_emotions = bila_nouns_full[bila_nouns_full['word'].isin(emotions)].reset_index(drop=True)
bila_nouns_full_emotions

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,estimate,regression_elaboration,dictsize_data,simple_elaboration,log_count
0,chi.14718491,fear,8.0,9.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-7.520776,-1.337584,10499,0.000857,2.302585
1,chi.14718491,pleasure,5.0,5.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.031819,-1.571145,10499,0.000476,1.791759
2,chi.14718491,regret,5.0,2.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.725128,-0.486657,10499,0.000190,1.098612
3,chi.14718491,admiration,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-0.710507,10499,0.000000,0.000000
4,chi.14718491,anger,5.0,2.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.725128,-2.335062,10499,0.000190,1.098612
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11083,wu.89119131142,disgust,3.0,16.0,Herero,here1253,1989.0,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,-7.795743,3.869782,33359,0.000480,2.833213
11084,wu.89119131142,frustration,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-10.629344,-0.596842,33359,0.000000,0.000000
11085,wu.89119131142,loneliness,3.0,4.0,Herero,here1253,1989.0,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,-9.019809,1.825273,33359,0.000120,1.609438
11086,wu.89119131142,relief,11.0,10.0,Herero,here1253,1989.0,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,-8.231207,0.866433,33359,0.000300,2.397895
11087,wu.89119131142,boredom,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-10.629344,-0.597769,33359,0.000000,0.000000

the dataset is missing two of the survey emotions, {'calm', 'moved'}

In [686]:
filtered.columns

Index(['countryname', 'countryname', 'Language_Name',
       'bila_language_name_mapping', 'admiration', 'calm', 'compassion',
       'determination', 'moved', 'gratitude', 'hope', 'love', 'relief',
       'pleasure', 'anger', 'anxiety', 'boredom', 'confusion', 'disgust',
       'fear', 'frustration', 'loneliness', 'regret', 'sadness'],
      dtype='object')

In [687]:
# already filtered out everything but the 20 emotions
# now we want to filter evrything but the 39 languages
# Where are lang_name and Language_Names the Same?
emotions_in_survey_languages_in_bila = bila_nouns_full_emotions[bila_nouns_full_emotions['langname'].isin(filtered['bila_language_name_mapping'].unique())].reset_index(drop=True)
emotions_in_survey_languages_in_bila

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,estimate,regression_elaboration,dictsize_data,simple_elaboration,log_count
0,coo.31924067983704,fear,8.0,126.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-6.924086,1.952545,121674,0.001036,4.844187
1,coo.31924067983704,pleasure,5.0,107.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-7.086289,3.153327,121674,0.000879,4.682131
2,coo.31924067983704,regret,5.0,41.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-8.031261,2.670962,121674,0.000337,3.737670
3,coo.31924067983704,admiration,3.0,10.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-9.371276,-0.854986,121674,0.000082,2.397895
4,coo.31924067983704,anger,5.0,85.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-7.314243,0.579516,121674,0.000699,4.454347
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,uva.x004877953,disgust,3.0,13.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-9.940215,-4.505457,282895,0.000046,2.639057
500,uva.x004877953,frustration,3.0,6.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-10.633387,-1.588076,282895,0.000021,1.945910
501,uva.x004877953,loneliness,3.0,7.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-10.499852,-1.873436,282895,0.000025,2.079442
502,uva.x004877953,relief,11.0,89.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-8.079201,3.907437,282895,0.000315,4.499810
503,uva.x004877953,boredom,1.0,6.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-10.633387,-1.590590,282895,0.000021,1.945910

In [688]:
filtered_mapped = filtered.loc[:, ~filtered.columns.duplicated()]

In [689]:
filtered

,countryname,countryname,Language_Name,bila_language_name_mapping,admiration,calm,compassion,determination,moved,gratitude,...,anger,anxiety,boredom,confusion,disgust,fear,frustration,loneliness,regret,sadness
0,Australia,Australia,Simplified Chinese,Mandarin Chinese,5.0,3.0,3.0,5.0,4.0,4.0,...,3.0,1.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0
1,Australia,Australia,Simplified Chinese,Mandarin Chinese,2.0,3.0,3.0,0.0,4.0,2.0,...,2.0,2.0,3.0,1.0,3.0,3.0,1.0,1.0,2.0,2.0
2,Australia,Australia,Simplified Chinese,Mandarin Chinese,3.0,3.0,0.0,0.0,0.0,3.0,...,1.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
3,Australia,Australia,Simplified Chinese,Mandarin Chinese,6.0,1.0,4.0,4.0,4.0,4.0,...,4.0,6.0,6.0,4.0,4.0,4.0,3.0,6.0,1.0,2.0
4,Australia,Australia,Simplified Chinese,Mandarin Chinese,0.0,6.0,6.0,6.0,2.0,0.0,...,3.0,5.0,4.0,5.0,2.0,4.0,2.0,1.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15436,Kazakhstan,Kazakhstan,Russian,Russian,1.0,3.0,3.0,1.0,5.0,5.0,...,4.0,2.0,3.0,2.0,2.0,3.0,2.0,3.0,3.0,2.0
15437,Kazakhstan,Kazakhstan,Russian,Russian,3.0,3.0,6.0,2.0,6.0,5.0,...,4.0,4.0,4.0,0.0,1.0,5.0,2.0,2.0,6.0,5.0
15438,Kazakhstan,Kazakhstan,Russian,Russian,3.0,3.0,3.0,3.0,4.0,4.0,...,3.0,2.0,0.0,3.0,3.0,2.0,5.0,4.0,4.0,3.0
15439,Kazakhstan,Kazakhstan,Russian,Russian,2.0,3.0,6.0,2.0,2.0,1.0,...,4.0,4.0,3.0,3.0,3.0,3.0,3.0,1.0,6.0,4.0
15440,Kazakhstan,Kazakhstan,Russian,Russian,0.0,1.0,4.0,2.0,1.0,3.0,...,4.0,4.0,0.0,1.0,0.0,4.0,2.0,0.0,6.0,5.0

In [690]:
# fileter just the 50 languages from the survey
bila_nouns_full_emotions_filtered = bila_nouns_full_emotions[bila_nouns_full_emotions['langname'].isin(covid_to_bila_nouns_full_lang_name_mapping['bila_language_name_mapping'].values)].reset_index(drop=True)
bila_nouns_full_emotions_filtered

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,estimate,regression_elaboration,dictsize_data,simple_elaboration,log_count
0,coo.31924067983704,fear,8.0,126.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-6.924086,1.952545,121674,0.001036,4.844187
1,coo.31924067983704,pleasure,5.0,107.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-7.086289,3.153327,121674,0.000879,4.682131
2,coo.31924067983704,regret,5.0,41.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-8.031261,2.670962,121674,0.000337,3.737670
3,coo.31924067983704,admiration,3.0,10.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-9.371276,-0.854986,121674,0.000082,2.397895
4,coo.31924067983704,anger,5.0,85.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-7.314243,0.579516,121674,0.000699,4.454347
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,uva.x004877953,disgust,3.0,13.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-9.940215,-4.505457,282895,0.000046,2.639057
727,uva.x004877953,frustration,3.0,6.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-10.633387,-1.588076,282895,0.000021,1.945910
728,uva.x004877953,loneliness,3.0,7.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-10.499852,-1.873436,282895,0.000025,2.079442
729,uva.x004877953,relief,11.0,89.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-8.079201,3.907437,282895,0.000315,4.499810
730,uva.x004877953,boredom,1.0,6.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-10.633387,-1.590590,282895,0.000021,1.945910

In [691]:

bila_nouns_full_emotions_filtered['langname'].nunique()

42

In [692]:
bila_nouns_full_emotions_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      731 non-null    object
 1   word                    731 non-null    object
 2   nsenses                 731 non-null    float64
 3   count                   731 non-null    float64
 4   langname                731 non-null    object
 5   glottocode              731 non-null    object
 6   year                    731 non-null    float64
 7   title                   731 non-null    object
 8   imprint                 731 non-null    object
 9   author                  731 non-null    object
 10  area                    731 non-null    object
 11  langfamily              731 non-null    object
 12  affiliation             731 non-null    object
 13  longitude               731 non-null    float64
 14  latitude                731 non-null    float64
 15  estimate                731 non-null    float64
 16  regression_elaboration  731 non-null    float64
 17  dictsize_data           731 non-null    int64
 18  simple_elaboration      731 non-null    float64
 19  log_count               731 non-null    float64
dtypes: float64(9), int64(1), object(10)
memory usage: 114.3+ KB

In [693]:
# add the rows of the emotions words which don't appear in each dictionary
bila_emotions = bila_nouns_full_emotions_filtered['word'].unique()
full_index = pd.MultiIndex.from_product(
    [bila_nouns_full_emotions_filtered["id"].unique(), bila_emotions],
    names=["id", "word"]
)

In [694]:

bila_nouns_full_emotions_filtered_full = (
    bila_nouns_full_emotions_filtered
    .set_index(["id", "word"])
    .reindex(full_index)
    .reset_index()
)
num_cols = ["nsenses", "count", "log_count"]
bila_nouns_full_emotions_filtered_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      756 non-null    object
 1   word                    756 non-null    object
 2   nsenses                 731 non-null    float64
 3   count                   731 non-null    float64
 4   langname                731 non-null    object
 5   glottocode              731 non-null    object
 6   year                    731 non-null    float64
 7   title                   731 non-null    object
 8   imprint                 731 non-null    object
 9   author                  731 non-null    object
 10  area                    731 non-null    object
 11  langfamily              731 non-null    object
 12  affiliation             731 non-null    object
 13  longitude               731 non-null    float64
 14  latitude                731 non-null    float64
 15  estimate                731 non-null    float64
 16  regression_elaboration  731 non-null    float64
 17  dictsize_data           731 non-null    float64
 18  simple_elaboration      731 non-null    float64
 19  log_count               731 non-null    float64
dtypes: float64(10), object(10)
memory usage: 118.3+ KB

In [695]:

#set the number columns to 0 where NaN
bila_nouns_full_emotions_filtered_full[num_cols] = bila_nouns_full_emotions_filtered_full[num_cols].fillna(0)
meta_cols = [
    "langname", "glottocode", "year", "title", "imprint", "author",
    "area", "langfamily", "affiliation", "longitude", "latitude"
]
bila_nouns_full_emotions_filtered_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      756 non-null    object
 1   word                    756 non-null    object
 2   nsenses                 756 non-null    float64
 3   count                   756 non-null    float64
 4   langname                731 non-null    object
 5   glottocode              731 non-null    object
 6   year                    731 non-null    float64
 7   title                   731 non-null    object
 8   imprint                 731 non-null    object
 9   author                  731 non-null    object
 10  area                    731 non-null    object
 11  langfamily              731 non-null    object
 12  affiliation             731 non-null    object
 13  longitude               731 non-null    float64
 14  latitude                731 non-null    float64
 15  estimate                731 non-null    float64
 16  regression_elaboration  731 non-null    float64
 17  dictsize_data           731 non-null    float64
 18  simple_elaboration      731 non-null    float64
 19  log_count               756 non-null    float64
dtypes: float64(10), object(10)
memory usage: 118.3+ KB

In [696]:
# fill the those zero rows with dictionary meta -data
bila_nouns_full_emotions_filtered_full[meta_cols] = (
    bila_nouns_full_emotions_filtered_full
    .groupby("id")[meta_cols]
    .transform("first")
)

bila_nouns_full_emotions_filtered_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      756 non-null    object
 1   word                    756 non-null    object
 2   nsenses                 756 non-null    float64
 3   count                   756 non-null    float64
 4   langname                756 non-null    object
 5   glottocode              756 non-null    object
 6   year                    756 non-null    float64
 7   title                   756 non-null    object
 8   imprint                 756 non-null    object
 9   author                  756 non-null    object
 10  area                    756 non-null    object
 11  langfamily              756 non-null    object
 12  affiliation             756 non-null    object
 13  longitude               756 non-null    float64
 14  latitude                756 non-null    float64
 15  estimate                731 non-null    float64
 16  regression_elaboration  731 non-null    float64
 17  dictsize_data           731 non-null    float64
 18  simple_elaboration      731 non-null    float64
 19  log_count               756 non-null    float64
dtypes: float64(10), object(10)
memory usage: 118.3+ KB

In [697]:
elab_per_emotion = bila_nouns_full_emotions_filtered_full[['langname',   'glottocode','word', 'count',  'id', 'year',"simple_elaboration", "regression_elaboration",	"dictsize_data"	]]
elab_per_emotion

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data
0,Turkish,nucl1301,fear,126.0,coo.31924067983704,1991.0,0.001036,1.952545,121674.0
1,Turkish,nucl1301,pleasure,107.0,coo.31924067983704,1991.0,0.000879,3.153327,121674.0
2,Turkish,nucl1301,regret,41.0,coo.31924067983704,1991.0,0.000337,2.670962,121674.0
3,Turkish,nucl1301,admiration,10.0,coo.31924067983704,1991.0,0.000082,-0.854986,121674.0
4,Turkish,nucl1301,anger,85.0,coo.31924067983704,1991.0,0.000699,0.579516,121674.0
...,...,...,...,...,...,...,...,...,...
751,Japanese,nucl1643,disgust,13.0,uva.x004877953,1974.0,0.000046,-4.505457,282895.0
752,Japanese,nucl1643,frustration,6.0,uva.x004877953,1974.0,0.000021,-1.588076,282895.0
753,Japanese,nucl1643,loneliness,7.0,uva.x004877953,1974.0,0.000025,-1.873436,282895.0
754,Japanese,nucl1643,relief,89.0,uva.x004877953,1974.0,0.000315,3.907437,282895.0
755,Japanese,nucl1643,boredom,6.0,uva.x004877953,1974.0,0.000021,-1.590590,282895.0

In [698]:
elab_per_emotion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   langname                756 non-null    object
 1   glottocode              756 non-null    object
 2   word                    756 non-null    object
 3   count                   756 non-null    float64
 4   id                      756 non-null    object
 5   year                    756 non-null    float64
 6   simple_elaboration      731 non-null    float64
 7   regression_elaboration  731 non-null    float64
 8   dictsize_data           731 non-null    float64
dtypes: float64(5), object(4)
memory usage: 53.3+ KB

In [699]:
stats_by_country = (
    filtered_mapped
    .groupby(['countryname', 'bila_language_name_mapping'])[emotions]
    .agg(['mean', 'std'])
)
stats_by_country = pd.DataFrame(stats_by_country)
stats_by_country

                                                          admiration  \
                                                                mean
countryname                    bila_language_name_mapping
Australia                      Mandarin Chinese             3.413408
Brazil                         Brazilian Portuguese         3.540984
Bulgaria                       Bulgarian                    2.498141
Canada                         Mandarin Chinese             3.076923
Chile                          Latin American Spanish       2.867521
China                          Mandarin Chinese             4.365940
Colombia                       Latin American Spanish       3.409836
Croatia                        Serbian-Croatian-Bosnian     2.548571
Curacao                        Dutch                        3.627778
Denmark                        Danish                       2.668919
Egypt                          Arabic                       2.547472
Finland                        Finnish                      2.738462
France                         French                       3.357977
Georgia                        Georgian                     2.523605
Germany                        German                       2.804124
Ghana                          Mandarin Chinese             6.000000
Greece                         Greek                        2.328889
Hong Kong (S.A.R)              Mandarin Chinese             2.669065
Hungary                        Hungarian                    2.679688
Iceland                        Icelandic                    3.469741
India                          Marathi                      3.500000
Indonesia                      Indonesian                   3.201863
Iran                           Persian                      2.347826
Ireland                        Serbian-Croatian-Bosnian     0.666667
Israel                         Hebrew                       1.569536
Italy                          Italian                      2.966981
Japan                          Japanese                     2.602176
Jordan                         Arabic                       3.108225
Kazakhstan                     Russian                      2.438849
Malaysia                       Standard Malay               3.793548
Mongolia                       Russian                      2.461538
Netherlands                    Dutch                        3.325048
New Zealand                    Mandarin Chinese             3.215686
Pakistan                       French                       2.000000
Peru                           Spanish                      3.706161
Russia                         Russian                      2.553043
Serbia                         Serbian-Croatian-Bosnian     2.716332
Singapore                      Mandarin Chinese             3.250000
South Africa                   Afrikaans                    2.946429
Spain                          Spanish                      3.428571
Sweden                         Swedish                      3.300000
Syria                          Arabic                       1.849372
Taiwan                         Mandarin Chinese             3.993307
Trinidad and Tobago            Latin American Spanish       3.000000
Turkey                         Turkish                      2.027888
Ukraine                        Ukrainian                    2.856489
United Kingdom (UK)            Mandarin Chinese             4.088235
United States of America (USA) Mandarin Chinese             3.044444
Vietnam                        Vietnamese                   4.219178

                                                                         calm  \
                                                                std      mean
countryname                    bila_language_name_mapping
Australia                      Mandarin Chinese            1.892338  3.849162
Brazil                         Brazilian Portuguese        1.745047  3.421569
Bulgaria                       Bulgarian                   1.980548  3.334572
Canada                         Mandarin Chinese            2.018377  3.576923
Chile                          Latin American Spanish      1.901080  2.899358
China                          Mandarin Chinese            1.736698  3.914807
Colombia                       Latin American Spanish      1.974022  3.418033
Croatia                        Serbian-Croatian-Bosnian    1.680610  3.336502
Curacao                        Dutch                       1.743401  3.961111
Denmark                        Danish                      1.513605  3.445946
Egypt                          Arabic                      1.886575  3.622222
Finland                        Finnish                     1.547467  3.726923
France                         French                      1.801764  3.746094
Georgia                        Georgian                    1.866354  3.248927
Germany                        German                      1.800225  3.628866
Ghana                          Mandarin Chinese                 NaN  6.000000
Greece                         Greek                       1.887059  3.337778
Hong Kong (S.A.R)              Mandarin Chinese            1.770894  3.064748
Hungary                        Hungarian                   1.925815  3.265625
Iceland                        Icelandic                   1.867297  3.299712
India                          Marathi                     1.768410  3.982143
Indonesia                      Indonesian                  1.577327  3.834365
Iran                           Persian                     1.745782  2.774194
Ireland                        Serbian-Croatian-Bosnian    1.154701  3.000000
Israel                         Hebrew                      1.718565  3.240000
Italy                          Italian                     1.900316  3.327059
Japan                          Japanese                    1.523357  3.559441
Jordan                         Arabic                      1.965235  3.952586
Kazakhstan                     Russian                     1.958468  3.469534
Malaysia                       Standard Malay              1.548761  4.000000
Mongolia                       Russian                     2.221688  3.615385
Netherlands                    Dutch                       1.646279  3.671756
New Zealand                    Mandarin Chinese            1.859562  4.019608
Pakistan                       French                      1.414214  2.500000
Peru                           Spanish                     1.884501  3.693023
Russia                         Russian                     1.774840  3.349565
Serbia                         Serbian-Croatian-Bosnian    1.845246  3.518519
Singapore                      Mandarin Chinese            1.281740  3.375000
South Africa                   Afrikaans                   1.712904  3.642857
Spain                          Spanish                     1.994498  3.428571
Sweden                         Swedish                     1.774224  3.580000
Syria                          Arabic                      1.996402  3.377593
Taiwan                         Mandarin Chinese            1.660520  3.666667
Trinidad and Tobago            Latin American Spanish           NaN  5.000000
Turkey                         Turkish                     1.760460  3.611111
Ukraine                        Ukrainian                   1.644428  3.203957
United Kingdom (UK)            Mandarin Chinese            1.781515  3.970588
United States of America (USA) Mandarin Chinese            1.594815  3.133333
Vietnam                        Vietnamese                  1.746841  4.263699

                                                                     \
                                                                std
countryname                    bila_language_name_mapping
Australia                      Mandarin Chinese            1.609186
Brazil                         Brazilian Portuguese        1.502585
Bulgaria                       Bulgarian                   1.712431
Canada                         Mandarin Chinese            1.447013
Chile                          Latin American Spanish      1.546330
China                          Mandarin Chinese            1.683731
Colombia                       Latin American Spanish      1.419115
Croatia                        Serbian-Croatian-Bosnian    1.487369
Curacao                        Dutch                       1.607816
Denmark                        Danish                      1.531012
Egypt                          Arabic                      1.728264
Finland                        Finnish                     1.380520
France                         French                      1.587322
Georgia                        Georgian                    1.698836
Germany                        German                      1.620895
Ghana                          Mandarin Chinese                 NaN
Greece                         Greek                       1.538681
Hong Kong (S.A.R)              Mandarin Chinese            1.455667
Hungary                        Hungarian                   1.730848
Iceland                        Icelandic                   1.757585
India                          Marathi                     1.700172
Indonesia                      Indonesian                  1.327863
Iran                           Persian                     1.831431
Ireland                        Serbian-Croatian-Bosnian    1.000000
Israel                         Hebrew                      1.407935
Italy                          Italian                     1.516839
Japan                          Japanese                    1.254913
Jordan                         Arabic                      1.807247
Kazakhstan                     Russian                     1.641953
Malaysia                       Standard Malay              1.232672
Mongolia                       Russian                     1.804553
Netherlands                    Dutch                       1.413904
New Zealand                    Mandarin Chinese            1.807467
Pakistan                       French                      2.121320
Peru                           Spanish                     1.503484
Russia                         Russian                     1.524902
Serbia                         Serbian-Croatian-Bosnian    1.578091
Singapore                      Mandarin Chinese            1.187735
South Africa                   Afrikaans                   1.341353
Spain                          Spanish                     1.616365
Sweden                         Swedish                     1.482936
Syria                          Arabic                      2.045971
Taiwan                         Mandarin Chinese            1.549020
Trinidad and Tobago            Latin American Spanish           NaN
Turkey                         Turkish                     1.439191
Ukraine                        Ukrainian                   1.565963
United Kingdom (UK)            Mandarin Chinese            1.336783
United States of America (USA) Mandarin Chinese            1.659682
Vietnam                        Vietnamese                  1.350442

                                                          compassion  \
                                                                mean
countryname                    bila_language_name_mapping
Australia                      Mandarin Chinese             4.055556
Brazil                         Brazilian Portuguese         4.633987
Bulgaria                       Bulgarian                    4.313433
Canada                         Mandarin Chinese             4.153846
Chile                          Latin American Spanish       3.893390
China                          Mandarin Chinese             4.240976
Colombia                       Latin American Spanish       4.024590
Croatia                        Serbian-Croatian-Bosnian     2.916190
Curacao                        Dutch                        4.777778
Denmark                        Danish                       4.067568
Egypt                          Arabic                       4.173006
Finland                        Finnish                      4.042471
France                         French                       3.809339
Georgia                        Georgian                     4.444444
Germany                        German                       4.347079
Ghana                          Mandarin Chinese             6.000000
Greece                         Greek                        3.843049
Hong Kong (S.A.R)              Mandarin Chinese             3.323741
Hungary                        Hungarian                    4.507812
Iceland                        Icelandic                    4.388406
India                          Marathi                      3.946429
Indonesia                      Indonesian                   4.547287
Iran                           Persian                      3.770053
Ireland                        Serbian-Croatian-Bosnian     3.000000
Israel                         Hebrew                       4.013245
Italy                          Italian                      3.613208
Japan                          Japanese                     3.533385
Jordan                         Arabic                       4.359307
Kazakhstan                     Russian                      3.602151
Malaysia                       Standard Malay               4.432258
Mongolia                       Russian                      2.692308
Netherlands                    Dutch                        4.160305
New Zealand                    Mandarin Chinese             3.693069
Pakistan                       French                       3.500000
Peru                           Spanish                      4.483721
Russia                         Russian                      3.557292
Serbia                         Serbian-Croatian-Bosnian     4.308571
Singapore                      Mandarin Chinese             3.625000
South Africa                   Afrikaans                    4.196429
Spain                          Spanish                      3.971154
Sweden                         Swedish                      4.537500
Syria                          Arabic                       3.878543
Taiwan                         Mandarin Chinese             3.722520
Trinidad and Tobago            Latin American Spanish       4.000000
Turkey                         Turkish                      3.956349
Ukraine                        Ukrainian                    3.576220
United Kingdom (UK)            Mandarin Chinese             4.529412
United States of America (USA) Mandarin Chinese             4.222222
Vietnam                        Vietnamese                   3.872852

                                                                     \
                                                                std
countryname                    bila_language_name_mapping
Australia                      Mandarin Chinese            1.780472
Brazil                         Brazilian Portuguese        1.319471
Bulgaria                       Bulgarian                   1.590788
Canada                         Mandarin Chinese            1.689788
Chile                          Latin American Spanish      1.693798
China                          Mandarin Chinese            1.701800
Colombia                       Latin American Spanish      1.678563
Croatia                        Serbian-Croatian-Bosnian    1.657917
Curacao                        Dutch                       1.174951
Denmark                        Danish                      1.450602
Egypt                          Arabic                      1.710858
Finland                        Finnish                     1.350471
France                         French                      1.648458
Georgia                        Georgian                    1.507887
Germany                        German                      1.283778
Ghana                          Mandarin Chinese                 NaN
Greece                         Greek                       1.662391
Hong Kong (S.A.R)              Mandarin Chinese            1.616114
Hungary                        Hungarian                   1.343079
Iceland                        Icelandic                   1.601193
India                          Marathi                     1.633954
Indonesia                      Indonesian                  1.238492
Iran                           Persian                     1.705639
Ireland                        Serbian-Croatian-Bosnian    2.000000
Israel                         Hebrew                      1.316494
Italy                          Italian                     1.729022
Japan                          Japanese                    1.375941
Jordan                         Arabic                      1.718414
Kazakhstan                     Russian                     1.755606
Malaysia                       Standard Malay              1.304435
Mongolia                       Russian                     2.358835
Netherlands                    Dutch                       1.402357
New Zealand                    Mandarin Chinese            1.579510
Pakistan                       French                      2.121320
Peru                           Spanish                     1.500301
Russia                         Russian                     1.654564
Serbia                         Serbian-Croatian-Bosnian    1.464650
Singapore                      Mandarin Chinese            1.685018
South Africa                   Afrikaans                   1.505780
Spain                          Spanish                     1.742984
Sweden                         Swedish                     1.289477
Syria                          Arabic                      1.921589
Taiwan                         Mandarin Chinese            1.628423
Trinidad and Tobago            Latin American Spanish           NaN
Turkey                         Turkish                     1.627111
Ukraine                        Ukrainian                   1.516419
United Kingdom (UK)            Mandarin Chinese            1.461326
United States of America (USA) Mandarin Chinese            1.730592
Vietnam                        Vietnamese                  1.779476

                                                          determination  \
                                                                   mean
countryname                    bila_language_name_mapping
Australia                      Mandarin Chinese                3.887640
Brazil                         Brazilian Portuguese            3.725490
Bulgaria                       Bulgarian                       3.565056
Canada                         Mandarin Chinese                3.615385
Chile                          Latin American Spanish          3.370450
China                          Mandarin Chinese                4.165992
Colombia                       Latin American Spanish          3.818182
Croatia                        Serbian-Croatian-Bosnian        3.516190
Curacao                        Dutch                           4.000000
Denmark                        Danish                          3.351351
Egypt                          Arabic                          3.161090
Finland                        Finnish                         3.532819
France                         French                          3.727626
Georgia                        Georgian                        3.692308
Germany                        German                          3.468966
Ghana                          Mandarin Chinese                6.000000
Greece                         Greek                           3.444934
Hong Kong (S.A.R)              Mandarin Chinese                3.366906
Hungary                        Hungarian                       3.652344
Iceland                        Icelandic                       3.589595
India                          Marathi                         3.660714

In [700]:
stats_by_country.columns = [
    f"{emotion}_{stat}" for emotion, stat in stats_by_country.columns
]
stats_by_country = stats_by_country.reset_index()
stats_by_country

,countryname,bila_language_name_mapping,admiration_mean,admiration_std,calm_mean,calm_std,compassion_mean,compassion_std,determination_mean,determination_std,...,fear_mean,fear_std,frustration_mean,frustration_std,loneliness_mean,loneliness_std,regret_mean,regret_std,sadness_mean,sadness_std
0,Australia,Mandarin Chinese,3.413408,1.892338,3.849162,1.609186,4.055556,1.780472,3.887640,1.604642,...,1.878453,1.631846,1.972067,1.730202,1.900000,1.818895,1.309392,1.473232,1.955556,1.680723
1,Brazil,Brazilian Portuguese,3.540984,1.745047,3.421569,1.502585,4.633987,1.319471,3.725490,1.593986,...,3.603279,1.757500,3.437908,1.941201,2.518033,2.069635,1.934426,1.881951,3.321311,1.833991
2,Bulgaria,Bulgarian,2.498141,1.980548,3.334572,1.712431,4.313433,1.590788,3.565056,1.684113,...,2.561338,1.954938,3.029740,2.089207,2.334572,2.154385,2.929104,2.009018,3.252788,1.930519
3,Canada,Mandarin Chinese,3.076923,2.018377,3.576923,1.447013,4.153846,1.689788,3.615385,1.328967,...,2.500000,1.881489,2.769231,1.795721,2.807692,1.720912,1.884615,1.451259,3.192308,1.720912
4,Chile,Latin American Spanish,2.867521,1.901080,2.899358,1.546330,3.893390,1.693798,3.370450,1.700109,...,3.528785,1.836746,4.119914,1.731608,2.869658,2.067930,2.352564,1.969156,3.799145,1.745670
5,China,Mandarin Chinese,4.365940,1.736698,3.914807,1.683731,4.240976,1.701800,4.165992,1.693406,...,1.809500,1.726083,1.815642,1.763461,1.812437,1.826492,1.477009,1.701083,2.256709,1.848471
6,Colombia,Latin American Spanish,3.409836,1.974022,3.418033,1.419115,4.024590,1.678563,3.818182,1.653280,...,3.024590,1.943258,3.409836,1.897167,2.578512,2.170837,1.721311,1.601973,3.459016,1.916210
7,Croatia,Serbian-Croatian-Bosnian,2.548571,1.680610,3.336502,1.487369,2.916190,1.657917,3.516190,1.441686,...,2.740952,1.825796,3.420952,1.812788,2.682510,1.955690,2.798479,1.710828,2.990494,1.760385
8,Curacao,Dutch,3.627778,1.743401,3.961111,1.607816,4.777778,1.174951,4.000000,1.549914,...,2.477778,1.933115,3.005556,1.877527,1.894444,1.853570,1.350000,1.645970,2.622222,1.906049
9,Denmark,Danish,2.668919,1.513605,3.445946,1.531012,4.067568,1.450602,3.351351,1.483996,...,1.824324,1.610832,3.148649,1.852980,2.277027,2.026427,1.479730,1.655622,1.601351,1.732993
10,Egypt,Arabic,2.547472,1.886575,3.622222,1.728264,4.173006,1.710858,3.161090,1.728845,...,3.556790,1.953694,3.419434,2.007981,3.686275,2.140949,2.710591,2.129295,4.047970,1.806232
11,Finland,Finnish,2.738462,1.547467,3.726923,1.380520,4.042471,1.350471,3.532819,1.327221,...,2.509653,1.600298,3.846154,1.699246,2.776062,1.927978,1.534615,1.570343,2.953668,1.672212
12,France,French,3.357977,1.801764,3.746094,1.587322,3.809339,1.648458,3.727626,1.582292,...,2.155642,1.796018,3.156250,1.829765,1.961089,1.932060,1.582031,1.708430,2.503906,1.874489
13,Georgia,Georgian,2.523605,1.866354,3.248927,1.698836,4.444444,1.507887,3.692308,1.815345,...,2.497854,1.864192,2.965665,1.920539,2.439655,2.131149,2.497854,1.916634,3.277778,1.955453
14,Germany,German,2.804124,1.800225,3.628866,1.620895,4.347079,1.283778,3.468966,1.464955,...,2.323024,1.757384,3.186207,1.856388,2.178694,1.887078,2.037931,1.705459,2.656357,1.749518
15,Ghana,Mandarin Chinese,6.000000,NaN,6.000000,NaN,6.000000,NaN,6.000000,NaN,...,0.000000,NaN,0.000000,NaN,3.000000,NaN,0.000000,NaN,1.000000,NaN
16,Greece,Greek,2.328889,1.887059,3.337778,1.538681,3.843049,1.662391,3.444934,1.682894,...,2.637168,1.939356,3.508850,1.663306,2.537445,2.015901,1.778761,1.836589,3.251101,1.886945
17,Hong Kong (S.A.R),Mandarin Chinese,2.669065,1.770894,3.064748,1.455667,3.323741,1.616114,3.366906,1.489791,...,2.633094,1.765794,2.431655,1.813997,2.345324,1.909975,1.956835,1.785085,2.618705,1.750344
18,Hungary,Hungarian,2.679688,1.925815,3.265625,1.730848,4.507812,1.343079,3.652344,1.698972,...,2.511719,1.823555,3.125000,1.919967,1.863281,2.000211,1.906250,1.723824,2.703125,1.869715
19,Iceland,Icelandic,3.469741,1.867297,3.299712,1.757585,4.388406,1.601193,3.589595,1.611303,...,2.227666,1.861548,2.129683,1.890931,2.465318,2.160303,1.527378,1.776931,2.376437,1.964884
20,India,Marathi,3.500000,1.768410,3.982143,1.700172,3.946429,1.633954,3.660714,1.880781,...,2.053571,1.891797,1.839286,1.961231,1.857143,1.833314,1.254545,1.723672,2.381818,2.022932
21,Indonesia,Indonesian,3.201863,1.577327,3.834365,1.327863,4.547287,1.238492,3.827372,1.301711,...,3.141085,1.749073,2.213292,1.869821,2.545595,1.978368,2.066563,1.647238,2.933333,1.730317
22,Iran,Persian,2.347826,1.745782,2.774194,1.831431,3.770053,1.705639,3.290323,1.601220,...,2.972973,1.929272,3.005405,1.918155,2.940860,2.032638,2.659459,1.999383,3.556150,1.881089
23,Ireland,Serbian-Croatian-Bosnian,0.666667,1.154701,3.000000,1.000000,3.000000,2.000000,3.666667,2.516611,...,4.666667,1.154701,5.333333,1.154701,5.666667,0.577350,4.666667,1.527525,4.333333,2.886751
24,Israel,Hebrew,1.569536,1.718565,3.240000,1.407935,4.013245,1.316494,3.403974,1.493001,...,2.092715,1.733401,3.125828,1.690383,2.026490,1.754792,1.662252,1.616116,2.536424,1.765502
25,Italy,Italian,2.966981,1.900316,3.327059,1.516839,3.613208,1.729022,3.716981,1.558958,...,2.666667,1.799782,3.320000,1.944077,2.535377,1.968709,2.411765,1.928523,3.343529,1.723755
26,Japan,Japanese,2.602176,1.523357,3.559441,1.254913,3.533385,1.375941,2.964258,1.522347,...,2.630148,1.743227,3.111888,1.729330,2.007764,1.817621,1.956522,1.623824,2.601399,1.710028
27,Jordan,Arabic,3.108225,1.965235,3.952586,1.807247,4.359307,1.718414,3.754386,1.846828,...,2.711207,2.012570,3.116379,2.076312,3.304348,2.156230,2.515152,2.218202,3.700000,1.917855
28,Kazakhstan,Russian,2.438849,1.958468,3.469534,1.641953,3.602151,1.755606,3.283154,1.783851,...,2.276978,1.979746,2.602151,2.078356,2.039568,2.156817,2.773381,2.002456,3.028674,1.913386
29,Malaysia,Standard Malay,3.793548,1.548761,4.000000,1.232672,4.432258,1.304435,3.845161,1.372939,...,2.503226,1.785127,2.412903,1.689490,2.296774,2.064462,1.980645,1.672819,2.761290,1.643894
30,Mongolia,Russian,2.461538,2.221688,3.615385,1.804553,2.692308,2.358835,3.384615,2.103111,...,2.615385,2.142369,2.230769,1.690850,0.692308,1.182132,2.923077,2.289889,1.615385,1.804553
31,Netherlands,Dutch,3.325048,1.646279,3.671756,1.413904,4.160305,1.402357,3.553435,1.404380,...,2.408397,1.663121,3.574427,1.658224,2.335878,1.853572,1.402672,1.482876,2.869981,1.738211
32,New Zealand,Mandarin Chinese,3.215686,1.859562,4.019608,1.807467,3.693069,1.579510,3.485149,1.797854,...,1.686275,1.740493,1.831683,1.887164,1.852941,2.065257,1.150000,1.578741,1.500000,1.602906
33,Pakistan,French,2.000000,1.414214,2.500000,2.121320,3.500000,2.121320,4.000000,0.000000,...,3.000000,1.414214,4.500000,2.121320,4.500000,0.707107,5.000000,0.000000,4.500000,0.707107
34,Peru,Spanish,3.706161,1.884501,3.693023,1.503484,4.483721,1.500301,3.939252,1.457070,...,2.868545,1.827875,3.181395,1.988196,1.604651,1.720404,1.469767,1.617015,3.065116,1.768214
35,Russia,Russian,2.553043,1.774840,3.349565,1.524902,3.557292,1.654564,3.057292,1.579824,...,2.394415,1.771404,2.713542,1.983293,2.157986,2.033897,2.841739,1.816781,3.288194,1.748619
36,Serbia,Serbian-Croatian-Bosnian,2.716332,1.845246,3.518519,1.578091,4.308571,1.464650,3.792023,1.578261,...,2.428977,1.784888,2.749288,1.953705,2.205128,2.008006,2.965714,1.929702,2.988636,1.816319
37,Singapore,Mandarin Chinese,3.250000,1.281740,3.375000,1.187735,3.625000,1.685018,2.500000,1.511858,...,1.250000,0.886405,2.625000,0.916125,1.375000,1.505941,1.500000,1.309307,1.500000,1.195229
38,South Africa,Afrikaans,2.946429,1.712904,3.642857,1.341353,4.196429,1.505780,3.696429,1.570214,...,2.883929,1.911301,3.991071,1.579688,2.276786,1.996437,2.098214,1.888609,3.160714,1.872290
39,Spain,Spanish,3.428571,1.994498,3.428571,1.616365,3.971154,1.742984,3.461538,1.773172,...,2.371429,1.771880,3.228571,1.912797,1.971429,2.011779,1.428571,1.663275,3.066667,1.733531
40,Sweden,Swedish,3.300000,1.774224,3.580000,1.482936,4.537500,1.289477,3.675000,1.374445,...,2.315000,1.693501,3.170000,1.835626,2.140000,1.990050,1.355890,1.523240,2.680000,1.773546
41,Syria,Arabic,1.849372,1.996402,3.377593,2.045971,3.878543,1.921589,2.888889,2.168520,...,2.122449,2.012590,2.275720,2.142184,2.325103,2.281181,1.636364,1.955946,2.799180,2.200972
42,Taiwan,Mandarin Chinese,3.993307,1.660520,3.666667,1.549020,3.722520,1.628423,3.695710,1.540472,...,1.990617,1.625689,1.842035,1.638740,1.605087,1.640841,1.215818,1.466518,1.962416,1.652201
43,Trinidad and Tobago,Latin American Spanish,3.000000,NaN,5.000000,NaN,4.000000,NaN,4.000000,NaN,...,1.000000,NaN,4.000000,NaN,1.000000,NaN,3.000000,NaN,3.000000,NaN
44,Turkey,Turkish,2.027888,1.760460,3.611111,1.439191,3.956349,1.627111,3.804781,1.561325,...,2.948617,1.892269,2.881423,1.976491,2.494071,2.042447,1.768000,1.788567,3.575397,1.681357
45,Ukraine,Ukrainian,2.856489,1.644428,3.203957,1.565963,3.576220,1.516419,3.260274,1.528436,...,2.393293,1.827914,2.936073,1.930703,2.181402,1.950304,2.705793,1.814369,3.169466,1.849121
46,United Kingdom (UK),Mandarin Chinese,4.088235,1.781515,3.970588,1.336783,4.529412,1.461326,3.147059,1.653872,...,2.264706,1.675290,3.088235,1.975113,2.382353,2.296436,2.676471,1.934074,3.088235,1.621216
47,United States of America (USA),Mandarin Chinese,3.044444,1.594815,3.133333,1.659682,4.222222,1.730592,3.377778,1.735837,...,2.733333,1.801515,2.933333,2.104109,2.488889,2.095691,1.666667,2.078024,2.666667,1.870829
48,Vietnam,Vietnamese,4.219178,1.746841,4.263699,1.350442,3.872852,1.779476,4.096220,1.507803,...,1.688356,1.687472,2.441781,1.901356,1.859589,1.964674,1.534247,1.709743,2.047945,1.841978

In [701]:
stats_long = (
    stats_by_country
    .set_index(['countryname', 'bila_language_name_mapping'])
    .filter(regex='_(mean|std)$')
    .stack()
    .reset_index()
)

stats_long[['word', 'stat']] = stats_long['level_2'].str.rsplit('_', n=1, expand=True)
stats_long = stats_long.rename(columns={0: 'value'}).drop(columns='level_2')

stats_long = (
    stats_long
    .pivot_table(
        index=['countryname', 'bila_language_name_mapping', 'word'],
        columns='stat',
        values='value'
    )
    .reset_index()
)

In [702]:

merged = elab_per_emotion.merge(
    stats_long,
    left_on=['langname', 'word'],
    right_on=['bila_language_name_mapping', 'word'],
    how='left'
)

merged

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,mean,std
0,Turkish,nucl1301,fear,126.0,coo.31924067983704,1991.0,0.001036,1.952545,121674.0,Turkey,Turkish,2.948617,1.892269
1,Turkish,nucl1301,pleasure,107.0,coo.31924067983704,1991.0,0.000879,3.153327,121674.0,Turkey,Turkish,3.083665,1.643463
2,Turkish,nucl1301,regret,41.0,coo.31924067983704,1991.0,0.000337,2.670962,121674.0,Turkey,Turkish,1.768000,1.788567
3,Turkish,nucl1301,admiration,10.0,coo.31924067983704,1991.0,0.000082,-0.854986,121674.0,Turkey,Turkish,2.027888,1.760460
4,Turkish,nucl1301,anger,85.0,coo.31924067983704,1991.0,0.000699,0.579516,121674.0,Turkey,Turkish,3.460000,1.871473
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111,Japanese,nucl1643,disgust,13.0,uva.x004877953,1974.0,0.000046,-4.505457,282895.0,Japan,Japanese,2.854701,1.747655
1112,Japanese,nucl1643,frustration,6.0,uva.x004877953,1974.0,0.000021,-1.588076,282895.0,Japan,Japanese,3.111888,1.729330
1113,Japanese,nucl1643,loneliness,7.0,uva.x004877953,1974.0,0.000025,-1.873436,282895.0,Japan,Japanese,2.007764,1.817621
1114,Japanese,nucl1643,relief,89.0,uva.x004877953,1974.0,0.000315,3.907437,282895.0,Japan,Japanese,2.403263,1.417428
1115,Japanese,nucl1643,boredom,6.0,uva.x004877953,1974.0,0.000021,-1.590590,282895.0,Japan,Japanese,3.180901,1.939018

In [703]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1116 entries, 0 to 1115
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   langname                    1116 non-null   object
 1   glottocode                  1116 non-null   object
 2   word                        1116 non-null   object
 3   count                       1116 non-null   float64
 4   id                          1116 non-null   object
 5   year                        1116 non-null   float64
 6   simple_elaboration          1091 non-null   float64
 7   regression_elaboration      1091 non-null   float64
 8   dictsize_data               1091 non-null   float64
 9   countryname                 882 non-null    object
 10  bila_language_name_mapping  882 non-null    object
 11  mean                        882 non-null    float64
 12  std                         845 non-null    float64
dtypes: float64(7), object(6)
memory usage: 113.5+ KB

In [704]:
# add the dictionary_count_mean column
merged = merged.merge(
    dictionary_means,
    left_on='id',
    right_on='id',
    how='left'
)
merged

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,mean,std,dictionary_count_mean
0,Turkish,nucl1301,fear,126.0,coo.31924067983704,1991.0,0.001036,1.952545,121674.0,Turkey,Turkish,2.948617,1.892269,14.502265
1,Turkish,nucl1301,pleasure,107.0,coo.31924067983704,1991.0,0.000879,3.153327,121674.0,Turkey,Turkish,3.083665,1.643463,14.502265
2,Turkish,nucl1301,regret,41.0,coo.31924067983704,1991.0,0.000337,2.670962,121674.0,Turkey,Turkish,1.768000,1.788567,14.502265
3,Turkish,nucl1301,admiration,10.0,coo.31924067983704,1991.0,0.000082,-0.854986,121674.0,Turkey,Turkish,2.027888,1.760460,14.502265
4,Turkish,nucl1301,anger,85.0,coo.31924067983704,1991.0,0.000699,0.579516,121674.0,Turkey,Turkish,3.460000,1.871473,14.502265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111,Japanese,nucl1643,disgust,13.0,uva.x004877953,1974.0,0.000046,-4.505457,282895.0,Japan,Japanese,2.854701,1.747655,33.718117
1112,Japanese,nucl1643,frustration,6.0,uva.x004877953,1974.0,0.000021,-1.588076,282895.0,Japan,Japanese,3.111888,1.729330,33.718117
1113,Japanese,nucl1643,loneliness,7.0,uva.x004877953,1974.0,0.000025,-1.873436,282895.0,Japan,Japanese,2.007764,1.817621,33.718117
1114,Japanese,nucl1643,relief,89.0,uva.x004877953,1974.0,0.000315,3.907437,282895.0,Japan,Japanese,2.403263,1.417428,33.718117
1115,Japanese,nucl1643,boredom,6.0,uva.x004877953,1974.0,0.000021,-1.590590,282895.0,Japan,Japanese,3.180901,1.939018,33.718117

In [705]:
merged = merged[merged['countryname'].notna()]

In [706]:
merged.columns

Index(['langname', 'glottocode', 'word', 'count', 'id', 'year',
       'simple_elaboration', 'regression_elaboration', 'dictsize_data',
       'countryname', 'bila_language_name_mapping', 'mean', 'std',
       'dictionary_count_mean'],
      dtype='object')

In [707]:
# clarify the meaning of mean
merged = merged.rename(columns={'mean': "response_mean"})
# Clarify what std we're talking about
merged = merged.rename(columns={'std': "response_std"})
# drop a bunch of columns

merged = merged[['langname', 'glottocode', 'word', 'count', 'id', 'year',
       'simple_elaboration', 'regression_elaboration', 'dictsize_data',
       'countryname', 'bila_language_name_mapping', 'response_mean',
       'response_std', 'dictionary_count_mean' ]]
merged = merged.sort_values(by=["langname", 'word'])
merged

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,response_mean,response_std,dictionary_count_mean
471,Afrikaans,afri1274,admiration,6.0,mdp.39015054154474,1999.0,0.000028,-3.291632,212992.0,South Africa,Afrikaans,2.946429,1.712904,25.386412
472,Afrikaans,afri1274,anger,55.0,mdp.39015054154474,1999.0,0.000258,-6.741147,212992.0,South Africa,Afrikaans,2.785714,1.803043,25.386412
475,Afrikaans,afri1274,anxiety,30.0,mdp.39015054154474,1999.0,0.000141,-2.655449,212992.0,South Africa,Afrikaans,3.535714,1.765171,25.386412
485,Afrikaans,afri1274,boredom,5.0,mdp.39015054154474,1999.0,0.000023,-1.176312,212992.0,South Africa,Afrikaans,2.241071,1.889971,25.386412
473,Afrikaans,afri1274,compassion,15.0,mdp.39015054154474,1999.0,0.000070,-2.918472,212992.0,South Africa,Afrikaans,4.196429,1.505780,25.386412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
654,Vietnamese,viet1252,love,308.0,uc1.31210024487306,2003.0,0.001143,-1.138291,269366.0,Vietnam,Vietnamese,4.786942,1.311475,32.105602
649,Vietnamese,viet1252,pleasure,216.0,uc1.31210024487306,2003.0,0.000802,3.511485,269366.0,Vietnam,Vietnamese,2.832192,1.885719,32.105602
650,Vietnamese,viet1252,regret,59.0,uc1.31210024487306,2003.0,0.000219,0.052866,269366.0,Vietnam,Vietnamese,1.534247,1.709743,32.105602
664,Vietnamese,viet1252,relief,74.0,uc1.31210024487306,2003.0,0.000275,2.404758,269366.0,Vietnam,Vietnamese,3.199313,1.720505,32.105602
660,Vietnamese,viet1252,sadness,51.0,uc1.31210024487306,2003.0,0.000189,4.028092,269366.0,Vietnam,Vietnamese,2.047945,1.841978,32.105602

In [708]:
merged = merged.reset_index(drop=True)
merged

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,response_mean,response_std,dictionary_count_mean
0,Afrikaans,afri1274,admiration,6.0,mdp.39015054154474,1999.0,0.000028,-3.291632,212992.0,South Africa,Afrikaans,2.946429,1.712904,25.386412
1,Afrikaans,afri1274,anger,55.0,mdp.39015054154474,1999.0,0.000258,-6.741147,212992.0,South Africa,Afrikaans,2.785714,1.803043,25.386412
2,Afrikaans,afri1274,anxiety,30.0,mdp.39015054154474,1999.0,0.000141,-2.655449,212992.0,South Africa,Afrikaans,3.535714,1.765171,25.386412
3,Afrikaans,afri1274,boredom,5.0,mdp.39015054154474,1999.0,0.000023,-1.176312,212992.0,South Africa,Afrikaans,2.241071,1.889971,25.386412
4,Afrikaans,afri1274,compassion,15.0,mdp.39015054154474,1999.0,0.000070,-2.918472,212992.0,South Africa,Afrikaans,4.196429,1.505780,25.386412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,Vietnamese,viet1252,love,308.0,uc1.31210024487306,2003.0,0.001143,-1.138291,269366.0,Vietnam,Vietnamese,4.786942,1.311475,32.105602
878,Vietnamese,viet1252,pleasure,216.0,uc1.31210024487306,2003.0,0.000802,3.511485,269366.0,Vietnam,Vietnamese,2.832192,1.885719,32.105602
879,Vietnamese,viet1252,regret,59.0,uc1.31210024487306,2003.0,0.000219,0.052866,269366.0,Vietnam,Vietnamese,1.534247,1.709743,32.105602
880,Vietnamese,viet1252,relief,74.0,uc1.31210024487306,2003.0,0.000275,2.404758,269366.0,Vietnam,Vietnamese,3.199313,1.720505,32.105602
881,Vietnamese,viet1252,sadness,51.0,uc1.31210024487306,2003.0,0.000189,4.028092,269366.0,Vietnam,Vietnamese,2.047945,1.841978,32.105602

In [709]:
merged['word'].nunique()

18

In [710]:
merged = merged.sort_values(by=["langname", 'countryname','word'])
merged = merged.reset_index(drop=True)
merged = merged.fillna(0)

In [711]:
merged

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,response_mean,response_std,dictionary_count_mean
0,Afrikaans,afri1274,admiration,6.0,mdp.39015054154474,1999.0,0.000028,-3.291632,212992.0,South Africa,Afrikaans,2.946429,1.712904,25.386412
1,Afrikaans,afri1274,anger,55.0,mdp.39015054154474,1999.0,0.000258,-6.741147,212992.0,South Africa,Afrikaans,2.785714,1.803043,25.386412
2,Afrikaans,afri1274,anxiety,30.0,mdp.39015054154474,1999.0,0.000141,-2.655449,212992.0,South Africa,Afrikaans,3.535714,1.765171,25.386412
3,Afrikaans,afri1274,boredom,5.0,mdp.39015054154474,1999.0,0.000023,-1.176312,212992.0,South Africa,Afrikaans,2.241071,1.889971,25.386412
4,Afrikaans,afri1274,compassion,15.0,mdp.39015054154474,1999.0,0.000070,-2.918472,212992.0,South Africa,Afrikaans,4.196429,1.505780,25.386412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,Vietnamese,viet1252,love,308.0,uc1.31210024487306,2003.0,0.001143,-1.138291,269366.0,Vietnam,Vietnamese,4.786942,1.311475,32.105602
878,Vietnamese,viet1252,pleasure,216.0,uc1.31210024487306,2003.0,0.000802,3.511485,269366.0,Vietnam,Vietnamese,2.832192,1.885719,32.105602
879,Vietnamese,viet1252,regret,59.0,uc1.31210024487306,2003.0,0.000219,0.052866,269366.0,Vietnam,Vietnamese,1.534247,1.709743,32.105602
880,Vietnamese,viet1252,relief,74.0,uc1.31210024487306,2003.0,0.000275,2.404758,269366.0,Vietnam,Vietnamese,3.199313,1.720505,32.105602
881,Vietnamese,viet1252,sadness,51.0,uc1.31210024487306,2003.0,0.000189,4.028092,269366.0,Vietnam,Vietnamese,2.047945,1.841978,32.105602

In [712]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 882 entries, 0 to 881
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   langname                    882 non-null    object
 1   glottocode                  882 non-null    object
 2   word                        882 non-null    object
 3   count                       882 non-null    float64
 4   id                          882 non-null    object
 5   year                        882 non-null    float64
 6   simple_elaboration          882 non-null    float64
 7   regression_elaboration      882 non-null    float64
 8   dictsize_data               882 non-null    float64
 9   countryname                 882 non-null    object
 10  bila_language_name_mapping  882 non-null    object
 11  response_mean               882 non-null    float64
 12  response_std                882 non-null    float64
 13  dictionary_count_mean       882 non-null    float64
dtypes: float64(8), object(6)
memory usage: 96.6+ KB

In [713]:
merged.to_csv(Path("~/Projects/hypocognition/data/processed/MAX_covid_bila_merge.csv").expanduser())

"Moving forward, could you create a table with the following columns (broken down into the 36 samples):
* The sample country
* The language
* The correlation between the log count and the response means
* The correlation between the log count and the response SDs
* The correlation between the log count and the absolute distance of the response means from the scale midpoint

In [714]:
merged['response_mean'].mean()

np.float64(3.0243984976459872)

In [715]:

# log count (add 1 to avoid log(0) just in case)
merged2 = merged.copy()
merged2["log_count"] = np.log(merged2["count"] + 1)

def corr_within_group(df, x, y):
    return df[x].corr(df[y])

countries = merged2['countryname'].unique().tolist()

for c in countries:
    df = merged2[merged2['countryname']==c]
    print(c,df['log_count'].corr(df['response_mean']), df['log_count'].corr(df['response_std']))

South Africa 0.09148865168961892 -0.12653514046747824
Egypt -0.11433067618319566 0.13329119935570388
Jordan -0.22730182023960746 0.22199851220158942
Syria 0.08928912107744537 -0.29449735181619413
Brazil 0.1624355100367705 -0.09586451876984464
Bulgaria 0.2914576122549996 -0.510940348557617
Denmark -0.3228657980051242 -0.19173518683367818
Curacao -0.22717185923377653 -0.01279205981994988
Netherlands -0.22757861410314467 -0.30170812809299574
Finland 0.0720360849933431 -0.29966805278456204
France -0.12485678545510513 0.16444273794734743
Pakistan 0.15151736280403277 0.16453879766845736
Georgia -0.09763318852656655 0.08255505707391594
Germany 0.17814793850857474 -0.09156428792952183
Greece 0.155470088914526 -0.2718482113675404
Israel -0.19576632870638763 0.22289222905270406
Hungary 0.27087397624337056 -0.3665163766184561
Iceland 0.13037213359602945 -0.3824791026602647
Indonesia -0.01639818458273091 -0.10834449797267735
Italy -0.02900174620842426 -0.3471079511701444
Japan 0.0804512593809085 -0.4519920306637275
Chile 0.3714361444880193 -0.362342851851946
Colombia 0.23656129683889426 -0.17526128345848155
Trinidad and Tobago -0.11375442905461723 nan
Australia 0.16409225986275572 -0.05047382146015632
Canada -0.053858673079066485 0.04828292352265023
China 0.19149418297264034 -0.4047439145055948
Ghana -0.16692425371482827 nan
Hong Kong (S.A.R) 0.11720350313316244 -0.37759598035115294
New Zealand 0.15374600482006429 -0.25211976351828347
Singapore 0.08374671097135508 -0.10298398758317759
Taiwan 0.23941839478073407 -0.3061637790253629
United Kingdom (UK) 0.15175790499801153 -0.42469243040977406
United States of America (USA) 0.04065752923180417 -0.3032431768160892
India 0.05353987345805218 -0.04789252552447254
Iran -0.04999927688577651 -0.052835803463284245
Kazakhstan -0.08288509303617991 0.24975091174620737
Mongolia 0.041567947168032 0.35749803984623213
Russia -0.07352418265199077 0.1308098406054469
Croatia -0.35970582690093206 -0.04146254069844667
Ireland 0.16053956339287956 0.15205753784389725
Serbia -0.2632673390900342 -0.008868140874677674
Peru 0.07703882461051899 0.06639217967192046
Spain 0.013714915843157453 -0.008543709773476073
Malaysia 0.1651937808983266 -0.28022368490738875
Sweden -0.06578773149503762 -0.21453055017820025
Turkey 0.28189768382983316 -0.32792732052609985
Ukraine 0.15457774093530283 0.016344073727504627
Vietnam 0.07716127645995545 -0.4397485234107762

/data/home/asher.katz/miniconda3/envs/hypenv/lib/python3.11/site-packages/numpy/lib/_function_base_impl.py:3023: RuntimeWarning:

invalid value encountered in divide

/data/home/asher.katz/miniconda3/envs/hypenv/lib/python3.11/site-packages/numpy/lib/_function_base_impl.py:3024: RuntimeWarning:

invalid value encountered in divide

In [716]:
import numpy as np

merged2 = merged.copy()

# log count
merged2["log_count"] = np.log(merged2["count"] + 1)

# absolute distance from midpoint
SCALE_MIDPOINT = merged2["response_mean"].mean()
merged2["abs_dist_midpoint"] = (
    merged2["response_mean"] - SCALE_MIDPOINT
).abs()

result = (
    merged2
    .groupby(["countryname", "langname", "id"])
    .agg(
        corr_logcount_response_mean=(
            "log_count",
            lambda x: x.corr(
                merged2.loc[x.index, "response_mean"]
            )
        ),
        corr_logcount_response_sd=(
            "log_count",
            lambda x: x.corr(
                merged2.loc[x.index, "response_std"]
            )
        ),
        corr_logcount_abs_dist_midpoint=(
            "log_count",
            lambda x: x.corr(
                merged2.loc[x.index, "abs_dist_midpoint"]
            )
        ),

    )
    .reset_index()
)

/data/home/asher.katz/miniconda3/envs/hypenv/lib/python3.11/site-packages/numpy/lib/_function_base_impl.py:3023: RuntimeWarning:

invalid value encountered in divide

/data/home/asher.katz/miniconda3/envs/hypenv/lib/python3.11/site-packages/numpy/lib/_function_base_impl.py:3024: RuntimeWarning:

invalid value encountered in divide

In [717]:
result

,countryname,langname,id,corr_logcount_response_mean,corr_logcount_response_sd,corr_logcount_abs_dist_midpoint
0,Australia,Mandarin Chinese,uc1.l0088545033,0.164092,-0.050474,-0.048882
1,Brazil,Brazilian Portuguese,txu.059173018640743,0.162436,-0.095865,0.060401
2,Bulgaria,Bulgarian,mdp.39015058560494,0.291458,-0.510940,0.258392
3,Canada,Mandarin Chinese,uc1.l0088545033,-0.053859,0.048283,0.283395
4,Chile,Latin American Spanish,mdp.39015050181174,0.371436,-0.362343,0.228992
5,China,Mandarin Chinese,uc1.l0088545033,0.191494,-0.404744,0.108853
6,Colombia,Latin American Spanish,mdp.39015050181174,0.236561,-0.175261,-0.137389
7,Croatia,Serbian-Croatian-Bosnian,mdp.39015012891506,-0.359706,-0.041463,-0.236971
8,Curacao,Dutch,uc1.31822004083036,-0.227172,-0.012792,-0.209647
9,Denmark,Danish,uc1.b3832576,-0.322866,-0.191735,0.323448
10,Egypt,Arabic,mdp.39015043036436,-0.114331,0.133291,-0.345568
11,Finland,Finnish,mdp.39015059174667,0.072036,-0.299668,-0.090114
12,France,French,mdp.39015066787105,-0.124857,0.164443,-0.175255
13,Georgia,Georgian,uva.x001957729,-0.097633,0.082555,0.153933
14,Germany,German,uc1.31822005249149,0.178148,-0.091564,0.027423
15,Ghana,Mandarin Chinese,uc1.l0088545033,-0.166924,NaN,0.392466
16,Greece,Greek,uc1.32106014581794,0.155470,-0.271848,0.090105
17,Hong Kong (S.A.R),Mandarin Chinese,uc1.l0088545033,0.117204,-0.377596,0.114414
18,Hungary,Hungarian,miun.aee0517.0001.001,0.270874,-0.366516,0.240183
19,Iceland,Icelandic,uc1.32106020063118,0.130372,-0.382479,0.240505
20,India,Marathi,mdp.39015055371309,0.053540,-0.047893,-0.092863
21,Indonesia,Indonesian,uc1.31822029604741,-0.016398,-0.108344,-0.186381
22,Iran,Persian,mdp.49015002913532,-0.049999,-0.052836,-0.065651
23,Ireland,Serbian-Croatian-Bosnian,mdp.39015012891506,0.160540,0.152058,-0.205678
24,Israel,Hebrew,uva.x004242694,-0.195766,0.222892,0.160723
25,Italy,Italian,mdp.39015042010226,-0.029002,-0.347108,0.231931
26,Japan,Japanese,uva.x004877953,0.080451,-0.451992,0.211355
27,Jordan,Arabic,mdp.39015043036436,-0.227302,0.221999,-0.189304
28,Kazakhstan,Russian,mdp.39015046500511,-0.082885,0.249751,-0.046167
29,Malaysia,Standard Malay,mdp.39015022909470,0.165194,-0.280224,0.229773
30,Mongolia,Russian,mdp.39015046500511,0.041568,0.357498,-0.266254
31,Netherlands,Dutch,uc1.31822004083036,-0.227579,-0.301708,-0.161399
32,New Zealand,Mandarin Chinese,uc1.l0088545033,0.153746,-0.252120,0.014888
33,Pakistan,French,mdp.39015066787105,0.151517,0.164539,-0.163210
34,Peru,Spanish,umn.31951d01452389x,0.077039,0.066392,-0.103178
35,Russia,Russian,mdp.39015046500511,-0.073524,0.130810,0.155982
36,Serbia,Serbian-Croatian-Bosnian,mdp.39015012891506,-0.263267,-0.008868,-0.370769
37,Singapore,Mandarin Chinese,uc1.l0088545033,0.083747,-0.102984,0.141356
38,South Africa,Afrikaans,mdp.39015054154474,0.091489,-0.126535,-0.065644
39,Spain,Spanish,umn.31951d01452389x,0.013715,-0.008544,-0.035789
40,Sweden,Swedish,mdp.39015052442327,-0.065788,-0.214531,0.092416
41,Syria,Arabic,mdp.39015043036436,0.089289,-0.294497,-0.134365
42,Taiwan,Mandarin Chinese,uc1.l0088545033,0.239418,-0.306164,-0.028000
43,Trinidad and Tobago,Latin American Spanish,mdp.39015050181174,-0.113754,NaN,0.053983
44,Turkey,Turkish,coo.31924067983704,0.281898,-0.327927,0.001340
45,Ukraine,Ukrainian,uc1.l0070891726,0.154578,0.016344,0.231206
46,United Kingdom (UK),Mandarin Chinese,uc1.l0088545033,0.151758,-0.424692,0.273416
47,United States of America (USA),Mandarin Chinese,uc1.l0088545033,0.040658,-0.303243,0.358334
48,Vietnam,Vietnamese,uc1.31210024487306,0.077161,-0.439749,0.140203

In [718]:
result.to_csv(Path("~/Projects/hypocognition/data/processed/MAX_corr_covid_bila.csv").expanduser())