In [926]:
# load libraries 
import pandas as pd
import numpy as np
import re
import math
import plotly.graph_objects as go
import plotly.express as px
from pathlib import Path

In [927]:
# get the SUN covid study dataset
Covid51countries = pd.read_csv(Path("~/Projects/hypocognition/data/raw/Covid51countries.csv").expanduser())
Covid51countries

,country,countryname,StartDate,EndDate,Status,Progress,Duration,Finished,RecordedDate,home,...,gender,ladder,employment,losejob,covidsymptom,language,datasource,ISO3,longstring,na_count
0,10,Australia,04/05/2020 19:34,04/05/2020 19:40,0.0,100.0,337.0,1.0,04/05/2020 19:40,8.0,...,1.0,5.0,4,NaN,0.0,ZH-S,snowball,AUS,3,0
1,10,Australia,04/05/2020 20:26,04/05/2020 20:35,0.0,100.0,530.0,1.0,04/05/2020 20:35,9.0,...,2.0,7.0,3,NaN,NaN,ZH-S,snowball,AUS,3,0
2,10,Australia,05/05/2020 21:54,05/05/2020 22:07,0.0,100.0,793.0,1.0,05/05/2020 22:07,29.0,...,1.0,4.0,1,NaN,0.0,ZH-S,snowball,AUS,5,0
3,10,Australia,04/05/2020 20:29,04/05/2020 20:34,0.0,100.0,285.0,1.0,04/05/2020 20:34,73.0,...,2.0,5.0,4,NaN,0.0,ZH-S,snowball,AUS,4,0
4,10,Australia,19/04/2020 20:21,19/04/2020 20:27,0.0,100.0,367.0,1.0,19/04/2020 20:27,100.0,...,1.0,5.0,1,NaN,0.0,ZH-S,snowball,AUS,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24216,92,Kenya,25/04/2020 01:25,25/04/2020 02:44,0.0,100.0,4690.0,1.0,25/04/2020 02:44,100.0,...,2.0,4.0,4,NaN,0.0,EN,snowball,KEN,4,0
24217,92,Kenya,24/04/2020 11:06,24/04/2020 11:15,0.0,100.0,556.0,1.0,24/04/2020 11:15,100.0,...,1.0,6.0,5,0.0,0.0,EN,snowball,KEN,2,0
24218,92,Kenya,26/04/2020 10:16,26/04/2020 10:36,0.0,100.0,1218.0,1.0,26/04/2020 10:36,80.0,...,1.0,3.0,4,NaN,0.0,EN,snowball,KEN,3,0
24219,92,Kenya,23/04/2020 03:46,23/04/2020 04:13,0.0,100.0,1641.0,1.0,23/04/2020 04:13,3.0,...,1.0,3.0,4,NaN,0.0,EN,snowball,KEN,3,0
24220,92,Kenya,24/04/2020 00:31,24/04/2020 00:42,0.0,100.0,700.0,1.0,24/04/2020 00:42,50.0,...,2.0,6.0,4,NaN,0.0,EN,snowball,KEN,2,0

In [928]:
Covid51countries.columns

Index(['country', 'countryname', 'StartDate', 'EndDate', 'Status', 'Progress',
       'Duration', 'Finished', 'RecordedDate', 'home', 'gathering', 'distance',
       'hands', 'help_covid', 'donate_covid', 'volunteer_covid', 'help',
       'donate', 'volunteer', 'admiration', 'calm', 'compassion',
       'determination', 'moved', 'gratitude', 'hope', 'love', 'relief',
       'pleasure', 'anger', 'anxiety', 'boredom', 'confusion', 'disgust',
       'fear', 'frustration', 'loneliness', 'regret', 'sadness',
       'ERQ1_rumination', 'ERQ2_reappraisal', 'ERQ3_suppression',
       'ERQ4_socialsharing', 'ERQ5_distraction', 'ERQ6_acceptance', 'support',
       'connected', 'phy_healthy', 'mentally_healthy', 'stressed', 'tired',
       'depressed', 'res_1', 'res_2', 'euda_1', 'euda_2', 'swl', 'sympathy',
       'concerned', 'overwhelmed', 'distressed', 'self_vulnerable',
       'country_vulnerable', 'age', 'education', 'gender', 'ladder',
       'employment', 'losejob', 'covidsymptom', 'language', 'datasource',
       'ISO3', 'longstring', 'na_count'],
      dtype='object')

In [929]:
Covid51countries = Covid51countries[['country', 'countryname', 'language','ISO3', 'admiration', 'calm', 'compassion',
       'determination', 'moved', 'gratitude', 'hope', 'love', 'relief',
       'pleasure', 'anger', 'anxiety', 'boredom', 'confusion', 'disgust',
       'fear', 'frustration', 'loneliness', 'regret', 'sadness']]

In [930]:
# add language names to the df
lang_names = pd.read_csv(Path("~/Projects/hypocognition/data/external/lang_names.csv"))
Covid51countries = Covid51countries.merge(lang_names, left_on="language", right_on="Code", how="left")
Covid51countries

,country,countryname,language,ISO3,admiration,calm,compassion,determination,moved,gratitude,...,boredom,confusion,disgust,fear,frustration,loneliness,regret,sadness,Code,Language_Name
0,10,Australia,ZH-S,AUS,5.0,3.0,3.0,5.0,4.0,4.0,...,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,ZH-S,Simplified Chinese
1,10,Australia,ZH-S,AUS,2.0,3.0,3.0,0.0,4.0,2.0,...,3.0,1.0,3.0,3.0,1.0,1.0,2.0,2.0,ZH-S,Simplified Chinese
2,10,Australia,ZH-S,AUS,3.0,3.0,0.0,0.0,0.0,3.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,ZH-S,Simplified Chinese
3,10,Australia,ZH-S,AUS,6.0,1.0,4.0,4.0,4.0,4.0,...,6.0,4.0,4.0,4.0,3.0,6.0,1.0,2.0,ZH-S,Simplified Chinese
4,10,Australia,ZH-S,AUS,0.0,6.0,6.0,6.0,2.0,0.0,...,4.0,5.0,2.0,4.0,2.0,1.0,0.0,3.0,ZH-S,Simplified Chinese
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24216,92,Kenya,EN,KEN,3.0,5.0,5.0,4.0,6.0,3.0,...,5.0,5.0,6.0,4.0,6.0,6.0,6.0,6.0,EN,English
24217,92,Kenya,EN,KEN,6.0,6.0,0.0,6.0,2.0,2.0,...,6.0,0.0,3.0,6.0,3.0,6.0,5.0,2.0,EN,English
24218,92,Kenya,EN,KEN,2.0,3.0,3.0,5.0,3.0,3.0,...,4.0,4.0,4.0,5.0,5.0,3.0,5.0,4.0,EN,English
24219,92,Kenya,EN,KEN,2.0,2.0,5.0,5.0,5.0,6.0,...,5.0,3.0,5.0,5.0,3.0,6.0,1.0,5.0,EN,English
24220,92,Kenya,EN,KEN,4.0,3.0,6.0,6.0,5.0,6.0,...,0.0,4.0,3.0,6.0,4.0,0.0,1.0,4.0,EN,English

In [931]:
# merge croatian, bosnian and serbian
scb = ["Serbian", "Croatian", "Bosnian"]
Covid51countries = Covid51countries.drop(columns=['language'])
Covid51countries.loc[Covid51countries["Language_Name"].isin(scb), "Language_Name"] = "Serbian-Croatian-Bosnian"

In [932]:
# We want to use on only one language of responses for each country
# Further, that language cannot be English

# Calculate the number of responses for each country
country_response_count = pd.DataFrame(Covid51countries[['countryname', 'ISO3']].value_counts())

#collect the languages which people used to respond from each country
languages_per_country = Covid51countries.groupby('countryname')['Language_Name'].value_counts().reset_index(name="count")

# mereg num resposes to languages people used
languages_per_country = languages_per_country.merge(
    country_response_count,
    on="countryname",
    how="left"
)

# Clean up
languages_per_country = languages_per_country.rename(columns={"count_x": "lang_responses", "count_y": "total_responses"})
languages_per_country["percent"] = languages_per_country["lang_responses"] / languages_per_country["total_responses"] * 100

languages_per_country

,countryname,Language_Name,lang_responses,total_responses,percent
0,Australia,Simplified Chinese,181,378,47.883598
1,Australia,English,156,378,41.269841
2,Australia,Indonesian,12,378,3.174603
3,Australia,Traditional Chinese,10,378,2.645503
4,Australia,Vietnamese,5,378,1.322751
...,...,...,...,...,...
491,Vietnam,Simplified Chinese,2,338,0.591716
492,Vietnam,French,1,338,0.295858
493,Vietnam,Japanese,1,338,0.295858
494,Vietnam,Polish,1,338,0.295858
495,Vietnam,Traditional Chinese (Taiwan),1,338,0.295858

In [933]:
non_eng = languages_per_country[languages_per_country['Language_Name'] != "English"]
non_eng

,countryname,Language_Name,lang_responses,total_responses,percent
0,Australia,Simplified Chinese,181,378,47.883598
2,Australia,Indonesian,12,378,3.174603
3,Australia,Traditional Chinese,10,378,2.645503
4,Australia,Vietnamese,5,378,1.322751
5,Australia,Danish,3,378,0.793651
...,...,...,...,...,...
491,Vietnam,Simplified Chinese,2,338,0.591716
492,Vietnam,French,1,338,0.295858
493,Vietnam,Japanese,1,338,0.295858
494,Vietnam,Polish,1,338,0.295858
495,Vietnam,Traditional Chinese (Taiwan),1,338,0.295858

In [934]:
non_eng[non_eng['Language_Name']=="Dari"]

,countryname,Language_Name,lang_responses,total_responses,percent
308,Netherlands,Dari,3,1348,0.222552
425,Ukraine,Dari,1,698,0.143266
454,United Kingdom (UK),Dari,1,662,0.151057

In [935]:
# gather list of top names
try:
    del top4
except:
    pass
for n in non_eng['countryname'].unique():
    df = non_eng[non_eng['countryname'] == n].reset_index(drop=True)
    try:
        top4 = pd.concat([top4, df.iloc[0:4]], ignore_index=True)
    except:
        top4 = df.iloc[0:4]

top4

,countryname,Language_Name,lang_responses,total_responses,percent
0,Australia,Simplified Chinese,181,378,47.883598
1,Australia,Indonesian,12,378,3.174603
2,Australia,Traditional Chinese,10,378,2.645503
3,Australia,Vietnamese,5,378,1.322751
4,Brazil,Brazilian Portuguese,306,325,94.153846
...,...,...,...,...,...
158,United States of America (USA),Japanese,13,952,1.365546
159,Vietnam,Vietnamese,292,338,86.390533
160,Vietnam,Danish,3,338,0.887574
161,Vietnam,Simplified Chinese,2,338,0.591716
162,Vietnam,French,1,338,0.295858

In [936]:
# we are short the 2*50 rows we'd excpect.
top4['countryname'].value_counts()

countryname
Australia                         4
Brazil                            4
Canada                            4
China                             4
Denmark                           4
Hong Kong (S.A.R)                 4
Germany                           4
Greece                            4
France                            4
Finland                           4
Japan                             4
Malaysia                          4
Israel                            4
Italy                             4
Ireland                           4
Indonesia                         4
India                             4
Hungary                           4
United States of America (USA)    4
Vietnam                           4
Ukraine                           4
Taiwan                            4
Sweden                            4
United Kingdom (UK)               4
Turkey                            4
Russia                            4
Netherlands                       4
New Zealand                       4
Mongolia                          4
Malta                             4
Singapore                         4
South Africa                      4
Spain                             4
Bulgaria                          3
Chile                             3
Peru                              3
Syria                             2
Jordan                            2
Croatia                           2
Colombia                          2
Iran                              2
Curacao                           2
Serbia                            2
Kazakhstan                        2
Egypt                             1
Georgia                           1
Ghana                             1
Iceland                           1
Pakistan                          1
Trinidad and Tobago               1
Name: count, dtype: int64

In [937]:

covid_to_bila_nouns_full_lang_name_mapping = pd.read_csv(Path("~/Projects/hypocognition/data/external/covid_to_full_bila_lang_name_mapping.csv"))
covid_to_bila_nouns_full_lang_name_mapping

,code,study_language_names,bila_language_name_mapping,possible_alternative_bila_language_name_mappings
0,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
1,EN,English,NaN,"Midland American English, Singlish, Devon, Sus..."
2,ID,Indonesian,Indonesian,"Standard Malay, Central Malay, Baba Malay"
3,ZH-T,Traditional Chinese,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese..."
4,VI,Vietnamese,Vietnamese,Nung (Viet Nam)
5,DA,Danish,Danish,NaN
6,AR,Arabic,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
7,ES,Spanish,Latin American Spanish,"Spanish, Mexican Spanish"
8,AFRI,Afrikaans,Afrikaans,Dutch
9,ES-ES,Spanish (Spain),Spanish,NaN
10,ET,Estonian,Estonian,Finnish
11,FR,French,French,"Old French, Cajun French, Louisiana Creole French"
12,JA,Japanese,Japanese,Middle Chinese
13,"HR, SR",Serbian-Croatian-Bosnian,Serbian-Croatian-Bosnian,NaN
14,ZH-TW,Traditional Chinese (Taiwan),Mandarin Chinese,"Min Nan Chinese, Hakka Chinese"
15,PT-BR,Brazilian Portuguese,Brazilian Portuguese,Portuguese
16,PT,Portuguese,Portuguese,Brazilian Portuguese
17,IT,Italian,Italian,Sicilian
18,BG,Bulgarian,Bulgarian,NaN
19,RU,Russian,Russian,Belarusian
20,FA,Persian,Persian,NaN
21,UK,Ukrainian,Ukrainian,NaN
22,NL,Dutch,Dutch,Western Flemish
23,DE,German,German,"Moselle Franconian, Plautdietsch, Pennsylvania..."
24,MS,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo"
25,TR,Turkish,Turkish,Turkmen
26,ISL,Icelandic,Icelandic,Old Norse
27,NO,Norwegian,Norwegian,NaN
28,RO,Romanian,Romanian,Aromanian
29,FI,Finnish,Finnish,Estonian
30,KAT,Georgian,Georgian,NaN
31,SV,Swedish,Swedish,NaN
32,EL,Greek,Greek,NaN
33,CA,Catalan,NaN,"Spanish, French"
34,HU,Hungarian,Hungarian,NaN
35,SL,Slovenian,Slovenian,NaN
36,CS,Czech,Czech,NaN
37,PL,Polish,Polish,NaN
38,SK,Slovak,Slovak,NaN
39,MAR,Marathi,Marathi,NaN
40,HI,Hindi,Hindi,"Hindustani, Caribbean Hindustani"
41,HE,Hebrew,Hebrew,Ancient Hebrew
42,KO,Korean,Korean,NaN
43,KAZ,Kazakh,Kazakh,NaN
44,ML,Malayalam,Malayalam,NaN
45,MALTI,Maltese,NaN,"Arabic, Italian"
46,FILIP,Filipino,Filipino,Tagalog-Pilipino
47,DARI,Dari,Persian,NaN

In [938]:
covid_to_bila_nouns_full_lang_name_mapping['study_language_names'].nunique()

48

In [939]:
map = set(covid_to_bila_nouns_full_lang_name_mapping['bila_language_name_mapping'].unique())
orig = set(covid_to_bila_nouns_full_lang_name_mapping['study_language_names'].unique())

In [940]:
# Add the mapping to our selection table
selection = top4.merge(
    covid_to_bila_nouns_full_lang_name_mapping,
    left_on="Language_Name",
    right_on = "study_language_names",
    how = "left"
).drop(columns=["code", "study_language_names"])
selection

,countryname,Language_Name,lang_responses,total_responses,percent,bila_language_name_mapping,possible_alternative_bila_language_name_mappings
0,Australia,Simplified Chinese,181,378,47.883598,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
1,Australia,Indonesian,12,378,3.174603,Indonesian,"Standard Malay, Central Malay, Baba Malay"
2,Australia,Traditional Chinese,10,378,2.645503,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese..."
3,Australia,Vietnamese,5,378,1.322751,Vietnamese,Nung (Viet Nam)
4,Brazil,Brazilian Portuguese,306,325,94.153846,Brazilian Portuguese,Portuguese
...,...,...,...,...,...,...,...
158,United States of America (USA),Japanese,13,952,1.365546,Japanese,Middle Chinese
159,Vietnam,Vietnamese,292,338,86.390533,Vietnamese,Nung (Viet Nam)
160,Vietnam,Danish,3,338,0.887574,Danish,NaN
161,Vietnam,Simplified Chinese,2,338,0.591716,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
162,Vietnam,French,1,338,0.295858,French,"Old French, Cajun French, Louisiana Creole French"

In [941]:
selection['Language_Name'].nunique()

42

In [942]:
selection['bila_language_name_mapping'].nunique()

37

In [943]:
map - set(selection['bila_language_name_mapping'].unique())

{'Estonian', 'Filipino', 'Norwegian', 'Slovak', 'Slovenian'}

In [944]:
orig - set(selection['Language_Name'].unique())

{'English', 'Estonian', 'Filipino', 'Norwegian', 'Slovak', 'Slovenian'}

In [945]:
# lets look at the results
with pd.option_context('display.max_rows', None):
    display(selection)

,countryname,Language_Name,lang_responses,total_responses,percent,bila_language_name_mapping,possible_alternative_bila_language_name_mappings
0,Australia,Simplified Chinese,181,378,47.883598,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
1,Australia,Indonesian,12,378,3.174603,Indonesian,"Standard Malay, Central Malay, Baba Malay"
2,Australia,Traditional Chinese,10,378,2.645503,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese..."
3,Australia,Vietnamese,5,378,1.322751,Vietnamese,Nung (Viet Nam)
4,Brazil,Brazilian Portuguese,306,325,94.153846,Brazilian Portuguese,Portuguese
5,Brazil,Spanish,7,325,2.153846,Latin American Spanish,"Spanish, Mexican Spanish"
6,Brazil,Danish,2,325,0.615385,Danish,NaN
7,Brazil,Portuguese,2,325,0.615385,Portuguese,Brazilian Portuguese
8,Bulgaria,Bulgarian,269,276,97.463768,Bulgarian,NaN
9,Bulgaria,Arabic,1,276,0.362319,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
10,Bulgaria,Russian,1,276,0.362319,Russian,Belarusian
11,Canada,Simplified Chinese,26,286,9.090909,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
12,Canada,French,14,286,4.895105,French,"Old French, Cajun French, Louisiana Creole French"
13,Canada,Arabic,13,286,4.545455,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
14,Canada,Persian,7,286,2.447552,Persian,NaN
15,Chile,Spanish,469,493,95.131846,Latin American Spanish,"Spanish, Mexican Spanish"
16,Chile,Spanish (Spain),20,493,4.056795,Spanish,NaN
17,Chile,Brazilian Portuguese,1,493,0.202840,Brazilian Portuguese,Portuguese
18,China,Simplified Chinese,1988,2009,98.954704,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
19,China,Traditional Chinese,7,2009,0.348432,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese..."
20,China,Traditional Chinese (Taiwan),2,2009,0.099552,Mandarin Chinese,"Min Nan Chinese, Hakka Chinese"
21,China,Turkish,1,2009,0.049776,Turkish,Turkmen
22,Colombia,Spanish,122,237,51.476793,Latin American Spanish,"Spanish, Mexican Spanish"
23,Colombia,Spanish (Spain),113,237,47.679325,Spanish,NaN
24,Croatia,Serbian-Croatian-Bosnian,526,528,99.621212,Serbian-Croatian-Bosnian,NaN
25,Croatia,German,1,528,0.189394,German,"Moselle Franconian, Plautdietsch, Pennsylvania..."
26,Curacao,Dutch,180,235,76.595745,Dutch,Western Flemish
27,Curacao,German,1,235,0.425532,German,"Moselle Franconian, Plautdietsch, Pennsylvania..."
28,Denmark,Danish,148,233,63.519313,Danish,NaN
29,Denmark,Icelandic,34,233,14.592275,Icelandic,Old Norse
30,Denmark,Arabic,2,233,0.858369,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
31,Denmark,French,2,233,0.858369,French,"Old French, Cajun French, Louisiana Creole French"
32,Egypt,Arabic,817,824,99.150485,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
33,Finland,Finnish,260,289,89.965398,Finnish,Estonian
34,Finland,Swedish,7,289,2.422145,Swedish,NaN
35,Finland,Ukrainian,2,289,0.692042,Ukrainian,NaN
36,Finland,Arabic,1,289,0.346021,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
37,France,French,257,363,70.798898,French,"Old French, Cajun French, Louisiana Creole French"
38,France,Arabic,24,363,6.611570,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
39,France,Danish,8,363,2.203857,Danish,NaN
40,France,Simplified Chinese,5,363,1.377410,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
41,Georgia,Georgian,234,236,99.152542,Georgian,NaN
42,Germany,German,291,567,51.322751,German,"Moselle Franconian, Plautdietsch, Pennsylvania..."
43,Germany,Arabic,123,567,21.693122,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
44,Germany,Serbian-Croatian-Bosnian,14,567,2.469136,Serbian-Croatian-Bosnian,NaN
45,Germany,Simplified Chinese,12,567,2.116402,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
46,Ghana,Simplified Chinese,1,328,0.304878,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
47,Greece,Greek,227,253,89.723320,Greek,NaN
48,Greece,Serbian-Croatian-Bosnian,8,253,3.162055,Serbian-Croatian-Bosnian,NaN
49,Greece,Romanian,2,253,0.790514,Romanian,Aromanian
50,Greece,Arabic,1,253,0.395257,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
51,Hong Kong (S.A.R),Traditional Chinese,139,228,60.964912,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese..."
52,Hong Kong (S.A.R),Simplified Chinese,55,228,24.122807,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
53,Hong Kong (S.A.R),Traditional Chinese (Taiwan),12,228,5.263158,Mandarin Chinese,"Min Nan Chinese, Hakka Chinese"
54,Hong Kong (S.A.R),Danish,1,228,0.438596,Danish,NaN
55,Hungary,Hungarian,256,464,55.172414,Hungarian,NaN
56,Hungary,Arabic,13,464,2.801724,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
57,Hungary,Simplified Chinese,9,464,1.939655,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
58,Hungary,Vietnamese,5,464,1.077586,Vietnamese,Nung (Viet Nam)
59,Iceland,Icelandic,348,354,98.305085,Icelandic,Old Norse
60,India,Marathi,56,243,23.045267,Marathi,NaN
61,India,Hindi,31,243,12.757202,Hindi,"Hindustani, Caribbean Hindustani"
62,India,Danish,2,243,0.823045,Danish,NaN
63,India,Dutch,1,243,0.411523,Dutch,Western Flemish
64,Indonesia,Indonesian,648,656,98.780488,Indonesian,"Standard Malay, Central Malay, Baba Malay"
65,Indonesia,Dutch,2,656,0.304878,Dutch,Western Flemish
66,Indonesia,Danish,1,656,0.152439,Danish,NaN
67,Indonesia,Persian,1,656,0.152439,Persian,NaN
68,Iran,Persian,187,195,95.897436,Persian,NaN
69,Iran,French,1,195,0.512821,French,"Old French, Cajun French, Louisiana Creole French"
70,Ireland,Serbian-Croatian-Bosnian,3,362,0.828729,Serbian-Croatian-Bosnian,NaN
71,Ireland,Polish,2,362,0.552486,Polish,NaN
72,Ireland,Romanian,2,362,0.552486,Romanian,Aromanian
73,Ireland,Russian,2,362,0.552486,Russian,Belarusian
74,Israel,Hebrew,151,211,71.563981,Hebrew,Ancient Hebrew
75,Israel,Russian,7,211,3.317536,Russian,Belarusian
76,Israel,Danish,2,211,0.947867,Danish,NaN
77,Israel,Polish,1,211,0.473934,Polish,NaN
78,Italy,Italian,426,466,91.416309,Italian,Sicilian
79,Italy,Simplified Chinese,7,466,1.502146,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
80,Italy,Arabic,2,466,0.429185,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
81,Italy,Greek,2,466,0.429185,Greek,NaN
82,Japan,Japanese,1288,1352,95.266272,Japanese,Middle Chinese
83,Japan,Simplified Chinese,22,1352,1.627219,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
84,Japan,Indonesian,6,1352,0.443787,Indonesian,"Standard Malay, Central Malay, Baba Malay"
85,Japan,Traditional Chinese (Taiwan),5,1352,0.369822,Mandarin Chinese,"Min Nan Chinese, Hakka Chinese"
86,Jordan,Arabic,233,236,98.728814,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
87,Jordan,Danish,1,236,0.423729,Danish,NaN
88,Kazakhstan,Russian,279,291,95.876289,Russian,Belarusian
89,Kazakhstan,Kazakh,4,291,1.374570,Kazakh,NaN
90,Malaysia,Malay,155,214,72.429907,Standard Malay,"Central Malay, Baba Malay, Malayo"
91,Malaysia,Indonesian,3,214,1.401869,Indonesian,"Standard Malay, Central Malay, Baba Malay"
92,Malaysia,Arabic,1,214,0.467290,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
93,Malaysia,Malayalam,1,214,0.467290,Malayalam,NaN
94,Malta,Maltese,284,1290,22.015504,NaN,"Arabic, Italian"
95,Malta,Italian,4,1290,0.310078,Italian,Sicilian
96,Malta,Greek,3,1290,0.232558,Greek,NaN
97,Malta,Hungarian,3,1290,0.232558,Hungarian,NaN
98,Mongolia,Russian,13,208,6.250000,Russian,Belarusian
99,Mongolia,Korean,2,208,0.961538,Korean,NaN
100,Mongolia,Turkish,2,208,0.961538,Turkish,Turkmen
101,Mongolia,Czech,1,208,0.480769,Czech,NaN
102,Netherlands,Dutch,524,1348,38.872404,Dutch,Western Flemish
103,Netherlands,Arabic,144,1348,10.682493,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
104,Netherlands,Greek,137,1348,10.163205,Greek,NaN
105,Netherlands,Persian,82,1348,6.083086,Persian,NaN
106,New Zealand,Simplified Chinese,102,262,38.931298,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
107,New Zealand,Danish,2,262,0.763359,Danish,NaN
108,New Zealand,Korean,2,262,0.763359,Korean,NaN
109,New Zealand,Traditional Chinese,2,262,0.763359,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese..."
110,Pakistan,French,2,557,0.359066,French,"Old French, Cajun French, Louisiana Creole French"
111,Peru,Spanish (Spain),215,357,60.224090,Spanish,NaN
112,Peru,Spanish,128,357,35.854342,Latin American Spanish,"Spanish, Mexican Spanish"
113,Peru,Italian,1,357,0.280112,Italian,Sicilian
114,Russia,Russian,577,586,98.464164,Russian,Belarusian
115,Russia,Arabic,1,586,0.170648,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
116,Russia,Romanian,1,586,0.170648,Romanian,Aromanian
117,Russia,Spanish (Spain),1,586,0.170648,Spanish,NaN
118,Serbia,Serbian-Croatian-Bosnian,352,354,99.435028,Serbian-Croatian-Bosnian,NaN
119,Serbia,Danish,1,354,0.282486,Danish,NaN
120,Singapore,Simplified Chinese,8,208,3.846154,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
121,Singapore,Danish,3,208,1.442308,Danish,NaN
122,Singapore,Indonesian,2,208,0.961538,Indonesian,"Standard Malay, Central Malay, Baba Malay"
123,Singapore,Malay,2,208,0.961538,Standard Malay,"Central Malay, Baba Malay, Malayo"
124,South Africa,Afrikaans,112,426,26.291080,Afrikaans,Dutch
125,South Africa,French,7,426,1.643192,French,"Old French, Cajun French, Louisiana Creole French"
126,South Africa,Arabic,2,426,0.469484,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
127,South Africa,Bulgarian,1,426,0.234742,Bulgarian,NaN
128,Spain,Catalan,187,418,44.736842,NaN,"Spanish, French"
129,Spain,Spanish (Spain),105,418,25.119617,Spanish,NaN
130,Spain,Simplified Chinese,61,418,14.593301,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
131,Spain,Spanish,21,418,5.023923,Latin American Spanish,"Spanish, Mexican Spanish"
132,Sweden,Swedish,400,529,75.614367,Swedish,NaN
133,Sweden,Arabic,23,529,4.347826,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
134,Sweden,Danish,21,529,3.969754,Danish,NaN
135,Sweden,Dutch,20,529,3.780718,Dutch,Western Flemish
136,Syria,Arabic,247,248,99.596774,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
137,Syria,Serbian-Croatian-Bosnian,1,248,0.403226,Serbian-Croatian-Bosnian,NaN
138,Taiwan,Traditional Chinese (Taiwan),747,761,98.160315,Mandarin Chinese,"Min Nan Chinese, Hakka Chinese"
139,Taiwan,Simplified Chinese,4,761,0.525624,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
140,Taiwan,Traditional Chinese,2,761,0.262812,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese..."
141,Taiwan,Danish,1,761,0.131406,Danish,NaN
142,Trinidad and Tobago,Spanish,1,334,0.299401,Latin American Spanish,"Spanish, Mexican Spanish"
143,Turkey,Turkish,253,346,73.121387,Turkish,Turkmen
144,Turkey,Arabic,77,346,22.254335,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
145,Turkey,Persian,2,346,0.578035,Persian,NaN
146,Turkey,Danish,1,346,0.289017,Danish,NaN
147,Ukraine,Ukrainian,657,698,94.126074,Ukrainian,NaN
148,Ukraine,Russian,34,698,4.871060,Russian,Belarusian
149,Ukraine,Arabic,1,698,0.143266,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
150,Ukraine,Dari,1,698,0.143266,Persian,NaN
151,United Kingdom (UK),Simplified Chinese,34,662,5.135952,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
152,United Kingdom (UK),Hungarian,24,662,3.625378,Hungarian,NaN
153,United Kingdom (UK),Indonesian,20,662,3.021148,Indonesian,"Standard Malay, Central Malay, Baba Malay"
154,United Kingdom (UK),Danish,16,662,2.416918,Danish,NaN
155,United States of America (USA),Simplified Chinese,45,952,4.726891,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
156,United States of America (USA),Traditional Chinese (Taiwan),28,952,2.941176,Mandarin Chinese,"Min Nan Chinese, Hakka Chinese"
157,United States of America (USA),Spanish,15,952,1.575630,Latin American Spanish,"Spanish, Mexican Spanish"
158,United States of America (USA),Japanese,13,952,1.365546,Japanese,Middle Chinese
159,Vietnam,Vietnamese,292,338,86.390533,Vietnamese,Nung (Viet Nam)
160,Vietnam,Danish,3,338,0.887574,Danish,NaN
161,Vietnam,Simplified Chinese,2,338,0.591716,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
162,Vietnam,French,1,338,0.295858,French,"Old French, Cajun French, Louisiana Creole French"

In [946]:
selection['Selected'] = np.nan
selection

,countryname,Language_Name,lang_responses,total_responses,percent,bila_language_name_mapping,possible_alternative_bila_language_name_mappings,Selected
0,Australia,Simplified Chinese,181,378,47.883598,Mandarin Chinese,"Beijing Mandarin, Wu Chinese",NaN
1,Australia,Indonesian,12,378,3.174603,Indonesian,"Standard Malay, Central Malay, Baba Malay",NaN
2,Australia,Traditional Chinese,10,378,2.645503,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese...",NaN
3,Australia,Vietnamese,5,378,1.322751,Vietnamese,Nung (Viet Nam),NaN
4,Brazil,Brazilian Portuguese,306,325,94.153846,Brazilian Portuguese,Portuguese,NaN
...,...,...,...,...,...,...,...,...
158,United States of America (USA),Japanese,13,952,1.365546,Japanese,Middle Chinese,NaN
159,Vietnam,Vietnamese,292,338,86.390533,Vietnamese,Nung (Viet Nam),NaN
160,Vietnam,Danish,3,338,0.887574,Danish,NaN,NaN
161,Vietnam,Simplified Chinese,2,338,0.591716,Mandarin Chinese,"Beijing Mandarin, Wu Chinese",NaN
162,Vietnam,French,1,338,0.295858,French,"Old French, Cajun French, Louisiana Creole French",NaN

In [947]:
# simplest way to get the table right is to just tweak it in excel and load it back in
selection.to_csv(Path("~/Projects/hypocognition/data/processed/outline_selection.csv").expanduser())

In [948]:
selection = pd.read_csv(Path("~/Projects/hypocognition/data/processed/selection_in_bila.csv").expanduser(), index_col=0).reset_index(drop=True)
selection = selection[selection['Selected']==1].rename(columns={'study_language_names':"Language_Name"} )

In [949]:
map - set(selection['bila_language_name_mapping'].unique())

{'Czech',
 'Estonian',
 'Filipino',
 'Hindi',
 'Kazakh',
 'Korean',
 'Malayalam',
 'Norwegian',
 'Polish',
 'Portuguese',
 'Romanian',
 'Slovak',
 'Slovenian'}

In [950]:
selection['bila_language_name_mapping'].nunique()

29

In [951]:
selection['countryname'].nunique()

39

In [952]:
selection['countryname'].unique()

array(['Brazil', 'Bulgaria', 'Chile', 'China', 'Colombia', 'Croatia',
       'Curacao', 'Denmark', 'Egypt', 'Finland', 'France', 'Georgia',
       'Germany', 'Greece', 'Hong Kong (S.A.R)', 'Hungary', 'Iceland',
       'India', 'Indonesia', 'Iran', 'Israel', 'Italy', 'Japan', 'Jordan',
       'Kazakhstan', 'Malaysia', 'Malta', 'Netherlands', 'Peru', 'Russia',
       'Serbia', 'South Africa', 'Spain', 'Sweden', 'Syria', 'Taiwan',
       'Turkey', 'Ukraine', 'Vietnam'], dtype=object)

In [953]:
orig - set(selection['Language_Name'].unique())

{'Catalan',
 'Czech',
 'Dari',
 'English',
 'Estonian',
 'Filipino',
 'Hindi',
 'Kazakh',
 'Korean',
 'Malayalam',
 'Norwegian',
 'Polish',
 'Portuguese',
 'Romanian',
 'Slovak',
 'Slovenian'}

In [954]:
# those are all good exclusions.
# Lets try filtering the dataset using our new selection
filtered = Covid51countries.merge(
    selection,
    on=['countryname', 'Language_Name'],
    how='inner'
)

filtered

,country,countryname,ISO3,admiration,calm,compassion,determination,moved,gratitude,hope,...,Code,Language_Name,language,bila_language_name_mapping,lang_responses,total_responses,percent,Selected,reason,possible_alternative_bila_language_name_mappings
0,109,Malaysia,MYS,1.0,6.0,1.0,0.0,0.0,0.0,6.0,...,MS,Malay,MS,Standard Malay,155,214,72.429907,1,Let's use Malay for Malaysia,"Central Malay, Baba Malay, Malayo"
1,109,Malaysia,MYS,4.0,4.0,2.0,3.0,2.0,3.0,4.0,...,MS,Malay,MS,Standard Malay,155,214,72.429907,1,Let's use Malay for Malaysia,"Central Malay, Baba Malay, Malayo"
2,109,Malaysia,MYS,3.0,3.0,3.0,3.0,3.0,1.0,0.0,...,MS,Malay,MS,Standard Malay,155,214,72.429907,1,Let's use Malay for Malaysia,"Central Malay, Baba Malay, Malayo"
3,109,Malaysia,MYS,6.0,3.0,6.0,4.0,6.0,5.0,6.0,...,MS,Malay,MS,Standard Malay,155,214,72.429907,1,Let's use Malay for Malaysia,"Central Malay, Baba Malay, Malayo"
4,109,Malaysia,MYS,5.0,5.0,5.0,6.0,4.0,6.0,5.0,...,MS,Malay,MS,Standard Malay,155,214,72.429907,1,Let's use Malay for Malaysia,"Central Malay, Baba Malay, Malayo"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15020,91,Kazakhstan,KAZ,1.0,3.0,3.0,1.0,5.0,5.0,3.0,...,RU,Russian,RU,Russian,279,291,95.876289,1,Let's use Russian for Kazakhstan,Belarusian
15021,91,Kazakhstan,KAZ,3.0,3.0,6.0,2.0,6.0,5.0,5.0,...,RU,Russian,RU,Russian,279,291,95.876289,1,Let's use Russian for Kazakhstan,Belarusian
15022,91,Kazakhstan,KAZ,3.0,3.0,3.0,3.0,4.0,4.0,0.0,...,RU,Russian,RU,Russian,279,291,95.876289,1,Let's use Russian for Kazakhstan,Belarusian
15023,91,Kazakhstan,KAZ,2.0,3.0,6.0,2.0,2.0,1.0,6.0,...,RU,Russian,RU,Russian,279,291,95.876289,1,Let's use Russian for Kazakhstan,Belarusian
15024,91,Kazakhstan,KAZ,0.0,1.0,4.0,2.0,1.0,3.0,1.0,...,RU,Russian,RU,Russian,279,291,95.876289,1,Let's use Russian for Kazakhstan,Belarusian

In [955]:
set(selection['Language_Name'].unique())- set(filtered['Language_Name'].unique())

set()

In [956]:
set(selection['bila_language_name_mapping'].unique())- set(filtered['bila_language_name_mapping'].unique())

set()

In [957]:
selection['Language_Name'].nunique()

32

In [958]:
selection['countryname'].nunique()

39

In [959]:
# Check to make sure it worked
filtered.groupby('countryname')['Language_Name'].unique()

countryname
Brazil                       [Brazilian Portuguese]
Bulgaria                                [Bulgarian]
Chile                                     [Spanish]
China                          [Simplified Chinese]
Colombia                                  [Spanish]
Croatia                  [Serbian-Croatian-Bosnian]
Curacao                                     [Dutch]
Denmark                                    [Danish]
Egypt                                      [Arabic]
Finland                                   [Finnish]
France                                     [French]
Georgia                                  [Georgian]
Germany                                    [German]
Greece                                      [Greek]
Hong Kong (S.A.R)             [Traditional Chinese]
Hungary                                 [Hungarian]
Iceland                                 [Icelandic]
India                                     [Marathi]
Indonesia                              [Indonesian]
Iran                                      [Persian]
Israel                                     [Hebrew]
Italy                                     [Italian]
Japan                                    [Japanese]
Jordan                                     [Arabic]
Kazakhstan                                [Russian]
Malaysia                                    [Malay]
Malta                                     [Maltese]
Netherlands                                 [Dutch]
Peru                              [Spanish (Spain)]
Russia                                    [Russian]
Serbia                   [Serbian-Croatian-Bosnian]
South Africa                            [Afrikaans]
Spain                             [Spanish (Spain)]
Sweden                                    [Swedish]
Syria                                      [Arabic]
Taiwan               [Traditional Chinese (Taiwan)]
Turkey                                    [Turkish]
Ukraine                                 [Ukrainian]
Vietnam                                [Vietnamese]
Name: Language_Name, dtype: object

In [960]:
filtered.groupby('countryname')['bila_language_name_mapping'].unique()

countryname
Brazil                   [Brazilian Portuguese]
Bulgaria                            [Bulgarian]
Chile                  [Latin American Spanish]
China                        [Mandarin Chinese]
Colombia               [Latin American Spanish]
Croatia              [Serbian-Croatian-Bosnian]
Curacao                                 [Dutch]
Denmark                                [Danish]
Egypt                                  [Arabic]
Finland                               [Finnish]
France                                 [French]
Georgia                              [Georgian]
Germany                                [German]
Greece                                  [Greek]
Hong Kong (S.A.R)            [Mandarin Chinese]
Hungary                             [Hungarian]
Iceland                             [Icelandic]
India                                 [Marathi]
Indonesia                          [Indonesian]
Iran                                  [Persian]
Israel                                 [Hebrew]
Italy                                 [Italian]
Japan                                [Japanese]
Jordan                                 [Arabic]
Kazakhstan                            [Russian]
Malaysia                       [Standard Malay]
Malta                                     [nan]
Netherlands                             [Dutch]
Peru                                  [Spanish]
Russia                                [Russian]
Serbia               [Serbian-Croatian-Bosnian]
South Africa                        [Afrikaans]
Spain                                 [Spanish]
Sweden                                [Swedish]
Syria                                  [Arabic]
Taiwan                       [Mandarin Chinese]
Turkey                                [Turkish]
Ukraine                             [Ukrainian]
Vietnam                            [Vietnamese]
Name: bila_language_name_mapping, dtype: object

Goals
* For each distinct language, what is the lexical ellaboration for each of the 20 emotions?
* For each distinct language, is there any statistical significance in the distribution of the results of any particular emotion?

In [961]:
emotions = ['admiration', 'calm', 'compassion',
       'determination', 'moved', 'gratitude', 'hope', 'love', 'relief',
       'pleasure', 'anger', 'anxiety', 'boredom', 'confusion', 'disgust',
       'fear', 'frustration', 'loneliness', 'regret', 'sadness']

In [962]:
# get the dataset of the dictionaries. We will look at how elaborated each of the twenty emotions are in each of the 39 languages
bila_nouns_full = pd.read_csv(Path("~/Projects/hypocognition/data/raw/bila_long_noun_lemmatized_full.csv").expanduser(), index_col=0)
bila_nouns_full

/tmp/ipykernel_2834355/268126284.py:2: DtypeWarning:

Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,estimate,regression_elaboration,dictsize_data,simple_elaboration,log_count
0,chi.14718491,ability,2.0,2.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.725128,-1.424169,10499,0.000190,1.098612
1,chi.14718491,accomplice,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-0.156552,10499,0.000000,0.000000
2,chi.14718491,account,14.0,9.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-7.520776,-2.250524,10499,0.000857,2.302585
3,chi.14718491,acre,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-0.444142,10499,0.000000,0.000000
4,chi.14718491,act,15.0,6.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,0.000000,0.000000,10499,0.000571,1.945910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5282195,wu.89119131142,prouds,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282196,wu.89119131142,facilitator,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282197,wu.89119131142,teacher-librarian,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282198,wu.89119131142,pandani,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282199,wu.89119131142,seat-bone,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000

In [963]:
with open(Path("~/Projects/hypocognition/data/external/stopwords.txt").expanduser()) as f:
    words = [line.strip() for line in f if line.strip()]

In [964]:
# remove stop words
bila_nouns_full = bila_nouns_full[~bila_nouns_full["word"].isin(words)]
bila_nouns_full

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,estimate,regression_elaboration,dictsize_data,simple_elaboration,log_count
0,chi.14718491,ability,2.0,2.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.725128,-1.424169,10499,0.000190,1.098612
1,chi.14718491,accomplice,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-0.156552,10499,0.000000,0.000000
2,chi.14718491,account,14.0,9.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-7.520776,-2.250524,10499,0.000857,2.302585
3,chi.14718491,acre,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-0.444142,10499,0.000000,0.000000
6,chi.14718491,actor,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-1.633890,10499,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5282195,wu.89119131142,prouds,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282196,wu.89119131142,facilitator,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282197,wu.89119131142,teacher-librarian,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282198,wu.89119131142,pandani,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282199,wu.89119131142,seat-bone,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000

In [965]:
tot_words = bila_nouns_full.groupby('id')['word'].nunique().reset_index(name='Total_words_in_dict')
tot_counts = bila_nouns_full.groupby('id')['count'].sum().reset_index(name='Total_counts_in_dict')

In [966]:
# I think we will needs these later
dictionary_means = (
    bila_nouns_full
        .groupby('id', as_index=False)['count']
        .mean()
        .rename(columns={'count': 'dictionary_count_mean'})
)

In [967]:
# filter just the emotions
bila_nouns_full_emotions = bila_nouns_full[bila_nouns_full['word'].isin(emotions)].reset_index(drop=True)
bila_nouns_full_emotions

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,estimate,regression_elaboration,dictsize_data,simple_elaboration,log_count
0,chi.14718491,fear,8.0,9.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-7.520776,-1.337584,10499,0.000857,2.302585
1,chi.14718491,pleasure,5.0,5.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.031819,-1.571145,10499,0.000476,1.791759
2,chi.14718491,regret,5.0,2.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.725128,-0.486657,10499,0.000190,1.098612
3,chi.14718491,admiration,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-0.710507,10499,0.000000,0.000000
4,chi.14718491,anger,5.0,2.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.725128,-2.335062,10499,0.000190,1.098612
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11083,wu.89119131142,disgust,3.0,16.0,Herero,here1253,1989.0,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,-7.795743,3.869782,33359,0.000480,2.833213
11084,wu.89119131142,frustration,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-10.629344,-0.596842,33359,0.000000,0.000000
11085,wu.89119131142,loneliness,3.0,4.0,Herero,here1253,1989.0,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,-9.019809,1.825273,33359,0.000120,1.609438
11086,wu.89119131142,relief,11.0,10.0,Herero,here1253,1989.0,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,-8.231207,0.866433,33359,0.000300,2.397895
11087,wu.89119131142,boredom,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-10.629344,-0.597769,33359,0.000000,0.000000

the dataset is missing two of the survey emotions, {'calm', 'moved'}

In [968]:
filtered.columns

Index(['country', 'countryname', 'ISO3', 'admiration', 'calm', 'compassion',
       'determination', 'moved', 'gratitude', 'hope', 'love', 'relief',
       'pleasure', 'anger', 'anxiety', 'boredom', 'confusion', 'disgust',
       'fear', 'frustration', 'loneliness', 'regret', 'sadness', 'Code',
       'Language_Name', 'language', 'bila_language_name_mapping',
       'lang_responses', 'total_responses', 'percent', 'Selected', 'reason',
       'possible_alternative_bila_language_name_mappings'],
      dtype='object')

In [969]:
filtered['bila_language_name_mapping'].nunique()

29

In [970]:
filtered['Language_Name'].nunique()

32

In [971]:
filtered['countryname'].nunique()

39

In [972]:
# already filtered out everything but the 18 emotions
# now we want to filter evrything but the 29 dictionaries
# Where are lang_name and Language_Names the Same?
bila_nouns_full_emotions_filtered = bila_nouns_full_emotions[bila_nouns_full_emotions['langname'].isin(filtered['bila_language_name_mapping'].unique())].reset_index(drop=True)
bila_nouns_full_emotions_filtered

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,estimate,regression_elaboration,dictsize_data,simple_elaboration,log_count
0,coo.31924067983704,fear,8.0,126.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-6.924086,1.952545,121674,0.001036,4.844187
1,coo.31924067983704,pleasure,5.0,107.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-7.086289,3.153327,121674,0.000879,4.682131
2,coo.31924067983704,regret,5.0,41.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-8.031261,2.670962,121674,0.000337,3.737670
3,coo.31924067983704,admiration,3.0,10.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-9.371276,-0.854986,121674,0.000082,2.397895
4,coo.31924067983704,anger,5.0,85.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-7.314243,0.579516,121674,0.000699,4.454347
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,uva.x004877953,disgust,3.0,13.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-9.940215,-4.505457,282895,0.000046,2.639057
500,uva.x004877953,frustration,3.0,6.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-10.633387,-1.588076,282895,0.000021,1.945910
501,uva.x004877953,loneliness,3.0,7.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-10.499852,-1.873436,282895,0.000025,2.079442
502,uva.x004877953,relief,11.0,89.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-8.079201,3.907437,282895,0.000315,4.499810
503,uva.x004877953,boredom,1.0,6.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-10.633387,-1.590590,282895,0.000021,1.945910

In [973]:
print(bila_nouns_full_emotions_filtered['langname'].nunique())

29

In [974]:
filtered = filtered.loc[:, ~filtered.columns.duplicated()]

In [975]:

bila_nouns_full_emotions_filtered['langname'].nunique()

29

In [976]:
word_counts = (
    bila_nouns_full_emotions_filtered
    .groupby("langname")["word"]
    .nunique()
    .reset_index(name="n_unique_words")
)
word_counts

                    langname  n_unique_words
0                  Afrikaans              18
1                     Arabic              18
2       Brazilian Portuguese               8
3                  Bulgarian              17
4                     Danish              18
5                      Dutch              18
6                    Finnish              18
7                     French              18
8                   Georgian              16
9                     German              18
10                     Greek              18
11                    Hebrew              16
12                 Hungarian              17
13                 Icelandic              17
14                Indonesian              18
15                   Italian              18
16                  Japanese              18
17    Latin American Spanish              18
18          Mandarin Chinese              18
19                   Marathi              17
20                   Persian              18
21                   Russian              18
22  Serbian-Croatian-Bosnian              18
23                   Spanish              18
24            Standard Malay              18
25                   Swedish              18
26                   Turkish              18
27                 Ukrainian              18
28                Vietnamese              18

In [977]:
bila_nouns_full_emotions_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 504 entries, 0 to 503
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      504 non-null    object
 1   word                    504 non-null    object
 2   nsenses                 504 non-null    float64
 3   count                   504 non-null    float64
 4   langname                504 non-null    object
 5   glottocode              504 non-null    object
 6   year                    504 non-null    float64
 7   title                   504 non-null    object
 8   imprint                 504 non-null    object
 9   author                  504 non-null    object
 10  area                    504 non-null    object
 11  langfamily              504 non-null    object
 12  affiliation             504 non-null    object
 13  longitude               504 non-null    float64
 14  latitude                504 non-null    float64
 15  estimate                504 non-null    float64
 16  regression_elaboration  504 non-null    float64
 17  dictsize_data           504 non-null    int64
 18  simple_elaboration      504 non-null    float64
 19  log_count               504 non-null    float64
dtypes: float64(9), int64(1), object(10)
memory usage: 78.9+ KB

In [978]:
# add the rows of the emotions words which don't appear in each dictionary

full_index = pd.MultiIndex.from_product(
    [bila_nouns_full_emotions_filtered["id"].unique(), bila_nouns_full_emotions_filtered["word"].unique()],
    names=["id", "word"]
)

In [979]:
# use the full index to add the missing values
bila_nouns_full_emotions_filtered_full = (
    bila_nouns_full_emotions_filtered
    .set_index(["id", "word"])
    .reindex(full_index)
    .reset_index()
)
num_cols = ["nsenses", "count", "log_count", 'regression_elaboration', 'dictsize_data', 'simple_elaboration']
bila_nouns_full_emotions_filtered_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 522 entries, 0 to 521
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      522 non-null    object
 1   word                    522 non-null    object
 2   nsenses                 504 non-null    float64
 3   count                   504 non-null    float64
 4   langname                504 non-null    object
 5   glottocode              504 non-null    object
 6   year                    504 non-null    float64
 7   title                   504 non-null    object
 8   imprint                 504 non-null    object
 9   author                  504 non-null    object
 10  area                    504 non-null    object
 11  langfamily              504 non-null    object
 12  affiliation             504 non-null    object
 13  longitude               504 non-null    float64
 14  latitude                504 non-null    float64
 15  estimate                504 non-null    float64
 16  regression_elaboration  504 non-null    float64
 17  dictsize_data           504 non-null    float64
 18  simple_elaboration      504 non-null    float64
 19  log_count               504 non-null    float64
dtypes: float64(10), object(10)
memory usage: 81.7+ KB

In [980]:

#set the number columns to 0 where NaN
bila_nouns_full_emotions_filtered_full[num_cols] = bila_nouns_full_emotions_filtered_full[num_cols].fillna(0)
meta_cols = [
    "langname", "glottocode", "year", "title", "imprint", "author",
    "area", "langfamily", "affiliation", "longitude", "latitude"
]
bila_nouns_full_emotions_filtered_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 522 entries, 0 to 521
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      522 non-null    object
 1   word                    522 non-null    object
 2   nsenses                 522 non-null    float64
 3   count                   522 non-null    float64
 4   langname                504 non-null    object
 5   glottocode              504 non-null    object
 6   year                    504 non-null    float64
 7   title                   504 non-null    object
 8   imprint                 504 non-null    object
 9   author                  504 non-null    object
 10  area                    504 non-null    object
 11  langfamily              504 non-null    object
 12  affiliation             504 non-null    object
 13  longitude               504 non-null    float64
 14  latitude                504 non-null    float64
 15  estimate                504 non-null    float64
 16  regression_elaboration  522 non-null    float64
 17  dictsize_data           522 non-null    float64
 18  simple_elaboration      522 non-null    float64
 19  log_count               522 non-null    float64
dtypes: float64(10), object(10)
memory usage: 81.7+ KB

In [981]:
# fill the those zero rows with dictionary meta -data
bila_nouns_full_emotions_filtered_full[meta_cols] = (
    bila_nouns_full_emotions_filtered_full
    .groupby("id")[meta_cols]
    .transform("first")
)

bila_nouns_full_emotions_filtered_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 522 entries, 0 to 521
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      522 non-null    object
 1   word                    522 non-null    object
 2   nsenses                 522 non-null    float64
 3   count                   522 non-null    float64
 4   langname                522 non-null    object
 5   glottocode              522 non-null    object
 6   year                    522 non-null    float64
 7   title                   522 non-null    object
 8   imprint                 522 non-null    object
 9   author                  522 non-null    object
 10  area                    522 non-null    object
 11  langfamily              522 non-null    object
 12  affiliation             522 non-null    object
 13  longitude               522 non-null    float64
 14  latitude                522 non-null    float64
 15  estimate                504 non-null    float64
 16  regression_elaboration  522 non-null    float64
 17  dictsize_data           522 non-null    float64
 18  simple_elaboration      522 non-null    float64
 19  log_count               522 non-null    float64
dtypes: float64(10), object(10)
memory usage: 81.7+ KB

In [982]:
# now we're don emaking datasets, this is a table of just the stuff we need for correlations
elab_per_emotion = bila_nouns_full_emotions_filtered_full[['langname',   'glottocode','word', 'count',  'id', 'year',"simple_elaboration", "regression_elaboration",	"dictsize_data"	]]
elab_per_emotion

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data
0,Turkish,nucl1301,fear,126.0,coo.31924067983704,1991.0,0.001036,1.952545,121674.0
1,Turkish,nucl1301,pleasure,107.0,coo.31924067983704,1991.0,0.000879,3.153327,121674.0
2,Turkish,nucl1301,regret,41.0,coo.31924067983704,1991.0,0.000337,2.670962,121674.0
3,Turkish,nucl1301,admiration,10.0,coo.31924067983704,1991.0,0.000082,-0.854986,121674.0
4,Turkish,nucl1301,anger,85.0,coo.31924067983704,1991.0,0.000699,0.579516,121674.0
...,...,...,...,...,...,...,...,...,...
517,Japanese,nucl1643,disgust,13.0,uva.x004877953,1974.0,0.000046,-4.505457,282895.0
518,Japanese,nucl1643,frustration,6.0,uva.x004877953,1974.0,0.000021,-1.588076,282895.0
519,Japanese,nucl1643,loneliness,7.0,uva.x004877953,1974.0,0.000025,-1.873436,282895.0
520,Japanese,nucl1643,relief,89.0,uva.x004877953,1974.0,0.000315,3.907437,282895.0
521,Japanese,nucl1643,boredom,6.0,uva.x004877953,1974.0,0.000021,-1.590590,282895.0

In [983]:
elab_per_emotion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 522 entries, 0 to 521
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   langname                522 non-null    object
 1   glottocode              522 non-null    object
 2   word                    522 non-null    object
 3   count                   522 non-null    float64
 4   id                      522 non-null    object
 5   year                    522 non-null    float64
 6   simple_elaboration      522 non-null    float64
 7   regression_elaboration  522 non-null    float64
 8   dictsize_data           522 non-null    float64
dtypes: float64(5), object(4)
memory usage: 36.8+ KB

In [984]:
# Make table of the 18 languages for each country
stats_by_country = (
    filtered
    .groupby(['countryname', 'bila_language_name_mapping'])[emotions]
    .agg(['mean', 'std'])
)
stats_by_country = pd.DataFrame(stats_by_country)
stats_by_country

                                             admiration                calm  \
                                                   mean       std      mean
countryname       bila_language_name_mapping
Brazil            Brazilian Portuguese         3.540984  1.745047  3.421569
Bulgaria          Bulgarian                    2.498141  1.980548  3.334572
Chile             Latin American Spanish       2.867521  1.901080  2.899358
China             Mandarin Chinese             4.365940  1.736698  3.914807
Colombia          Latin American Spanish       3.409836  1.974022  3.418033
Croatia           Serbian-Croatian-Bosnian     2.548571  1.680610  3.336502
Curacao           Dutch                        3.627778  1.743401  3.961111
Denmark           Danish                       2.668919  1.513605  3.445946
Egypt             Arabic                       2.547472  1.886575  3.622222
Finland           Finnish                      2.738462  1.547467  3.726923
France            French                       3.357977  1.801764  3.746094
Georgia           Georgian                     2.523605  1.866354  3.248927
Germany           German                       2.804124  1.800225  3.628866
Greece            Greek                        2.328889  1.887059  3.337778
Hong Kong (S.A.R) Mandarin Chinese             2.669065  1.770894  3.064748
Hungary           Hungarian                    2.679688  1.925815  3.265625
Iceland           Icelandic                    3.469741  1.867297  3.299712
India             Marathi                      3.500000  1.768410  3.982143
Indonesia         Indonesian                   3.201863  1.577327  3.834365
Iran              Persian                      2.347826  1.745782  2.774194
Israel            Hebrew                       1.569536  1.718565  3.240000
Italy             Italian                      2.966981  1.900316  3.327059
Japan             Japanese                     2.602176  1.523357  3.559441
Jordan            Arabic                       3.108225  1.965235  3.952586
Kazakhstan        Russian                      2.438849  1.958468  3.469534
Malaysia          Standard Malay               3.793548  1.548761  4.000000
Netherlands       Dutch                        3.325048  1.646279  3.671756
Peru              Spanish                      3.706161  1.884501  3.693023
Russia            Russian                      2.553043  1.774840  3.349565
Serbia            Serbian-Croatian-Bosnian     2.716332  1.845246  3.518519
South Africa      Afrikaans                    2.946429  1.712904  3.642857
Spain             Spanish                      3.428571  1.994498  3.428571
Sweden            Swedish                      3.300000  1.774224  3.580000
Syria             Arabic                       1.849372  1.996402  3.377593
Taiwan            Mandarin Chinese             3.993307  1.660520  3.666667
Turkey            Turkish                      2.027888  1.760460  3.611111
Ukraine           Ukrainian                    2.856489  1.644428  3.203957
Vietnam           Vietnamese                   4.219178  1.746841  4.263699

                                                       compassion            \
                                                   std       mean       std
countryname       bila_language_name_mapping
Brazil            Brazilian Portuguese        1.502585   4.633987  1.319471
Bulgaria          Bulgarian                   1.712431   4.313433  1.590788
Chile             Latin American Spanish      1.546330   3.893390  1.693798
China             Mandarin Chinese            1.683731   4.240976  1.701800
Colombia          Latin American Spanish      1.419115   4.024590  1.678563
Croatia           Serbian-Croatian-Bosnian    1.487369   2.916190  1.657917
Curacao           Dutch                       1.607816   4.777778  1.174951
Denmark           Danish                      1.531012   4.067568  1.450602
Egypt             Arabic                      1.728264   4.173006  1.710858
Finland           Finnish                     1.380520   4.042471  1.350471
France            French                      1.587322   3.809339  1.648458
Georgia           Georgian                    1.698836   4.444444  1.507887
Germany           German                      1.620895   4.347079  1.283778
Greece            Greek                       1.538681   3.843049  1.662391
Hong Kong (S.A.R) Mandarin Chinese            1.455667   3.323741  1.616114
Hungary           Hungarian                   1.730848   4.507812  1.343079
Iceland           Icelandic                   1.757585   4.388406  1.601193
India             Marathi                     1.700172   3.946429  1.633954
Indonesia         Indonesian                  1.327863   4.547287  1.238492
Iran              Persian                     1.831431   3.770053  1.705639
Israel            Hebrew                      1.407935   4.013245  1.316494
Italy             Italian                     1.516839   3.613208  1.729022
Japan             Japanese                    1.254913   3.533385  1.375941
Jordan            Arabic                      1.807247   4.359307  1.718414
Kazakhstan        Russian                     1.641953   3.602151  1.755606
Malaysia          Standard Malay              1.232672   4.432258  1.304435
Netherlands       Dutch                       1.413904   4.160305  1.402357
Peru              Spanish                     1.503484   4.483721  1.500301
Russia            Russian                     1.524902   3.557292  1.654564
Serbia            Serbian-Croatian-Bosnian    1.578091   4.308571  1.464650
South Africa      Afrikaans                   1.341353   4.196429  1.505780
Spain             Spanish                     1.616365   3.971154  1.742984
Sweden            Swedish                     1.482936   4.537500  1.289477
Syria             Arabic                      2.045971   3.878543  1.921589
Taiwan            Mandarin Chinese            1.549020   3.722520  1.628423
Turkey            Turkish                     1.439191   3.956349  1.627111
Ukraine           Ukrainian                   1.565963   3.576220  1.516419
Vietnam           Vietnamese                  1.350442   3.872852  1.779476

                                             determination            \
                                                      mean       std
countryname       bila_language_name_mapping
Brazil            Brazilian Portuguese            3.725490  1.593986
Bulgaria          Bulgarian                       3.565056  1.684113
Chile             Latin American Spanish          3.370450  1.700109
China             Mandarin Chinese                4.165992  1.693406
Colombia          Latin American Spanish          3.818182  1.653280
Croatia           Serbian-Croatian-Bosnian        3.516190  1.441686
Curacao           Dutch                           4.000000  1.549914
Denmark           Danish                          3.351351  1.483996
Egypt             Arabic                          3.161090  1.728845
Finland           Finnish                         3.532819  1.327221
France            French                          3.727626  1.582292
Georgia           Georgian                        3.692308  1.815345
Germany           German                          3.468966  1.464955
Greece            Greek                           3.444934  1.682894
Hong Kong (S.A.R) Mandarin Chinese                3.366906  1.489791
Hungary           Hungarian                       3.652344  1.698972
Iceland           Icelandic                       3.589595  1.611303
India             Marathi                         3.660714  1.880781
Indonesia         Indonesian                      3.827372  1.301711
Iran              Persian                         3.290323  1.601220
Israel            Hebrew                          3.403974  1.493001
Italy             Italian                         3.716981  1.558958
Japan             Japanese                        2.964258  1.522347
Jordan            Arabic                          3.754386  1.846828
Kazakhstan        Russian                         3.283154  1.783851
Malaysia          Standard Malay                  3.845161  1.372939
Netherlands       Dutch                           3.553435  1.404380
Peru              Spanish                         3.939252  1.457070
Russia            Russian                         3.057292  1.579824
Serbia            Serbian-Croatian-Bosnian        3.792023  1.578261
South Africa      Afrikaans                       3.696429  1.570214
Spain             Spanish                         3.461538  1.773172
Sweden            Swedish                         3.675000  1.374445
Syria             Arabic                          2.888889  2.168520
Taiwan            Mandarin Chinese                3.695710  1.540472
Turkey            Turkish                         3.804781  1.561325
Ukraine           Ukrainian                       3.260274  1.528436
Vietnam           Vietnamese                      4.096220  1.507803

                                                 moved            ...  \
                                                  mean       std  ...
countryname       bila_language_name_mapping                      ...
Brazil            Brazilian Portuguese        4.464052  1.603382  ...
Bulgaria          Bulgarian                   3.587361  1.860024  ...
Chile             Latin American Spanish      3.886266  1.722072  ...
China             Mandarin Chinese            4.426538  1.700508  ...
Colombia          Latin American Spanish      4.049180  1.719372  ...
Croatia           Serbian-Croatian-Bosnian    2.663498  1.667298  ...
Curacao           Dutch                       3.394444  1.632413  ...
Denmark           Danish                      3.304054  1.417379  ...
Egypt             Arabic                      4.028325  1.684172  ...
Finland           Finnish                     3.084615  1.655852  ...
France            French                      3.046693  1.710994  ...
Georgia           Georgian                    3.424893  1.794310  ...
Germany           German                      3.529412  1.559024  ...
Greece            Greek                       3.273128  1.910690  ...
Hong Kong (S.A.R) Mandarin Chinese            2.920863  1.597393  ...
Hungary           Hungarian                   2.847656  1.927162  ...
Iceland           Icelandic                   2.489914  1.878318  ...
India             Marathi                     2.357143  1.920498  ...
Indonesia         Indonesian                  4.057099  1.293718  ...
Iran              Persian                     3.150538  1.845059  ...
Israel            Hebrew                      2.980132  1.601958  ...
Italy             Italian                     3.280660  1.828072  ...
Japan             Japanese                    2.777174  1.525502  ...
Jordan            Arabic                      3.899123  1.781797  ...
Kazakhstan        Russian                     2.587814  2.029990  ...
Malaysia          Standard Malay              3.490323  1.656815  ...
Netherlands       Dutch                       3.409178  1.592870  ...
Peru              Spanish                     4.455814  1.493491  ...
Russia            Russian                     2.503484  1.727255  ...
Serbia            Serbian-Croatian-Bosnian    3.338068  1.769293  ...
South Africa      Afrikaans                   3.142857  1.686497  ...
Spain             Spanish                     3.894231  1.576023  ...
Sweden            Swedish                     3.120000  1.646931  ...
Syria             Arabic                      3.651452  1.962908  ...
Taiwan            Mandarin Chinese            3.935657  1.593995  ...
Turkey            Turkish                     3.234127  1.854451  ...
Ukraine           Ukrainian                   2.955860  1.657264  ...
Vietnam           Vietnamese                  4.185567  1.667105  ...

                                                  fear           frustration  \
                                                  mean       std        mean
countryname       bila_language_name_mapping
Brazil            Brazilian Portuguese        3.603279  1.757500    3.437908
Bulgaria          Bulgarian                   2.561338  1.954938    3.029740
Chile             Latin American Spanish      3.528785  1.836746    4.119914
China             Mandarin Chinese            1.809500  1.726083    1.815642
Colombia          Latin American Spanish      3.024590  1.943258    3.409836
Croatia           Serbian-Croatian-Bosnian    2.740952  1.825796    3.420952
Curacao           Dutch                       2.477778  1.933115    3.005556
Denmark           Danish                      1.824324  1.610832    3.148649
Egypt             Arabic                      3.556790  1.953694    3.419434
Finland           Finnish                     2.509653  1.600298    3.846154
France            French                      2.155642  1.796018    3.156250
Georgia           Georgian                    2.497854  1.864192    2.965665
Germany           German                      2.323024  1.757384    3.186207
Greece            Greek                       2.637168  1.939356    3.508850
Hong Kong (S.A.R) Mandarin Chinese            2.633094  1.765794    2.431655
Hungary           Hungarian                   2.511719  1.823555    3.125000
Iceland           Icelandic                   2.227666  1.861548    2.129683
India             Marathi                     2.053571  1.891797    1.839286
Indonesia         Indonesian                  3.141085  1.749073    2.213292
Iran              Persian                     2.972973  1.929272    3.005405
Israel            Hebrew                      2.092715  1.733401    3.125828
Italy             Italian                     2.666667  1.799782    3.320000
Japan             Japanese                    2.630148  1.743227    3.111888
Jordan            Arabic                      2.711207  2.012570    3.116379
Kazakhstan        Russian                     2.276978  1.979746    2.602151
Malaysia          Standard Malay              2.503226  1.785127    2.412903
Netherlands       Dutch                       2.408397  1.663121    3.574427
Peru              Spanish                     2.868545  1.827875    3.181395
Russia            Russian                     2.394415  1.771404    2.713542
Serbia            Serbian-Croatian-Bosnian    2.428977  1.784888    2.749288
South Africa      Afrikaans                   2.883929  1.911301    3.991071
Spain             Spanish                     2.371429  1.771880    3.228571
Sweden            Swedish                     2.315000  1.693501    3.170000
Syria             Arabic                      2.122449  2.012590    2.275720
Taiwan            Mandarin Chinese            1.990617  1.625689    1.842035
Turkey            Turkish                     2.948617  1.892269    2.881423
Ukraine           Ukrainian                   2.393293  1.827914    2.936073
Vietnam           Vietnamese                  1.688356  1.687472    2.441781

                                                       loneliness            \
                                                   std       mean       std
countryname       bila_language_name_mapping
Brazil            Brazilian Portuguese        1.941201   2.518033  2.069635
Bulgaria          Bulgarian                   2.089207   2.334572  2.154385
Chile             Latin American Spanish      1.731608   2.869658  2.067930
China             Mandarin Chinese            1.763461   1.812437  1.826492
Colombia          Latin American Spanish      1.897167   2.578512  2.170837
Croatia           Serbian-Croatian-Bosnian    1.812788   2.682510  1.955690
Curacao           Dutch                       1.877527   1.894444  1.853570
Denmark           Danish                      1.852980   2.277027  2.026427
Egypt             Arabic                      2.007981   3.686275  2.140949
Finland           Finnish                     1.699246   2.776062  1.927978
France            French                      1.829765   1.961089  1.932060
Georgia           Georgian                    1.920539   2.439655  2.131149
Germany           German                      1.856388   2.178694  1.887078
Greece            Greek                       1.663306   2.537445  2.015901
Hong Kong (S.A.R) Mandarin Chinese            1.813997   2.345324  1.909975
Hungary           Hungarian                   1.919967   1.863281  2.000211
Iceland           Icelandic                   1.890931   2.465318  2.160303
India             Marathi                     1.961231   1.857143  1.833314
Indonesia         Indonesian                  1.869821   2.545595  1.978368
Iran              Persian                     1.918155   2.940860  2.032638
Israel            Hebrew                      1.690383   2.026490  1.754792
Italy             Italian                     1.944077   2.535377  1.968709
Japan             Japanese                    1.729330   2.007764  1.817621
Jordan            Arabic                      2.076312   3.304348  2.156230
Kazakhstan        Russian                     2.078356   2.039568  2.156817
Malaysia          Standard Malay              1.689490   2.296774  2.064462
Netherlands       Dutch                       1.658224   2.335878  1.853572
Peru              Spanish                     1.988196   1.604651  1.720404
Russia            Russian                     1.983293   2.157986  2.033897
Serbia            Serbian-Croatian-Bosnian    1.953705   2.205128  2.008006
South Africa      Afrikaans                   1.579688   2.276786  1.996437
Spain             Spanish                     1.912797   1.971429  2.011779
Sweden            Swedish                     1.835626   2.140000  1.990050
Syria             Arabic                      2.142184   2.325103  2.281181
Taiwan            Mandarin Chinese            1.638740   1.605087  1.640841
Turkey            Turkish                     1.976491   2.494071  2.042447
Ukraine           Ukrainian                   1.930703   2.181402  1.950304
Vietnam           Vietnamese                  1.901356   1.859589  1.964674

                                                regret             sadness  \
                                                  mean       std      mean
countryname       bila_language_name_mapping
Brazil            Brazilian Portuguese        1.934426  1.881951  3.321311
Bulgaria          Bulgarian                   2.929104  2.009018  3.252788
Chile             Latin American Spanish      2.352564  1.969156  3.799145
China             Mandarin Chinese            1.477009  1.701083  2.256709
Colombia          Latin American Spanish      1.721311  1.601973  3.459016
Croatia           Serbian-Croatian-Bosnian    2.798479  1.710828  2.990494
Curacao           Dutch                       1.350000  1.645970  2.622222
Denmark           Danish                      1.479730  1.655622  1.601351
Egypt             Arabic                      2.710591  2.129295  4.047970
Finland           Finnish                     1.534615  1.570343  2.953668
France            French                      1.582031  1.708430  2.503906
Georgia           Georgian                    2.497854  1.916634  3.277778
Germany           German                      2.037931  1.705459  2.656357
Greece            Greek                       1.778761  1.836589  3.251101
Hong Kong (S.A.R) Mandarin Chinese            1.956835  1.785085  2.618705
Hungary           Hungarian                   1.906250  1.723824  2.703125
Iceland           Icelandic                   1.527378  1.776931  2.376437
India             Marathi                     1.254545  1.723672  2.381818
Indonesia         Indonesian                  2.066563  1.647238  2.933333
Iran              Persian                     2.659459  1.999383  3.556150
Israel            Hebrew                      1.662252  1.616116  2.536424
Italy             Italian                     2.411765  1.928523  3.343529

In [985]:
# lets just flatten out the 3 level column names
stats_by_country.columns = [
    f"{emotion}_{stat}" for emotion, stat in stats_by_country.columns
]
stats_by_country = stats_by_country.reset_index()
stats_by_country

,countryname,bila_language_name_mapping,admiration_mean,admiration_std,calm_mean,calm_std,compassion_mean,compassion_std,determination_mean,determination_std,...,fear_mean,fear_std,frustration_mean,frustration_std,loneliness_mean,loneliness_std,regret_mean,regret_std,sadness_mean,sadness_std
0,Brazil,Brazilian Portuguese,3.540984,1.745047,3.421569,1.502585,4.633987,1.319471,3.725490,1.593986,...,3.603279,1.757500,3.437908,1.941201,2.518033,2.069635,1.934426,1.881951,3.321311,1.833991
1,Bulgaria,Bulgarian,2.498141,1.980548,3.334572,1.712431,4.313433,1.590788,3.565056,1.684113,...,2.561338,1.954938,3.029740,2.089207,2.334572,2.154385,2.929104,2.009018,3.252788,1.930519
2,Chile,Latin American Spanish,2.867521,1.901080,2.899358,1.546330,3.893390,1.693798,3.370450,1.700109,...,3.528785,1.836746,4.119914,1.731608,2.869658,2.067930,2.352564,1.969156,3.799145,1.745670
3,China,Mandarin Chinese,4.365940,1.736698,3.914807,1.683731,4.240976,1.701800,4.165992,1.693406,...,1.809500,1.726083,1.815642,1.763461,1.812437,1.826492,1.477009,1.701083,2.256709,1.848471
4,Colombia,Latin American Spanish,3.409836,1.974022,3.418033,1.419115,4.024590,1.678563,3.818182,1.653280,...,3.024590,1.943258,3.409836,1.897167,2.578512,2.170837,1.721311,1.601973,3.459016,1.916210
5,Croatia,Serbian-Croatian-Bosnian,2.548571,1.680610,3.336502,1.487369,2.916190,1.657917,3.516190,1.441686,...,2.740952,1.825796,3.420952,1.812788,2.682510,1.955690,2.798479,1.710828,2.990494,1.760385
6,Curacao,Dutch,3.627778,1.743401,3.961111,1.607816,4.777778,1.174951,4.000000,1.549914,...,2.477778,1.933115,3.005556,1.877527,1.894444,1.853570,1.350000,1.645970,2.622222,1.906049
7,Denmark,Danish,2.668919,1.513605,3.445946,1.531012,4.067568,1.450602,3.351351,1.483996,...,1.824324,1.610832,3.148649,1.852980,2.277027,2.026427,1.479730,1.655622,1.601351,1.732993
8,Egypt,Arabic,2.547472,1.886575,3.622222,1.728264,4.173006,1.710858,3.161090,1.728845,...,3.556790,1.953694,3.419434,2.007981,3.686275,2.140949,2.710591,2.129295,4.047970,1.806232
9,Finland,Finnish,2.738462,1.547467,3.726923,1.380520,4.042471,1.350471,3.532819,1.327221,...,2.509653,1.600298,3.846154,1.699246,2.776062,1.927978,1.534615,1.570343,2.953668,1.672212
10,France,French,3.357977,1.801764,3.746094,1.587322,3.809339,1.648458,3.727626,1.582292,...,2.155642,1.796018,3.156250,1.829765,1.961089,1.932060,1.582031,1.708430,2.503906,1.874489
11,Georgia,Georgian,2.523605,1.866354,3.248927,1.698836,4.444444,1.507887,3.692308,1.815345,...,2.497854,1.864192,2.965665,1.920539,2.439655,2.131149,2.497854,1.916634,3.277778,1.955453
12,Germany,German,2.804124,1.800225,3.628866,1.620895,4.347079,1.283778,3.468966,1.464955,...,2.323024,1.757384,3.186207,1.856388,2.178694,1.887078,2.037931,1.705459,2.656357,1.749518
13,Greece,Greek,2.328889,1.887059,3.337778,1.538681,3.843049,1.662391,3.444934,1.682894,...,2.637168,1.939356,3.508850,1.663306,2.537445,2.015901,1.778761,1.836589,3.251101,1.886945
14,Hong Kong (S.A.R),Mandarin Chinese,2.669065,1.770894,3.064748,1.455667,3.323741,1.616114,3.366906,1.489791,...,2.633094,1.765794,2.431655,1.813997,2.345324,1.909975,1.956835,1.785085,2.618705,1.750344
15,Hungary,Hungarian,2.679688,1.925815,3.265625,1.730848,4.507812,1.343079,3.652344,1.698972,...,2.511719,1.823555,3.125000,1.919967,1.863281,2.000211,1.906250,1.723824,2.703125,1.869715
16,Iceland,Icelandic,3.469741,1.867297,3.299712,1.757585,4.388406,1.601193,3.589595,1.611303,...,2.227666,1.861548,2.129683,1.890931,2.465318,2.160303,1.527378,1.776931,2.376437,1.964884
17,India,Marathi,3.500000,1.768410,3.982143,1.700172,3.946429,1.633954,3.660714,1.880781,...,2.053571,1.891797,1.839286,1.961231,1.857143,1.833314,1.254545,1.723672,2.381818,2.022932
18,Indonesia,Indonesian,3.201863,1.577327,3.834365,1.327863,4.547287,1.238492,3.827372,1.301711,...,3.141085,1.749073,2.213292,1.869821,2.545595,1.978368,2.066563,1.647238,2.933333,1.730317
19,Iran,Persian,2.347826,1.745782,2.774194,1.831431,3.770053,1.705639,3.290323,1.601220,...,2.972973,1.929272,3.005405,1.918155,2.940860,2.032638,2.659459,1.999383,3.556150,1.881089
20,Israel,Hebrew,1.569536,1.718565,3.240000,1.407935,4.013245,1.316494,3.403974,1.493001,...,2.092715,1.733401,3.125828,1.690383,2.026490,1.754792,1.662252,1.616116,2.536424,1.765502
21,Italy,Italian,2.966981,1.900316,3.327059,1.516839,3.613208,1.729022,3.716981,1.558958,...,2.666667,1.799782,3.320000,1.944077,2.535377,1.968709,2.411765,1.928523,3.343529,1.723755
22,Japan,Japanese,2.602176,1.523357,3.559441,1.254913,3.533385,1.375941,2.964258,1.522347,...,2.630148,1.743227,3.111888,1.729330,2.007764,1.817621,1.956522,1.623824,2.601399,1.710028
23,Jordan,Arabic,3.108225,1.965235,3.952586,1.807247,4.359307,1.718414,3.754386,1.846828,...,2.711207,2.012570,3.116379,2.076312,3.304348,2.156230,2.515152,2.218202,3.700000,1.917855
24,Kazakhstan,Russian,2.438849,1.958468,3.469534,1.641953,3.602151,1.755606,3.283154,1.783851,...,2.276978,1.979746,2.602151,2.078356,2.039568,2.156817,2.773381,2.002456,3.028674,1.913386
25,Malaysia,Standard Malay,3.793548,1.548761,4.000000,1.232672,4.432258,1.304435,3.845161,1.372939,...,2.503226,1.785127,2.412903,1.689490,2.296774,2.064462,1.980645,1.672819,2.761290,1.643894
26,Netherlands,Dutch,3.325048,1.646279,3.671756,1.413904,4.160305,1.402357,3.553435,1.404380,...,2.408397,1.663121,3.574427,1.658224,2.335878,1.853572,1.402672,1.482876,2.869981,1.738211
27,Peru,Spanish,3.706161,1.884501,3.693023,1.503484,4.483721,1.500301,3.939252,1.457070,...,2.868545,1.827875,3.181395,1.988196,1.604651,1.720404,1.469767,1.617015,3.065116,1.768214
28,Russia,Russian,2.553043,1.774840,3.349565,1.524902,3.557292,1.654564,3.057292,1.579824,...,2.394415,1.771404,2.713542,1.983293,2.157986,2.033897,2.841739,1.816781,3.288194,1.748619
29,Serbia,Serbian-Croatian-Bosnian,2.716332,1.845246,3.518519,1.578091,4.308571,1.464650,3.792023,1.578261,...,2.428977,1.784888,2.749288,1.953705,2.205128,2.008006,2.965714,1.929702,2.988636,1.816319
30,South Africa,Afrikaans,2.946429,1.712904,3.642857,1.341353,4.196429,1.505780,3.696429,1.570214,...,2.883929,1.911301,3.991071,1.579688,2.276786,1.996437,2.098214,1.888609,3.160714,1.872290
31,Spain,Spanish,3.428571,1.994498,3.428571,1.616365,3.971154,1.742984,3.461538,1.773172,...,2.371429,1.771880,3.228571,1.912797,1.971429,2.011779,1.428571,1.663275,3.066667,1.733531
32,Sweden,Swedish,3.300000,1.774224,3.580000,1.482936,4.537500,1.289477,3.675000,1.374445,...,2.315000,1.693501,3.170000,1.835626,2.140000,1.990050,1.355890,1.523240,2.680000,1.773546
33,Syria,Arabic,1.849372,1.996402,3.377593,2.045971,3.878543,1.921589,2.888889,2.168520,...,2.122449,2.012590,2.275720,2.142184,2.325103,2.281181,1.636364,1.955946,2.799180,2.200972
34,Taiwan,Mandarin Chinese,3.993307,1.660520,3.666667,1.549020,3.722520,1.628423,3.695710,1.540472,...,1.990617,1.625689,1.842035,1.638740,1.605087,1.640841,1.215818,1.466518,1.962416,1.652201
35,Turkey,Turkish,2.027888,1.760460,3.611111,1.439191,3.956349,1.627111,3.804781,1.561325,...,2.948617,1.892269,2.881423,1.976491,2.494071,2.042447,1.768000,1.788567,3.575397,1.681357
36,Ukraine,Ukrainian,2.856489,1.644428,3.203957,1.565963,3.576220,1.516419,3.260274,1.528436,...,2.393293,1.827914,2.936073,1.930703,2.181402,1.950304,2.705793,1.814369,3.169466,1.849121
37,Vietnam,Vietnamese,4.219178,1.746841,4.263699,1.350442,3.872852,1.779476,4.096220,1.507803,...,1.688356,1.687472,2.441781,1.901356,1.859589,1.964674,1.534247,1.709743,2.047945,1.841978

In [986]:
map - set(stats_by_country['bila_language_name_mapping'].unique())

{'Czech',
 'Estonian',
 'Filipino',
 'Hindi',
 'Kazakh',
 'Korean',
 'Malayalam',
 'Norwegian',
 'Polish',
 'Portuguese',
 'Romanian',
 'Slovak',
 'Slovenian',
 nan}

In [987]:
# it was very wide, leyts make it narrow, longer, and more robust
stats_long = (
    stats_by_country
    .set_index(['countryname', 'bila_language_name_mapping'])
    .filter(regex='_(mean|std)$')
    .stack()
    .reset_index()
)

stats_long[['word', 'stat']] = stats_long['level_2'].str.rsplit('_', n=1, expand=True)
stats_long = stats_long.rename(columns={0: 'value'}).drop(columns='level_2')

stats_long = (
    stats_long
    .pivot_table(
        index=['countryname', 'bila_language_name_mapping', 'word'],
        columns='stat',
        values='value'
    )
    .reset_index()
)

In [988]:
#Merge our cleaned survey data with the BILA dictionary data
merged = elab_per_emotion.merge(
    stats_long,
    left_on=['langname', 'word'],
    right_on=['bila_language_name_mapping', 'word'],
    how='left'
)

merged

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,mean,std
0,Turkish,nucl1301,fear,126.0,coo.31924067983704,1991.0,0.001036,1.952545,121674.0,Turkey,Turkish,2.948617,1.892269
1,Turkish,nucl1301,pleasure,107.0,coo.31924067983704,1991.0,0.000879,3.153327,121674.0,Turkey,Turkish,3.083665,1.643463
2,Turkish,nucl1301,regret,41.0,coo.31924067983704,1991.0,0.000337,2.670962,121674.0,Turkey,Turkish,1.768000,1.788567
3,Turkish,nucl1301,admiration,10.0,coo.31924067983704,1991.0,0.000082,-0.854986,121674.0,Turkey,Turkish,2.027888,1.760460
4,Turkish,nucl1301,anger,85.0,coo.31924067983704,1991.0,0.000699,0.579516,121674.0,Turkey,Turkish,3.460000,1.871473
...,...,...,...,...,...,...,...,...,...,...,...,...,...
679,Japanese,nucl1643,disgust,13.0,uva.x004877953,1974.0,0.000046,-4.505457,282895.0,Japan,Japanese,2.854701,1.747655
680,Japanese,nucl1643,frustration,6.0,uva.x004877953,1974.0,0.000021,-1.588076,282895.0,Japan,Japanese,3.111888,1.729330
681,Japanese,nucl1643,loneliness,7.0,uva.x004877953,1974.0,0.000025,-1.873436,282895.0,Japan,Japanese,2.007764,1.817621
682,Japanese,nucl1643,relief,89.0,uva.x004877953,1974.0,0.000315,3.907437,282895.0,Japan,Japanese,2.403263,1.417428
683,Japanese,nucl1643,boredom,6.0,uva.x004877953,1974.0,0.000021,-1.590590,282895.0,Japan,Japanese,3.180901,1.939018

In [989]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 684 entries, 0 to 683
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   langname                    684 non-null    object
 1   glottocode                  684 non-null    object
 2   word                        684 non-null    object
 3   count                       684 non-null    float64
 4   id                          684 non-null    object
 5   year                        684 non-null    float64
 6   simple_elaboration          684 non-null    float64
 7   regression_elaboration      684 non-null    float64
 8   dictsize_data               684 non-null    float64
 9   countryname                 684 non-null    object
 10  bila_language_name_mapping  684 non-null    object
 11  mean                        684 non-null    float64
 12  std                         684 non-null    float64
dtypes: float64(7), object(6)
memory usage: 69.6+ KB

In [990]:
# add the dictionary_count_mean column
merged = merged.merge(
    dictionary_means,
    left_on='id',
    right_on='id',
    how='left'
)
merged

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,mean,std,dictionary_count_mean
0,Turkish,nucl1301,fear,126.0,coo.31924067983704,1991.0,0.001036,1.952545,121674.0,Turkey,Turkish,2.948617,1.892269,14.502265
1,Turkish,nucl1301,pleasure,107.0,coo.31924067983704,1991.0,0.000879,3.153327,121674.0,Turkey,Turkish,3.083665,1.643463,14.502265
2,Turkish,nucl1301,regret,41.0,coo.31924067983704,1991.0,0.000337,2.670962,121674.0,Turkey,Turkish,1.768000,1.788567,14.502265
3,Turkish,nucl1301,admiration,10.0,coo.31924067983704,1991.0,0.000082,-0.854986,121674.0,Turkey,Turkish,2.027888,1.760460,14.502265
4,Turkish,nucl1301,anger,85.0,coo.31924067983704,1991.0,0.000699,0.579516,121674.0,Turkey,Turkish,3.460000,1.871473,14.502265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679,Japanese,nucl1643,disgust,13.0,uva.x004877953,1974.0,0.000046,-4.505457,282895.0,Japan,Japanese,2.854701,1.747655,33.718117
680,Japanese,nucl1643,frustration,6.0,uva.x004877953,1974.0,0.000021,-1.588076,282895.0,Japan,Japanese,3.111888,1.729330,33.718117
681,Japanese,nucl1643,loneliness,7.0,uva.x004877953,1974.0,0.000025,-1.873436,282895.0,Japan,Japanese,2.007764,1.817621,33.718117
682,Japanese,nucl1643,relief,89.0,uva.x004877953,1974.0,0.000315,3.907437,282895.0,Japan,Japanese,2.403263,1.417428,33.718117
683,Japanese,nucl1643,boredom,6.0,uva.x004877953,1974.0,0.000021,-1.590590,282895.0,Japan,Japanese,3.180901,1.939018,33.718117

In [991]:
merged = merged[merged['countryname'].notna()]

In [992]:
merged.columns

Index(['langname', 'glottocode', 'word', 'count', 'id', 'year',
       'simple_elaboration', 'regression_elaboration', 'dictsize_data',
       'countryname', 'bila_language_name_mapping', 'mean', 'std',
       'dictionary_count_mean'],
      dtype='object')

In [993]:
# clarify the meaning of mean
merged = merged.rename(columns={'mean': "response_mean"})
# Clarify what std we're talking about
merged = merged.rename(columns={'std': "response_std"})
# drop a bunch of columns

merged = merged[['langname', 'glottocode', 'word', 'count', 'id', 'year',
       'simple_elaboration', 'regression_elaboration', 'dictsize_data',
       'countryname', 'bila_language_name_mapping', 'response_mean',
       'response_std', 'dictionary_count_mean' ]]
merged = merged.sort_values(by=["langname", 'word'])
merged

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,response_mean,response_std,dictionary_count_mean
237,Afrikaans,afri1274,admiration,6.0,mdp.39015054154474,1999.0,0.000028,-3.291632,212992.0,South Africa,Afrikaans,2.946429,1.712904,25.386412
238,Afrikaans,afri1274,anger,55.0,mdp.39015054154474,1999.0,0.000258,-6.741147,212992.0,South Africa,Afrikaans,2.785714,1.803043,25.386412
241,Afrikaans,afri1274,anxiety,30.0,mdp.39015054154474,1999.0,0.000141,-2.655449,212992.0,South Africa,Afrikaans,3.535714,1.765171,25.386412
251,Afrikaans,afri1274,boredom,5.0,mdp.39015054154474,1999.0,0.000023,-1.176312,212992.0,South Africa,Afrikaans,2.241071,1.889971,25.386412
239,Afrikaans,afri1274,compassion,15.0,mdp.39015054154474,1999.0,0.000070,-2.918472,212992.0,South Africa,Afrikaans,4.196429,1.505780,25.386412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384,Vietnamese,viet1252,love,308.0,uc1.31210024487306,2003.0,0.001143,-1.138291,269366.0,Vietnam,Vietnamese,4.786942,1.311475,32.105602
379,Vietnamese,viet1252,pleasure,216.0,uc1.31210024487306,2003.0,0.000802,3.511485,269366.0,Vietnam,Vietnamese,2.832192,1.885719,32.105602
380,Vietnamese,viet1252,regret,59.0,uc1.31210024487306,2003.0,0.000219,0.052866,269366.0,Vietnam,Vietnamese,1.534247,1.709743,32.105602
394,Vietnamese,viet1252,relief,74.0,uc1.31210024487306,2003.0,0.000275,2.404758,269366.0,Vietnam,Vietnamese,3.199313,1.720505,32.105602
390,Vietnamese,viet1252,sadness,51.0,uc1.31210024487306,2003.0,0.000189,4.028092,269366.0,Vietnam,Vietnamese,2.047945,1.841978,32.105602

In [994]:
merged = merged.reset_index(drop=True)
merged

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,response_mean,response_std,dictionary_count_mean
0,Afrikaans,afri1274,admiration,6.0,mdp.39015054154474,1999.0,0.000028,-3.291632,212992.0,South Africa,Afrikaans,2.946429,1.712904,25.386412
1,Afrikaans,afri1274,anger,55.0,mdp.39015054154474,1999.0,0.000258,-6.741147,212992.0,South Africa,Afrikaans,2.785714,1.803043,25.386412
2,Afrikaans,afri1274,anxiety,30.0,mdp.39015054154474,1999.0,0.000141,-2.655449,212992.0,South Africa,Afrikaans,3.535714,1.765171,25.386412
3,Afrikaans,afri1274,boredom,5.0,mdp.39015054154474,1999.0,0.000023,-1.176312,212992.0,South Africa,Afrikaans,2.241071,1.889971,25.386412
4,Afrikaans,afri1274,compassion,15.0,mdp.39015054154474,1999.0,0.000070,-2.918472,212992.0,South Africa,Afrikaans,4.196429,1.505780,25.386412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679,Vietnamese,viet1252,love,308.0,uc1.31210024487306,2003.0,0.001143,-1.138291,269366.0,Vietnam,Vietnamese,4.786942,1.311475,32.105602
680,Vietnamese,viet1252,pleasure,216.0,uc1.31210024487306,2003.0,0.000802,3.511485,269366.0,Vietnam,Vietnamese,2.832192,1.885719,32.105602
681,Vietnamese,viet1252,regret,59.0,uc1.31210024487306,2003.0,0.000219,0.052866,269366.0,Vietnam,Vietnamese,1.534247,1.709743,32.105602
682,Vietnamese,viet1252,relief,74.0,uc1.31210024487306,2003.0,0.000275,2.404758,269366.0,Vietnam,Vietnamese,3.199313,1.720505,32.105602
683,Vietnamese,viet1252,sadness,51.0,uc1.31210024487306,2003.0,0.000189,4.028092,269366.0,Vietnam,Vietnamese,2.047945,1.841978,32.105602

In [997]:
print(merged['langname'].nunique(),
      merged['bila_language_name_mapping'].nunique(),
merged['word'].nunique(),
merged['countryname'].nunique(), sep="\n")

29
29
18
38

In [998]:
merged = merged.sort_values(by=["langname", 'countryname','word'])
merged = merged.reset_index(drop=True)
merged = merged.fillna(0)

In [999]:
merged

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,response_mean,response_std,dictionary_count_mean
0,Afrikaans,afri1274,admiration,6.0,mdp.39015054154474,1999.0,0.000028,-3.291632,212992.0,South Africa,Afrikaans,2.946429,1.712904,25.386412
1,Afrikaans,afri1274,anger,55.0,mdp.39015054154474,1999.0,0.000258,-6.741147,212992.0,South Africa,Afrikaans,2.785714,1.803043,25.386412
2,Afrikaans,afri1274,anxiety,30.0,mdp.39015054154474,1999.0,0.000141,-2.655449,212992.0,South Africa,Afrikaans,3.535714,1.765171,25.386412
3,Afrikaans,afri1274,boredom,5.0,mdp.39015054154474,1999.0,0.000023,-1.176312,212992.0,South Africa,Afrikaans,2.241071,1.889971,25.386412
4,Afrikaans,afri1274,compassion,15.0,mdp.39015054154474,1999.0,0.000070,-2.918472,212992.0,South Africa,Afrikaans,4.196429,1.505780,25.386412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679,Vietnamese,viet1252,love,308.0,uc1.31210024487306,2003.0,0.001143,-1.138291,269366.0,Vietnam,Vietnamese,4.786942,1.311475,32.105602
680,Vietnamese,viet1252,pleasure,216.0,uc1.31210024487306,2003.0,0.000802,3.511485,269366.0,Vietnam,Vietnamese,2.832192,1.885719,32.105602
681,Vietnamese,viet1252,regret,59.0,uc1.31210024487306,2003.0,0.000219,0.052866,269366.0,Vietnam,Vietnamese,1.534247,1.709743,32.105602
682,Vietnamese,viet1252,relief,74.0,uc1.31210024487306,2003.0,0.000275,2.404758,269366.0,Vietnam,Vietnamese,3.199313,1.720505,32.105602
683,Vietnamese,viet1252,sadness,51.0,uc1.31210024487306,2003.0,0.000189,4.028092,269366.0,Vietnam,Vietnamese,2.047945,1.841978,32.105602

In [1000]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 684 entries, 0 to 683
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   langname                    684 non-null    object
 1   glottocode                  684 non-null    object
 2   word                        684 non-null    object
 3   count                       684 non-null    float64
 4   id                          684 non-null    object
 5   year                        684 non-null    float64
 6   simple_elaboration          684 non-null    float64
 7   regression_elaboration      684 non-null    float64
 8   dictsize_data               684 non-null    float64
 9   countryname                 684 non-null    object
 10  bila_language_name_mapping  684 non-null    object
 11  response_mean               684 non-null    float64
 12  response_std                684 non-null    float64
 13  dictionary_count_mean       684 non-null    float64
dtypes: float64(8), object(6)
memory usage: 74.9+ KB

In [1001]:
merged.to_csv(Path("~/Projects/hypocognition/data/processed/covid_bila_merge.csv").expanduser())

"Moving forward, could you create a table with the following columns (broken down into the 36 samples):
* The sample country
* The language
* The correlation between the log count and the response means
* The correlation between the log count and the response SDs
* The correlation between the log count and the absolute distance of the response means from the scale midpoint

In [1002]:
merged['response_mean'].mean()

np.float64(3.0094256137821955)

In [1003]:
import numpy as np

merged2 = merged.copy()

# log count
merged2["log_count"] = np.log(merged2["count"] + 1)

# absolute distance from midpoint
SCALE_MIDPOINT = merged2["response_mean"].mean()
merged2["abs_dist_midpoint"] = (
    merged2["response_mean"] - SCALE_MIDPOINT
).abs()

result = (
    merged2
    .groupby(["countryname", "langname", "id"])
    .agg(
        corr_logcount_response_mean=(
            "log_count",
            lambda x: x.corr(
                merged2.loc[x.index, "response_mean"]
            )
        ),
        corr_logcount_response_sd=(
            "log_count",
            lambda x: x.corr(
                merged2.loc[x.index, "response_std"]
            )
        ),
        corr_logcount_abs_dist_midpoint=(
            "log_count",
            lambda x: x.corr(
                merged2.loc[x.index, "abs_dist_midpoint"]
            )
        ),

    )
    .reset_index()
)

In [1004]:
result

,countryname,langname,id,corr_logcount_response_mean,corr_logcount_response_sd,corr_logcount_abs_dist_midpoint
0,Brazil,Brazilian Portuguese,txu.059173018640743,0.162436,-0.095865,0.058828
1,Bulgaria,Bulgarian,mdp.39015058560494,0.291458,-0.510940,0.265170
2,Chile,Latin American Spanish,mdp.39015050181174,0.371436,-0.362343,0.241683
3,China,Mandarin Chinese,uc1.l0088545033,0.191494,-0.404744,0.116165
4,Colombia,Latin American Spanish,mdp.39015050181174,0.236561,-0.175261,-0.137527
5,Croatia,Serbian-Croatian-Bosnian,mdp.39015012891506,-0.359706,-0.041463,-0.245080
6,Curacao,Dutch,uc1.31822004083036,-0.227172,-0.012792,-0.211599
7,Denmark,Danish,uc1.b3832576,-0.322866,-0.191735,0.313734
8,Egypt,Arabic,mdp.39015043036436,-0.114331,0.133291,-0.338184
9,Finland,Finnish,mdp.39015059174667,0.072036,-0.299668,-0.086978
10,France,French,mdp.39015066787105,-0.124857,0.164443,-0.189515
11,Georgia,Georgian,uva.x001957729,-0.097633,0.082555,0.153908
12,Germany,German,uc1.31822005249149,0.178148,-0.091564,0.031434
13,Greece,Greek,uc1.32106014581794,0.155470,-0.271848,0.093597
14,Hong Kong (S.A.R),Mandarin Chinese,uc1.l0088545033,0.117204,-0.377596,0.118973
15,Hungary,Hungarian,miun.aee0517.0001.001,0.270874,-0.366516,0.245803
16,Iceland,Icelandic,uc1.32106020063118,0.130372,-0.382479,0.245578
17,India,Marathi,mdp.39015055371309,0.053540,-0.047893,-0.092320
18,Indonesia,Indonesian,uc1.31822029604741,-0.016398,-0.108344,-0.185879
19,Iran,Persian,mdp.49015002913532,-0.049999,-0.052836,-0.071080
20,Israel,Hebrew,uva.x004242694,-0.195766,0.222892,0.152106
21,Italy,Italian,mdp.39015042010226,-0.029002,-0.347108,0.223337
22,Japan,Japanese,uva.x004877953,0.080451,-0.451992,0.205401
23,Jordan,Arabic,mdp.39015043036436,-0.227302,0.221999,-0.194749
24,Kazakhstan,Russian,mdp.39015046500511,-0.082885,0.249751,-0.055628
25,Malaysia,Standard Malay,mdp.39015022909470,0.165194,-0.280224,0.226840
26,Netherlands,Dutch,uc1.31822004083036,-0.227579,-0.301708,-0.172409
27,Peru,Spanish,umn.31951d01452389x,0.077039,0.066392,-0.106614
28,Russia,Russian,mdp.39015046500511,-0.073524,0.130810,0.149612
29,Serbia,Serbian-Croatian-Bosnian,mdp.39015012891506,-0.263267,-0.008868,-0.369231
30,South Africa,Afrikaans,mdp.39015054154474,0.091489,-0.126535,-0.062983
31,Spain,Spanish,umn.31951d01452389x,0.013715,-0.008544,-0.040795
32,Sweden,Swedish,mdp.39015052442327,-0.065788,-0.214531,0.093412
33,Syria,Arabic,mdp.39015043036436,0.089289,-0.294497,-0.136168
34,Taiwan,Mandarin Chinese,uc1.l0088545033,0.239418,-0.306164,-0.019581
35,Turkey,Turkish,coo.31924067983704,0.281898,-0.327927,0.013572
36,Ukraine,Ukrainian,uc1.l0070891726,0.154578,0.016344,0.232980
37,Vietnam,Vietnamese,uc1.31210024487306,0.077161,-0.439749,0.141317

In [1005]:
result.to_csv(Path("~/Projects/hypocognition/data/processed/corr_covid_bila.csv").expanduser())