In [100]:
# load libraries 
import pandas as pd
import numpy as np
import re
import math
import plotly.graph_objects as go
import plotly.express as px
from pathlib import Path

In [101]:
# get the SUN covid study dataset
Covid51countries = pd.read_csv(Path("~/Projects/hypocognition/data/raw/Covid51countries.csv").expanduser())
Covid51countries

,country,countryname,StartDate,EndDate,Status,Progress,Duration,Finished,RecordedDate,home,...,gender,ladder,employment,losejob,covidsymptom,language,datasource,ISO3,longstring,na_count
0,10,Australia,04/05/2020 19:34,04/05/2020 19:40,0.0,100.0,337.0,1.0,04/05/2020 19:40,8.0,...,1.0,5.0,4,NaN,0.0,ZH-S,snowball,AUS,3,0
1,10,Australia,04/05/2020 20:26,04/05/2020 20:35,0.0,100.0,530.0,1.0,04/05/2020 20:35,9.0,...,2.0,7.0,3,NaN,NaN,ZH-S,snowball,AUS,3,0
2,10,Australia,05/05/2020 21:54,05/05/2020 22:07,0.0,100.0,793.0,1.0,05/05/2020 22:07,29.0,...,1.0,4.0,1,NaN,0.0,ZH-S,snowball,AUS,5,0
3,10,Australia,04/05/2020 20:29,04/05/2020 20:34,0.0,100.0,285.0,1.0,04/05/2020 20:34,73.0,...,2.0,5.0,4,NaN,0.0,ZH-S,snowball,AUS,4,0
4,10,Australia,19/04/2020 20:21,19/04/2020 20:27,0.0,100.0,367.0,1.0,19/04/2020 20:27,100.0,...,1.0,5.0,1,NaN,0.0,ZH-S,snowball,AUS,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24216,92,Kenya,25/04/2020 01:25,25/04/2020 02:44,0.0,100.0,4690.0,1.0,25/04/2020 02:44,100.0,...,2.0,4.0,4,NaN,0.0,EN,snowball,KEN,4,0
24217,92,Kenya,24/04/2020 11:06,24/04/2020 11:15,0.0,100.0,556.0,1.0,24/04/2020 11:15,100.0,...,1.0,6.0,5,0.0,0.0,EN,snowball,KEN,2,0
24218,92,Kenya,26/04/2020 10:16,26/04/2020 10:36,0.0,100.0,1218.0,1.0,26/04/2020 10:36,80.0,...,1.0,3.0,4,NaN,0.0,EN,snowball,KEN,3,0
24219,92,Kenya,23/04/2020 03:46,23/04/2020 04:13,0.0,100.0,1641.0,1.0,23/04/2020 04:13,3.0,...,1.0,3.0,4,NaN,0.0,EN,snowball,KEN,3,0
24220,92,Kenya,24/04/2020 00:31,24/04/2020 00:42,0.0,100.0,700.0,1.0,24/04/2020 00:42,50.0,...,2.0,6.0,4,NaN,0.0,EN,snowball,KEN,2,0

In [102]:
Covid51countries.columns

Index(['country', 'countryname', 'StartDate', 'EndDate', 'Status', 'Progress',
       'Duration', 'Finished', 'RecordedDate', 'home', 'gathering', 'distance',
       'hands', 'help_covid', 'donate_covid', 'volunteer_covid', 'help',
       'donate', 'volunteer', 'admiration', 'calm', 'compassion',
       'determination', 'moved', 'gratitude', 'hope', 'love', 'relief',
       'pleasure', 'anger', 'anxiety', 'boredom', 'confusion', 'disgust',
       'fear', 'frustration', 'loneliness', 'regret', 'sadness',
       'ERQ1_rumination', 'ERQ2_reappraisal', 'ERQ3_suppression',
       'ERQ4_socialsharing', 'ERQ5_distraction', 'ERQ6_acceptance', 'support',
       'connected', 'phy_healthy', 'mentally_healthy', 'stressed', 'tired',
       'depressed', 'res_1', 'res_2', 'euda_1', 'euda_2', 'swl', 'sympathy',
       'concerned', 'overwhelmed', 'distressed', 'self_vulnerable',
       'country_vulnerable', 'age', 'education', 'gender', 'ladder',
       'employment', 'losejob', 'covidsymptom', 'language', 'datasource',
       'ISO3', 'longstring', 'na_count'],
      dtype='object')

In [103]:
Covid51countries = Covid51countries[['country', 'countryname', 'language','ISO3', 'admiration', 'calm', 'compassion',
       'determination', 'moved', 'gratitude', 'hope', 'love', 'relief',
       'pleasure', 'anger', 'anxiety', 'boredom', 'confusion', 'disgust',
       'fear', 'frustration', 'loneliness', 'regret', 'sadness']]

In [104]:
# add language names to the df
lang_names = pd.read_csv(Path("~/Projects/hypocognition/data/external/lang_names.csv"))
Covid51countries = Covid51countries.merge(lang_names, left_on="language", right_on="Code", how="left")
Covid51countries

,country,countryname,language,ISO3,admiration,calm,compassion,determination,moved,gratitude,...,boredom,confusion,disgust,fear,frustration,loneliness,regret,sadness,Code,Language_Name
0,10,Australia,ZH-S,AUS,5.0,3.0,3.0,5.0,4.0,4.0,...,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,ZH-S,Simplified Chinese
1,10,Australia,ZH-S,AUS,2.0,3.0,3.0,0.0,4.0,2.0,...,3.0,1.0,3.0,3.0,1.0,1.0,2.0,2.0,ZH-S,Simplified Chinese
2,10,Australia,ZH-S,AUS,3.0,3.0,0.0,0.0,0.0,3.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,ZH-S,Simplified Chinese
3,10,Australia,ZH-S,AUS,6.0,1.0,4.0,4.0,4.0,4.0,...,6.0,4.0,4.0,4.0,3.0,6.0,1.0,2.0,ZH-S,Simplified Chinese
4,10,Australia,ZH-S,AUS,0.0,6.0,6.0,6.0,2.0,0.0,...,4.0,5.0,2.0,4.0,2.0,1.0,0.0,3.0,ZH-S,Simplified Chinese
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24216,92,Kenya,EN,KEN,3.0,5.0,5.0,4.0,6.0,3.0,...,5.0,5.0,6.0,4.0,6.0,6.0,6.0,6.0,EN,English
24217,92,Kenya,EN,KEN,6.0,6.0,0.0,6.0,2.0,2.0,...,6.0,0.0,3.0,6.0,3.0,6.0,5.0,2.0,EN,English
24218,92,Kenya,EN,KEN,2.0,3.0,3.0,5.0,3.0,3.0,...,4.0,4.0,4.0,5.0,5.0,3.0,5.0,4.0,EN,English
24219,92,Kenya,EN,KEN,2.0,2.0,5.0,5.0,5.0,6.0,...,5.0,3.0,5.0,5.0,3.0,6.0,1.0,5.0,EN,English
24220,92,Kenya,EN,KEN,4.0,3.0,6.0,6.0,5.0,6.0,...,0.0,4.0,3.0,6.0,4.0,0.0,1.0,4.0,EN,English

In [105]:
# merge croatian, bosnian and serbian
scb = ["Serbian", "Croatian", "Bosnian"]
Covid51countries = Covid51countries.drop(columns=['language'])
Covid51countries.loc[Covid51countries["Language_Name"].isin(scb), "Language_Name"] = "Serbian-Croatian-Bosnian"

In [106]:
# We want to use on only one language of responses for each country
# Further, that language cannot be English

# Calculate the number of responses for each country
country_response_count = pd.DataFrame(Covid51countries[['countryname', 'ISO3']].value_counts())

#collect the languages which people used to respond from each country
languages_per_country = Covid51countries.groupby('countryname')['Language_Name'].value_counts().reset_index(name="count")

# mereg num resposes to languages people used
languages_per_country = languages_per_country.merge(
    country_response_count,
    on="countryname",
    how="left"
)

# Clean up
languages_per_country = languages_per_country.rename(columns={"count_x": "lang_responses", "count_y": "total_responses"})
languages_per_country["percent"] = languages_per_country["lang_responses"] / languages_per_country["total_responses"] * 100

languages_per_country

,countryname,Language_Name,lang_responses,total_responses,percent
0,Australia,Simplified Chinese,181,378,47.883598
1,Australia,English,156,378,41.269841
2,Australia,Indonesian,12,378,3.174603
3,Australia,Traditional Chinese,10,378,2.645503
4,Australia,Vietnamese,5,378,1.322751
...,...,...,...,...,...
491,Vietnam,Simplified Chinese,2,338,0.591716
492,Vietnam,French,1,338,0.295858
493,Vietnam,Japanese,1,338,0.295858
494,Vietnam,Polish,1,338,0.295858
495,Vietnam,Traditional Chinese (Taiwan),1,338,0.295858

In [107]:
languages_per_country.to_csv(Path("~/Projects/hypocognition/data/processed/languages_per_country.csv").expanduser())

In [108]:
non_eng = languages_per_country[languages_per_country['Language_Name'] != "English"]
non_eng

,countryname,Language_Name,lang_responses,total_responses,percent
0,Australia,Simplified Chinese,181,378,47.883598
2,Australia,Indonesian,12,378,3.174603
3,Australia,Traditional Chinese,10,378,2.645503
4,Australia,Vietnamese,5,378,1.322751
5,Australia,Danish,3,378,0.793651
...,...,...,...,...,...
491,Vietnam,Simplified Chinese,2,338,0.591716
492,Vietnam,French,1,338,0.295858
493,Vietnam,Japanese,1,338,0.295858
494,Vietnam,Polish,1,338,0.295858
495,Vietnam,Traditional Chinese (Taiwan),1,338,0.295858

In [109]:
non_eng[non_eng['Language_Name']=="Dari"]

,countryname,Language_Name,lang_responses,total_responses,percent
308,Netherlands,Dari,3,1348,0.222552
425,Ukraine,Dari,1,698,0.143266
454,United Kingdom (UK),Dari,1,662,0.151057

In [110]:
# gather list of top names
try:
    del top4
except:
    pass
for n in non_eng['countryname'].unique():
    df = non_eng[non_eng['countryname'] == n].reset_index(drop=True)
    try:
        top4 = pd.concat([top4, df.iloc[0:len(df)]], ignore_index=True)
    except:
        top4 = df.iloc[0:len(df)]

top4

,countryname,Language_Name,lang_responses,total_responses,percent
0,Australia,Simplified Chinese,181,378,47.883598
1,Australia,Indonesian,12,378,3.174603
2,Australia,Traditional Chinese,10,378,2.645503
3,Australia,Vietnamese,5,378,1.322751
4,Australia,Danish,3,378,0.793651
...,...,...,...,...,...
441,Vietnam,Simplified Chinese,2,338,0.591716
442,Vietnam,French,1,338,0.295858
443,Vietnam,Japanese,1,338,0.295858
444,Vietnam,Polish,1,338,0.295858
445,Vietnam,Traditional Chinese (Taiwan),1,338,0.295858

In [111]:
# we are short the 2*50 rows we'd excpect.
top4['countryname'].value_counts()

countryname
Netherlands                       34
United Kingdom (UK)               31
United States of America (USA)    28
Germany                           26
France                            25
Spain                             21
Sweden                            20
Canada                            18
Hungary                           18
Italy                             17
Malta                             15
Australia                         14
Denmark                           13
Greece                            12
Japan                             11
Finland                            9
Singapore                          9
Brazil                             8
Israel                             8
New Zealand                        7
Malaysia                           7
Vietnam                            7
Turkey                             6
South Africa                       6
Ireland                            6
Mongolia                           6
Taiwan                             6
China                              5
Hong Kong (S.A.R)                  5
Ukraine                            5
India                              4
Indonesia                          4
Russia                             4
Bulgaria                           3
Chile                              3
Peru                               3
Syria                              2
Jordan                             2
Croatia                            2
Colombia                           2
Iran                               2
Curacao                            2
Serbia                             2
Kazakhstan                         2
Egypt                              1
Georgia                            1
Ghana                              1
Iceland                            1
Pakistan                           1
Trinidad and Tobago                1
Name: count, dtype: int64

In [112]:

covid_to_bila_nouns_full_lang_name_mapping = pd.read_csv(Path("~/Projects/hypocognition/data/external/covid_to_full_bila_lang_name_mapping.csv"))
covid_to_bila_nouns_full_lang_name_mapping

,code,study_language_names,bila_language_name_mapping,possible_alternative_bila_language_name_mappings
0,ZH-S,Simplified Chinese,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
1,EN,English,NaN,"Midland American English, Singlish, Devon, Sus..."
2,ID,Indonesian,Indonesian,"Standard Malay, Central Malay, Baba Malay"
3,ZH-T,Traditional Chinese,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese..."
4,VI,Vietnamese,Vietnamese,Nung (Viet Nam)
5,DA,Danish,Danish,NaN
6,AR,Arabic,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
7,ES,Spanish,Latin American Spanish,"Spanish, Mexican Spanish"
8,AFRI,Afrikaans,Afrikaans,Dutch
9,ES-ES,Spanish (Spain),Spanish,NaN
10,ET,Estonian,Estonian,Finnish
11,FR,French,French,"Old French, Cajun French, Louisiana Creole French"
12,JA,Japanese,Japanese,Middle Chinese
13,"HR, SR",Serbian-Croatian-Bosnian,Serbian-Croatian-Bosnian,NaN
14,ZH-TW,Traditional Chinese (Taiwan),Mandarin Chinese,"Min Nan Chinese, Hakka Chinese"
15,PT-BR,Brazilian Portuguese,Brazilian Portuguese,Portuguese
16,PT,Portuguese,Portuguese,Brazilian Portuguese
17,IT,Italian,Italian,Sicilian
18,BG,Bulgarian,Bulgarian,NaN
19,RU,Russian,Russian,Belarusian
20,FA,Persian,Persian,NaN
21,UK,Ukrainian,Ukrainian,NaN
22,NL,Dutch,Dutch,Western Flemish
23,DE,German,German,"Moselle Franconian, Plautdietsch, Pennsylvania..."
24,MS,Malay,Standard Malay,"Central Malay, Baba Malay, Malayo"
25,TR,Turkish,Turkish,Turkmen
26,ISL,Icelandic,Icelandic,Old Norse
27,NO,Norwegian,Norwegian,NaN
28,RO,Romanian,Romanian,Aromanian
29,FI,Finnish,Finnish,Estonian
30,KAT,Georgian,Georgian,NaN
31,SV,Swedish,Swedish,NaN
32,EL,Greek,Greek,NaN
33,CA,Catalan,NaN,"Spanish, French"
34,HU,Hungarian,Hungarian,NaN
35,SL,Slovenian,Slovenian,NaN
36,CS,Czech,Czech,NaN
37,PL,Polish,Polish,NaN
38,SK,Slovak,Slovak,NaN
39,MAR,Marathi,Marathi,NaN
40,HI,Hindi,Hindi,"Hindustani, Caribbean Hindustani"
41,HE,Hebrew,Hebrew,Ancient Hebrew
42,KO,Korean,Korean,NaN
43,KAZ,Kazakh,Kazakh,NaN
44,ML,Malayalam,Malayalam,NaN
45,MALTI,Maltese,NaN,"Arabic, Italian"
46,FILIP,Filipino,Filipino,Tagalog-Pilipino
47,DARI,Dari,Persian,NaN

In [113]:
covid_to_bila_nouns_full_lang_name_mapping['study_language_names'].nunique()

48

In [114]:
# Add the mapping to our selection table
selection = top4.merge(
    covid_to_bila_nouns_full_lang_name_mapping,
    left_on="Language_Name",
    right_on = "study_language_names",
    how = "left"
).drop(columns=["code", "study_language_names"])
selection

,countryname,Language_Name,lang_responses,total_responses,percent,bila_language_name_mapping,possible_alternative_bila_language_name_mappings
0,Australia,Simplified Chinese,181,378,47.883598,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
1,Australia,Indonesian,12,378,3.174603,Indonesian,"Standard Malay, Central Malay, Baba Malay"
2,Australia,Traditional Chinese,10,378,2.645503,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese..."
3,Australia,Vietnamese,5,378,1.322751,Vietnamese,Nung (Viet Nam)
4,Australia,Danish,3,378,0.793651,Danish,NaN
...,...,...,...,...,...,...,...
441,Vietnam,Simplified Chinese,2,338,0.591716,Mandarin Chinese,"Beijing Mandarin, Wu Chinese"
442,Vietnam,French,1,338,0.295858,French,"Old French, Cajun French, Louisiana Creole French"
443,Vietnam,Japanese,1,338,0.295858,Japanese,Middle Chinese
444,Vietnam,Polish,1,338,0.295858,Polish,NaN
445,Vietnam,Traditional Chinese (Taiwan),1,338,0.295858,Mandarin Chinese,"Min Nan Chinese, Hakka Chinese"

In [115]:
selection['Selected'] = np.nan
selection

,countryname,Language_Name,lang_responses,total_responses,percent,bila_language_name_mapping,possible_alternative_bila_language_name_mappings,Selected
0,Australia,Simplified Chinese,181,378,47.883598,Mandarin Chinese,"Beijing Mandarin, Wu Chinese",NaN
1,Australia,Indonesian,12,378,3.174603,Indonesian,"Standard Malay, Central Malay, Baba Malay",NaN
2,Australia,Traditional Chinese,10,378,2.645503,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese...",NaN
3,Australia,Vietnamese,5,378,1.322751,Vietnamese,Nung (Viet Nam),NaN
4,Australia,Danish,3,378,0.793651,Danish,NaN,NaN
...,...,...,...,...,...,...,...,...
441,Vietnam,Simplified Chinese,2,338,0.591716,Mandarin Chinese,"Beijing Mandarin, Wu Chinese",NaN
442,Vietnam,French,1,338,0.295858,French,"Old French, Cajun French, Louisiana Creole French",NaN
443,Vietnam,Japanese,1,338,0.295858,Japanese,Middle Chinese,NaN
444,Vietnam,Polish,1,338,0.295858,Polish,NaN,NaN
445,Vietnam,Traditional Chinese (Taiwan),1,338,0.295858,Mandarin Chinese,"Min Nan Chinese, Hakka Chinese",NaN

In [118]:
selection = pd.read_csv(Path("~/Projects/hypocognition/data/processed/selection_in_bila.csv").expanduser(), index_col=0).reset_index(drop=True)
selection = selection[selection['Selected']==1].rename(columns={'study_language_names':"Language_Name"} )

In [119]:
selection['countryname'].nunique()

38

In [23]:
selection

,countryname,Language_Name,lang_responses,total_responses,percent,bila_language_name_mapping,possible_alternative_bila_language_name_mappings,Selected
14,Brazil,Brazilian Portuguese,306,325,94.153846,Brazilian Portuguese,Portuguese,1
22,Bulgaria,Bulgarian,269,276,97.463768,Bulgarian,NaN,1
43,Chile,Spanish,469,493,95.131846,Latin American Spanish,"Spanish, Mexican Spanish",1
46,China,Simplified Chinese,1988,2009,98.954704,Mandarin Chinese,"Beijing Mandarin, Wu Chinese",1
51,Colombia,Spanish,122,237,51.476793,Latin American Spanish,"Spanish, Mexican Spanish",1
52,Colombia,Spanish (Spain),113,237,47.679325,Spanish,NaN,1
53,Croatia,Serbian-Croatian-Bosnian,526,528,99.621212,Serbian-Croatian-Bosnian,NaN,1
55,Curacao,Dutch,180,235,76.595745,Dutch,Western Flemish,1
57,Denmark,Danish,148,233,63.519313,Danish,NaN,1
70,Egypt,Arabic,817,824,99.150485,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar...",1
71,Finland,Finnish,260,289,89.965398,Finnish,Estonian,1
80,France,French,257,363,70.798898,French,"Old French, Cajun French, Louisiana Creole French",1
105,Georgia,Georgian,234,236,99.152542,Georgian,NaN,1
106,Germany,German,291,567,51.322751,German,"Moselle Franconian, Plautdietsch, Pennsylvania...",1
133,Greece,Greek,227,253,89.723320,Greek,NaN,1
145,Hong Kong (S.A.R),Traditional Chinese,139,228,60.964912,Mandarin Chinese,"Yue Chinese, Min Dong Chinese, Min Nan Chinese...",1
150,Hungary,Hungarian,256,464,55.172414,Hungarian,NaN,1
168,Iceland,Icelandic,348,354,98.305085,Icelandic,Old Norse,1
169,India,Marathi,56,243,23.045267,Marathi,NaN,1
173,Indonesia,Indonesian,648,656,98.780488,Indonesian,"Standard Malay, Central Malay, Baba Malay",1
177,Iran,Persian,187,195,95.897436,Persian,NaN,1
185,Israel,Hebrew,151,211,71.563981,Hebrew,Ancient Hebrew,1
193,Italy,Italian,426,466,91.416309,Italian,Sicilian,1
210,Japan,Japanese,1288,1352,95.266272,Japanese,Middle Chinese,1
221,Jordan,Arabic,233,236,98.728814,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar...",1
223,Kazakhstan,Russian,279,291,95.876289,Russian,Belarusian,1
225,Malaysia,Malay,155,214,72.429907,Standard Malay,"Central Malay, Baba Malay, Malayo",1
253,Netherlands,Dutch,524,1348,38.872404,Dutch,Western Flemish,1
295,Peru,Spanish (Spain),215,357,60.224090,Spanish,NaN,1
298,Russia,Russian,577,586,98.464164,Russian,Belarusian,1
302,Serbia,Serbian-Croatian-Bosnian,352,354,99.435028,Serbian-Croatian-Bosnian,NaN,1
313,South Africa,Afrikaans,112,426,26.291080,Afrikaans,Dutch,1
320,Spain,Spanish (Spain),105,418,25.119617,Spanish,NaN,1
340,Sweden,Swedish,400,529,75.614367,Swedish,NaN,1
360,Syria,Arabic,247,248,99.596774,Arabic,"Egyptian Arabic, Levantine Arabic, Moroccan Ar...",1
362,Taiwan,Traditional Chinese (Taiwan),747,761,98.160315,Mandarin Chinese,"Min Nan Chinese, Hakka Chinese",1
369,Turkey,Turkish,253,346,73.121387,Turkish,Turkmen,1
375,Ukraine,Ukrainian,657,698,94.126075,Ukrainian,NaN,1
439,Vietnam,Vietnamese,292,338,86.390533,Vietnamese,Nung (Viet Nam),1

In [ ]:
# simplest way to get the table right is to just tweak it in excel and load it back in. Mark the "Selection" column of outline_selection.csv with 1 for the languages we want to use
selection.to_csv(Path("~/Projects/hypocognition/data/processed/outline_selection.csv").expanduser())

In [120]:
#Rename outline_selection.csv to selection_in_bila.csv and load it back in
selection = pd.read_csv(Path("~/Projects/hypocognition/data/processed/selection_in_bila.csv").expanduser(), index_col=0).reset_index(drop=True)
selection = selection[selection['Selected']==1].rename(columns={'study_language_names':"Language_Name"} )

In [121]:
# those are all good exclusions.
# Lets try filtering the dataset using our new selection
filtered = Covid51countries.merge(
    selection,
    on=['countryname', 'Language_Name'],
    how='inner'
)

filtered

,country,countryname,ISO3,admiration,calm,compassion,determination,moved,gratitude,hope,...,regret,sadness,Code,Language_Name,lang_responses,total_responses,percent,bila_language_name_mapping,possible_alternative_bila_language_name_mappings,Selected
0,109,Malaysia,MYS,1.0,6.0,1.0,0.0,0.0,0.0,6.0,...,6.0,6.0,MS,Malay,155,214,72.429907,Standard Malay,"Central Malay, Baba Malay, Malayo",1
1,109,Malaysia,MYS,4.0,4.0,2.0,3.0,2.0,3.0,4.0,...,2.0,3.0,MS,Malay,155,214,72.429907,Standard Malay,"Central Malay, Baba Malay, Malayo",1
2,109,Malaysia,MYS,3.0,3.0,3.0,3.0,3.0,1.0,0.0,...,1.0,4.0,MS,Malay,155,214,72.429907,Standard Malay,"Central Malay, Baba Malay, Malayo",1
3,109,Malaysia,MYS,6.0,3.0,6.0,4.0,6.0,5.0,6.0,...,0.0,2.0,MS,Malay,155,214,72.429907,Standard Malay,"Central Malay, Baba Malay, Malayo",1
4,109,Malaysia,MYS,5.0,5.0,5.0,6.0,4.0,6.0,5.0,...,2.0,3.0,MS,Malay,155,214,72.429907,Standard Malay,"Central Malay, Baba Malay, Malayo",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14849,91,Kazakhstan,KAZ,1.0,3.0,3.0,1.0,5.0,5.0,3.0,...,3.0,2.0,RU,Russian,279,291,95.876289,Russian,Belarusian,1
14850,91,Kazakhstan,KAZ,3.0,3.0,6.0,2.0,6.0,5.0,5.0,...,6.0,5.0,RU,Russian,279,291,95.876289,Russian,Belarusian,1
14851,91,Kazakhstan,KAZ,3.0,3.0,3.0,3.0,4.0,4.0,0.0,...,4.0,3.0,RU,Russian,279,291,95.876289,Russian,Belarusian,1
14852,91,Kazakhstan,KAZ,2.0,3.0,6.0,2.0,2.0,1.0,6.0,...,6.0,4.0,RU,Russian,279,291,95.876289,Russian,Belarusian,1
14853,91,Kazakhstan,KAZ,0.0,1.0,4.0,2.0,1.0,3.0,1.0,...,6.0,5.0,RU,Russian,279,291,95.876289,Russian,Belarusian,1

In [122]:
filtered.columns

Index(['country', 'countryname', 'ISO3', 'admiration', 'calm', 'compassion',
       'determination', 'moved', 'gratitude', 'hope', 'love', 'relief',
       'pleasure', 'anger', 'anxiety', 'boredom', 'confusion', 'disgust',
       'fear', 'frustration', 'loneliness', 'regret', 'sadness', 'Code',
       'Language_Name', 'lang_responses', 'total_responses', 'percent',
       'bila_language_name_mapping',
       'possible_alternative_bila_language_name_mappings', 'Selected'],
      dtype='object')

In [123]:
# Check to make sure it worked
filtered.groupby('countryname')['Language_Name'].unique()

countryname
Brazil                       [Brazilian Portuguese]
Bulgaria                                [Bulgarian]
Chile                                     [Spanish]
China                          [Simplified Chinese]
Colombia                 [Spanish, Spanish (Spain)]
Croatia                  [Serbian-Croatian-Bosnian]
Curacao                                     [Dutch]
Denmark                                    [Danish]
Egypt                                      [Arabic]
Finland                                   [Finnish]
France                                     [French]
Georgia                                  [Georgian]
Germany                                    [German]
Greece                                      [Greek]
Hong Kong (S.A.R)             [Traditional Chinese]
Hungary                                 [Hungarian]
Iceland                                 [Icelandic]
India                                     [Marathi]
Indonesia                              [Indonesian]
Iran                                      [Persian]
Israel                                     [Hebrew]
Italy                                     [Italian]
Japan                                    [Japanese]
Jordan                                     [Arabic]
Kazakhstan                                [Russian]
Malaysia                                    [Malay]
Netherlands                                 [Dutch]
Peru                              [Spanish (Spain)]
Russia                                    [Russian]
Serbia                   [Serbian-Croatian-Bosnian]
South Africa                            [Afrikaans]
Spain                             [Spanish (Spain)]
Sweden                                    [Swedish]
Syria                                      [Arabic]
Taiwan               [Traditional Chinese (Taiwan)]
Turkey                                    [Turkish]
Ukraine                                 [Ukrainian]
Vietnam                                [Vietnamese]
Name: Language_Name, dtype: object

In [124]:
filtered.groupby('countryname')['bila_language_name_mapping'].unique()

countryname
Brazil                          [Brazilian Portuguese]
Bulgaria                                   [Bulgarian]
Chile                         [Latin American Spanish]
China                               [Mandarin Chinese]
Colombia             [Latin American Spanish, Spanish]
Croatia                     [Serbian-Croatian-Bosnian]
Curacao                                        [Dutch]
Denmark                                       [Danish]
Egypt                                         [Arabic]
Finland                                      [Finnish]
France                                        [French]
Georgia                                     [Georgian]
Germany                                       [German]
Greece                                         [Greek]
Hong Kong (S.A.R)                   [Mandarin Chinese]
Hungary                                    [Hungarian]
Iceland                                    [Icelandic]
India                                        [Marathi]
Indonesia                                 [Indonesian]
Iran                                         [Persian]
Israel                                        [Hebrew]
Italy                                        [Italian]
Japan                                       [Japanese]
Jordan                                        [Arabic]
Kazakhstan                                   [Russian]
Malaysia                              [Standard Malay]
Netherlands                                    [Dutch]
Peru                                         [Spanish]
Russia                                       [Russian]
Serbia                      [Serbian-Croatian-Bosnian]
South Africa                               [Afrikaans]
Spain                                        [Spanish]
Sweden                                       [Swedish]
Syria                                         [Arabic]
Taiwan                              [Mandarin Chinese]
Turkey                                       [Turkish]
Ukraine                                    [Ukrainian]
Vietnam                                   [Vietnamese]
Name: bila_language_name_mapping, dtype: object

Goals
* For each distinct language, what is the lexical ellaboration for each of the 20 emotions?
* For each distinct language, is there any statistical significance in the distribution of the results of any particular emotion?

In [125]:
emotions = ['admiration', 'calm', 'compassion',
       'determination', 'moved', 'gratitude', 'hope', 'love', 'relief',
       'pleasure', 'anger', 'anxiety', 'boredom', 'confusion', 'disgust',
       'fear', 'frustration', 'loneliness', 'regret', 'sadness']

In [126]:
# get the dataset of the dictionaries. We will look at how elaborated each of the twenty emotions are in each of the 39 languages
bila_nouns_full = pd.read_csv(Path("~/Projects/hypocognition/data/raw/bila_long_noun_lemmatized_full.csv").expanduser(), index_col=0)
bila_nouns_full

/tmp/ipykernel_745939/268126284.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  bila_nouns_full = pd.read_csv(Path("~/Projects/hypocognition/data/raw/bila_long_noun_lemmatized_full.csv").expanduser(), index_col=0)

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,estimate,regression_elaboration,dictsize_data,simple_elaboration,log_count
0,chi.14718491,ability,2.0,2.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.725128,-1.424169,10499,0.000190,1.098612
1,chi.14718491,accomplice,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-0.156552,10499,0.000000,0.000000
2,chi.14718491,account,14.0,9.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-7.520776,-2.250524,10499,0.000857,2.302585
3,chi.14718491,acre,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-0.444142,10499,0.000000,0.000000
4,chi.14718491,act,15.0,6.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,0.000000,0.000000,10499,0.000571,1.945910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5282195,wu.89119131142,prouds,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282196,wu.89119131142,facilitator,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282197,wu.89119131142,teacher-librarian,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282198,wu.89119131142,pandani,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000
5282199,wu.89119131142,seat-bone,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,0.000000,0.000000,33359,0.000000,0.000000

In [127]:
# with open(Path("~/Projects/hypocognition/data/external/stopwords.txt").expanduser()) as f:
#     words = [line.strip() for line in f if line.strip()]
# # remove stop words
# bila_nouns_full = bila_nouns_full[~bila_nouns_full["word"].isin(words)]
# bila_nouns_full

In [159]:
tot_words = bila_nouns_full[bila_nouns_full['count']>0].groupby('id')['word'].nunique().reset_index(name='Total_words_in_dict')
tot_words_old = bila_nouns_full.groupby('id')['word'].nunique().reset_index(name='Total_words_in_dict')
tot_counts = bila_nouns_full.groupby('id')['count'].sum().reset_index(name='Total_counts_in_dict')

In [138]:
tot_words

                                          id  Total_words_in_dict
0                               chi.14718491                 1768
1                         coo.31924067983704                 6449
2                         coo.31924099174934                 4068
3                  coo1.ark:/13960/t9m33d507                 4758
4     dictionaria.daakaka_vonprince_daka1243                  829
..                                       ...                  ...
611  webonary.sursurunga_hutchisson_surs1246                 2337
612         webonary.tampulma_asare_tamp1252                  883
613      webonary.turkmen_almamedow_turk1304                 3951
614                           wu.89017649658                 2983
615                           wu.89119131142                 3426

[616 rows x 2 columns]

In [139]:
tot_counts

                                          id  Total_counts_in_dict
0                               chi.14718491               14415.0
1                         coo.31924067983704              146478.0
2                         coo.31924099174934               11458.0
3                  coo1.ark:/13960/t9m33d507               24896.0
4     dictionaria.daakaka_vonprince_daka1243                2366.0
..                                       ...                   ...
611  webonary.sursurunga_hutchisson_surs1246               52879.0
612         webonary.tampulma_asare_tamp1252                7386.0
613      webonary.turkmen_almamedow_turk1304               35714.0
614                           wu.89017649658               13818.0
615                           wu.89119131142               47587.0

[616 rows x 2 columns]

In [135]:
14415.0/8575

1.6810495626822157

In [166]:
dict_means2 = pd.DataFrame({'id': tot_counts['id'], 'dict_mean': tot_counts['Total_counts_in_dict'] / tot_words_old['Total_words_in_dict']})
dict_means2

                                          id  dict_mean
0                               chi.14718491   1.681050
1                         coo.31924067983704  17.081983
2                         coo.31924099174934   1.336210
3                  coo1.ark:/13960/t9m33d507   2.903324
4     dictionaria.daakaka_vonprince_daka1243   0.275918
..                                       ...        ...
611  webonary.sursurunga_hutchisson_surs1246   6.166647
612         webonary.tampulma_asare_tamp1252   0.861341
613      webonary.turkmen_almamedow_turk1304   4.164898
614                           wu.89017649658   1.611429
615                           wu.89119131142   5.549504

[616 rows x 2 columns]

In [167]:
dict_means = pd.DataFrame({'id': tot_counts['id'], 'dict_mean': tot_counts['Total_counts_in_dict'] / tot_words['Total_words_in_dict']})
dict_means

                                          id  dict_mean
0                               chi.14718491   8.153281
1                         coo.31924067983704  22.713289
2                         coo.31924099174934   2.816618
3                  coo1.ark:/13960/t9m33d507   5.232451
4     dictionaria.daakaka_vonprince_daka1243   2.854041
..                                       ...        ...
611  webonary.sursurunga_hutchisson_surs1246  22.626872
612         webonary.tampulma_asare_tamp1252   8.364666
613      webonary.turkmen_almamedow_turk1304   9.039231
614                           wu.89017649658   4.632249
615                           wu.89119131142  13.889959

[616 rows x 2 columns]

In [31]:
# I think we will needs these later
dictionary_means = (
    bila_nouns_full
        .groupby('id', as_index=False)['count']
        .mean()
        .rename(columns={'count': 'dictionary_count_mean'})
)

In [136]:
dictionary_means

                                          id  dictionary_count_mean
0                               chi.14718491               1.681050
1                         coo.31924067983704              17.081983
2                         coo.31924099174934               1.336210
3                  coo1.ark:/13960/t9m33d507               2.903324
4     dictionaria.daakaka_vonprince_daka1243               0.275918
..                                       ...                    ...
611  webonary.sursurunga_hutchisson_surs1246               6.166647
612         webonary.tampulma_asare_tamp1252               0.861341
613      webonary.turkmen_almamedow_turk1304               4.164898
614                           wu.89017649658               1.611429
615                           wu.89119131142               5.549504

[616 rows x 2 columns]

In [134]:
bila_nouns_full.groupby('id', as_index=False)['count'].sum()

                                          id     count
0                               chi.14718491   14415.0
1                         coo.31924067983704  146478.0
2                         coo.31924099174934   11458.0
3                  coo1.ark:/13960/t9m33d507   24896.0
4     dictionaria.daakaka_vonprince_daka1243    2366.0
..                                       ...       ...
611  webonary.sursurunga_hutchisson_surs1246   52879.0
612         webonary.tampulma_asare_tamp1252    7386.0
613      webonary.turkmen_almamedow_turk1304   35714.0
614                           wu.89017649658   13818.0
615                           wu.89119131142   47587.0

[616 rows x 2 columns]

In [32]:
# filter just the emotions
bila_nouns_full_emotions = bila_nouns_full[bila_nouns_full['word'].isin(emotions)].reset_index(drop=True)
bila_nouns_full_emotions

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,estimate,regression_elaboration,dictsize_data,simple_elaboration,log_count
0,chi.14718491,fear,8.0,9.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-7.520776,-1.337584,10499,0.000857,2.302585
1,chi.14718491,pleasure,5.0,5.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.031819,-1.571145,10499,0.000476,1.791759
2,chi.14718491,regret,5.0,2.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.725128,-0.486657,10499,0.000190,1.098612
3,chi.14718491,admiration,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-9.823849,-0.710507,10499,0.000000,0.000000
4,chi.14718491,anger,5.0,2.0,Nancowry,nanc1247,1884.0,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.725128,-2.335062,10499,0.000190,1.098612
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11083,wu.89119131142,disgust,3.0,16.0,Herero,here1253,1989.0,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,-7.795743,3.869782,33359,0.000480,2.833213
11084,wu.89119131142,frustration,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-10.629344,-0.596842,33359,0.000000,0.000000
11085,wu.89119131142,loneliness,3.0,4.0,Herero,here1253,1989.0,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,-9.019809,1.825273,33359,0.000120,1.609438
11086,wu.89119131142,relief,11.0,10.0,Herero,here1253,1989.0,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,-8.231207,0.866433,33359,0.000300,2.397895
11087,wu.89119131142,boredom,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0.0000,0.00000,-10.629344,-0.597769,33359,0.000000,0.000000

the dataset is missing two of the survey emotions, {'calm', 'moved'}

In [33]:
filtered.columns

Index(['country', 'countryname', 'ISO3', 'admiration', 'calm', 'compassion',
       'determination', 'moved', 'gratitude', 'hope', 'love', 'relief',
       'pleasure', 'anger', 'anxiety', 'boredom', 'confusion', 'disgust',
       'fear', 'frustration', 'loneliness', 'regret', 'sadness', 'Code',
       'Language_Name', 'lang_responses', 'total_responses', 'percent',
       'bila_language_name_mapping',
       'possible_alternative_bila_language_name_mappings', 'Selected'],
      dtype='object')

In [34]:
filtered['bila_language_name_mapping'].nunique()

29

In [35]:
filtered['Language_Name'].nunique()

31

In [36]:
filtered['countryname'].nunique()

38

In [37]:
# already filtered out everything but the 18 emotions
# now we want to filter evrything but the 29 dictionaries
# Where are lang_name and Language_Names the Same?
bila_nouns_full_emotions_filtered = bila_nouns_full_emotions[bila_nouns_full_emotions['langname'].isin(filtered['bila_language_name_mapping'].unique())].reset_index(drop=True)
bila_nouns_full_emotions_filtered

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,estimate,regression_elaboration,dictsize_data,simple_elaboration,log_count
0,coo.31924067983704,fear,8.0,126.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-6.924086,1.952545,121674,0.001036,4.844187
1,coo.31924067983704,pleasure,5.0,107.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-7.086289,3.153327,121674,0.000879,4.682131
2,coo.31924067983704,regret,5.0,41.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-8.031261,2.670962,121674,0.000337,3.737670
3,coo.31924067983704,admiration,3.0,10.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-9.371276,-0.854986,121674,0.000082,2.397895
4,coo.31924067983704,anger,5.0,85.0,Turkish,nucl1301,1991.0,Redhouse yeni Türkçe-İngilizce sözlük = New Re...,"Redhouse Yayınevi, 1991, c1968.",0,Eurasia,Turkic,"Turkic, Common Turkic, Oghuz, Nuclear Oghuz, W...",32.8667,39.8667,-7.314243,0.579516,121674,0.000699,4.454347
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,uva.x004877953,disgust,3.0,13.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-9.940215,-4.505457,282895,0.000046,2.639057
500,uva.x004877953,frustration,3.0,6.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-10.633387,-1.588076,282895,0.000021,1.945910
501,uva.x004877953,loneliness,3.0,7.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-10.499852,-1.873436,282895,0.000025,2.079442
502,uva.x004877953,relief,11.0,89.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-8.079201,3.907437,282895,0.000315,4.499810
503,uva.x004877953,boredom,1.0,6.0,Japanese,nucl1643,1974.0,Kenkyusha's new Japanese-English dictionary. K...,Kenkyusha [1974],0,Eurasia,Japonic,"Japonic, Japanesic, Japan-Taiwan Japanese",135.0000,35.0000,-10.633387,-1.590590,282895,0.000021,1.945910

In [38]:
print(bila_nouns_full_emotions_filtered['langname'].nunique())

29

In [39]:
filtered = filtered.loc[:, ~filtered.columns.duplicated()]

In [40]:

bila_nouns_full_emotions_filtered['langname'].nunique()

29

In [41]:
word_counts = (
    bila_nouns_full_emotions_filtered
    .groupby("langname")["word"]
    .nunique()
    .reset_index(name="n_unique_words")
)
word_counts

                    langname  n_unique_words
0                  Afrikaans              18
1                     Arabic              18
2       Brazilian Portuguese               8
3                  Bulgarian              17
4                     Danish              18
5                      Dutch              18
6                    Finnish              18
7                     French              18
8                   Georgian              16
9                     German              18
10                     Greek              18
11                    Hebrew              16
12                 Hungarian              17
13                 Icelandic              17
14                Indonesian              18
15                   Italian              18
16                  Japanese              18
17    Latin American Spanish              18
18          Mandarin Chinese              18
19                   Marathi              17
20                   Persian              18
21                   Russian              18
22  Serbian-Croatian-Bosnian              18
23                   Spanish              18
24            Standard Malay              18
25                   Swedish              18
26                   Turkish              18
27                 Ukrainian              18
28                Vietnamese              18

In [42]:
bila_nouns_full_emotions_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 504 entries, 0 to 503
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      504 non-null    object
 1   word                    504 non-null    object
 2   nsenses                 504 non-null    float64
 3   count                   504 non-null    float64
 4   langname                504 non-null    object
 5   glottocode              504 non-null    object
 6   year                    504 non-null    float64
 7   title                   504 non-null    object
 8   imprint                 504 non-null    object
 9   author                  504 non-null    object
 10  area                    504 non-null    object
 11  langfamily              504 non-null    object
 12  affiliation             504 non-null    object
 13  longitude               504 non-null    float64
 14  latitude                504 non-null    float64
 15  estimate                504 non-null    float64
 16  regression_elaboration  504 non-null    float64
 17  dictsize_data           504 non-null    int64
 18  simple_elaboration      504 non-null    float64
 19  log_count               504 non-null    float64
dtypes: float64(9), int64(1), object(10)
memory usage: 78.9+ KB

In [43]:
# add the rows of the emotions words which don't appear in each dictionary

full_index = pd.MultiIndex.from_product(
    [bila_nouns_full_emotions_filtered["id"].unique(), bila_nouns_full_emotions_filtered["word"].unique()],
    names=["id", "word"]
)

In [44]:
# use the full index to add the missing values
bila_nouns_full_emotions_filtered_full = (
    bila_nouns_full_emotions_filtered
    .set_index(["id", "word"])
    .reindex(full_index)
    .reset_index()
)
num_cols = ["nsenses", "count", "log_count", 'regression_elaboration', 'dictsize_data', 'simple_elaboration']
bila_nouns_full_emotions_filtered_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 522 entries, 0 to 521
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      522 non-null    object
 1   word                    522 non-null    object
 2   nsenses                 504 non-null    float64
 3   count                   504 non-null    float64
 4   langname                504 non-null    object
 5   glottocode              504 non-null    object
 6   year                    504 non-null    float64
 7   title                   504 non-null    object
 8   imprint                 504 non-null    object
 9   author                  504 non-null    object
 10  area                    504 non-null    object
 11  langfamily              504 non-null    object
 12  affiliation             504 non-null    object
 13  longitude               504 non-null    float64
 14  latitude                504 non-null    float64
 15  estimate                504 non-null    float64
 16  regression_elaboration  504 non-null    float64
 17  dictsize_data           504 non-null    float64
 18  simple_elaboration      504 non-null    float64
 19  log_count               504 non-null    float64
dtypes: float64(10), object(10)
memory usage: 81.7+ KB

In [45]:

#set the number columns to 0 where NaN
bila_nouns_full_emotions_filtered_full[num_cols] = bila_nouns_full_emotions_filtered_full[num_cols].fillna(0)
meta_cols = [
    "langname", "glottocode", "year", "title", "imprint", "author",
    "area", "langfamily", "affiliation", "longitude", "latitude"
]
bila_nouns_full_emotions_filtered_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 522 entries, 0 to 521
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      522 non-null    object
 1   word                    522 non-null    object
 2   nsenses                 522 non-null    float64
 3   count                   522 non-null    float64
 4   langname                504 non-null    object
 5   glottocode              504 non-null    object
 6   year                    504 non-null    float64
 7   title                   504 non-null    object
 8   imprint                 504 non-null    object
 9   author                  504 non-null    object
 10  area                    504 non-null    object
 11  langfamily              504 non-null    object
 12  affiliation             504 non-null    object
 13  longitude               504 non-null    float64
 14  latitude                504 non-null    float64
 15  estimate                504 non-null    float64
 16  regression_elaboration  522 non-null    float64
 17  dictsize_data           522 non-null    float64
 18  simple_elaboration      522 non-null    float64
 19  log_count               522 non-null    float64
dtypes: float64(10), object(10)
memory usage: 81.7+ KB

In [46]:
# fill the those zero rows with dictionary meta -data
bila_nouns_full_emotions_filtered_full[meta_cols] = (
    bila_nouns_full_emotions_filtered_full
    .groupby("id")[meta_cols]
    .transform("first")
)

bila_nouns_full_emotions_filtered_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 522 entries, 0 to 521
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      522 non-null    object
 1   word                    522 non-null    object
 2   nsenses                 522 non-null    float64
 3   count                   522 non-null    float64
 4   langname                522 non-null    object
 5   glottocode              522 non-null    object
 6   year                    522 non-null    float64
 7   title                   522 non-null    object
 8   imprint                 522 non-null    object
 9   author                  522 non-null    object
 10  area                    522 non-null    object
 11  langfamily              522 non-null    object
 12  affiliation             522 non-null    object
 13  longitude               522 non-null    float64
 14  latitude                522 non-null    float64
 15  estimate                504 non-null    float64
 16  regression_elaboration  522 non-null    float64
 17  dictsize_data           522 non-null    float64
 18  simple_elaboration      522 non-null    float64
 19  log_count               522 non-null    float64
dtypes: float64(10), object(10)
memory usage: 81.7+ KB

In [47]:
# now we're don emaking datasets, this is a table of just the stuff we need for correlations
elab_per_emotion = bila_nouns_full_emotions_filtered_full[['langname',   'glottocode','word', 'count',  'id', 'year',"simple_elaboration", "regression_elaboration",	"dictsize_data"	]]
elab_per_emotion

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data
0,Turkish,nucl1301,fear,126.0,coo.31924067983704,1991.0,0.001036,1.952545,121674.0
1,Turkish,nucl1301,pleasure,107.0,coo.31924067983704,1991.0,0.000879,3.153327,121674.0
2,Turkish,nucl1301,regret,41.0,coo.31924067983704,1991.0,0.000337,2.670962,121674.0
3,Turkish,nucl1301,admiration,10.0,coo.31924067983704,1991.0,0.000082,-0.854986,121674.0
4,Turkish,nucl1301,anger,85.0,coo.31924067983704,1991.0,0.000699,0.579516,121674.0
...,...,...,...,...,...,...,...,...,...
517,Japanese,nucl1643,disgust,13.0,uva.x004877953,1974.0,0.000046,-4.505457,282895.0
518,Japanese,nucl1643,frustration,6.0,uva.x004877953,1974.0,0.000021,-1.588076,282895.0
519,Japanese,nucl1643,loneliness,7.0,uva.x004877953,1974.0,0.000025,-1.873436,282895.0
520,Japanese,nucl1643,relief,89.0,uva.x004877953,1974.0,0.000315,3.907437,282895.0
521,Japanese,nucl1643,boredom,6.0,uva.x004877953,1974.0,0.000021,-1.590590,282895.0

In [166]:
elab_per_emotion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   langname                18 non-null     object
 1   glottocode              18 non-null     object
 2   word                    18 non-null     object
 3   count                   18 non-null     float64
 4   id                      18 non-null     object
 5   year                    18 non-null     float64
 6   simple_elaboration      18 non-null     float64
 7   regression_elaboration  18 non-null     float64
 8   dictsize_data           18 non-null     int64
dtypes: float64(4), int64(1), object(4)
memory usage: 1.4+ KB

In [48]:
# Make table of the 18 languages for each country
stats_by_country = (
    filtered
    .groupby(['countryname', 'bila_language_name_mapping'])[emotions]
    .agg(['mean', 'std'])
)
stats_by_country = pd.DataFrame(stats_by_country)
stats_by_country

                                             admiration                calm  \
                                                   mean       std      mean
countryname       bila_language_name_mapping
Brazil            Brazilian Portuguese         3.540984  1.745047  3.421569
Bulgaria          Bulgarian                    2.498141  1.980548  3.334572
Chile             Latin American Spanish       2.867521  1.901080  2.899358
China             Mandarin Chinese             4.365940  1.736698  3.914807
Colombia          Latin American Spanish       3.409836  1.974022  3.418033
                  Spanish                      3.732143  1.981819  4.256637
Croatia           Serbian-Croatian-Bosnian     2.548571  1.680610  3.336502
Curacao           Dutch                        3.627778  1.743401  3.961111
Denmark           Danish                       2.668919  1.513605  3.445946
Egypt             Arabic                       2.547472  1.886575  3.622222
Finland           Finnish                      2.738462  1.547467  3.726923
France            French                       3.357977  1.801764  3.746094
Georgia           Georgian                     2.523605  1.866354  3.248927
Germany           German                       2.804124  1.800225  3.628866
Greece            Greek                        2.328889  1.887059  3.337778
Hong Kong (S.A.R) Mandarin Chinese             2.669065  1.770894  3.064748
Hungary           Hungarian                    2.679688  1.925815  3.265625
Iceland           Icelandic                    3.469741  1.867297  3.299712
India             Marathi                      3.500000  1.768410  3.982143
Indonesia         Indonesian                   3.201863  1.577327  3.834365
Iran              Persian                      2.347826  1.745782  2.774194
Israel            Hebrew                       1.569536  1.718565  3.240000
Italy             Italian                      2.966981  1.900316  3.327059
Japan             Japanese                     2.602176  1.523357  3.559441
Jordan            Arabic                       3.108225  1.965235  3.952586
Kazakhstan        Russian                      2.438849  1.958468  3.469534
Malaysia          Standard Malay               3.793548  1.548761  4.000000
Netherlands       Dutch                        3.325048  1.646279  3.671756
Peru              Spanish                      3.706161  1.884501  3.693023
Russia            Russian                      2.553043  1.774840  3.349565
Serbia            Serbian-Croatian-Bosnian     2.716332  1.845246  3.518519
South Africa      Afrikaans                    2.946429  1.712904  3.642857
Spain             Spanish                      3.428571  1.994498  3.428571
Sweden            Swedish                      3.300000  1.774224  3.580000
Syria             Arabic                       1.849372  1.996402  3.377593
Taiwan            Mandarin Chinese             3.993307  1.660520  3.666667
Turkey            Turkish                      2.027888  1.760460  3.611111
Ukraine           Ukrainian                    2.856489  1.644428  3.203957
Vietnam           Vietnamese                   4.219178  1.746841  4.263699

                                                       compassion            \
                                                   std       mean       std
countryname       bila_language_name_mapping
Brazil            Brazilian Portuguese        1.502585   4.633987  1.319471
Bulgaria          Bulgarian                   1.712431   4.313433  1.590788
Chile             Latin American Spanish      1.546330   3.893390  1.693798
China             Mandarin Chinese            1.683731   4.240976  1.701800
Colombia          Latin American Spanish      1.419115   4.024590  1.678563
                  Spanish                     1.468592   4.194690  1.821785
Croatia           Serbian-Croatian-Bosnian    1.487369   2.916190  1.657917
Curacao           Dutch                       1.607816   4.777778  1.174951
Denmark           Danish                      1.531012   4.067568  1.450602
Egypt             Arabic                      1.728264   4.173006  1.710858
Finland           Finnish                     1.380520   4.042471  1.350471
France            French                      1.587322   3.809339  1.648458
Georgia           Georgian                    1.698836   4.444444  1.507887
Germany           German                      1.620895   4.347079  1.283778
Greece            Greek                       1.538681   3.843049  1.662391
Hong Kong (S.A.R) Mandarin Chinese            1.455667   3.323741  1.616114
Hungary           Hungarian                   1.730848   4.507812  1.343079
Iceland           Icelandic                   1.757585   4.388406  1.601193
India             Marathi                     1.700172   3.946429  1.633954
Indonesia         Indonesian                  1.327863   4.547287  1.238492
Iran              Persian                     1.831431   3.770053  1.705639
Israel            Hebrew                      1.407935   4.013245  1.316494
Italy             Italian                     1.516839   3.613208  1.729022
Japan             Japanese                    1.254913   3.533385  1.375941
Jordan            Arabic                      1.807247   4.359307  1.718414
Kazakhstan        Russian                     1.641953   3.602151  1.755606
Malaysia          Standard Malay              1.232672   4.432258  1.304435
Netherlands       Dutch                       1.413904   4.160305  1.402357
Peru              Spanish                     1.503484   4.483721  1.500301
Russia            Russian                     1.524902   3.557292  1.654564
Serbia            Serbian-Croatian-Bosnian    1.578091   4.308571  1.464650
South Africa      Afrikaans                   1.341353   4.196429  1.505780
Spain             Spanish                     1.616365   3.971154  1.742984
Sweden            Swedish                     1.482936   4.537500  1.289477
Syria             Arabic                      2.045971   3.878543  1.921589
Taiwan            Mandarin Chinese            1.549020   3.722520  1.628423
Turkey            Turkish                     1.439191   3.956349  1.627111
Ukraine           Ukrainian                   1.565963   3.576220  1.516419
Vietnam           Vietnamese                  1.350442   3.872852  1.779476

                                             determination            \
                                                      mean       std
countryname       bila_language_name_mapping
Brazil            Brazilian Portuguese            3.725490  1.593986
Bulgaria          Bulgarian                       3.565056  1.684113
Chile             Latin American Spanish          3.370450  1.700109
China             Mandarin Chinese                4.165992  1.693406
Colombia          Latin American Spanish          3.818182  1.653280
                  Spanish                         4.247788  1.538384
Croatia           Serbian-Croatian-Bosnian        3.516190  1.441686
Curacao           Dutch                           4.000000  1.549914
Denmark           Danish                          3.351351  1.483996
Egypt             Arabic                          3.161090  1.728845
Finland           Finnish                         3.532819  1.327221
France            French                          3.727626  1.582292
Georgia           Georgian                        3.692308  1.815345
Germany           German                          3.468966  1.464955
Greece            Greek                           3.444934  1.682894
Hong Kong (S.A.R) Mandarin Chinese                3.366906  1.489791
Hungary           Hungarian                       3.652344  1.698972
Iceland           Icelandic                       3.589595  1.611303
India             Marathi                         3.660714  1.880781
Indonesia         Indonesian                      3.827372  1.301711
Iran              Persian                         3.290323  1.601220
Israel            Hebrew                          3.403974  1.493001
Italy             Italian                         3.716981  1.558958
Japan             Japanese                        2.964258  1.522347
Jordan            Arabic                          3.754386  1.846828
Kazakhstan        Russian                         3.283154  1.783851
Malaysia          Standard Malay                  3.845161  1.372939
Netherlands       Dutch                           3.553435  1.404380
Peru              Spanish                         3.939252  1.457070
Russia            Russian                         3.057292  1.579824
Serbia            Serbian-Croatian-Bosnian        3.792023  1.578261
South Africa      Afrikaans                       3.696429  1.570214
Spain             Spanish                         3.461538  1.773172
Sweden            Swedish                         3.675000  1.374445
Syria             Arabic                          2.888889  2.168520
Taiwan            Mandarin Chinese                3.695710  1.540472
Turkey            Turkish                         3.804781  1.561325
Ukraine           Ukrainian                       3.260274  1.528436
Vietnam           Vietnamese                      4.096220  1.507803

                                                 moved            ...  \
                                                  mean       std  ...
countryname       bila_language_name_mapping                      ...
Brazil            Brazilian Portuguese        4.464052  1.603382  ...
Bulgaria          Bulgarian                   3.587361  1.860024  ...
Chile             Latin American Spanish      3.886266  1.722072  ...
China             Mandarin Chinese            4.426538  1.700508  ...
Colombia          Latin American Spanish      4.049180  1.719372  ...
                  Spanish                     4.194690  1.608340  ...
Croatia           Serbian-Croatian-Bosnian    2.663498  1.667298  ...
Curacao           Dutch                       3.394444  1.632413  ...
Denmark           Danish                      3.304054  1.417379  ...
Egypt             Arabic                      4.028325  1.684172  ...
Finland           Finnish                     3.084615  1.655852  ...
France            French                      3.046693  1.710994  ...
Georgia           Georgian                    3.424893  1.794310  ...
Germany           German                      3.529412  1.559024  ...
Greece            Greek                       3.273128  1.910690  ...
Hong Kong (S.A.R) Mandarin Chinese            2.920863  1.597393  ...
Hungary           Hungarian                   2.847656  1.927162  ...
Iceland           Icelandic                   2.489914  1.878318  ...
India             Marathi                     2.357143  1.920498  ...
Indonesia         Indonesian                  4.057099  1.293718  ...
Iran              Persian                     3.150538  1.845059  ...
Israel            Hebrew                      2.980132  1.601958  ...
Italy             Italian                     3.280660  1.828072  ...
Japan             Japanese                    2.777174  1.525502  ...
Jordan            Arabic                      3.899123  1.781797  ...
Kazakhstan        Russian                     2.587814  2.029990  ...
Malaysia          Standard Malay              3.490323  1.656815  ...
Netherlands       Dutch                       3.409178  1.592870  ...
Peru              Spanish                     4.455814  1.493491  ...
Russia            Russian                     2.503484  1.727255  ...
Serbia            Serbian-Croatian-Bosnian    3.338068  1.769293  ...
South Africa      Afrikaans                   3.142857  1.686497  ...
Spain             Spanish                     3.894231  1.576023  ...
Sweden            Swedish                     3.120000  1.646931  ...
Syria             Arabic                      3.651452  1.962908  ...
Taiwan            Mandarin Chinese            3.935657  1.593995  ...
Turkey            Turkish                     3.234127  1.854451  ...
Ukraine           Ukrainian                   2.955860  1.657264  ...
Vietnam           Vietnamese                  4.185567  1.667105  ...

                                                  fear           frustration  \
                                                  mean       std        mean
countryname       bila_language_name_mapping
Brazil            Brazilian Portuguese        3.603279  1.757500    3.437908
Bulgaria          Bulgarian                   2.561338  1.954938    3.029740
Chile             Latin American Spanish      3.528785  1.836746    4.119914
China             Mandarin Chinese            1.809500  1.726083    1.815642
Colombia          Latin American Spanish      3.024590  1.943258    3.409836
                  Spanish                     2.398230  1.825121    2.929204
Croatia           Serbian-Croatian-Bosnian    2.740952  1.825796    3.420952
Curacao           Dutch                       2.477778  1.933115    3.005556
Denmark           Danish                      1.824324  1.610832    3.148649
Egypt             Arabic                      3.556790  1.953694    3.419434
Finland           Finnish                     2.509653  1.600298    3.846154
France            French                      2.155642  1.796018    3.156250
Georgia           Georgian                    2.497854  1.864192    2.965665
Germany           German                      2.323024  1.757384    3.186207
Greece            Greek                       2.637168  1.939356    3.508850
Hong Kong (S.A.R) Mandarin Chinese            2.633094  1.765794    2.431655
Hungary           Hungarian                   2.511719  1.823555    3.125000
Iceland           Icelandic                   2.227666  1.861548    2.129683
India             Marathi                     2.053571  1.891797    1.839286
Indonesia         Indonesian                  3.141085  1.749073    2.213292
Iran              Persian                     2.972973  1.929272    3.005405
Israel            Hebrew                      2.092715  1.733401    3.125828
Italy             Italian                     2.666667  1.799782    3.320000
Japan             Japanese                    2.630148  1.743227    3.111888
Jordan            Arabic                      2.711207  2.012570    3.116379
Kazakhstan        Russian                     2.276978  1.979746    2.602151
Malaysia          Standard Malay              2.503226  1.785127    2.412903
Netherlands       Dutch                       2.408397  1.663121    3.574427
Peru              Spanish                     2.868545  1.827875    3.181395
Russia            Russian                     2.394415  1.771404    2.713542
Serbia            Serbian-Croatian-Bosnian    2.428977  1.784888    2.749288
South Africa      Afrikaans                   2.883929  1.911301    3.991071
Spain             Spanish                     2.371429  1.771880    3.228571
Sweden            Swedish                     2.315000  1.693501    3.170000
Syria             Arabic                      2.122449  2.012590    2.275720
Taiwan            Mandarin Chinese            1.990617  1.625689    1.842035
Turkey            Turkish                     2.948617  1.892269    2.881423
Ukraine           Ukrainian                   2.393293  1.827914    2.936073
Vietnam           Vietnamese                  1.688356  1.687472    2.441781

                                                       loneliness            \
                                                   std       mean       std
countryname       bila_language_name_mapping
Brazil            Brazilian Portuguese        1.941201   2.518033  2.069635
Bulgaria          Bulgarian                   2.089207   2.334572  2.154385
Chile             Latin American Spanish      1.731608   2.869658  2.067930
China             Mandarin Chinese            1.763461   1.812437  1.826492
Colombia          Latin American Spanish      1.897167   2.578512  2.170837
                  Spanish                     2.034158   1.646018  1.787458
Croatia           Serbian-Croatian-Bosnian    1.812788   2.682510  1.955690
Curacao           Dutch                       1.877527   1.894444  1.853570
Denmark           Danish                      1.852980   2.277027  2.026427
Egypt             Arabic                      2.007981   3.686275  2.140949
Finland           Finnish                     1.699246   2.776062  1.927978
France            French                      1.829765   1.961089  1.932060
Georgia           Georgian                    1.920539   2.439655  2.131149
Germany           German                      1.856388   2.178694  1.887078
Greece            Greek                       1.663306   2.537445  2.015901
Hong Kong (S.A.R) Mandarin Chinese            1.813997   2.345324  1.909975
Hungary           Hungarian                   1.919967   1.863281  2.000211
Iceland           Icelandic                   1.890931   2.465318  2.160303
India             Marathi                     1.961231   1.857143  1.833314
Indonesia         Indonesian                  1.869821   2.545595  1.978368
Iran              Persian                     1.918155   2.940860  2.032638
Israel            Hebrew                      1.690383   2.026490  1.754792
Italy             Italian                     1.944077   2.535377  1.968709
Japan             Japanese                    1.729330   2.007764  1.817621
Jordan            Arabic                      2.076312   3.304348  2.156230
Kazakhstan        Russian                     2.078356   2.039568  2.156817
Malaysia          Standard Malay              1.689490   2.296774  2.064462
Netherlands       Dutch                       1.658224   2.335878  1.853572
Peru              Spanish                     1.988196   1.604651  1.720404
Russia            Russian                     1.983293   2.157986  2.033897
Serbia            Serbian-Croatian-Bosnian    1.953705   2.205128  2.008006
South Africa      Afrikaans                   1.579688   2.276786  1.996437
Spain             Spanish                     1.912797   1.971429  2.011779
Sweden            Swedish                     1.835626   2.140000  1.990050
Syria             Arabic                      2.142184   2.325103  2.281181
Taiwan            Mandarin Chinese            1.638740   1.605087  1.640841
Turkey            Turkish                     1.976491   2.494071  2.042447
Ukraine           Ukrainian                   1.930703   2.181402  1.950304
Vietnam           Vietnamese                  1.901356   1.859589  1.964674

                                                regret             sadness  \
                                                  mean       std      mean
countryname       bila_language_name_mapping
Brazil            Brazilian Portuguese        1.934426  1.881951  3.321311
Bulgaria          Bulgarian                   2.929104  2.009018  3.252788
Chile             Latin American Spanish      2.352564  1.969156  3.799145
China             Mandarin Chinese            1.477009  1.701083  2.256709
Colombia          Latin American Spanish      1.721311  1.601973  3.459016
                  Spanish                     1.415929  1.699399  2.389381
Croatia           Serbian-Croatian-Bosnian    2.798479  1.710828  2.990494
Curacao           Dutch                       1.350000  1.645970  2.622222
Denmark           Danish                      1.479730  1.655622  1.601351
Egypt             Arabic                      2.710591  2.129295  4.047970
Finland           Finnish                     1.534615  1.570343  2.953668
France            French                      1.582031  1.708430  2.503906
Georgia           Georgian                    2.497854  1.916634  3.277778
Germany           German                      2.037931  1.705459  2.656357
Greece            Greek                       1.778761  1.836589  3.251101
Hong Kong (S.A.R) Mandarin Chinese            1.956835  1.785085  2.618705
Hungary           Hungarian                   1.906250  1.723824  2.703125

In [49]:
# lets just flatten out the 3 level column names
stats_by_country.columns = [
    f"{emotion}_{stat}" for emotion, stat in stats_by_country.columns
]
stats_by_country = stats_by_country.reset_index()
stats_by_country

,countryname,bila_language_name_mapping,admiration_mean,admiration_std,calm_mean,calm_std,compassion_mean,compassion_std,determination_mean,determination_std,...,fear_mean,fear_std,frustration_mean,frustration_std,loneliness_mean,loneliness_std,regret_mean,regret_std,sadness_mean,sadness_std
0,Brazil,Brazilian Portuguese,3.540984,1.745047,3.421569,1.502585,4.633987,1.319471,3.725490,1.593986,...,3.603279,1.757500,3.437908,1.941201,2.518033,2.069635,1.934426,1.881951,3.321311,1.833991
1,Bulgaria,Bulgarian,2.498141,1.980548,3.334572,1.712431,4.313433,1.590788,3.565056,1.684113,...,2.561338,1.954938,3.029740,2.089207,2.334572,2.154385,2.929104,2.009018,3.252788,1.930519
2,Chile,Latin American Spanish,2.867521,1.901080,2.899358,1.546330,3.893390,1.693798,3.370450,1.700109,...,3.528785,1.836746,4.119914,1.731608,2.869658,2.067930,2.352564,1.969156,3.799145,1.745670
3,China,Mandarin Chinese,4.365940,1.736698,3.914807,1.683731,4.240976,1.701800,4.165992,1.693406,...,1.809500,1.726083,1.815642,1.763461,1.812437,1.826492,1.477009,1.701083,2.256709,1.848471
4,Colombia,Latin American Spanish,3.409836,1.974022,3.418033,1.419115,4.024590,1.678563,3.818182,1.653280,...,3.024590,1.943258,3.409836,1.897167,2.578512,2.170837,1.721311,1.601973,3.459016,1.916210
5,Colombia,Spanish,3.732143,1.981819,4.256637,1.468592,4.194690,1.821785,4.247788,1.538384,...,2.398230,1.825121,2.929204,2.034158,1.646018,1.787458,1.415929,1.699399,2.389381,1.901285
6,Croatia,Serbian-Croatian-Bosnian,2.548571,1.680610,3.336502,1.487369,2.916190,1.657917,3.516190,1.441686,...,2.740952,1.825796,3.420952,1.812788,2.682510,1.955690,2.798479,1.710828,2.990494,1.760385
7,Curacao,Dutch,3.627778,1.743401,3.961111,1.607816,4.777778,1.174951,4.000000,1.549914,...,2.477778,1.933115,3.005556,1.877527,1.894444,1.853570,1.350000,1.645970,2.622222,1.906049
8,Denmark,Danish,2.668919,1.513605,3.445946,1.531012,4.067568,1.450602,3.351351,1.483996,...,1.824324,1.610832,3.148649,1.852980,2.277027,2.026427,1.479730,1.655622,1.601351,1.732993
9,Egypt,Arabic,2.547472,1.886575,3.622222,1.728264,4.173006,1.710858,3.161090,1.728845,...,3.556790,1.953694,3.419434,2.007981,3.686275,2.140949,2.710591,2.129295,4.047970,1.806232
10,Finland,Finnish,2.738462,1.547467,3.726923,1.380520,4.042471,1.350471,3.532819,1.327221,...,2.509653,1.600298,3.846154,1.699246,2.776062,1.927978,1.534615,1.570343,2.953668,1.672212
11,France,French,3.357977,1.801764,3.746094,1.587322,3.809339,1.648458,3.727626,1.582292,...,2.155642,1.796018,3.156250,1.829765,1.961089,1.932060,1.582031,1.708430,2.503906,1.874489
12,Georgia,Georgian,2.523605,1.866354,3.248927,1.698836,4.444444,1.507887,3.692308,1.815345,...,2.497854,1.864192,2.965665,1.920539,2.439655,2.131149,2.497854,1.916634,3.277778,1.955453
13,Germany,German,2.804124,1.800225,3.628866,1.620895,4.347079,1.283778,3.468966,1.464955,...,2.323024,1.757384,3.186207,1.856388,2.178694,1.887078,2.037931,1.705459,2.656357,1.749518
14,Greece,Greek,2.328889,1.887059,3.337778,1.538681,3.843049,1.662391,3.444934,1.682894,...,2.637168,1.939356,3.508850,1.663306,2.537445,2.015901,1.778761,1.836589,3.251101,1.886945
15,Hong Kong (S.A.R),Mandarin Chinese,2.669065,1.770894,3.064748,1.455667,3.323741,1.616114,3.366906,1.489791,...,2.633094,1.765794,2.431655,1.813997,2.345324,1.909975,1.956835,1.785085,2.618705,1.750344
16,Hungary,Hungarian,2.679688,1.925815,3.265625,1.730848,4.507812,1.343079,3.652344,1.698972,...,2.511719,1.823555,3.125000,1.919967,1.863281,2.000211,1.906250,1.723824,2.703125,1.869715
17,Iceland,Icelandic,3.469741,1.867297,3.299712,1.757585,4.388406,1.601193,3.589595,1.611303,...,2.227666,1.861548,2.129683,1.890931,2.465318,2.160303,1.527378,1.776931,2.376437,1.964884
18,India,Marathi,3.500000,1.768410,3.982143,1.700172,3.946429,1.633954,3.660714,1.880781,...,2.053571,1.891797,1.839286,1.961231,1.857143,1.833314,1.254545,1.723672,2.381818,2.022932
19,Indonesia,Indonesian,3.201863,1.577327,3.834365,1.327863,4.547287,1.238492,3.827372,1.301711,...,3.141085,1.749073,2.213292,1.869821,2.545595,1.978368,2.066563,1.647238,2.933333,1.730317
20,Iran,Persian,2.347826,1.745782,2.774194,1.831431,3.770053,1.705639,3.290323,1.601220,...,2.972973,1.929272,3.005405,1.918155,2.940860,2.032638,2.659459,1.999383,3.556150,1.881089
21,Israel,Hebrew,1.569536,1.718565,3.240000,1.407935,4.013245,1.316494,3.403974,1.493001,...,2.092715,1.733401,3.125828,1.690383,2.026490,1.754792,1.662252,1.616116,2.536424,1.765502
22,Italy,Italian,2.966981,1.900316,3.327059,1.516839,3.613208,1.729022,3.716981,1.558958,...,2.666667,1.799782,3.320000,1.944077,2.535377,1.968709,2.411765,1.928523,3.343529,1.723755
23,Japan,Japanese,2.602176,1.523357,3.559441,1.254913,3.533385,1.375941,2.964258,1.522347,...,2.630148,1.743227,3.111888,1.729330,2.007764,1.817621,1.956522,1.623824,2.601399,1.710028
24,Jordan,Arabic,3.108225,1.965235,3.952586,1.807247,4.359307,1.718414,3.754386,1.846828,...,2.711207,2.012570,3.116379,2.076312,3.304348,2.156230,2.515152,2.218202,3.700000,1.917855
25,Kazakhstan,Russian,2.438849,1.958468,3.469534,1.641953,3.602151,1.755606,3.283154,1.783851,...,2.276978,1.979746,2.602151,2.078356,2.039568,2.156817,2.773381,2.002456,3.028674,1.913386
26,Malaysia,Standard Malay,3.793548,1.548761,4.000000,1.232672,4.432258,1.304435,3.845161,1.372939,...,2.503226,1.785127,2.412903,1.689490,2.296774,2.064462,1.980645,1.672819,2.761290,1.643894
27,Netherlands,Dutch,3.325048,1.646279,3.671756,1.413904,4.160305,1.402357,3.553435,1.404380,...,2.408397,1.663121,3.574427,1.658224,2.335878,1.853572,1.402672,1.482876,2.869981,1.738211
28,Peru,Spanish,3.706161,1.884501,3.693023,1.503484,4.483721,1.500301,3.939252,1.457070,...,2.868545,1.827875,3.181395,1.988196,1.604651,1.720404,1.469767,1.617015,3.065116,1.768214
29,Russia,Russian,2.553043,1.774840,3.349565,1.524902,3.557292,1.654564,3.057292,1.579824,...,2.394415,1.771404,2.713542,1.983293,2.157986,2.033897,2.841739,1.816781,3.288194,1.748619
30,Serbia,Serbian-Croatian-Bosnian,2.716332,1.845246,3.518519,1.578091,4.308571,1.464650,3.792023,1.578261,...,2.428977,1.784888,2.749288,1.953705,2.205128,2.008006,2.965714,1.929702,2.988636,1.816319
31,South Africa,Afrikaans,2.946429,1.712904,3.642857,1.341353,4.196429,1.505780,3.696429,1.570214,...,2.883929,1.911301,3.991071,1.579688,2.276786,1.996437,2.098214,1.888609,3.160714,1.872290
32,Spain,Spanish,3.428571,1.994498,3.428571,1.616365,3.971154,1.742984,3.461538,1.773172,...,2.371429,1.771880,3.228571,1.912797,1.971429,2.011779,1.428571,1.663275,3.066667,1.733531
33,Sweden,Swedish,3.300000,1.774224,3.580000,1.482936,4.537500,1.289477,3.675000,1.374445,...,2.315000,1.693501,3.170000,1.835626,2.140000,1.990050,1.355890,1.523240,2.680000,1.773546
34,Syria,Arabic,1.849372,1.996402,3.377593,2.045971,3.878543,1.921589,2.888889,2.168520,...,2.122449,2.012590,2.275720,2.142184,2.325103,2.281181,1.636364,1.955946,2.799180,2.200972
35,Taiwan,Mandarin Chinese,3.993307,1.660520,3.666667,1.549020,3.722520,1.628423,3.695710,1.540472,...,1.990617,1.625689,1.842035,1.638740,1.605087,1.640841,1.215818,1.466518,1.962416,1.652201
36,Turkey,Turkish,2.027888,1.760460,3.611111,1.439191,3.956349,1.627111,3.804781,1.561325,...,2.948617,1.892269,2.881423,1.976491,2.494071,2.042447,1.768000,1.788567,3.575397,1.681357
37,Ukraine,Ukrainian,2.856489,1.644428,3.203957,1.565963,3.576220,1.516419,3.260274,1.528436,...,2.393293,1.827914,2.936073,1.930703,2.181402,1.950304,2.705793,1.814369,3.169466,1.849121
38,Vietnam,Vietnamese,4.219178,1.746841,4.263699,1.350442,3.872852,1.779476,4.096220,1.507803,...,1.688356,1.687472,2.441781,1.901356,1.859589,1.964674,1.534247,1.709743,2.047945,1.841978

In [50]:
# it was very wide, leyts make it narrow, longer, and more robust
stats_long = (
    stats_by_country
    .set_index(['countryname', 'bila_language_name_mapping'])
    .filter(regex='_(mean|std)$')
    .stack()
    .reset_index()
)

stats_long[['word', 'stat']] = stats_long['level_2'].str.rsplit('_', n=1, expand=True)
stats_long = stats_long.rename(columns={0: 'value'}).drop(columns='level_2')

stats_long = (
    stats_long
    .pivot_table(
        index=['countryname', 'bila_language_name_mapping', 'word'],
        columns='stat',
        values='value'
    )
    .reset_index()
)

In [51]:
#Merge our cleaned survey data with the BILA dictionary data
merged = elab_per_emotion.merge(
    stats_long,
    left_on=['langname', 'word'],
    right_on=['bila_language_name_mapping', 'word'],
    how='left'
)

merged

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,mean,std
0,Turkish,nucl1301,fear,126.0,coo.31924067983704,1991.0,0.001036,1.952545,121674.0,Turkey,Turkish,2.948617,1.892269
1,Turkish,nucl1301,pleasure,107.0,coo.31924067983704,1991.0,0.000879,3.153327,121674.0,Turkey,Turkish,3.083665,1.643463
2,Turkish,nucl1301,regret,41.0,coo.31924067983704,1991.0,0.000337,2.670962,121674.0,Turkey,Turkish,1.768000,1.788567
3,Turkish,nucl1301,admiration,10.0,coo.31924067983704,1991.0,0.000082,-0.854986,121674.0,Turkey,Turkish,2.027888,1.760460
4,Turkish,nucl1301,anger,85.0,coo.31924067983704,1991.0,0.000699,0.579516,121674.0,Turkey,Turkish,3.460000,1.871473
...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,Japanese,nucl1643,disgust,13.0,uva.x004877953,1974.0,0.000046,-4.505457,282895.0,Japan,Japanese,2.854701,1.747655
698,Japanese,nucl1643,frustration,6.0,uva.x004877953,1974.0,0.000021,-1.588076,282895.0,Japan,Japanese,3.111888,1.729330
699,Japanese,nucl1643,loneliness,7.0,uva.x004877953,1974.0,0.000025,-1.873436,282895.0,Japan,Japanese,2.007764,1.817621
700,Japanese,nucl1643,relief,89.0,uva.x004877953,1974.0,0.000315,3.907437,282895.0,Japan,Japanese,2.403263,1.417428
701,Japanese,nucl1643,boredom,6.0,uva.x004877953,1974.0,0.000021,-1.590590,282895.0,Japan,Japanese,3.180901,1.939018

In [52]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 702 entries, 0 to 701
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   langname                    702 non-null    object
 1   glottocode                  702 non-null    object
 2   word                        702 non-null    object
 3   count                       702 non-null    float64
 4   id                          702 non-null    object
 5   year                        702 non-null    float64
 6   simple_elaboration          702 non-null    float64
 7   regression_elaboration      702 non-null    float64
 8   dictsize_data               702 non-null    float64
 9   countryname                 702 non-null    object
 10  bila_language_name_mapping  702 non-null    object
 11  mean                        702 non-null    float64
 12  std                         702 non-null    float64
dtypes: float64(7), object(6)
memory usage: 71.4+ KB

In [53]:
# add the dictionary_count_mean column
merged = merged.merge(
    dictionary_means,
    left_on='id',
    right_on='id',
    how='left'
)
merged

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,mean,std,dictionary_count_mean
0,Turkish,nucl1301,fear,126.0,coo.31924067983704,1991.0,0.001036,1.952545,121674.0,Turkey,Turkish,2.948617,1.892269,17.081983
1,Turkish,nucl1301,pleasure,107.0,coo.31924067983704,1991.0,0.000879,3.153327,121674.0,Turkey,Turkish,3.083665,1.643463,17.081983
2,Turkish,nucl1301,regret,41.0,coo.31924067983704,1991.0,0.000337,2.670962,121674.0,Turkey,Turkish,1.768000,1.788567,17.081983
3,Turkish,nucl1301,admiration,10.0,coo.31924067983704,1991.0,0.000082,-0.854986,121674.0,Turkey,Turkish,2.027888,1.760460,17.081983
4,Turkish,nucl1301,anger,85.0,coo.31924067983704,1991.0,0.000699,0.579516,121674.0,Turkey,Turkish,3.460000,1.871473,17.081983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,Japanese,nucl1643,disgust,13.0,uva.x004877953,1974.0,0.000046,-4.505457,282895.0,Japan,Japanese,2.854701,1.747655,41.449679
698,Japanese,nucl1643,frustration,6.0,uva.x004877953,1974.0,0.000021,-1.588076,282895.0,Japan,Japanese,3.111888,1.729330,41.449679
699,Japanese,nucl1643,loneliness,7.0,uva.x004877953,1974.0,0.000025,-1.873436,282895.0,Japan,Japanese,2.007764,1.817621,41.449679
700,Japanese,nucl1643,relief,89.0,uva.x004877953,1974.0,0.000315,3.907437,282895.0,Japan,Japanese,2.403263,1.417428,41.449679
701,Japanese,nucl1643,boredom,6.0,uva.x004877953,1974.0,0.000021,-1.590590,282895.0,Japan,Japanese,3.180901,1.939018,41.449679

In [54]:
merged = merged[merged['countryname'].notna()]

In [55]:
# clarify the meaning of mean
merged = merged.rename(columns={'mean': "response_mean"})
# Clarify what std we're talking about
merged = merged.rename(columns={'std': "response_std"})
# drop a bunch of columns

merged = merged[['langname', 'glottocode', 'word', 'count', 'id', 'year',
       'simple_elaboration', 'regression_elaboration', 'dictsize_data',
       'countryname', 'bila_language_name_mapping', 'response_mean',
       'response_std', 'dictionary_count_mean' ]]
merged = merged.sort_values(by=["langname", 'word'])
merged

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,response_mean,response_std,dictionary_count_mean
237,Afrikaans,afri1274,admiration,6.0,mdp.39015054154474,1999.0,0.000028,-3.291632,212992.0,South Africa,Afrikaans,2.946429,1.712904,29.193469
238,Afrikaans,afri1274,anger,55.0,mdp.39015054154474,1999.0,0.000258,-6.741147,212992.0,South Africa,Afrikaans,2.785714,1.803043,29.193469
241,Afrikaans,afri1274,anxiety,30.0,mdp.39015054154474,1999.0,0.000141,-2.655449,212992.0,South Africa,Afrikaans,3.535714,1.765171,29.193469
251,Afrikaans,afri1274,boredom,5.0,mdp.39015054154474,1999.0,0.000023,-1.176312,212992.0,South Africa,Afrikaans,2.241071,1.889971,29.193469
239,Afrikaans,afri1274,compassion,15.0,mdp.39015054154474,1999.0,0.000070,-2.918472,212992.0,South Africa,Afrikaans,4.196429,1.505780,29.193469
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384,Vietnamese,viet1252,love,308.0,uc1.31210024487306,2003.0,0.001143,-1.138291,269366.0,Vietnam,Vietnamese,4.786942,1.311475,40.491312
379,Vietnamese,viet1252,pleasure,216.0,uc1.31210024487306,2003.0,0.000802,3.511485,269366.0,Vietnam,Vietnamese,2.832192,1.885719,40.491312
380,Vietnamese,viet1252,regret,59.0,uc1.31210024487306,2003.0,0.000219,0.052866,269366.0,Vietnam,Vietnamese,1.534247,1.709743,40.491312
394,Vietnamese,viet1252,relief,74.0,uc1.31210024487306,2003.0,0.000275,2.404758,269366.0,Vietnam,Vietnamese,3.199313,1.720505,40.491312
390,Vietnamese,viet1252,sadness,51.0,uc1.31210024487306,2003.0,0.000189,4.028092,269366.0,Vietnam,Vietnamese,2.047945,1.841978,40.491312

In [56]:
merged = merged.reset_index(drop=True)
merged

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,response_mean,response_std,dictionary_count_mean
0,Afrikaans,afri1274,admiration,6.0,mdp.39015054154474,1999.0,0.000028,-3.291632,212992.0,South Africa,Afrikaans,2.946429,1.712904,29.193469
1,Afrikaans,afri1274,anger,55.0,mdp.39015054154474,1999.0,0.000258,-6.741147,212992.0,South Africa,Afrikaans,2.785714,1.803043,29.193469
2,Afrikaans,afri1274,anxiety,30.0,mdp.39015054154474,1999.0,0.000141,-2.655449,212992.0,South Africa,Afrikaans,3.535714,1.765171,29.193469
3,Afrikaans,afri1274,boredom,5.0,mdp.39015054154474,1999.0,0.000023,-1.176312,212992.0,South Africa,Afrikaans,2.241071,1.889971,29.193469
4,Afrikaans,afri1274,compassion,15.0,mdp.39015054154474,1999.0,0.000070,-2.918472,212992.0,South Africa,Afrikaans,4.196429,1.505780,29.193469
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,Vietnamese,viet1252,love,308.0,uc1.31210024487306,2003.0,0.001143,-1.138291,269366.0,Vietnam,Vietnamese,4.786942,1.311475,40.491312
698,Vietnamese,viet1252,pleasure,216.0,uc1.31210024487306,2003.0,0.000802,3.511485,269366.0,Vietnam,Vietnamese,2.832192,1.885719,40.491312
699,Vietnamese,viet1252,regret,59.0,uc1.31210024487306,2003.0,0.000219,0.052866,269366.0,Vietnam,Vietnamese,1.534247,1.709743,40.491312
700,Vietnamese,viet1252,relief,74.0,uc1.31210024487306,2003.0,0.000275,2.404758,269366.0,Vietnam,Vietnamese,3.199313,1.720505,40.491312
701,Vietnamese,viet1252,sadness,51.0,uc1.31210024487306,2003.0,0.000189,4.028092,269366.0,Vietnam,Vietnamese,2.047945,1.841978,40.491312

In [57]:
print(merged['langname'].nunique(),
      merged['bila_language_name_mapping'].nunique(),
merged['word'].nunique(),
merged['countryname'].nunique(), sep="\n")

29
29
18
38

In [58]:
merged = merged.sort_values(by=["langname", 'countryname','word'])
merged = merged.reset_index(drop=True)
merged = merged.fillna(0)

In [59]:
merged

,langname,glottocode,word,count,id,year,simple_elaboration,regression_elaboration,dictsize_data,countryname,bila_language_name_mapping,response_mean,response_std,dictionary_count_mean
0,Afrikaans,afri1274,admiration,6.0,mdp.39015054154474,1999.0,0.000028,-3.291632,212992.0,South Africa,Afrikaans,2.946429,1.712904,29.193469
1,Afrikaans,afri1274,anger,55.0,mdp.39015054154474,1999.0,0.000258,-6.741147,212992.0,South Africa,Afrikaans,2.785714,1.803043,29.193469
2,Afrikaans,afri1274,anxiety,30.0,mdp.39015054154474,1999.0,0.000141,-2.655449,212992.0,South Africa,Afrikaans,3.535714,1.765171,29.193469
3,Afrikaans,afri1274,boredom,5.0,mdp.39015054154474,1999.0,0.000023,-1.176312,212992.0,South Africa,Afrikaans,2.241071,1.889971,29.193469
4,Afrikaans,afri1274,compassion,15.0,mdp.39015054154474,1999.0,0.000070,-2.918472,212992.0,South Africa,Afrikaans,4.196429,1.505780,29.193469
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,Vietnamese,viet1252,love,308.0,uc1.31210024487306,2003.0,0.001143,-1.138291,269366.0,Vietnam,Vietnamese,4.786942,1.311475,40.491312
698,Vietnamese,viet1252,pleasure,216.0,uc1.31210024487306,2003.0,0.000802,3.511485,269366.0,Vietnam,Vietnamese,2.832192,1.885719,40.491312
699,Vietnamese,viet1252,regret,59.0,uc1.31210024487306,2003.0,0.000219,0.052866,269366.0,Vietnam,Vietnamese,1.534247,1.709743,40.491312
700,Vietnamese,viet1252,relief,74.0,uc1.31210024487306,2003.0,0.000275,2.404758,269366.0,Vietnam,Vietnamese,3.199313,1.720505,40.491312
701,Vietnamese,viet1252,sadness,51.0,uc1.31210024487306,2003.0,0.000189,4.028092,269366.0,Vietnam,Vietnamese,2.047945,1.841978,40.491312

In [60]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 702 entries, 0 to 701
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   langname                    702 non-null    object
 1   glottocode                  702 non-null    object
 2   word                        702 non-null    object
 3   count                       702 non-null    float64
 4   id                          702 non-null    object
 5   year                        702 non-null    float64
 6   simple_elaboration          702 non-null    float64
 7   regression_elaboration      702 non-null    float64
 8   dictsize_data               702 non-null    float64
 9   countryname                 702 non-null    object
 10  bila_language_name_mapping  702 non-null    object
 11  response_mean               702 non-null    float64
 12  response_std                702 non-null    float64
 13  dictionary_count_mean       702 non-null    float64
dtypes: float64(8), object(6)
memory usage: 76.9+ KB

In [65]:
prevdf.columns

Index(['langname', 'glottocode', 'word', 'count', 'id', 'year',
       'simple_elaboration', 'regression_elaboration', 'dictsize_data',
       'countryname', 'bila_language_name_mapping', 'response_mean',
       'response_std', 'dictionary_count_mean'],
      dtype='object')

In [67]:
merged.columns

Index(['langname', 'glottocode', 'word', 'count', 'id', 'year',
       'simple_elaboration', 'regression_elaboration', 'dictsize_data',
       'countryname', 'bila_language_name_mapping', 'response_mean',
       'response_std', 'dictionary_count_mean'],
      dtype='object')

In [95]:
merged.groupby(['langname', 'countryname'])['word'].size().reset_index(name='count')

                    langname        countryname  count
0                  Afrikaans       South Africa     18
1                     Arabic              Egypt     18
2                     Arabic             Jordan     18
3                     Arabic              Syria     18
4       Brazilian Portuguese             Brazil     18
5                  Bulgarian           Bulgaria     18
6                     Danish            Denmark     18
7                      Dutch            Curacao     18
8                      Dutch        Netherlands     18
9                    Finnish            Finland     18
10                    French             France     18
11                  Georgian            Georgia     18
12                    German            Germany     18
13                     Greek             Greece     18
14                    Hebrew             Israel     18
15                 Hungarian            Hungary     18
16                 Icelandic            Iceland     18
17                Indonesian          Indonesia     18
18                   Italian              Italy     18
19                  Japanese              Japan     18
20    Latin American Spanish              Chile     18
21    Latin American Spanish           Colombia     18
22          Mandarin Chinese              China     18
23          Mandarin Chinese  Hong Kong (S.A.R)     18
24          Mandarin Chinese             Taiwan     18
25                   Marathi              India     18
26                   Persian               Iran     18
27                   Russian         Kazakhstan     18
28                   Russian             Russia     18
29  Serbian-Croatian-Bosnian            Croatia     18
30  Serbian-Croatian-Bosnian             Serbia     18
31                   Spanish           Colombia     18
32                   Spanish               Peru     18
33                   Spanish              Spain     18
34            Standard Malay           Malaysia     18
35                   Swedish             Sweden     18
36                   Turkish             Turkey     18
37                 Ukrainian            Ukraine     18
38                Vietnamese            Vietnam     18

In [94]:
prevdf.groupby(['langname', 'countryname'])['word'].size().reset_index(name='count')

                    langname        countryname  count
0                  Afrikaans       South Africa     18
1                     Arabic              Egypt     18
2                     Arabic             Jordan     18
3                     Arabic              Syria     18
4       Brazilian Portuguese             Brazil     18
5                  Bulgarian           Bulgaria     18
6                     Danish            Denmark     18
7                      Dutch            Curacao     18
8                      Dutch        Netherlands     18
9                    Finnish            Finland     18
10                    French             France     18
11                  Georgian            Georgia     18
12                    German            Germany     18
13                     Greek             Greece     18
14                    Hebrew             Israel     18
15                 Hungarian            Hungary     18
16                 Icelandic            Iceland     18
17                Indonesian          Indonesia     18
18                   Italian              Italy     18
19                  Japanese              Japan     18
20    Latin American Spanish              Chile     18
21    Latin American Spanish           Colombia     18
22          Mandarin Chinese              China     18
23          Mandarin Chinese  Hong Kong (S.A.R)     18
24          Mandarin Chinese             Taiwan     18
25                   Marathi              India     18
26                   Persian               Iran     18
27                   Russian         Kazakhstan     18
28                   Russian             Russia     18
29  Serbian-Croatian-Bosnian            Croatia     18
30  Serbian-Croatian-Bosnian             Serbia     18
31                   Spanish               Peru     18
32                   Spanish              Spain     18
33            Standard Malay           Malaysia     18
34                   Swedish             Sweden     18
35                   Turkish             Turkey     18
36                 Ukrainian            Ukraine     18
37                Vietnamese            Vietnam     18

In [141]:
# compare the unique tuples countryname,language
# compare the unique words each dictionary
# Shows only the cells that are different side-by-side
# Merges on all columns and adds a '_merge' column
comparison = merged.merge(prevdf, how='outer')

# # Rows only in merged
# only_merged = comparison[comparison['_merge'] == 'left_only']

# # Rows only in prevdf
# only_prevdf = comparison[comparison['_merge'] == 'right_only']

# only_merged

In [82]:
comparison = comparison.drop_duplicates(inplace=True)

In [170]:
merged[['id','dictionary_count_mean']].drop_duplicates(keep='first')[['id','dictionary_count_mean']].sort_values(by='id')

                        id  dictionary_count_mean
648     coo.31924067983704              17.081983
522     mdp.39015012891506               4.415160
612     mdp.39015022909470              21.347872
324     mdp.39015042010226              19.416910
18      mdp.39015043036436               9.851429
486     mdp.39015046500511               4.078717
360     mdp.39015050181174              11.002566
630     mdp.39015052442327              14.788338
0       mdp.39015054154474              29.193469
450     mdp.39015055371309               5.836968
90      mdp.39015058560494               8.997085
162     mdp.39015059174667              13.405131
180     mdp.39015066787105              30.926997
468     mdp.49015002913532               9.138076
270  miun.aee0517.0001.001              12.705773
72     txu.059173018640743               2.417843
684     uc1.31210024487306              40.491312
126     uc1.31822004083036               9.057259
216     uc1.31822005249149              31.592770
306     uc1.31822029604741              11.181574
234     uc1.32106014581794              12.585073
288     uc1.32106020063118              15.460525
108           uc1.b3832576               8.999767
666        uc1.l0070891726               7.967697
396        uc1.l0088545033              14.175510
558    umn.31951d01452389x              26.801983
198         uva.x001957729               1.465773
252         uva.x004242694               2.789971
342         uva.x004877953              41.449679

In [171]:
dict_means[dict_means['id'].isin(merged['id'].unique().tolist())]

                        id  dict_mean
1       coo.31924067983704  22.713289
83      mdp.39015012891506   6.269250
105     mdp.39015022909470  23.960471
179     mdp.39015042010226  23.991354
181     mdp.39015043036436  12.030191
187     mdp.39015046500511   4.832136
197     mdp.39015050181174  13.217568
208     mdp.39015052442327  19.222374
222     mdp.39015054154474  32.693483
228     mdp.39015055371309   9.274041
243     mdp.39015058560494  13.700941
246     mdp.39015059174667  15.718447
279     mdp.39015066787105  44.541317
308     mdp.49015002913532  11.235876
310  miun.aee0517.0001.001  18.050364
411    txu.059173018640743   8.979212
424     uc1.31210024487306  43.856638
427     uc1.31822004083036  12.839478
428     uc1.31822005249149  35.123558
433     uc1.31822029604741  14.883887
447     uc1.32106014581794  14.773032
452     uc1.32106020063118  28.590468
461           uc1.b3832576  12.037592
486        uc1.l0070891726  10.418268
489        uc1.l0088545033  15.996184
503    umn.31951d01452389x  32.766895
549         uva.x001957729   2.770333
574         uva.x004242694   3.707998
578         uva.x004877953  45.428298

In [172]:
dict_means2[dict_means2['id'].isin(merged['id'].unique().tolist())]

                        id  dict_mean
1       coo.31924067983704  17.081983
83      mdp.39015012891506   4.415160
105     mdp.39015022909470  21.347872
179     mdp.39015042010226  19.416910
181     mdp.39015043036436   9.851429
187     mdp.39015046500511   4.078717
197     mdp.39015050181174  11.002566
208     mdp.39015052442327  14.788338
222     mdp.39015054154474  29.193469
228     mdp.39015055371309   5.836968
243     mdp.39015058560494   8.997085
246     mdp.39015059174667  13.405131
279     mdp.39015066787105  30.926997
308     mdp.49015002913532   9.138076
310  miun.aee0517.0001.001  12.705773
411    txu.059173018640743   2.417843
424     uc1.31210024487306  40.491312
427     uc1.31822004083036   9.057259
428     uc1.31822005249149  31.592770
433     uc1.31822029604741  11.181574
447     uc1.32106014581794  12.585073
452     uc1.32106020063118  15.460525
461           uc1.b3832576   8.999767
486        uc1.l0070891726   7.967697
489        uc1.l0088545033  14.175510
503    umn.31951d01452389x  26.801983
549         uva.x001957729   1.465773
574         uva.x004242694   2.789971
578         uva.x004877953  41.449679

In [142]:
with pd.option_context('display.max_rows', None):
    display(comparison)

                      langname glottocode           word  count  \
0                    Afrikaans   afri1274     admiration    6.0
1                    Afrikaans   afri1274     admiration    6.0
2                    Afrikaans   afri1274          anger   55.0
3                    Afrikaans   afri1274          anger   55.0
4                    Afrikaans   afri1274        anxiety   30.0
5                    Afrikaans   afri1274        anxiety   30.0
6                    Afrikaans   afri1274        boredom    5.0
7                    Afrikaans   afri1274        boredom    5.0
8                    Afrikaans   afri1274     compassion   15.0
9                    Afrikaans   afri1274     compassion   15.0
10                   Afrikaans   afri1274      confusion   44.0
11                   Afrikaans   afri1274      confusion   44.0
12                   Afrikaans   afri1274  determination   20.0
13                   Afrikaans   afri1274  determination   20.0
14                   Afrikaans   afri1274        disgust   14.0
15                   Afrikaans   afri1274        disgust   14.0
16                   Afrikaans   afri1274           fear  120.0
17                   Afrikaans   afri1274           fear  120.0
18                   Afrikaans   afri1274    frustration    4.0
19                   Afrikaans   afri1274    frustration    4.0
20                   Afrikaans   afri1274      gratitude    7.0
21                   Afrikaans   afri1274      gratitude    7.0
22                   Afrikaans   afri1274           hope   34.0
23                   Afrikaans   afri1274           hope   34.0
24                   Afrikaans   afri1274     loneliness    5.0
25                   Afrikaans   afri1274     loneliness    5.0
26                   Afrikaans   afri1274           love  278.0
27                   Afrikaans   afri1274           love  278.0
28                   Afrikaans   afri1274       pleasure  108.0
29                   Afrikaans   afri1274       pleasure  108.0
30                   Afrikaans   afri1274         regret   39.0
31                   Afrikaans   afri1274         regret   39.0
32                   Afrikaans   afri1274         relief   80.0
33                   Afrikaans   afri1274         relief   80.0
34                   Afrikaans   afri1274        sadness    9.0
35                   Afrikaans   afri1274        sadness    9.0
36                      Arabic   stan1318     admiration    4.0
37                      Arabic   stan1318     admiration    4.0
38                      Arabic   stan1318     admiration    4.0
39                      Arabic   stan1318     admiration    4.0
40                      Arabic   stan1318     admiration    4.0
41                      Arabic   stan1318     admiration    4.0
42                      Arabic   stan1318          anger   49.0
43                      Arabic   stan1318          anger   49.0
44                      Arabic   stan1318          anger   49.0
45                      Arabic   stan1318          anger   49.0
46                      Arabic   stan1318          anger   49.0
47                      Arabic   stan1318          anger   49.0
48                      Arabic   stan1318        anxiety   22.0
49                      Arabic   stan1318        anxiety   22.0
50                      Arabic   stan1318        anxiety   22.0
51                      Arabic   stan1318        anxiety   22.0
52                      Arabic   stan1318        anxiety   22.0
53                      Arabic   stan1318        anxiety   22.0
54                      Arabic   stan1318        boredom    5.0
55                      Arabic   stan1318        boredom    5.0
56                      Arabic   stan1318        boredom    5.0
57                      Arabic   stan1318        boredom    5.0
58                      Arabic   stan1318        boredom    5.0
59                      Arabic   stan1318        boredom    5.0
60                      Arabic   stan1318     compassion   20.0
61                      Arabic   stan1318     compassion   20.0
62                      Arabic   stan1318     compassion   20.0
63                      Arabic   stan1318     compassion   20.0
64                      Arabic   stan1318     compassion   20.0
65                      Arabic   stan1318     compassion   20.0
66                      Arabic   stan1318      confusion   32.0
67                      Arabic   stan1318      confusion   32.0
68                      Arabic   stan1318      confusion   32.0
69                      Arabic   stan1318      confusion   32.0
70                      Arabic   stan1318      confusion   32.0
71                      Arabic   stan1318      confusion   32.0
72                      Arabic   stan1318  determination   20.0
73                      Arabic   stan1318  determination   20.0
74                      Arabic   stan1318  determination   20.0
75                      Arabic   stan1318  determination   20.0
76                      Arabic   stan1318  determination   20.0
77                      Arabic   stan1318  determination   20.0
78                      Arabic   stan1318        disgust   28.0
79                      Arabic   stan1318        disgust   28.0
80                      Arabic   stan1318        disgust   28.0
81                      Arabic   stan1318        disgust   28.0
82                      Arabic   stan1318        disgust   28.0
83                      Arabic   stan1318        disgust   28.0
84                      Arabic   stan1318           fear   57.0
85                      Arabic   stan1318           fear   57.0
86                      Arabic   stan1318           fear   57.0
87                      Arabic   stan1318           fear   57.0
88                      Arabic   stan1318           fear   57.0
89                      Arabic   stan1318           fear   57.0
90                      Arabic   stan1318    frustration   16.0
91                      Arabic   stan1318    frustration   16.0
92                      Arabic   stan1318    frustration   16.0
93                      Arabic   stan1318    frustration   16.0
94                      Arabic   stan1318    frustration   16.0
95                      Arabic   stan1318    frustration   16.0
96                      Arabic   stan1318      gratitude    4.0
97                      Arabic   stan1318      gratitude    4.0
98                      Arabic   stan1318      gratitude    4.0
99                      Arabic   stan1318      gratitude    4.0
100                     Arabic   stan1318      gratitude    4.0
101                     Arabic   stan1318      gratitude    4.0
102                     Arabic   stan1318           hope   15.0
103                     Arabic   stan1318           hope   15.0
104                     Arabic   stan1318           hope   15.0
105                     Arabic   stan1318           hope   15.0
106                     Arabic   stan1318           hope   15.0
107                     Arabic   stan1318           hope   15.0
108                     Arabic   stan1318     loneliness    6.0
109                     Arabic   stan1318     loneliness    6.0
110                     Arabic   stan1318     loneliness    6.0
111                     Arabic   stan1318     loneliness    6.0
112                     Arabic   stan1318     loneliness    6.0
113                     Arabic   stan1318     loneliness    6.0
114                     Arabic   stan1318           love  134.0
115                     Arabic   stan1318           love  134.0
116                     Arabic   stan1318           love  134.0
117                     Arabic   stan1318           love  134.0
118                     Arabic   stan1318           love  134.0
119                     Arabic   stan1318           love  134.0
120                     Arabic   stan1318       pleasure   43.0
121                     Arabic   stan1318       pleasure   43.0
122                     Arabic   stan1318       pleasure   43.0
123                     Arabic   stan1318       pleasure   43.0
124                     Arabic   stan1318       pleasure   43.0
125                     Arabic   stan1318       pleasure   43.0
126                     Arabic   stan1318         regret   15.0
127                     Arabic   stan1318         regret   15.0
128                     Arabic   stan1318         regret   15.0
129                     Arabic   stan1318         regret   15.0
130                     Arabic   stan1318         regret   15.0
131                     Arabic   stan1318         regret   15.0
132                     Arabic   stan1318         relief   42.0
133                     Arabic   stan1318         relief   42.0
134                     Arabic   stan1318         relief   42.0
135                     Arabic   stan1318         relief   42.0
136                     Arabic   stan1318         relief   42.0
137                     Arabic   stan1318         relief   42.0
138                     Arabic   stan1318        sadness   11.0
139                     Arabic   stan1318        sadness   11.0
140                     Arabic   stan1318        sadness   11.0
141                     Arabic   stan1318        sadness   11.0
142                     Arabic   stan1318        sadness   11.0
143                     Arabic   stan1318        sadness   11.0
144       Brazilian Portuguese   braz1246     admiration    0.0
145       Brazilian Portuguese   braz1246     admiration    0.0
146       Brazilian Portuguese   braz1246          anger    7.0
147       Brazilian Portuguese   braz1246          anger    7.0
148       Brazilian Portuguese   braz1246        anxiety    0.0
149       Brazilian Portuguese   braz1246        anxiety    0.0
150       Brazilian Portuguese   braz1246        boredom    0.0
151       Brazilian Portuguese   braz1246        boredom    0.0
152       Brazilian Portuguese   braz1246     compassion    0.0
153       Brazilian Portuguese   braz1246     compassion    0.0
154       Brazilian Portuguese   braz1246      confusion    3.0
155       Brazilian Portuguese   braz1246      confusion    3.0
156       Brazilian Portuguese   braz1246  determination    1.0
157       Brazilian Portuguese   braz1246  determination    1.0
158       Brazilian Portuguese   braz1246        disgust    0.0
159       Brazilian Portuguese   braz1246        disgust    0.0
160       Brazilian Portuguese   braz1246           fear    3.0
161       Brazilian Portuguese   braz1246           fear    3.0
162       Brazilian Portuguese   braz1246    frustration    0.0
163       Brazilian Portuguese   braz1246    frustration    0.0
164       Brazilian Portuguese   braz1246      gratitude    1.0
165       Brazilian Portuguese   braz1246      gratitude    1.0
166       Brazilian Portuguese   braz1246           hope    0.0
167       Brazilian Portuguese   braz1246           hope    0.0
168       Brazilian Portuguese   braz1246     loneliness    0.0
169       Brazilian Portuguese   braz1246     loneliness    0.0
170       Brazilian Portuguese   braz1246           love   56.0
171       Brazilian Portuguese   braz1246           love   56.0
172       Brazilian Portuguese   braz1246       pleasure    0.0
173       Brazilian Portuguese   braz1246       pleasure    0.0
174       Brazilian Portuguese   braz1246         regret    2.0
175       Brazilian Portuguese   braz1246         regret    2.0
176       Brazilian Portuguese   braz1246         relief    0.0
177       Brazilian Portuguese   braz1246         relief    0.0
178       Brazilian Portuguese   braz1246        sadness    2.0
179       Brazilian Portuguese   braz1246        sadness    2.0
180                  Bulgarian   bulg1262     admiration    8.0
181                  Bulgarian   bulg1262     admiration    8.0
182                  Bulgarian   bulg1262          anger   33.0
183                  Bulgarian   bulg1262          anger   33.0
184                  Bulgarian   bulg1262        anxiety   29.0
185                  Bulgarian   bulg1262        anxiety   29.0
186                  Bulgarian   bulg1262        boredom    0.0
187                  Bulgarian   bulg1262        boredom    0.0
188                  Bulgarian   bulg1262     compassion   23.0
189                  Bulgarian   bulg1262     compassion   23.0
190                  Bulgarian   bulg1262      confusion   27.0
191                  Bulgarian   bulg1262      confusion   27.0
192                  Bulgarian   bulg1262  determination   12.0
193                  Bulgarian   bulg1262  determination   12.0
194                  Bulgarian   bulg1262        disgust   15.0
195                  Bulgarian   bulg1262        disgust   15.0
196                  Bulgarian   bulg1262           fear   71.0
197                  Bulgarian   bulg1262           fear   71.0
198                  Bulgarian   bulg1262    frustration    2.0
199                  Bulgarian   bulg1262    frustration    2.0
200                  Bulgarian   bulg1262      gratitude    5.0
201                  Bulgarian   bulg1262      gratitude    5.0
202                  Bulgarian   bulg1262           hope    7.0
203                  Bulgarian   bulg1262           hope    7.0
204                  Bulgarian   bulg1262     loneliness    1.0
205                  Bulgarian   bulg1262     loneliness    1.0
206                  Bulgarian   bulg1262           love  137.0
207                  Bulgarian   bulg1262           love  137.0
208                  Bulgarian   bulg1262       pleasure   42.0
209                  Bulgarian   bulg1262       pleasure   42.0
210                  Bulgarian   bulg1262         regret   14.0
211                  Bulgarian   bulg1262         regret   14.0
212                  Bulgarian   bulg1262         relief   22.0
213                  Bulgarian   bulg1262         relief   22.0
214                  Bulgarian   bulg1262        sadness    7.0
215                  Bulgarian   bulg1262        sadness    7.0
216                     Danish   dani1285     admiration    2.0
217                     Danish   dani1285     admiration    2.0
218                     Danish   dani1285          anger   19.0
219                     Danish   dani1285          anger   19.0
220                     Danish   dani1285        anxiety    9.0
221                     Danish   dani1285        anxiety    9.0
222                     Danish   dani1285        boredom    3.0
223                     Danish   dani1285        boredom    3.0
224                     Danish   dani1285     compassion    4.0
225                     Danish   dani1285     compassion    4.0
226                     Danish   dani1285      confusion   15.0
227                     Danish   dani1285      confusion   15.0
228                     Danish   dani1285  determination    0.0
229                     Danish   dani1285  determination    0.0
230                     Danish   dani1285        disgust    8.0
231                     Danish   dani1285        disgust    8.0
232                     Danish   dani1285           fear   38.0
233                     Danish   dani1285           fear   38.0
234                     Danish   dani1285    frustration    0.0
235                     Danish   dani1285    frustration    0.0
236                     Danish   dani1285      gratitude   11.0
237                     Danish   dani1285      gratitude   11.0
238                     Danish   dani1285           hope   10.0
239                     Danish   dani1285           hope   10.0
240                     Danish   dani1285     loneliness    2.0
241                     Danish   dani1285     loneliness    2.0
242                     Danish   dani1285           love    0.0
243                     Danish   dani1285           love    0.0
244                     Danish   dani1285       pleasure   39.0
245                     Danish   dani1285       pleasure   39.0
246                     Danish   dani1285         regret   18.0
247                     Danish   dani1285         regret   18.0
248                     Danish   dani1285         relief   56.0
249                     Danish   dani1285         relief   56.0
250                     Danish   dani1285        sadness    5.0
251                     Danish   dani1285        sadness    5.0
252                      Dutch   dutc1256     admiration    5.0
253                      Dutch   dutc1256     admiration    5.0
254                      Dutch   dutc1256     admiration    5.0
255                      Dutch   dutc1256     admiration    5.0
256                      Dutch   dutc1256          anger   26.0
257                      Dutch   dutc1256          anger   26.0
258                      Dutch   dutc1256          anger   26.0
259                      Dutch   dutc1256          anger   26.0
260                      Dutch   dutc1256        anxiety   13.0
261                      Dutch   dutc1256        anxiety   13.0
262                      Dutch   dutc1256        anxiety   13.0
263                      Dutch   dutc1256        anxiety   13.0
264                      Dutch   dutc1256        boredom    2.0
265                      Dutch   dutc1256        boredom    2.0
266                      Dutch   dutc1256        boredom    2.0
267                      Dutch   dutc1256        boredom    2.0
268                      Dutch   dutc1256     compassion    8.0
269                      Dutch   dutc1256     compassion    8.0
270                      Dutch   dutc1256     compassion    8.0
271                      Dutch   dutc1256     compassion    8.0
272                      Dutch   dutc1256      confusion   16.0
273                      Dutch   dutc1256      confusion   16.0
274                      Dutch   dutc1256      confusion   16.0
275                      Dutch   dutc1256      confusion   16.0
276                      Dutch   dutc1256  determination    7.0
277                      Dutch   dutc1256  determination    7.0
278                      Dutch   dutc1256  determination    7.0
279                      Dutch   dutc1256  determination    7.0
280                      Dutch   dutc1256        disgust    5.0
281                      Dutch   dutc1256        disgust    5.0
282                      Dutch   dutc1256        disgust    5.0
283                      Dutch   dutc1256        disgust    5.0
284                      Dutch   dutc1256           fear   62.0
285                      Dutch   dutc1256           fear   62.0
286                      Dutch   dutc1256           fear   62.0
287                      Dutch   dutc1256           fear   62.0
288                      Dutch   dutc1256    frustration    2.0
289                      Dutch   dutc1256    frustration    2.0
290                      Dutch   dutc1256    frustration    2.0
291                      Dutch   dutc1256    frustration    2.0
292                      Dutch   dutc1256      gratitude    5.0
293                      Dutch   dutc1256      gratitude    5.0
294                      Dutch   dutc1256      gratitude    5.0
295                      Dutch   dutc1256      gratitude    5.0
296                      Dutch   dutc1256           hope   14.0
297                      Dutch   dutc1256           hope   14.0
298                      Dutch   dutc1256           hope   14.0
299                      Dutch   dutc1256           hope   14.0
300                      Dutch   dutc1256     loneliness    3.0
301                      Dutch   dutc1256     loneliness    3.0
302                      Dutch   dutc1256     loneliness    3.0
303                      Dutch   dutc1256     loneliness    3.0
304                      Dutch   dutc1256           love    0.0
305                      Dutch   dutc1256           love    0.0
306                      Dutch   dutc1256           love    0.0
307                      Dutch   dutc1256           love    0.0
308                      Dutch   dutc1256       pleasure   61.0
309                      Dutch   dutc1256       pleasure   61.0
310                      Dutch   dutc1256       pleasure   61.0

In [98]:
# This shows all rows that have at least one exact copy elsewhere
duplicates = comparison[comparison.duplicated(keep='first')]
display(duplicates.sort_values(by=['langname', 'word', 'countryname']))

Empty DataFrame
Columns: [langname, glottocode, word, count, id, year, simple_elaboration, regression_elaboration, dictsize_data, countryname, bila_language_name_mapping, response_mean, response_std, dictionary_count_mean]
Index: []

In [96]:
merged.to_csv(Path("~/Projects/hypocognition/data/processed/covid_bila_merge.csv").expanduser())

"Moving forward, could you create a table with the following columns (broken down into the 36 samples):
* The sample country
* The language
* The correlation between the log count and the response means
* The correlation between the log count and the response SDs
* The correlation between the log count and the absolute distance of the response means from the scale midpoint

In [183]:
merged['response_mean'].mean()

np.float64(2.941825947484964)

In [184]:
import numpy as np

merged2 = merged.copy()

# log count
merged2["log_count"] = np.log(merged2["count"] + 1)

# absolute distance from midpoint
SCALE_MIDPOINT = merged2["response_mean"].mean()
merged2["abs_dist_midpoint"] = (
    merged2["response_mean"] - SCALE_MIDPOINT
).abs()

result = (
    merged2
    .groupby(["countryname", "langname", "id"])
    .agg(
        corr_logcount_response_mean=(
            "log_count",
            lambda x: x.corr(
                merged2.loc[x.index, "response_mean"]
            )
        ),
        corr_logcount_response_sd=(
            "log_count",
            lambda x: x.corr(
                merged2.loc[x.index, "response_std"]
            )
        ),
        corr_logcount_abs_dist_midpoint=(
            "log_count",
            lambda x: x.corr(
                merged2.loc[x.index, "abs_dist_midpoint"]
            )
        ),

    )
    .reset_index()
)

In [185]:
result

,countryname,langname,id,corr_logcount_response_mean,corr_logcount_response_sd,corr_logcount_abs_dist_midpoint
0,Germany,Arabic,mdp.39015043036436,-0.144513,-0.294592,-0.127128
1,Netherlands,Arabic,mdp.39015043036436,-0.050352,-0.066060,-0.181116
2,Turkey,Arabic,mdp.39015043036436,-0.069355,-0.224864,0.032368

In [186]:
result.to_csv(Path("~/Projects/hypocognition/data/processed/ARABIC2corr_covid_bila.csv").expanduser())