In [330]:
# get the data maniplulation library 
import pandas as pd
import numpy as np
import re
import math
import plotly.graph_objects as go
import plotly.express as px

from pathlib import Path

In [331]:
tamir = pd.read_spss(Path("~/Projects/hypocognition/data/raw/Tamir2016data.sav").expanduser())
tamir

,ID,Sample,subjectnumber,GratW,DisappW,ContntW,GuiltW,JealW,SurpW,AffctnW,...,UNC3,UNT1,UNT2,UNT3,BEC1,BEC2,BEC3,BED1,BED2,BED3
0,45.0,Germany,1.0,Most of the time,Rarely,Most of the time,Rarely,Rarely,Often,Most of the time,...,Like me,Very much like me,Very much like me,Very much like me,Moderately like me,Like me,Moderately like me,Like me,Like me,Very much like me
1,47.0,Germany,2.0,Often,Rarely,Most of the time,Rarely,Rarely,Sometimes,Most of the time,...,Like me,Very much like me,Like me,Like me,Very much like me,Very much like me,Moderately like me,Moderately like me,Very much like me,Very much like me
2,48.0,Germany,3.0,Most of the time,Never,Most of the time,Never,Never,Sometimes,Most of the time,...,A little like me,Not like me,Very much like me,Very much like me,Very much like me,Like me,Like me,Very much like me,Very much like me,Very much like me
3,49.0,Germany,4.0,Often,Rarely,Most of the time,Never,Rarely,Sometimes,Often,...,Very much like me,Very much like me,Very much like me,Very much like me,Very much like me,Very much like me,Very much like me,Very much like me,Like me,Very much like me
4,50.0,Germany,5.0,Sometimes,Never,Most of the time,Never,Never,Sometimes,Sometimes,...,Moderately like me,Like me,Like me,Like me,Like me,Like me,Like me,Like me,Like me,Like me
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2323,298.0,Singapore,2324.0,Sometimes,Sometimes,Sometimes,Rarely,Rarely,Sometimes,Never,...,Moderately like me,Moderately like me,Moderately like me,Moderately like me,Moderately like me,Moderately like me,Not like me,Moderately like me,Like me,A little like me
2324,299.0,Singapore,2325.0,Often,Rarely,Often,Rarely,Rarely,Sometimes,Often,...,Moderately like me,Like me,Like me,Like me,Like me,Very much like me,Like me,Like me,Very much like me,Like me
2325,300.0,Singapore,2326.0,Often,Rarely,Most of the time,Never,Sometimes,Often,Often,...,Like me,Moderately like me,Like me,Very much like me,Very much like me,Very much like me,Very much like me,Like me,Very much like me,Very much like me
2326,301.0,Singapore,2327.0,Often,Never,Often,Rarely,Rarely,Often,Sometimes,...,Like me,Not like me,Like me,Like me,Like me,Like me,Moderately like me,A little like me,Like me,Like me
2327,302.0,Singapore,2328.0,Most of the time,Never,Most of the time,Rarely,Sometimes,Often,Most of the time,...,Very much like me,A little like me,Moderately like me,Like me,Very much like me,Like me,Like me,Moderately like me,Very much like me,Not like me

In [332]:
tamir.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2328 entries, 0 to 2327
Columns: 182 entries, ID to BED3
dtypes: category(180), float64(2)
memory usage: 506.8 KB

In [333]:
for i in tamir.columns:
    print("'",i,"',", sep="")

'ID',
'Sample',
'subjectnumber',
'GratW',
'DisappW',
'ContntW',
'GuiltW',
'JealW',
'SurpW',
'AffctnW',
'EnthuW',
'IntrstW',
'CmpssnW',
'CntmptW',
'CuriosW',
'DstressW',
'RegrtW',
'TrustW',
'ExctmntW',
'HostltyW',
'AweW',
'AdmrtnW',
'PrideW',
'LonlnsW',
'PleasrW',
'WorryW',
'HopeW',
'DesprW',
'AmazW',
'EmpthyW',
'PassnW',
'CheerfW',
'HappyW',
'StressW',
'DoubtW',
'JoyW',
'FatgueW',
'SympthW',
'EuphrW',
'PityW',
'NervousW',
'HateW',
'BordmW',
'ShameW',
'PainW',
'CalmW',
'IrritnW',
'DsgustW',
'AlertW',
'ActivW',
'FrustnW',
'DeprssW',
'EnvyW',
'SadW',
'ReliefW',
'RelaxW',
'LoveW',
'FearW',
'AmuseW',
'ShyW',
'AngrW',
'AnxtyW',
'EmbarrW',
'AweE',
'FrustnE',
'LonlnsE',
'EmpthyE',
'FearE',
'PainE',
'DstressE',
'EuphrE',
'CmpssnE',
'BordmE',
'DisappE',
'ExctmntE',
'HopeE',
'GuiltE',
'WorryE',
'DsgustE',
'DoubtE',
'HostltyE',
'DesprE',
'FatgueE',
'IrritnE',
'ReliefE',
'CalmE',
'PassnE',
'PrideE',
'EnthuE',
'NervousE',
'AdmrtnE',
'AlertE',
'GratE',
'CheerfE',
'EmbarrE',
'ShyE',
'StressE',
'DeprssE',
'JoyE',
'AmazE',
'SympthE',
'SadE',
'LoveE',
'EnvyE',
'PleasrE',
'SurpE',
'PityE',
'CntmptE',
'HappyE',
'CuriosE',
'ShameE',
'AngrE',
'RelaxE',
'ContntE',
'AffctnE',
'RegrtE',
'IntrstE',
'AnxtyE',
'AmuseE',
'TrustE',
'HateE',
'ActivE',
'JealE',
'S7_Age',
'S7_Gender',
'SDT1',
'SDT2',
'SDT3',
'SDA1',
'SDA2',
'SDA3',
'ST1',
'ST2',
'ST3',
'HE1',
'HE2',
'HE3',
'AC1',
'AC2',
'AC3',
'POD1',
'POD2',
'POD3',
'POR1',
'POR2',
'POR3',
'FAC1',
'FAC2',
'FAC3',
'SEP1',
'SEP2',
'SEP3',
'SES1',
'SES2',
'SES3',
'TR1',
'TR2',
'TR3',
'COR1',
'COR2',
'COR3',
'COI1',
'COI2',
'COI3',
'HUM1',
'HUM2',
'HUM3',
'UNN1',
'UNN2',
'UNN3',
'UNC1',
'UNC2',
'UNC3',
'UNT1',
'UNT2',
'UNT3',
'BEC1',
'BEC2',
'BEC3',
'BED1',
'BED2',
'BED3',

In [334]:
df = tamir[['ID',
'Sample',
'subjectnumber',
'GratW',
'DisappW',
'ContntW',
'GuiltW',
'JealW',
'SurpW',
'AffctnW',
'EnthuW',
'IntrstW',
'CmpssnW',
'CntmptW',
'CuriosW',
'DstressW',
'RegrtW',
'TrustW',
'ExctmntW',
'HostltyW',
'AweW',
'AdmrtnW',
'PrideW',
'LonlnsW',
'PleasrW',
'WorryW',
'HopeW',
'DesprW',
'AmazW',
'EmpthyW',
'PassnW',
'CheerfW',
'HappyW',
'StressW',
'DoubtW',
'JoyW',
'FatgueW',
'SympthW',
'EuphrW',
'PityW',
'NervousW',
'HateW',
'BordmW',
'ShameW',
'PainW',
'CalmW',
'IrritnW',
'DsgustW',
'AlertW',
'ActivW',
'FrustnW',
'DeprssW',
'EnvyW',
'SadW',
'ReliefW',
'RelaxW',
'LoveW',
'FearW',
'AmuseW',
'ShyW',
'AngrW',
'AnxtyW',
'EmbarrW',
'AweE',
'FrustnE',
'LonlnsE',
'EmpthyE',
'FearE',
'PainE',
'DstressE',
'EuphrE',
'CmpssnE',
'BordmE',
'DisappE',
'ExctmntE',
'HopeE',
'GuiltE',
'WorryE',
'DsgustE',
'DoubtE',
'HostltyE',
'DesprE',
'FatgueE',
'IrritnE',
'ReliefE',
'CalmE',
'PassnE',
'PrideE',
'EnthuE',
'NervousE',
'AdmrtnE',
'AlertE',
'GratE',
'CheerfE',
'EmbarrE',
'ShyE',
'StressE',
'DeprssE',
'JoyE',
'AmazE',
'SympthE',
'SadE',
'LoveE',
'EnvyE',
'PleasrE',
'SurpE',
'PityE',
'CntmptE',
'HappyE',
'CuriosE',
'ShameE',
'AngrE',
'RelaxE',
'ContntE',
'AffctnE',
'RegrtE',
'IntrstE',
'AnxtyE',
'AmuseE',
'TrustE',
'HateE',
'ActivE',
'JealE',
'S7_Age',
'S7_Gender']].copy()
df

,ID,Sample,subjectnumber,GratW,DisappW,ContntW,GuiltW,JealW,SurpW,AffctnW,...,RegrtE,IntrstE,AnxtyE,AmuseE,TrustE,HateE,ActivE,JealE,S7_Age,S7_Gender
0,45.0,Germany,1.0,Most of the time,Rarely,Most of the time,Rarely,Rarely,Often,Most of the time,...,Sometimes,Most of the time,Rarely,Rarely,Often,Never,Often,Rarely,23.0,Female
1,47.0,Germany,2.0,Often,Rarely,Most of the time,Rarely,Rarely,Sometimes,Most of the time,...,Often,Most of the time,Rarely,Sometimes,Never,Never,Sometimes,Sometimes,23.0,Female
2,48.0,Germany,3.0,Most of the time,Never,Most of the time,Never,Never,Sometimes,Most of the time,...,Sometimes,Often,Sometimes,Often,Often,Sometimes,Sometimes,Rarely,27.0,Male
3,49.0,Germany,4.0,Often,Rarely,Most of the time,Never,Rarely,Sometimes,Often,...,Sometimes,Often,Sometimes,Sometimes,Often,Never,Sometimes,Never,34.0,Female
4,50.0,Germany,5.0,Sometimes,Never,Most of the time,Never,Never,Sometimes,Sometimes,...,Rarely,Often,Rarely,Rarely,Most of the time,Never,Sometimes,Rarely,34.0,Female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2323,298.0,Singapore,2324.0,Sometimes,Sometimes,Sometimes,Rarely,Rarely,Sometimes,Never,...,Most of the time,Often,Often,Sometimes,Rarely,Often,Often,Sometimes,25.0,Male
2324,299.0,Singapore,2325.0,Often,Rarely,Often,Rarely,Rarely,Sometimes,Often,...,Sometimes,Often,Sometimes,Sometimes,Often,Never,Sometimes,Sometimes,24.0,Male
2325,300.0,Singapore,2326.0,Often,Rarely,Most of the time,Never,Sometimes,Often,Often,...,Rarely,Often,Often,Often,Sometimes,Rarely,Often,Often,NaN,Male
2326,301.0,Singapore,2327.0,Often,Never,Often,Rarely,Rarely,Often,Sometimes,...,Often,Often,Sometimes,Sometimes,Often,Rarely,Sometimes,Sometimes,24.0,Female
2327,302.0,Singapore,2328.0,Most of the time,Never,Most of the time,Rarely,Sometimes,Often,Most of the time,...,Rarely,Often,Rarely,Most of the time,Often,Rarely,Sometimes,Sometimes,20.0,Female

In [335]:
df.ID.nunique()

653

In [336]:
df.subjectnumber.nunique()

2328

In [337]:
df.Sample.nunique()

8

In [338]:
df.GratE.unique()

['Most of the time', 'Often', 'Sometimes', 'Rarely', 'Never', NaN]
Categories (5, object): ['Most of the time', 'Never', 'Often', 'Rarely', 'Sometimes']

In [339]:
missing_cols = df.isna().sum().sort_values(ascending=False)
print(missing_cols.to_string())

EmbarrW          45
ActivE           20
AffctnE          18
BordmE           17
AweW             17
DisappE          16
CmpssnE          16
NervousE         16
EnthuE           16
CheerfE          16
IntrstE          15
DesprE           15
HateE            15
AweE             15
EmpthyE          15
SadE             15
HopeE            14
GuiltE           14
EuphrE           14
StressE          14
EmbarrE          14
CntmptE          14
RegrtE           14
AmuseE           14
AlertE           14
EnvyE            13
SurpE            13
DoubtE           13
ReliefE          13
GratE            13
HostltyE         13
ExctmntE         13
AngrE            13
DesprW           12
CalmW            12
EuphrW           12
PassnW           12
DeprssE          12
PityE            12
PrideE           12
PassnE           12
CalmE            12
LoveE            12
ShameE           12
AnxtyE           12
AdmrtnE          12
FearE            12
DsgustE          11
IrritnE          11
ContntE          11
PainE            11
WorryE           11
FrustnE          11
ShameW           11
LoveW            11
EmpthyW          10
FatgueW          10
ExctmntW         10
PrideW           10
ContntW          10
TrustE           10
SympthE          10
AmazE            10
FatgueE          10
DstressE         10
HappyE           10
PleasrE          10
WorryW            9
LonlnsE           9
S7_Age            9
JoyE              9
JoyW              9
AmuseW            9
AngrW             9
CntmptW           9
TrustW            9
SympthW           9
JealE             9
CuriosE           9
ShyE              9
FearW             8
ActivW            8
PainW             8
CmpssnW           8
AffctnW           8
HostltyW          8
RelaxE            8
GuiltW            8
CheerfW           7
DstressW          7
RegrtW            7
StressW           7
DsgustW           7
IrritnW           6
IntrstW           6
CuriosW           6
AmazW             6
PityW             6
EnvyW             6
EnthuW            5
GratW             5
HopeW             5
BordmW            5
DeprssW           5
NervousW          5
AdmrtnW           5
LonlnsW           5
ShyW              4
SadW              4
HappyW            4
JealW             4
S7_Gender         4
DisappW           4
PleasrW           3
HateW             3
SurpW             3
FrustnW           3
DoubtW            3
RelaxW            3
AlertW            3
ReliefW           3
AnxtyW            2
Sample            0
ID                0
subjectnumber     0

In [340]:
# replace catagorical variables to discrete variables
value_map = {
    "Never": 1,
    "Rarely": 2,
    "Sometimes": 3,
    "Often": 4,
    "Most of the time": 5,
    "Male": "M",
    "Female": "F"
}

df_num = df.replace(value_map)
df_num['countryname']=df_num['Sample']

/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df.replace(value_map)
/tmp/ipykernel_2714865/424137317.py:12: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_num = df.replace(value_map)

In [341]:
df_num = df_num[df_num["countryname"].isin(['Germany', 'Israel','Brazil', 'Poland', 'China'])]
df_num

,ID,Sample,subjectnumber,GratW,DisappW,ContntW,GuiltW,JealW,SurpW,AffctnW,...,IntrstE,AnxtyE,AmuseE,TrustE,HateE,ActivE,JealE,S7_Age,S7_Gender,countryname
0,45.0,Germany,1.0,5,2,5,2,2,4,5,...,5,2,2,4,1,4,2,23.0,F,Germany
1,47.0,Germany,2.0,4,2,5,2,2,3,5,...,5,2,3,1,1,3,3,23.0,F,Germany
2,48.0,Germany,3.0,5,1,5,1,1,3,5,...,4,3,4,4,3,3,2,27.0,M,Germany
3,49.0,Germany,4.0,4,2,5,1,2,3,4,...,4,3,3,4,1,3,1,34.0,F,Germany
4,50.0,Germany,5.0,3,1,5,1,1,3,3,...,4,2,2,5,1,3,2,34.0,F,Germany
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2122,209.0,China,2123.0,3,3,4,3,2,5,4,...,4,2,4,4,2,3,2,20.0,M,China
2123,210.0,China,2124.0,5,1,5,2,1,4,4,...,3,3,3,2,2,3,2,19.0,F,China
2124,211.0,China,2125.0,3,1,4,1,2,3,4,...,4,4,3,4,2,3,2,20.0,M,China
2125,212.0,China,2126.0,3,1,4,1,2,4,5,...,4,3,3,3,2,2,2,19.0,F,China
2126,213.0,China,2127.0,3,3,4,4,4,3,4,...,3,3,3,3,3,3,3,21.0,M,China

In [342]:
df_num[(df_num['Sample']=="China")]['EmbarrE'].value_counts()

EmbarrE
3    96
2    93
4    16
1     8
5     0
Name: count, dtype: int64

In [343]:
df_num[(df_num['Sample']=="China")]['EmbarrW'].value_counts()

EmbarrW
2    90
1    69
3    39
4    14
5     1
Name: count, dtype: int64

In [344]:
emotion_map = {
    'Grat': 'Gratitude',
    'Disapp': 'Disappointment',
    'Contnt': 'Contentment',
    'Guilt': 'Guilt',
    'Jeal': 'Jealousy',
    'Surp': 'Surprise',
    'Affctn': 'Affection',
    'Enthu': 'Enthusiasm',
    'Intrst': 'Interest',
    'Cmpssn': 'Compassion',
    'Cntmpt': 'Contempt',
    'Curios': 'Curiosity',
    'Dstress': 'Distress',
    'Regrt': 'Regret',
    'Trust': 'Trust',
    'Exctmnt': 'Excitement',
    'Hostlty': 'Hostility',
    'Awe': 'Awe',
    'Admrtn': 'Admiration',
    'Pride': 'Pride',
    'Lonlns': 'Loneliness',
    'Pleasr': 'Pleasure',
    'Worry': 'Worry',
    'Hope': 'Hope',
    'Despr': 'Despair',
    'Amaz': 'Amazement',
    'Empthy': 'Empathy',
    'Passn': 'Passion',
    'Cheerf': 'Cheerfulness',
    'Happy': 'Happiness',
    'Stress': 'Stress',
    'Doubt': 'Doubt',
    'Joy': 'Joy',
    'Fatgue': 'Fatigue',
    'Sympth': 'Sympathy',
    'Euphr': 'Euphoria',
    'Pity': 'Pity',
    'Nervous': 'Nervousness',
    'Hate': 'Hatred',
    'Bordm': 'Boredom',
    'Shame': 'Shame',
    'Pain': 'Pain',
    'Calm': 'Calmness',
    'Irritn': 'Irritation',
    'Dsgust': 'Disgust',
    'Alert': 'Alertness',
    'Activ': 'Activation',
    'Frustn': 'Frustration',
    'Deprss': 'Depression',
    'Envy': 'Envy',
    'Sad': 'Sadness',
    'Relief': 'Relief',
    'Relax': 'Relaxation',
    'Love': 'Love',
    'Fear': 'Fear',
    'Amuse': 'Amusement',
    'Shy': 'Shyness',
    'Angr': 'Anger',
    'Anxty': 'Anxiety',
    'Embarr': 'Embarrassment'
}

In [345]:
# create seperate want and experience columns
want_cols = [c for c in df_num.columns if c.endswith("W")]
exp_cols  = [c for c in df_num.columns if c.endswith("E")]
want_cols

['GratW',
 'DisappW',
 'ContntW',
 'GuiltW',
 'JealW',
 'SurpW',
 'AffctnW',
 'EnthuW',
 'IntrstW',
 'CmpssnW',
 'CntmptW',
 'CuriosW',
 'DstressW',
 'RegrtW',
 'TrustW',
 'ExctmntW',
 'HostltyW',
 'AweW',
 'AdmrtnW',
 'PrideW',
 'LonlnsW',
 'PleasrW',
 'WorryW',
 'HopeW',
 'DesprW',
 'AmazW',
 'EmpthyW',
 'PassnW',
 'CheerfW',
 'HappyW',
 'StressW',
 'DoubtW',
 'JoyW',
 'FatgueW',
 'SympthW',
 'EuphrW',
 'PityW',
 'NervousW',
 'HateW',
 'BordmW',
 'ShameW',
 'PainW',
 'CalmW',
 'IrritnW',
 'DsgustW',
 'AlertW',
 'ActivW',
 'FrustnW',
 'DeprssW',
 'EnvyW',
 'SadW',
 'ReliefW',
 'RelaxW',
 'LoveW',
 'FearW',
 'AmuseW',
 'ShyW',
 'AngrW',
 'AnxtyW',
 'EmbarrW']

In [346]:
exp_cols

['AweE',
 'FrustnE',
 'LonlnsE',
 'EmpthyE',
 'FearE',
 'PainE',
 'DstressE',
 'EuphrE',
 'CmpssnE',
 'BordmE',
 'DisappE',
 'ExctmntE',
 'HopeE',
 'GuiltE',
 'WorryE',
 'DsgustE',
 'DoubtE',
 'HostltyE',
 'DesprE',
 'FatgueE',
 'IrritnE',
 'ReliefE',
 'CalmE',
 'PassnE',
 'PrideE',
 'EnthuE',
 'NervousE',
 'AdmrtnE',
 'AlertE',
 'GratE',
 'CheerfE',
 'EmbarrE',
 'ShyE',
 'StressE',
 'DeprssE',
 'JoyE',
 'AmazE',
 'SympthE',
 'SadE',
 'LoveE',
 'EnvyE',
 'PleasrE',
 'SurpE',
 'PityE',
 'CntmptE',
 'HappyE',
 'CuriosE',
 'ShameE',
 'AngrE',
 'RelaxE',
 'ContntE',
 'AffctnE',
 'RegrtE',
 'IntrstE',
 'AnxtyE',
 'AmuseE',
 'TrustE',
 'HateE',
 'ActivE',
 'JealE']

In [347]:
# transform the dataset to have those new columns
base_cols = ["ID","countryname","subjectnumber","S7_Age","S7_Gender"]

want_long = df_num.melt(
    id_vars=base_cols,
    value_vars=want_cols,
    var_name="emotion_code",
    value_name="want"
)

exp_long = df_num.melt(
    id_vars=base_cols,
    value_vars=exp_cols,
    var_name="emotion_code",
    value_name="experience"
)
want_long

          ID countryname  subjectnumber  S7_Age S7_Gender emotion_code want
0       45.0     Germany            1.0    23.0         F        GratW    5
1       47.0     Germany            2.0    23.0         F        GratW    4
2       48.0     Germany            3.0    27.0         M        GratW    5
3       49.0     Germany            4.0    34.0         F        GratW    4
4       50.0     Germany            5.0    34.0         F        GratW    3
...      ...         ...            ...     ...       ...          ...  ...
96955  209.0       China         2123.0    20.0         M      EmbarrW    2
96956  210.0       China         2124.0    19.0         F      EmbarrW    1
96957  211.0       China         2125.0    20.0         M      EmbarrW    1
96958  212.0       China         2126.0    19.0         F      EmbarrW    2
96959  213.0       China         2127.0    21.0         M      EmbarrW    4

[96960 rows x 7 columns]

In [348]:
want_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96960 entries, 0 to 96959
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             96960 non-null  category
 1   countryname    96960 non-null  category
 2   subjectnumber  96960 non-null  float64
 3   S7_Age         96600 non-null  float64
 4   S7_Gender      96780 non-null  category
 5   emotion_code   96960 non-null  object
 6   want           96817 non-null  category
dtypes: category(4), float64(2), object(1)
memory usage: 2.7+ MB

In [349]:
exp_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96960 entries, 0 to 96959
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             96960 non-null  category
 1   countryname    96960 non-null  category
 2   subjectnumber  96960 non-null  float64
 3   S7_Age         96600 non-null  float64
 4   S7_Gender      96780 non-null  category
 5   emotion_code   96960 non-null  object
 6   experience     96451 non-null  category
dtypes: category(4), float64(2), object(1)
memory usage: 2.7+ MB

In [350]:
# break up the column name into two new columns, emotion and want, and a sepearte table for emotion and experience
want_long['word'] = (
    want_long["emotion_code"]
    .str.replace(r".$", "", regex=True)
    .map(emotion_map)
)

exp_long['word'] = (
    exp_long["emotion_code"]
    .str.replace(r".$", "", regex=True)
    .map(emotion_map)
)
exp_long

,ID,countryname,subjectnumber,S7_Age,S7_Gender,emotion_code,experience,word
0,45.0,Germany,1.0,23.0,F,AweE,3,Awe
1,47.0,Germany,2.0,23.0,F,AweE,3,Awe
2,48.0,Germany,3.0,27.0,M,AweE,3,Awe
3,49.0,Germany,4.0,34.0,F,AweE,3,Awe
4,50.0,Germany,5.0,34.0,F,AweE,2,Awe
...,...,...,...,...,...,...,...,...
96955,209.0,China,2123.0,20.0,M,JealE,2,Jealousy
96956,210.0,China,2124.0,19.0,F,JealE,2,Jealousy
96957,211.0,China,2125.0,20.0,M,JealE,2,Jealousy
96958,212.0,China,2126.0,19.0,F,JealE,2,Jealousy
96959,213.0,China,2127.0,21.0,M,JealE,3,Jealousy

In [351]:
# here is where things fall apart
exp_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96960 entries, 0 to 96959
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             96960 non-null  category
 1   countryname    96960 non-null  category
 2   subjectnumber  96960 non-null  float64
 3   S7_Age         96600 non-null  float64
 4   S7_Gender      96780 non-null  category
 5   emotion_code   96960 non-null  object
 6   experience     96451 non-null  category
 7   word           96960 non-null  object
dtypes: category(4), float64(2), object(2)
memory usage: 3.4+ MB

In [352]:
want_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96960 entries, 0 to 96959
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             96960 non-null  category
 1   countryname    96960 non-null  category
 2   subjectnumber  96960 non-null  float64
 3   S7_Age         96600 non-null  float64
 4   S7_Gender      96780 non-null  category
 5   emotion_code   96960 non-null  object
 6   want           96817 non-null  category
 7   word           96960 non-null  object
dtypes: category(4), float64(2), object(2)
memory usage: 3.4+ MB

In [353]:
# merge the want and experience tables togethor
final = want_long.merge(
    exp_long[["ID","countryname","subjectnumber","word","experience"]],
    on=["ID","countryname","subjectnumber","word"],
    how="left"
)

final["word"] = final["word"].str.lower()

final

,ID,countryname,subjectnumber,S7_Age,S7_Gender,emotion_code,want,word,experience
0,45.0,Germany,1.0,23.0,F,GratW,5,gratitude,5
1,47.0,Germany,2.0,23.0,F,GratW,4,gratitude,5
2,48.0,Germany,3.0,27.0,M,GratW,5,gratitude,4
3,49.0,Germany,4.0,34.0,F,GratW,4,gratitude,4
4,50.0,Germany,5.0,34.0,F,GratW,3,gratitude,3
...,...,...,...,...,...,...,...,...,...
96955,209.0,China,2123.0,20.0,M,EmbarrW,2,embarrassment,3
96956,210.0,China,2124.0,19.0,F,EmbarrW,1,embarrassment,3
96957,211.0,China,2125.0,20.0,M,EmbarrW,1,embarrassment,3
96958,212.0,China,2126.0,19.0,F,EmbarrW,2,embarrassment,3
96959,213.0,China,2127.0,21.0,M,EmbarrW,4,embarrassment,4

In [354]:
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96960 entries, 0 to 96959
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             96960 non-null  category
 1   countryname    96960 non-null  category
 2   subjectnumber  96960 non-null  float64
 3   S7_Age         96600 non-null  float64
 4   S7_Gender      96780 non-null  category
 5   emotion_code   96960 non-null  object
 6   want           96817 non-null  category
 7   word           96960 non-null  object
 8   experience     96451 non-null  category
dtypes: category(5), float64(2), object(2)
memory usage: 3.5+ MB

In [355]:
#clean up
final = final.rename(columns={
    "S7_Age":"age",
    "S7_Gender":"gender"
})

final = final[[
    "ID","countryname","subjectnumber",
    "word","want","experience",
    "age","gender"
]]
final

,ID,countryname,subjectnumber,word,want,experience,age,gender
0,45.0,Germany,1.0,gratitude,5,5,23.0,F
1,47.0,Germany,2.0,gratitude,4,5,23.0,F
2,48.0,Germany,3.0,gratitude,5,4,27.0,M
3,49.0,Germany,4.0,gratitude,4,4,34.0,F
4,50.0,Germany,5.0,gratitude,3,3,34.0,F
...,...,...,...,...,...,...,...,...
96955,209.0,China,2123.0,embarrassment,2,3,20.0,M
96956,210.0,China,2124.0,embarrassment,1,3,19.0,F
96957,211.0,China,2125.0,embarrassment,1,3,20.0,M
96958,212.0,China,2126.0,embarrassment,2,3,19.0,F
96959,213.0,China,2127.0,embarrassment,4,4,21.0,M

In [356]:
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96960 entries, 0 to 96959
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             96960 non-null  category
 1   countryname    96960 non-null  category
 2   subjectnumber  96960 non-null  float64
 3   word           96960 non-null  object
 4   want           96817 non-null  category
 5   experience     96451 non-null  category
 6   age            96600 non-null  float64
 7   gender         96780 non-null  category
dtypes: category(5), float64(2), object(1)
memory usage: 2.8+ MB

In [357]:
# Load prviously created table of language selections
selection = pd.read_csv(Path("~/Projects/hypocognition/data/processed/selection_in_bila.csv"), index_col=0)
selection

,countryname,language,study_language_names,bila_language_name_mapping,lang_responses,total_responses,percent,Selected,reason,possible_alternative_bila_language_name_mappings
0,Australia,ZH-S,Simplified Chinese,Mandarin Chinese,181,378,47.883598,0,We will leave out Australia for now because i...,"Beijing Mandarin, Wu Chinese"
1,Brazil,PT-BR,Brazilian Portuguese,Brazilian Portuguese,306,325,94.153846,1,Let's use Brazilian Portuguese for Brazil,Portuguese
2,Bulgaria,BG,Bulgarian,Bulgarian,269,276,97.463768,1,Let's use Bulgarian for Bulgaria,NaN
3,Canada,EN,English,NaN,195,286,68.181818,0,"Doesn't look good for Canada, we will drop the...","Midland American English, Singlish, Devon, Sus..."
4,Chile,ES,Spanish,Spanish,469,493,95.131846,1,Let's use Spanish (General) for chile,"Latin American Spanish, Mexican Spanish"
5,China,ZH-S,Simplified Chinese,Mandarin Chinese,1988,2009,98.954704,1,Let's use Simplified Chinese for china,"Beijing Mandarin, Wu Chinese"
6,Colombia,ES,Spanish,Spanish,122,237,51.476793,1,Let's use Spanish (General) for Colombia,"Latin American Spanish, Mexican Spanish"
7,Croatia,HR,Croatian,Serbian-Croatian-Bosnian,524,528,99.242424,1,Let's use croatian for croatia,NaN
8,Curacao,NL,Dutch,Dutch,180,235,76.595745,1,Let's use Dutch for Curacao,Western Flemish
9,Denmark,DA,Danish,Danish,148,233,63.519313,1,Let's use Danish for Denmark,NaN
10,Egypt,AR,Arabic,Arabic,817,824,99.150485,1,Let's use Arabic for Eygpt,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
11,Finland,FI,Finnish,Finnish,260,289,89.965398,1,Let's use Finnish for Finland,Estonian
12,France,FR,French,French,257,363,70.798898,1,Let's use french for france,"Old French, Cajun French, Louisiana Creole French"
13,Georgia,KAT,Georgian,Georgian,234,236,99.152542,1,Let's use Georgian for Georgia,NaN
14,Germany,DE,German,German,291,567,51.322751,1,Let's use German for Germany,"Moselle Franconian, Plautdietsch, Pennsylvania..."
15,Ghana,EN,English,NaN,327,328,99.695122,0,"doesnt look good for Ghana, well drop it","Midland American English, Singlish, Devon, Sus..."
16,Greece,EL,Greek,Greek,227,253,89.723320,1,Let's use Greek for Greece,NaN
17,Hong Kong (S.A.R),ZH-T,Traditional Chinese,Mandarin Chinese,139,228,60.964912,1,Let's use Traditional Chinese for Hong Kong,"Yue Chinese, Min Dong Chinese, Min Nan Chinese..."
18,Hungary,HU,Hungarian,Hungarian,256,464,55.172414,1,Let's use Hungarian for Hungary,NaN
19,Iceland,ISL,Icelandic,Icelandic,348,354,98.305085,1,Let's use Icelandic for Iceland,Old Norse
20,India,MAR,Marathi,Marathi,56,243,23.045267,1,This is a tough call. I think we will use Mar...,NaN
21,Indonesia,ID,Indonesian,Indonesian,648,656,98.780488,1,Let's use Indonesian for indonesia,"Standard Malay, Central Malay, Baba Malay"
22,Iran,FA,Persian,Persian,187,195,95.897436,1,Let's use persian for Iran,NaN
23,Ireland,EN,English,NaN,351,362,96.961326,0,"Doesn't look good for Ireland, their primary ...","Midland American English, Singlish, Devon, Sus..."
24,Israel,HE,Hebrew,Hebrew,151,211,71.563981,1,Lets use Hebrew for Israel,Ancient Hebrew
25,Italy,IT,Italian,Italian,426,466,91.416309,1,lets use Italian for Italy,Sicilian
26,Japan,JA,Japanese,Japanese,1288,1352,95.266272,1,Let's use Japanese for Japan,Middle Chinese
27,Jordan,AR,Arabic,Arabic,233,236,98.728814,1,Let's use Arabic for Jordan,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
28,Kazakhstan,RU,Russian,Russian,279,291,95.876289,1,Let's use Russian for Kazakhstan,Belarusian
29,Kenya,EN,English,NaN,207,207,100.000000,0,"Nope, sorry Kenya, to much english","Midland American English, Singlish, Devon, Sus..."
30,Malaysia,MS,Malay,Standard Malay,155,214,72.429907,1,Let's use Malay for Malaysia,"Central Malay, Baba Malay, Malayo"
31,Malta,MALTI,Maltese,NaN,284,1290,22.015504,1,"Tough call, we will use Maltese for Malta ins...","Arabic, Italian"
32,Mongolia,EN,English,NaN,188,208,90.384615,0,"Nope, sorry mongolia, too much english","Midland American English, Singlish, Devon, Sus..."
33,Netherlands,NL,Dutch,Dutch,524,1348,38.872404,1,Let's use dutch for the Netherlands,Western Flemish
34,New Zealand,EN,English,NaN,150,262,57.251908,0,We're actually not going to keep Australia an...,"Midland American English, Singlish, Devon, Sus..."
35,Pakistan,EN,English,NaN,555,557,99.640934,0,"nope, sorry pakistan, too much english","Midland American English, Singlish, Devon, Sus..."
36,Peru,ES-ES,Spanish (Spain),Spanish,215,357,60.224090,1,lets use Spanish spain for PEru,NaN
37,Russia,RU,Russian,Russian,577,586,98.464164,1,# lets use russian for russia,Belarusian
38,Serbia,SR,Serbian,Serbian-Croatian-Bosnian,351,354,99.152542,1,lets use serbian for serbia,NaN
39,Singapore,EN,English,NaN,187,208,89.903846,0,"nope, sorry singapore, too much english","Midland American English, Singlish, Devon, Sus..."
40,South Africa,AFRI,Afrikaans,Afrikaans,112,426,26.291080,1,"Interesting, we will use Africaans for south ...",Dutch
41,Spain,ES-ES,Spanish (Spain),Spanish,105,418,25.119617,1,"I know we don't have Catalan dictionary, so w...",NaN
42,Sweden,SV,Swedish,Swedish,400,529,75.614367,1,We will use Swedish for Sweden,NaN
43,Syria,AR,Arabic,Arabic,247,248,99.596774,1,we will use Arabic for Syria,"Egyptian Arabic, Levantine Arabic, Moroccan Ar..."
44,Taiwan,ZH-TW,Traditional Chinese (Taiwan),Mandarin Chinese,747,761,98.160315,1,we will use Traditional Chinese (Taiwan) for...,"Min Nan Chinese, Hakka Chinese"
45,Trinidad and Tobago,EN,English,NaN,333,334,99.700599,0,"nope, sorry T&T, too much english","Midland American English, Singlish, Devon, Sus..."
46,Turkey,TR,Turkish,Turkish,253,346,73.121387,1,# we will use Turkish for turkey,Turkmen
47,Ukraine,UK,Ukrainian,Ukrainian,657,698,94.126074,1,we will use ukrainian for Ukraine,NaN
48,United Kingdom (UK),EN,English,NaN,454,662,68.580060,0,"nope, sorry UK, too much english","Midland American English, Singlish, Devon, Sus..."
49,United States of America (USA),EN,English,NaN,768,952,80.672269,0,"nope, sorry US, too much english","Midland American English, Singlish, Devon, Sus..."
50,Vietnam,VI,Vietnamese,Vietnamese,292,338,86.390533,1,We will use vietnamese for vietnam,Nung (Viet Nam)

In [358]:
# merge what we want from our selection table into of Tamir data
some_info = selection[['countryname',	'study_language_names',	'bila_language_name_mapping']].copy()
final_mapped = final.merge(
    some_info,
    left_on='countryname',
    right_on='countryname',
    how='left'
)
final_mapped

,ID,countryname,subjectnumber,word,want,experience,age,gender,study_language_names,bila_language_name_mapping
0,45.0,Germany,1.0,gratitude,5,5,23.0,F,German,German
1,47.0,Germany,2.0,gratitude,4,5,23.0,F,German,German
2,48.0,Germany,3.0,gratitude,5,4,27.0,M,German,German
3,49.0,Germany,4.0,gratitude,4,4,34.0,F,German,German
4,50.0,Germany,5.0,gratitude,3,3,34.0,F,German,German
...,...,...,...,...,...,...,...,...,...,...
96955,209.0,China,2123.0,embarrassment,2,3,20.0,M,Simplified Chinese,Mandarin Chinese
96956,210.0,China,2124.0,embarrassment,1,3,19.0,F,Simplified Chinese,Mandarin Chinese
96957,211.0,China,2125.0,embarrassment,1,3,20.0,M,Simplified Chinese,Mandarin Chinese
96958,212.0,China,2126.0,embarrassment,2,3,19.0,F,Simplified Chinese,Mandarin Chinese
96959,213.0,China,2127.0,embarrassment,4,4,21.0,M,Simplified Chinese,Mandarin Chinese

In [359]:
final_mapped[final_mapped['countryname']=='Poland']

,ID,countryname,subjectnumber,word,want,experience,age,gender,study_language_names,bila_language_name_mapping
1101,"1,00",Poland,1613.0,gratitude,2,2,21.0,M,NaN,NaN
1102,"2,00",Poland,1614.0,gratitude,3,2,23.0,F,NaN,NaN
1103,"3,00",Poland,1615.0,gratitude,3,3,22.0,F,NaN,NaN
1104,"4,00",Poland,1616.0,gratitude,4,3,19.0,F,NaN,NaN
1105,"5,00",Poland,1617.0,gratitude,2,3,23.0,F,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
96742,304.0,Poland,1910.0,embarrassment,1,2,24.0,M,NaN,NaN
96743,306.0,Poland,1911.0,embarrassment,3,3,NaN,NaN,NaN,NaN
96744,307.0,Poland,1912.0,embarrassment,2,2,23.0,M,NaN,NaN
96745,308.0,Poland,1913.0,embarrassment,1,1,20.0,M,NaN,NaN
96746,309.0,Poland,1914.0,embarrassment,1,3,22.0,M,NaN,NaN

In [360]:
# Poland wasn't an option in our previious selection, but we do have BILA data on it, so we'll just manually add the mapping
final_mapped.loc[final_mapped["countryname"] == "Poland", ["study_language_names", "bila_language_name_mapping"]] = "Polish"
final_mapped[final_mapped['countryname']=='Poland']

,ID,countryname,subjectnumber,word,want,experience,age,gender,study_language_names,bila_language_name_mapping
1101,"1,00",Poland,1613.0,gratitude,2,2,21.0,M,Polish,Polish
1102,"2,00",Poland,1614.0,gratitude,3,2,23.0,F,Polish,Polish
1103,"3,00",Poland,1615.0,gratitude,3,3,22.0,F,Polish,Polish
1104,"4,00",Poland,1616.0,gratitude,4,3,19.0,F,Polish,Polish
1105,"5,00",Poland,1617.0,gratitude,2,3,23.0,F,Polish,Polish
...,...,...,...,...,...,...,...,...,...,...
96742,304.0,Poland,1910.0,embarrassment,1,2,24.0,M,Polish,Polish
96743,306.0,Poland,1911.0,embarrassment,3,3,NaN,NaN,Polish,Polish
96744,307.0,Poland,1912.0,embarrassment,2,2,23.0,M,Polish,Polish
96745,308.0,Poland,1913.0,embarrassment,1,1,20.0,M,Polish,Polish
96746,309.0,Poland,1914.0,embarrassment,1,3,22.0,M,Polish,Polish

In [361]:
# A specific status check we will run
def combo_counts(df):
    cc = df.groupby(["countryname", "glottocode"])
    size = cc.size().reset_index(name="n_rows").sort_values("n_rows", ascending=False)
    return size

In [362]:
# get the dataset of the dictionaries. We will look at how elaborated each of the twenty emotions are in each of the 39 languages
bila_nouns_full = pd.read_csv(Path("~/Projects/hypocognition/data/raw/bila_long_noun_lemmatized_full.csv").expanduser(), index_col=0)
bila_nouns_full

/tmp/ipykernel_2714865/268126284.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  bila_nouns_full = pd.read_csv(Path("~/Projects/hypocognition/data/raw/bila_long_noun_lemmatized_full.csv").expanduser(), index_col=0)

,id,word,nsenses,count,langname,glottocode,year,title,imprint,author,area,langfamily,affiliation,longitude,latitude,estimate,regression_elaboration,dictsize_data,simple_elaboration,log_count
0,chi.14718491,abdomen,2.0,1.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-9.130648,-0.030722,10499,0.000095,0.693147
1,chi.14718491,ability,2.0,2.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.725128,-1.424169,10499,0.000190,1.098612
2,chi.14718491,absence,4.0,2.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.725128,-0.677996,10499,0.000190,1.098612
3,chi.14718491,abstinence,2.0,5.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.031819,3.864680,10499,0.000476,1.791759
4,chi.14718491,abundance,3.0,4.0,Nancowry,nanc1247,1884,A dictionary of the Nancowry dialect of the Ni...,"Printed at the Home Dept. Press, 1884.",0,Eurasia,Austroasiatic,"Austroasiatic, Nicobaric, Nuclear Nicobaric, C...",93.3921,7.94812,-8.214194,0.484280,10499,0.000381,1.609438
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1824416,wu.89119131142,zephyr,2.0,2.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,-9.530683,1.086020,33359,0.000060,1.098612
1824417,wu.89119131142,zinc,2.0,2.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,-9.530683,-0.009188,33359,0.000060,1.098612
1824418,wu.89119131142,zone,6.0,4.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,-9.019809,-0.305218,33359,0.000120,1.609438
1824419,wu.89119131142,zoo,1.0,1.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,-9.936173,-1.879701,33359,0.000030,0.693147
1824420,wu.89119131142,zoom,5.0,1.0,Herero,here1253,1989,An English-Herero dictionary : with an introdu...,"J.C. Juta, 1883.",0,Africa,Atlantic-Congo,"Atlantic-Congo, Volta-Congo, Benue-Congo, Bant...",20.5655,-21.02310,-9.936173,0.493464,33359,0.000030,0.693147

In [363]:
# Get the list of columns as a vertical list
for i in bila_nouns_full.columns:
    print("'", i, "',", sep="")

'id',
'word',
'nsenses',
'count',
'langname',
'glottocode',
'year',
'title',
'imprint',
'author',
'area',
'langfamily',
'affiliation',
'longitude',
'latitude',
'estimate',
'regression_elaboration',
'dictsize_data',
'simple_elaboration',
'log_count',

In [364]:
# Merge the BILA data we care about
some_info = bila_nouns_full[[
    'id',
    'word',
    'count',
    'langname',
    'glottocode',
    'year',
    'title',
    'author',
    'regression_elaboration',
    'dictsize_data',
    'simple_elaboration',
    'log_count']].copy()
final_mapped = final_mapped.merge(
    some_info,
    left_on=['word', 'bila_language_name_mapping'],
    right_on=['word','langname'],
    how='left'
)
final_mapped

,ID,countryname,subjectnumber,word,want,experience,age,gender,study_language_names,bila_language_name_mapping,...,count,langname,glottocode,year,title,author,regression_elaboration,dictsize_data,simple_elaboration,log_count
0,45.0,Germany,1.0,gratitude,5,5,23.0,F,German,German,...,19.0,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732
1,47.0,Germany,2.0,gratitude,4,5,23.0,F,German,German,...,19.0,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732
2,48.0,Germany,3.0,gratitude,5,4,27.0,M,German,German,...,19.0,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732
3,49.0,Germany,4.0,gratitude,4,4,34.0,F,German,German,...,19.0,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732
4,50.0,Germany,5.0,gratitude,3,3,34.0,F,German,German,...,19.0,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96955,209.0,China,2123.0,embarrassment,2,3,20.0,M,Simplified Chinese,Mandarin Chinese,...,7.0,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442
96956,210.0,China,2124.0,embarrassment,1,3,19.0,F,Simplified Chinese,Mandarin Chinese,...,7.0,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442
96957,211.0,China,2125.0,embarrassment,1,3,20.0,M,Simplified Chinese,Mandarin Chinese,...,7.0,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442
96958,212.0,China,2126.0,embarrassment,2,3,19.0,F,Simplified Chinese,Mandarin Chinese,...,7.0,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442
96959,213.0,China,2127.0,embarrassment,4,4,21.0,M,Simplified Chinese,Mandarin Chinese,...,7.0,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442

In [365]:
bila_nouns_full[(bila_nouns_full['id']=="uc1.l0088545033") & (bila_nouns_full['word']== 'activation')]['count']

1457576    1.0
Name: count, dtype: float64

In [366]:
final_mapped[(final_mapped['id']=="uc1.l0088545033") & (final_mapped['word']== 'activation')]['count'].head(1)

75739    1.0
Name: count, dtype: float64

In [367]:
combo_counts(final_mapped)

  countryname glottocode  n_rows
0      Brazil   braz1246   18937
4      Poland   poli1260   16610
3      Israel   hebr1245   13392
1       China   mand1415   11928
2     Germany   stan1295   11600

In [368]:
final_mapped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96960 entries, 0 to 96959
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          96960 non-null  category
 1   countryname                 96960 non-null  object
 2   subjectnumber               96960 non-null  float64
 3   word                        96960 non-null  object
 4   want                        96817 non-null  category
 5   experience                  96451 non-null  category
 6   age                         96600 non-null  float64
 7   gender                      96780 non-null  category
 8   study_language_names        96960 non-null  object
 9   bila_language_name_mapping  96960 non-null  object
 10  id                          72467 non-null  object
 11  count                       72467 non-null  float64
 12  langname                    72467 non-null  object
 13  glottocode                  72467 non-null  object
 14  year                        72467 non-null  float64
 15  title                       72467 non-null  object
 16  author                      72467 non-null  object
 17  regression_elaboration      72467 non-null  float64
 18  dictsize_data               72467 non-null  float64
 19  simple_elaboration          72467 non-null  float64
 20  log_count                   72467 non-null  float64
dtypes: category(4), float64(8), object(9)
memory usage: 13.1+ MB

In [369]:
# I think we will needs these later
dictionary_means = (
    bila_nouns_full
        .groupby('id', as_index=False)['count']
        .mean()
        .rename(columns={'count': 'dictionary_count_mean'})
)
dictionary_means

                                          id  dictionary_count_mean
0                               chi.14718491               8.153281
1                         coo.31924067983704              22.086550
2                         coo.31924099174934               2.813851
3                  coo1.ark:/13960/t9m33d507               5.176960
4     dictionaria.daakaka_vonprince_daka1243               2.854041
..                                       ...                    ...
611  webonary.sursurunga_hutchisson_surs1246              22.626872
612         webonary.tampulma_asare_tamp1252               8.364666
613      webonary.turkmen_almamedow_turk1304               9.002773
614                           wu.89017649658               4.613689
615                           wu.89119131142              13.889959

[616 rows x 2 columns]

In [370]:
# add a value of zero to the numerical columns, becuase the dictionary doesn't have those words and therefore the value is 0
# we're doing it one at a time becuase of things got corrupted when I tried doing them all at the same time
print(final_mapped[(final_mapped['id']=="uc1.l0088545033") & (final_mapped['word']== 'activation')]['count'].head(1))
final_mapped['count'] = final_mapped['count'].fillna(0)
print(final_mapped[(final_mapped['id']=="uc1.l0088545033") & (final_mapped['word']== 'activation')]['count'].head(1))

75739    1.0
Name: count, dtype: float64
75739    1.0
Name: count, dtype: float64

In [371]:
print(final_mapped[(final_mapped['id']=="uc1.l0088545033") & (final_mapped['word']== 'activation')]['regression_elaboration'].head(1))
final_mapped['regression_elaboration'] = final_mapped['regression_elaboration'].fillna(0)
print(final_mapped[(final_mapped['id']=="uc1.l0088545033") & (final_mapped['word']== 'activation')]['regression_elaboration'].head(1))

75739   -0.514848
Name: regression_elaboration, dtype: float64
75739   -0.514848
Name: regression_elaboration, dtype: float64

In [372]:
print(final_mapped[(final_mapped['id']=="uc1.l0088545033") & (final_mapped['word']== 'activation')]['simple_elaboration'].head(1))
final_mapped['simple_elaboration'] = final_mapped['simple_elaboration'].fillna(0)
print(final_mapped[(final_mapped['id']=="uc1.l0088545033") & (final_mapped['word']== 'activation')]['simple_elaboration'].head(1))

75739    0.00001
Name: simple_elaboration, dtype: float64
75739    0.00001
Name: simple_elaboration, dtype: float64

In [373]:
print(final_mapped[(final_mapped['id']=="uc1.l0088545033") & (final_mapped['word']== 'activation')]['log_count'].head(1))
final_mapped['log_count'] = final_mapped['log_count'].fillna(0)
print(final_mapped[(final_mapped['id']=="uc1.l0088545033") & (final_mapped['word']== 'activation')]['log_count'].head(1))

75739    0.693147
Name: log_count, dtype: float64
75739    0.693147
Name: log_count, dtype: float64

In [374]:
final_mapped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96960 entries, 0 to 96959
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          96960 non-null  category
 1   countryname                 96960 non-null  object
 2   subjectnumber               96960 non-null  float64
 3   word                        96960 non-null  object
 4   want                        96817 non-null  category
 5   experience                  96451 non-null  category
 6   age                         96600 non-null  float64
 7   gender                      96780 non-null  category
 8   study_language_names        96960 non-null  object
 9   bila_language_name_mapping  96960 non-null  object
 10  id                          72467 non-null  object
 11  count                       96960 non-null  float64
 12  langname                    72467 non-null  object
 13  glottocode                  72467 non-null  object
 14  year                        72467 non-null  float64
 15  title                       72467 non-null  object
 16  author                      72467 non-null  object
 17  regression_elaboration      96960 non-null  float64
 18  dictsize_data               72467 non-null  float64
 19  simple_elaboration          96960 non-null  float64
 20  log_count                   96960 non-null  float64
dtypes: category(4), float64(8), object(9)
memory usage: 13.1+ MB

In [375]:
final_complete = final_mapped.copy()

In [376]:
combo_counts(final_complete)

  countryname glottocode  n_rows
0      Brazil   braz1246   18937
4      Poland   poli1260   16610
3      Israel   hebr1245   13392
1       China   mand1415   11928
2     Germany   stan1295   11600

In [380]:
#Create full ID × word grid so that we can fill in the missing data for words which don't appear in a particular dictionary

# Columns to to impute based on where they are present in other rows with the same ID
cols_to_fill = ['id', 'langname', 
                'glottocode', 'year', 'title', 'author', 'dictsize_data']

# Fill missing metadata using other rows in the same country + language
final_complete[cols_to_fill] = (
    final_complete
    .groupby(['countryname', 'bila_language_name_mapping'])[cols_to_fill]
    .transform(lambda x: x.ffill().bfill())
)
final_complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96960 entries, 0 to 96959
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          96960 non-null  category
 1   countryname                 96960 non-null  object
 2   subjectnumber               96960 non-null  float64
 3   word                        96960 non-null  object
 4   want                        96817 non-null  category
 5   experience                  96451 non-null  category
 6   age                         96600 non-null  float64
 7   gender                      96780 non-null  category
 8   study_language_names        96960 non-null  object
 9   bila_language_name_mapping  96960 non-null  object
 10  id                          96960 non-null  object
 11  count                       96960 non-null  float64
 12  langname                    96960 non-null  object
 13  glottocode                  96960 non-null  object
 14  year                        96960 non-null  float64
 15  title                       96960 non-null  object
 16  author                      96960 non-null  object
 17  regression_elaboration      96960 non-null  float64
 18  dictsize_data               96960 non-null  float64
 19  simple_elaboration          96960 non-null  float64
 20  log_count                   96960 non-null  float64
dtypes: category(4), float64(8), object(9)
memory usage: 13.1+ MB

/tmp/ipykernel_2714865/1604633816.py:11: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .transform(lambda x: x.ffill().bfill())

In [381]:
combo_counts(final_complete)

  countryname glottocode  n_rows
0      Brazil   braz1246   39180
4      Poland   poli1260   18120
3      Israel   hebr1245   14880
1       China   mand1415   12780
2     Germany   stan1295   12000

In [382]:

final_complete

,ID,countryname,subjectnumber,word,want,experience,age,gender,study_language_names,bila_language_name_mapping,...,count,langname,glottocode,year,title,author,regression_elaboration,dictsize_data,simple_elaboration,log_count
0,45.0,Germany,1.0,gratitude,5,5,23.0,F,German,German,...,19.0,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732
1,47.0,Germany,2.0,gratitude,4,5,23.0,F,German,German,...,19.0,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732
2,48.0,Germany,3.0,gratitude,5,4,27.0,M,German,German,...,19.0,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732
3,49.0,Germany,4.0,gratitude,4,4,34.0,F,German,German,...,19.0,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732
4,50.0,Germany,5.0,gratitude,3,3,34.0,F,German,German,...,19.0,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96955,209.0,China,2123.0,embarrassment,2,3,20.0,M,Simplified Chinese,Mandarin Chinese,...,7.0,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442
96956,210.0,China,2124.0,embarrassment,1,3,19.0,F,Simplified Chinese,Mandarin Chinese,...,7.0,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442
96957,211.0,China,2125.0,embarrassment,1,3,20.0,M,Simplified Chinese,Mandarin Chinese,...,7.0,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442
96958,212.0,China,2126.0,embarrassment,2,3,19.0,F,Simplified Chinese,Mandarin Chinese,...,7.0,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442
96959,213.0,China,2127.0,embarrassment,4,4,21.0,M,Simplified Chinese,Mandarin Chinese,...,7.0,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442

In [383]:
print(bila_nouns_full[(bila_nouns_full['id']=="uc1.l0088545033") & (bila_nouns_full['word']== 'activation')]['count'])
print(final_complete[(final_complete['id']=="uc1.l0088545033") & (final_complete['word']== 'activation')]['count'].head(1))

1457576    1.0
Name: count, dtype: float64
75739    1.0
Name: count, dtype: float64

In [384]:
# need dict count mean
# add the dictionary_count_mean
final_complete = final_complete.merge(
    dictionary_means,
    left_on='id',
    right_on='id',
    how='left'
)
final_complete
# need response_std, so perhaps one for want and one for experienced

,ID,countryname,subjectnumber,word,want,experience,age,gender,study_language_names,bila_language_name_mapping,...,langname,glottocode,year,title,author,regression_elaboration,dictsize_data,simple_elaboration,log_count,dictionary_count_mean
0,45.0,Germany,1.0,gratitude,5,5,23.0,F,German,German,...,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732,34.214196
1,47.0,Germany,2.0,gratitude,4,5,23.0,F,German,German,...,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732,34.214196
2,48.0,Germany,3.0,gratitude,5,4,27.0,M,German,German,...,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732,34.214196
3,49.0,Germany,4.0,gratitude,4,4,34.0,F,German,German,...,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732,34.214196
4,50.0,Germany,5.0,gratitude,3,3,34.0,F,German,German,...,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732,34.214196
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96955,209.0,China,2123.0,embarrassment,2,3,20.0,M,Simplified Chinese,Mandarin Chinese,...,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442,15.648172
96956,210.0,China,2124.0,embarrassment,1,3,19.0,F,Simplified Chinese,Mandarin Chinese,...,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442,15.648172
96957,211.0,China,2125.0,embarrassment,1,3,20.0,M,Simplified Chinese,Mandarin Chinese,...,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442,15.648172
96958,212.0,China,2126.0,embarrassment,2,3,19.0,F,Simplified Chinese,Mandarin Chinese,...,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442,15.648172
96959,213.0,China,2127.0,embarrassment,4,4,21.0,M,Simplified Chinese,Mandarin Chinese,...,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442,15.648172

In [385]:
print(bila_nouns_full[(bila_nouns_full['id']=="uc1.l0088545033") & (bila_nouns_full['word']== 'activation')]['count'])
print(final_complete[(final_complete['id']=="uc1.l0088545033") & (final_complete['word']== 'activation')]['count'].head(1))

1457576    1.0
Name: count, dtype: float64
75739    1.0
Name: count, dtype: float64

In [386]:
final_complete[(final_complete['countryname']=="China") & (final_complete['word']=="embarrassment")]['experience']

96747    3
96748    2
96749    2
96750    2
96751    2
        ..
96955    3
96956    3
96957    3
96958    3
96959    4
Name: experience, Length: 213, dtype: category
Categories (5, int64): [5, 1, 4, 2, 3]

In [387]:
final_complete.columns

Index(['ID', 'countryname', 'subjectnumber', 'word', 'want', 'experience',
       'age', 'gender', 'study_language_names', 'bila_language_name_mapping',
       'id', 'count', 'langname', 'glottocode', 'year', 'title', 'author',
       'regression_elaboration', 'dictsize_data', 'simple_elaboration',
       'log_count', 'dictionary_count_mean'],
      dtype='object')

In [388]:
combo_counts(final_complete)

  countryname glottocode  n_rows
0      Brazil   braz1246   39180
4      Poland   poli1260   18120
3      Israel   hebr1245   14880
1       China   mand1415   12780
2     Germany   stan1295   12000

In [389]:
final_complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96960 entries, 0 to 96959
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          96960 non-null  category
 1   countryname                 96960 non-null  object
 2   subjectnumber               96960 non-null  float64
 3   word                        96960 non-null  object
 4   want                        96817 non-null  category
 5   experience                  96451 non-null  category
 6   age                         96600 non-null  float64
 7   gender                      96780 non-null  category
 8   study_language_names        96960 non-null  object
 9   bila_language_name_mapping  96960 non-null  object
 10  id                          96960 non-null  object
 11  count                       96960 non-null  float64
 12  langname                    96960 non-null  object
 13  glottocode                  96960 non-null  object
 14  year                        96960 non-null  float64
 15  title                       96960 non-null  object
 16  author                      96960 non-null  object
 17  regression_elaboration      96960 non-null  float64
 18  dictsize_data               96960 non-null  float64
 19  simple_elaboration          96960 non-null  float64
 20  log_count                   96960 non-null  float64
 21  dictionary_count_mean       96960 non-null  float64
dtypes: category(4), float64(9), object(9)
memory usage: 13.8+ MB

In [390]:
final_complete.to_csv(Path("~/Projects/hypocognition/data/processed/tamir_bila_merge.csv").expanduser())

In [391]:
print(bila_nouns_full[(bila_nouns_full['id']=="uc1.l0088545033") & (bila_nouns_full['word']== 'activation')]['count'])
print(final_complete[(final_complete['id']=="uc1.l0088545033") & (final_complete['word']== 'activation')]['count'].head(1))

1457576    1.0
Name: count, dtype: float64
75739    1.0
Name: count, dtype: float64

In [394]:
final_complete.groupby(['word', 'countryname']).first()

                          ID  subjectnumber want experience   age gender  \
word       countryname
activation Brazil       1,00          752.0    5          3  24.0      F
           China        1,00         1915.0    3          3  20.0      F
           Germany      45.0            1.0    4          4  23.0      F
           Israel       1,00          201.0    1          3  24.0      F
           Poland       1,00         1613.0    4          4  21.0      M
...                      ...            ...  ...        ...   ...    ...
worry      Brazil       1,00          752.0    1          5  24.0      F
           China        1,00         1915.0    4          3  20.0      F
           Germany      45.0            1.0    2          2  23.0      F
           Israel       1,00          201.0    1          4  24.0      F
           Poland       1,00         1613.0    1          3  21.0      M

                        study_language_names bila_language_name_mapping  \
word       countryname
activation Brazil       Brazilian Portuguese       Brazilian Portuguese
           China          Simplified Chinese           Mandarin Chinese
           Germany                    German                     German
           Israel                     Hebrew                     Hebrew
           Poland                     Polish                     Polish
...                                      ...                        ...
worry      Brazil       Brazilian Portuguese       Brazilian Portuguese
           China          Simplified Chinese           Mandarin Chinese
           Germany                    German                     German
           Israel                     Hebrew                     Hebrew
           Poland                     Polish                     Polish

                                         id  count              langname  \
word       countryname
activation Brazil       txu.059173018640743    0.0  Brazilian Portuguese
           China            uc1.l0088545033    1.0      Mandarin Chinese
           Germany       uc1.31822005249149    2.0                German
           Israel            uva.x004242694    1.0                Hebrew
           Poland        mdp.39015015059622    0.0                Polish
...                                     ...    ...                   ...
worry      Brazil       txu.059173018640743    1.0  Brazilian Portuguese
           China            uc1.l0088545033   19.0      Mandarin Chinese
           Germany       uc1.31822005249149   29.0                German
           Israel            uva.x004242694    0.0                Hebrew
           Poland        mdp.39015015059622    6.0                Polish

                       glottocode    year  \
word       countryname
activation Brazil        braz1246  1983.0
           China         mand1415  2004.0
           Germany       stan1295  1983.0
           Israel        hebr1245  1977.0
           Poland        poli1260  1962.0
...                           ...     ...
worry      Brazil        braz1246  1983.0
           China         mand1415  2004.0
           Germany       stan1295  1983.0
           Israel        hebr1245  1977.0
           Poland        poli1260  1962.0

                                                                    title  \
word       countryname
activation Brazil       A dictionary of informal Brazilian Portuguese ...
           China        Wai yan she jing bian Ying Han Han Ying ci dia...
           Germany      Collins German-English dictionary / by Roland ...
           Israel       The new Bantam-Megiddo Hebrew & English dictio...
           Poland       The Kościuszko Foundation dictionary: English-...
...                                                                   ...
worry      Brazil       A dictionary of informal Brazilian Portuguese ...
           China        Wai yan she jing bian Ying Han Han Ying ci dia...
           Germany      Collins German-English dictionary / by Roland ...
           Israel       The new Bantam-Megiddo Hebrew & English dictio...
           Poland       The Kościuszko Foundation dictionary: English-...

                       author  regression_elaboration  dictsize_data  \
word       countryname
activation Brazil           0                0.000000        16427.0
           China            0               -0.514848       101618.0
           Germany          0               -1.142327       212621.0
           Israel           0                1.335953        21514.0
           Poland           0                0.000000        89579.0
...                       ...                     ...            ...
worry      Brazil           0                0.533318        16427.0
           China            0                5.267704       101618.0
           Germany          0                4.829055       212621.0
           Israel           0                0.000000        21514.0
           Poland           0                0.662484        89579.0

                        simple_elaboration  log_count  dictionary_count_mean
word       countryname
activation Brazil                 0.000000   0.000000               8.979212
           China                  0.000010   0.693147              15.648172
           Germany                0.000009   1.098612              34.214196
           Israel                 0.000046   0.693147               3.707998
           Poland                 0.000000   0.000000              14.661022
...                                    ...        ...                    ...
worry      Brazil                 0.000061   0.693147               8.979212
           China                  0.000187   2.995732              15.648172
           Germany                0.000136   3.401197              34.214196
           Israel                 0.000000   0.000000               3.707998
           Poland                 0.000067   1.945910              14.661022

[300 rows x 20 columns]

In [393]:
final_complete

,ID,countryname,subjectnumber,word,want,experience,age,gender,study_language_names,bila_language_name_mapping,...,langname,glottocode,year,title,author,regression_elaboration,dictsize_data,simple_elaboration,log_count,dictionary_count_mean
0,45.0,Germany,1.0,gratitude,5,5,23.0,F,German,German,...,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732,34.214196
1,47.0,Germany,2.0,gratitude,4,5,23.0,F,German,German,...,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732,34.214196
2,48.0,Germany,3.0,gratitude,5,4,27.0,M,German,German,...,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732,34.214196
3,49.0,Germany,4.0,gratitude,4,4,34.0,F,German,German,...,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732,34.214196
4,50.0,Germany,5.0,gratitude,3,3,34.0,F,German,German,...,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732,34.214196
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96955,209.0,China,2123.0,embarrassment,2,3,20.0,M,Simplified Chinese,Mandarin Chinese,...,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442,15.648172
96956,210.0,China,2124.0,embarrassment,1,3,19.0,F,Simplified Chinese,Mandarin Chinese,...,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442,15.648172
96957,211.0,China,2125.0,embarrassment,1,3,20.0,M,Simplified Chinese,Mandarin Chinese,...,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442,15.648172
96958,212.0,China,2126.0,embarrassment,2,3,19.0,F,Simplified Chinese,Mandarin Chinese,...,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442,15.648172
96959,213.0,China,2127.0,embarrassment,4,4,21.0,M,Simplified Chinese,Mandarin Chinese,...,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442,15.648172

In [395]:
# # convert columns to numeric
final_complete['want_num'] = pd.to_numeric(final_complete['want'], errors='coerce')
final_complete['experience_num'] = pd.to_numeric(final_complete['experience'], errors='coerce')

# full country x word combinations
countries = final_complete['countryname'].unique()
words = final_complete['word'].unique()
full_index = pd.MultiIndex.from_product([countries, words], names=['countryname', 'word'])
full_table = pd.DataFrame(index=full_index).reset_index()

# aggregate mean/std ignoring NaNs
agg_table = (
    final_complete
    .groupby(['countryname','word'], as_index=False)
    .agg(
        want_mean = ('want_num', 'mean'),
        want_std  = ('want_num', 'std'),
        experience_mean = ('experience_num', 'mean'),
        experience_std  = ('experience_num', 'std')
    )
)

# merge with full table
final_table = full_table.merge(agg_table, on=['countryname','word'], how='left')

# fill groups that were all NaN with 0
final_table['want_mean'] = final_table['want_mean'].fillna(0)
final_table['want_std']  = final_table['want_std'].fillna(0)
final_table['experience_mean'] = final_table['experience_mean'].fillna(0)
final_table['experience_std']  = final_table['experience_std'].fillna(0)

final_table

,countryname,word,want_mean,want_std,experience_mean,experience_std
0,Germany,gratitude,3.935000,0.845190,3.460000,0.807254
1,Germany,disappointment,1.570000,0.597398,2.620000,0.786571
2,Germany,contentment,4.725000,0.510567,3.640000,0.832988
3,Germany,guilt,1.405000,0.549989,2.295000,0.775229
4,Germany,jealousy,1.555000,0.647356,2.135000,0.842809
...,...,...,...,...,...,...
295,China,amusement,4.000000,0.881619,3.549296,0.760872
296,China,shyness,2.563380,0.880594,2.718310,0.804171
297,China,anger,2.000000,0.852300,2.339623,0.665846
298,China,anxiety,2.061033,0.885434,2.723005,0.802876
299,China,embarrassment,2.004695,0.903336,2.563380,0.688156

In [396]:
final_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   countryname      300 non-null    object
 1   word             300 non-null    object
 2   want_mean        300 non-null    float64
 3   want_std         300 non-null    float64
 4   experience_mean  300 non-null    float64
 5   experience_std   300 non-null    float64
dtypes: float64(4), object(2)
memory usage: 14.2+ KB

In [ ]:
# the following merge was causeing problems, send a copy through the merge 
final_table2= final_table.copy()

In [398]:
some_info = final_complete[['word', 'countryname','study_language_names', 'bila_language_name_mapping',
       'id', 'count', 'langname', 'glottocode', 'year', 'title', 'author',
       'regression_elaboration', 'dictsize_data', 'simple_elaboration',
       'log_count', 'dictionary_count_mean']].copy().drop_duplicates().reset_index(drop=True)


final_table2 = final_table2.merge(
    some_info,
    on=["countryname", "word"],
    how="left"
)
final_table2

,countryname,word,want_mean,want_std,experience_mean,experience_std,study_language_names,bila_language_name_mapping,id,count,langname,glottocode,year,title,author,regression_elaboration,dictsize_data,simple_elaboration,log_count,dictionary_count_mean
0,Germany,gratitude,3.935000,0.845190,3.460000,0.807254,German,German,uc1.31822005249149,19.0,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732,34.214196
1,Germany,disappointment,1.570000,0.597398,2.620000,0.786571,German,German,uc1.31822005249149,17.0,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.213324,212621.0,0.000080,2.890372,34.214196
2,Germany,contentment,4.725000,0.510567,3.640000,0.832988,German,German,uc1.31822005249149,5.0,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-1.870528,212621.0,0.000024,1.791759,34.214196
3,Germany,guilt,1.405000,0.549989,2.295000,0.775229,German,German,uc1.31822005249149,45.0,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,2.383329,212621.0,0.000212,3.828641,34.214196
4,Germany,jealousy,1.555000,0.647356,2.135000,0.842809,German,German,uc1.31822005249149,13.0,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-2.070226,212621.0,0.000061,2.639057,34.214196
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,China,amusement,4.000000,0.881619,3.549296,0.760872,Simplified Chinese,Mandarin Chinese,uc1.l0088545033,7.0,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-1.568026,101618.0,0.000069,2.079442,15.648172
296,China,shyness,2.563380,0.880594,2.718310,0.804171,Simplified Chinese,Mandarin Chinese,uc1.l0088545033,2.0,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-1.303179,101618.0,0.000020,1.098612,15.648172
297,China,anger,2.000000,0.852300,2.339623,0.665846,Simplified Chinese,Mandarin Chinese,uc1.l0088545033,59.0,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.995820,101618.0,0.000581,4.094345,15.648172
298,China,anxiety,2.061033,0.885434,2.723005,0.802876,Simplified Chinese,Mandarin Chinese,uc1.l0088545033,33.0,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,1.855676,101618.0,0.000325,3.526361,15.648172
299,China,embarrassment,2.004695,0.903336,2.563380,0.688156,Simplified Chinese,Mandarin Chinese,uc1.l0088545033,7.0,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442,15.648172

In [399]:
print(bila_nouns_full[(bila_nouns_full['id']=="uc1.l0088545033") & (bila_nouns_full['word']== 'activation')]['count'])
print(final_table2[(final_table2['id']=="uc1.l0088545033") & (final_table2['word']== 'activation')]['count'].head(1))

1457576    1.0
Name: count, dtype: float64
286    1.0
Name: count, dtype: float64

In [401]:
final_table2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   countryname                 300 non-null    object
 1   word                        300 non-null    object
 2   want_mean                   300 non-null    float64
 3   want_std                    300 non-null    float64
 4   experience_mean             300 non-null    float64
 5   experience_std              300 non-null    float64
 6   study_language_names        300 non-null    object
 7   bila_language_name_mapping  300 non-null    object
 8   id                          300 non-null    object
 9   count                       300 non-null    float64
 10  langname                    300 non-null    object
 11  glottocode                  300 non-null    object
 12  year                        300 non-null    float64
 13  title                       300 non-null    object
 14  author                      300 non-null    object
 15  regression_elaboration      300 non-null    float64
 16  dictsize_data               300 non-null    float64
 17  simple_elaboration          300 non-null    float64
 18  log_count                   300 non-null    float64
 19  dictionary_count_mean       300 non-null    float64
dtypes: float64(11), object(9)
memory usage: 47.0+ KB

In [402]:
final_table2.to_csv(Path("~/Projects/hypocognition/data/processed/tamir_bila_stats.csv").expanduser())

In [403]:
final_table2

,countryname,word,want_mean,want_std,experience_mean,experience_std,study_language_names,bila_language_name_mapping,id,count,langname,glottocode,year,title,author,regression_elaboration,dictsize_data,simple_elaboration,log_count,dictionary_count_mean
0,Germany,gratitude,3.935000,0.845190,3.460000,0.807254,German,German,uc1.31822005249149,19.0,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.818696,212621.0,0.000089,2.995732,34.214196
1,Germany,disappointment,1.570000,0.597398,2.620000,0.786571,German,German,uc1.31822005249149,17.0,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-0.213324,212621.0,0.000080,2.890372,34.214196
2,Germany,contentment,4.725000,0.510567,3.640000,0.832988,German,German,uc1.31822005249149,5.0,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-1.870528,212621.0,0.000024,1.791759,34.214196
3,Germany,guilt,1.405000,0.549989,2.295000,0.775229,German,German,uc1.31822005249149,45.0,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,2.383329,212621.0,0.000212,3.828641,34.214196
4,Germany,jealousy,1.555000,0.647356,2.135000,0.842809,German,German,uc1.31822005249149,13.0,German,stan1295,1983.0,Collins German-English dictionary / by Roland ...,0,-2.070226,212621.0,0.000061,2.639057,34.214196
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,China,amusement,4.000000,0.881619,3.549296,0.760872,Simplified Chinese,Mandarin Chinese,uc1.l0088545033,7.0,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-1.568026,101618.0,0.000069,2.079442,15.648172
296,China,shyness,2.563380,0.880594,2.718310,0.804171,Simplified Chinese,Mandarin Chinese,uc1.l0088545033,2.0,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-1.303179,101618.0,0.000020,1.098612,15.648172
297,China,anger,2.000000,0.852300,2.339623,0.665846,Simplified Chinese,Mandarin Chinese,uc1.l0088545033,59.0,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.995820,101618.0,0.000581,4.094345,15.648172
298,China,anxiety,2.061033,0.885434,2.723005,0.802876,Simplified Chinese,Mandarin Chinese,uc1.l0088545033,33.0,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,1.855676,101618.0,0.000325,3.526361,15.648172
299,China,embarrassment,2.004695,0.903336,2.563380,0.688156,Simplified Chinese,Mandarin Chinese,uc1.l0088545033,7.0,Mandarin Chinese,mand1415,2004.0,Wai yan she jing bian Ying Han Han Ying ci dia...,0,-0.147078,101618.0,0.000069,2.079442,15.648172

In [405]:
final_table2.columns

Index(['countryname', 'word', 'want_mean', 'want_std', 'experience_mean',
       'experience_std', 'study_language_names', 'bila_language_name_mapping',
       'id', 'count', 'langname', 'glottocode', 'year', 'title', 'author',
       'regression_elaboration', 'dictsize_data', 'simple_elaboration',
       'log_count', 'dictionary_count_mean'],
      dtype='object')

"Moving forward, could you create a table with the following columns:
* The sample country
* The language
* The correlation between the log count and the response means
* The correlation between the log count and the response SDs
* The correlation between the log count and the absolute distance of the response means from the scale midpoint
"

In [406]:

merged2 = final_table2.copy()
merged2["log_count"] = np.log(merged2["count"] + 1)

def corr_within_group(df, x, y):
    return df[x].corr(df[y])

countries = merged2['countryname'].unique().tolist()

# Loop over countries
for c in countries:
    df = merged2[merged2['countryname'] == c]
    
    # Correlations for 'want' mean and std
    corr_want_mean = df['log_count'].corr(df['want_mean'])
    corr_want_std  = df['log_count'].corr(df['want_std'])
    
    # Correlations for 'experience' mean and std
    corr_exp_mean = df['log_count'].corr(df['experience_mean'])
    corr_exp_std  = df['log_count'].corr(df['experience_std'])
    
    print(f"{c}: want_mean={corr_want_mean:.3f}, want_std={corr_want_std:.3f}, "
          f"experience_mean={corr_exp_mean:.3f}, experience_std={corr_exp_std:.3f}")

Germany: want_mean=-0.005, want_std=-0.223, experience_mean=0.060, experience_std=-0.203
Israel: want_mean=-0.136, want_std=-0.356, experience_mean=-0.151, experience_std=-0.217
Brazil: want_mean=-0.010, want_std=-0.262, experience_mean=0.023, experience_std=0.026
Poland: want_mean=-0.041, want_std=-0.140, experience_mean=0.013, experience_std=0.003
China: want_mean=0.048, want_std=-0.207, experience_mean=0.053, experience_std=-0.211

In [407]:
merged2 = final_table2.copy()

# log count
merged2["log_count"] = np.log(merged2["count"] + 1)

# absolute distance from midpoint (if needed)
SCALE_MIDPOINT = merged2["want_mean"].mean()  # or experience_mean, or combine both
merged2["abs_dist_midpoint_want"] = (merged2["want_mean"] - SCALE_MIDPOINT).abs()
merged2["abs_dist_midpoint_exp"]  = (merged2["experience_mean"] - SCALE_MIDPOINT).abs()

# Group by country, language, and id
result = (
    merged2
    .groupby(["countryname", "langname", "id"])
    .agg(
        corr_logcount_want_mean=(
            "log_count",
            lambda x: x.corr(merged2.loc[x.index, "want_mean"])
        ),
        corr_logcount_want_std=(
            "log_count",
            lambda x: x.corr(merged2.loc[x.index, "want_std"])
        ),
        corr_logcount_experience_mean=(
            "log_count",
            lambda x: x.corr(merged2.loc[x.index, "experience_mean"])
        ),
        corr_logcount_experience_std=(
            "log_count",
            lambda x: x.corr(merged2.loc[x.index, "experience_std"])
        ),
        corr_logcount_abs_dist_midpoint_want=(
            "log_count",
            lambda x: x.corr(merged2.loc[x.index, "abs_dist_midpoint_want"])
        ),
        corr_logcount_abs_dist_midpoint_exp=(
            "log_count",
            lambda x: x.corr(merged2.loc[x.index, "abs_dist_midpoint_exp"])
        ),
    )
    .reset_index()
)

print(result.head())

  countryname              langname                   id  \
0      Brazil  Brazilian Portuguese  txu.059173018640743
1       China      Mandarin Chinese      uc1.l0088545033
2     Germany                German   uc1.31822005249149
3      Israel                Hebrew       uva.x004242694
4      Poland                Polish   mdp.39015015059622

   corr_logcount_want_mean  corr_logcount_want_std  \
0                -0.010408               -0.262473
1                 0.047903               -0.207080
2                -0.004501               -0.222991
3                -0.136126               -0.356184
4                -0.041114               -0.139571

   corr_logcount_experience_mean  corr_logcount_experience_std  \
0                       0.022874                      0.025541
1                       0.052515                     -0.211274
2                       0.059870                     -0.203244
3                      -0.150969                     -0.216588
4                       0.013075                      0.003101

   corr_logcount_abs_dist_midpoint_want  corr_logcount_abs_dist_midpoint_exp
0                              0.098576                            -0.010912
1                              0.152479                             0.207594
2                              0.133334                             0.151559
3                              0.162182                             0.057673
4                              0.138696                             0.235645

In [408]:
result

,countryname,langname,id,corr_logcount_want_mean,corr_logcount_want_std,corr_logcount_experience_mean,corr_logcount_experience_std,corr_logcount_abs_dist_midpoint_want,corr_logcount_abs_dist_midpoint_exp
0,Brazil,Brazilian Portuguese,txu.059173018640743,-0.010408,-0.262473,0.022874,0.025541,0.098576,-0.010912
1,China,Mandarin Chinese,uc1.l0088545033,0.047903,-0.207080,0.052515,-0.211274,0.152479,0.207594
2,Germany,German,uc1.31822005249149,-0.004501,-0.222991,0.059870,-0.203244,0.133334,0.151559
3,Israel,Hebrew,uva.x004242694,-0.136126,-0.356184,-0.150969,-0.216588,0.162182,0.057673
4,Poland,Polish,mdp.39015015059622,-0.041114,-0.139571,0.013075,0.003101,0.138696,0.235645

In [410]:
result.to_csv(Path("~/Projects/hypocognition/data/processed/tamir_bila_corr.csv").expanduser())